### ISSUE TITLE
group by inner elements of an object

### ISSUE THREAD

**Issue by carbuz** [agershun/alasql#100]
Hi,
I 've an issue in running this query:

var data=[{a:{aa:1},b:{bb:2}},{a:{aa:2},b:{bb:2}},{a:{aa:1},b:{bb:3}}]
alasql('select SUM(a->aa),b->bb from ? group by b->bb',[data])

Thanks!

**Comment by agershun** [comment]
The problem here is that ```b->bbb``` is not a column from your GROUP BY clause. You can use FIRST(b->bb) instead:
```js
    var res = alasql('select SUM(a->aa), FIRST(b->bb) from ? group by b->bb',[data]);
```
Try this [example in jsFIddle](http://jsfiddle.net/5jwqrs0f/). I added ```AS [b->bb]```, but this is unimportant.

**Comment by carbuz** [comment]
thank you amazing library and support!
Il 24/mar/2015 13:57 "agershun" <notifications@github.com> ha scritto:

**Comment by agershun** [comment]
Thank you!
