### ISSUE TITLE
Am grouping and rodering the JSON data using alasql queries for every 5 minutes but getting FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory 

### ISSUE THREAD

**Issue by ManjunathDevangaAdisheshappa** [agershun/alasql#1000]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Programming question?
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something not working as expected? 
- Describe the problem  
- Provide code that replicates the problem 
- We suggest to spawn a jsfiddle from http://jsfiddle.net/mtt9r7rx/

**Comment by mathiasrw** [comment]
Please describe the issue in the description - not in the header. 

Please remember to provide code that replicates the problem.
