### ISSUE TITLE
Unable to perform date filter after exporting JSON date to excel

### ISSUE THREAD

**Issue by mailmrmanoj** [agershun/alasql#1006]
I'm using below query to export JSON with dates(DD/MM/YYYY) into excel

```
var loginInfo=[
  {
    "Login Date": "5/3/2018"
  },
  {
    "Login Date": "15/4/2018"
  },
  {
    "Login Date": "12/8/2018"
  },
  {
    "Login Date": "10/7/2018"
  }
];
alasql("SELECT * INTO XLSX('test.xlsx',{headers:true}) FROM ? ",[loginInfo]);
```

Upon exporting data to excel, since the date column is a string I'm not able to directly apply date filter in excel. Is there any way which I can make the dates appear as dates in excel further exporting so that I can filter dates ?Thanks

**Excel date after exporting JSON :**
![image](https://user-images.githubusercontent.com/7077567/40429557-98013a32-5ec0-11e8-9ff3-b2721c7b044a.png)
**Current filter :**
![image](https://user-images.githubusercontent.com/7077567/40429731-027c2caa-5ec1-11e8-8dd7-cdcc3d492cb3.png)
**Expected filter :**
![image](https://user-images.githubusercontent.com/7077567/40429922-72f50fc4-5ec1-11e8-9346-1d407752c174.png)

**Comment by mathiasrw** [comment]
I have a feeling this should fix your problem. Please reopen if there is still an issue: https://github.com/agershun/alasql/issues/395#issuecomment-290392777
