### ISSUE TITLE
Angular JS fiddle link not working

### ISSUE THREAD

**Issue by chandanch** [agershun/alasql#1007]
**Something not working as expected**
 In the JS fiddle example for angularJs export is not working. This due to library load issue. On the browser console the following error is shown:
`404 Not found: http://alasql.org/console/xlsx.core.min.js`
`404 Not found: http://alasql.org/console/alasql.min.js`

**Comment by mathiasrw** [comment]
Ohh, thanks for letting us know. Do you have the link to the JS fiddle?

**Comment by mathiasrw** [comment]
The examples on https://github.com/agershun/alasql/wiki/Angular.js have now been updated - Thank you for letting us know.
