### ISSUE TITLE
I am trying to read a excel file but I am getting  Invalid HTML: could not find <table> issue

### ISSUE THREAD

**Issue by TarunGarg12** [agershun/alasql#1014]
Hi All,

I am reading an excel file using below code 

``` 
if (event.fromElement.files.length==0) {
            return(false);   // leave in case no file was chosen
        };
        alasql('SELECT * FROM FILE(?,{headers:true})', [event], function (data) {
            $rootScope.eData = data;     //  eData contains the JSON representation of the Excel sheet rows
        }); 
```

and the html code is as follows:

`<input type="file" ng-mouseleave="loadFile($event)" />`

On observing the browser console the issue is 

```
xlsx.full.min.js:21 Uncaught Error: Invalid HTML: could not find <table>
    at e (xlsx.full.min.js:21)
    at Object.r [as to_workbook] (xlsx.full.min.js:21)
    at Pp (xlsx.full.min.js:19)
    at Np (xlsx.full.min.js:19)
    at Object.dg [as read] (xlsx.full.min.js:22)
    at alasql.min.js:2
    at XMLHttpRequest.a.onload (alasql.min.js:11)`
```

Thanks in advance!!!

**Comment by mathiasrw** [comment]
Any chance you can make an example on jsfiddle?

**Comment by mathiasrw** [comment]
Any news on this?

**Comment by TarunGarg12** [comment]
Hi.. I am new to JSFiddle so tried to create a JSFiddle but faced issues so couldn't make it.

**Comment by mathiasrw** [comment]
If you can make a html with the example code that is also cool (attache to this issue by dragging it into the text box where you write text)

**Comment by gursimran-agile** [comment]
@mathiasrw  i am having same problem, can you please help me out, here is my code
// url is link of google sheet -> https://docs.google.com/spreadsheets/d/1Xr2IjT8Ohh3fYqoAKIMLiR21AleNMNJ9SXVlkLIn2F4/edit?usp=sharing



fetch (url)
    .then(response => {
      const reader = response.body.getReader();
      reader.read()
      .then(({value}) => {
        try {
          var workbook = XLSX.read(value, {type:'array'});
        } catch (error) {
          setErrorMessage(error.message);
          return;
        }
        console.log(workbook);
        var sheetName = workbook.SheetNames;
        console.log(XLSX.utils.sheet_to_json(workbook.Sheets[sheetName[0]],{raw: true, defval:null}));
      });
    });

**Comment by mathiasrw** [comment]
@gursimran-agile 

I have a feeling you could do the same with something like

    alasql.promise('select * from xlsx("https://docs.google.com/spreadsheets/d/1Xr2IjT8Ohh3fYqoAKIMLiR21AleNMNJ9SXVlkLIn2F4/edit?usp=sharing",{sheetid:?})', sheetName[0])


But to be fair there is actually a plugin only to read data from google spreadsheet. Please have a look at https://github.com/agershun/alasql/wiki/TABLETOP - in the example its loaded directly to a html table, but could just a well be used to load into a DB table (or read out directly).

**Comment by gursimran-agile** [comment]
thanks a lot @mathiasrw , reading the links provided by works for me,
I published my spreadSheet, now it works fine. Thanks a lot once again :+1: :)
