### ISSUE TITLE
Salesforce Locker Service

### ISSUE THREAD

**Issue by KyooMario** [agershun/alasql#1017]
Hello Team,

We are using your solution with great pleasure within Salesforce (and Sharepoint) scripting. Till the latest version release of Salesforce everything was working fine but since a week (summer 18 release) we get an error. (Actually no error but it just stops working)

Now Salesforce has introduced the Locker Service which seems to cause the issue:
https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_code.htm

When we set the working version back to "before" Locker Service everything works as expected.

Question: Do you recognize what is causing the issue code wise and can you fix this?

Kind regards,
Mario

**Comment by mathiasrw** [comment]
Hi Mario

Thanks for reaching out. I feel convinced that the demand for `use strict` is the main reason its not running anymore.

We should look into this. Im a bit worried about the autogenerated code for the JISON parser but hopefully it turs out ok. 

If we manage to get this going, would you be interested in writing a few words describing how/why you use AlaSQL in your salesfoce setup?

**Comment by KyooMario** [comment]
Hello Mathias,

Thanks. And of course.

Kind regards,
Mario

**Comment by mathiasrw** [comment]
Are you using SQL triggers?

(Having a trigger related bug but if you dont use that we can test if `use strict` helps (and work on the bug - but you can get a version that runs))

**Comment by KyooMario** [comment]
Hello Mathias,

No.  I don’t use them. ( I wasn’t aware we have them 😉)

Kind regards,
Mario

**Comment by mathiasrw** [comment]
The latest release `0.4.6` is now in strict mode. 

Would it be possible for you to check if the last version is working in your salesforce setup?

**Comment by KyooMario** [comment]
Hello Mathias,

I get the following error message:

[Cannot read property 'indexedDB' of undefined]
eval()@https://kyooact-dev-ed.lightning.force.com/resource/1529050604000/kyooact__Kyoo/alasql.js:3435:24
eval()@https://kyooact-dev-ed.lightning.force.com/resource/1529050604000/kyooact__Kyoo/alasql.js:3436:3
eval()@https://kyooact-dev-ed.lightning.force.com/resource/1529050604000/kyooact__Kyoo/alasql.js:59:23
Proxy.eval()@https://kyooact-dev-ed.lightning.force.com/resource/1529050604000/kyooact__Kyoo/alasql.js:61:2

Kind regards,
Mario

**Comment by mathiasrw** [comment]
Hmmmm. 

Any chance you can share the SQL running for me to get some leads?

**Comment by KyooMario** [comment]
Hello Matthias,

Give me a few days and I will set something up.

Kind regards,
Mario

Sent from my iPhone

On 17 Jun 2018, at 13:47, Mathias Rangel Wulff <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmmm.

Any chance you can share the SQL running for me to get some leads?

**Comment by mathiasrw** [comment]
Cool. Ill have a look at it in the weekend.

**Comment by mathiasrw** [comment]
> You're trying to Log In to Salesforce. To make sure your Salesforce account is secure, we have to verify your identity.
> Enter the verification code we emailed to ma***@**oo.studio.
> Verification Code

**Comment by mathiasrw** [comment]
Can you help me login? You might want to change the email to m@rawu.dk so I can do the verification thing myself?

**Comment by KyooMario** [comment]
Hello Mathias,

I have changed the email address to m@rawu.dk<mailto:m@rawu.dk>

Kind regards,
Mario

**Comment by mathiasrw** [comment]
Perfect. I will look into this in the weekend.

**Comment by mathiasrw** [comment]
With the latest changes no error is displayed - but I see no output on the alasql-dev-ed.lightning.force.com/lightning/n/ALASQL page. 

Is it meant to provide any output after `alasqlResult =`?

**Comment by KyooMario** [comment]
Hello Mathias,

The Static Resource must also include “jquery.min.js”
<ltng:require scripts="{!join(',',
            $Resource.Kyoo+ '/jquery.min.js',
            $Resource.Kyoo+ '/alasql.js')}" afterScriptsLoaded="{!c.doInit}" ></ltng:require>

You left it out? And now I included it again: With the correct result 😉 Good Job !!

The code used is:
var source = [{"Title":"Item 01"},{"Title":"Item 02"}]
        var result = alasql('SELECT * FROM ? ', [source]);
        console.log('result: '+result);
        component.set('v.alasqlResult', JSON.stringify(result));

You can see the result on the page now 😉

Just in case: If you want to code yourselves you can do this as follows:

  1.  Open the Developer Console:
[cid:image003.jpg@01D41B09.EC7F0530]

  2.  Open the ALASQL Component:
[cid:image005.jpg@01D41B09.EC7F0530]

  3.  You can open the Component (page) and the Controller (script)
The code is not hard to read.

If questions please ask.

Thanks so far.

Kind regards,
Mario

**Comment by mathiasrw** [comment]
Perfect!

The updated version is now deployed as version 0.4.7.

I would love to play around a bit if you could let the link be open a week or so more :)

**Comment by KyooMario** [comment]
Hello Mathias,

Great. Thanks a lot.
Take as long as you want. There are no cost involved.

Kind regards,
Mario

Sent from my iPhone

On 14 Jul 2018, at 21:02, Mathias Rangel Wulff <notifications@github.com<mailto:notifications@github.com>> wrote:


Perfect!

The updated version is now deployed as version 0.4.7.

I would love to play around a bit if you could let the link be open a week or so more :)

**Comment by KyooMario** [comment]
Hello Mathias or Andrey,

I have constructed the following statement:
alasql.fn.writeButton = function(name) {
return '{"buttonAction":"addTab","buttonValue":"'+name+'"}';
}
result = alasql('SELECT Title, {label:Form,[value]:writeButton(CONCAT("{\\"label\\":\\"",Title,"\\",\\"value\\":\\"",Title,"\\"}")),[action]:"{!c.buttonAction}"} AS [Form] FROM ?', [result]);

it returns:
[{"Title":"Kyoo Demo Form","Form":{"value":"{\"buttonAction\":\"addTab\",\"buttonValue\":\"{\"label\":\"Kyoo Demo Form\",\"value\":\"Kyoo Demo Form\"}\"}","action":"{!c.buttonAction}"}},{"Title":"test","Form":{"value":"{\"buttonAction\":\"addTab\",\"buttonValue\":\"{\"label\":\"test\",\"value\":\"test\"}\"}","action":"{!c.buttonAction}"}}]

As you can see we end up with a \” in the object where we need only the “.

But if we only use \” instead of \\” alasql returns an error.

Can you advise how to fix this?

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello Mathias,

Playing a bit I think I should do it as follows:
result = alasql('SELECT Title, ({"label":"Form","value":{"label":Title,"value":Title},"action":"{!c.buttonAction}"}) AS [Form] FROM ?', [result]);

Kind regards,
Mario

From: Mario Kyoo
Sent: Saturday, 15 September 2018 19:54
To: agershun/alasql <reply@reply.github.com>
Cc: agershun/alasql <alasql@noreply.github.com>; Author <author@noreply.github.com>
Subject: Escape double quote in select statement

Hello Mathias or Andrey,

I have constructed the following statement:
alasql.fn.writeButton = function(name) {
return '{"buttonAction":"addTab","buttonValue":"'+name+'"}';
}
result = alasql('SELECT Title, {label:Form,[value]:writeButton(CONCAT("{\\"label\\":\\"",Title,"\\",\\"value\\":\\"",Title,"\\"}")),[action]:"{!c.buttonAction}"} AS [Form] FROM ?', [result]);

it returns:
[{"Title":"Kyoo Demo Form","Form":{"value":"{\"buttonAction\":\"addTab\",\"buttonValue\":\"{\"label\":\"Kyoo Demo Form\",\"value\":\"Kyoo Demo Form\"}\"}","action":"{!c.buttonAction}"}},{"Title":"test","Form":{"value":"{\"buttonAction\":\"addTab\",\"buttonValue\":\"{\"label\":\"test\",\"value\":\"test\"}\"}","action":"{!c.buttonAction}"}}]

As you can see we end up with a \” in the object where we need only the “.

But if we only use \” instead of \\” alasql returns an error.

Can you advise how to fix this?

Kind regards,
Mario

**Comment by mathiasrw** [comment]
So, did you manage to solve it?

**Comment by KyooMario** [comment]
Hello Mathias,

Yes. Thanks. Actually it was quite easy. Could not find documentation about it though so it took a while with trial and error to learn.

Thanks for following up this fast.

Kind regards
Mario

Sent from my iPhone

On 16 Sep 2018, at 09:30, Mathias Rangel Wulff <notifications@github.com<mailto:notifications@github.com>> wrote:


So, did you manage to solve it?
