### ISSUE TITLE
Can alasql dump the in-memory database to file stream

### ISSUE THREAD

**Issue by alexwenbj** [agershun/alasql#1023]
Is it possible to dump the in-memory database to file stream ,so i can save it to my disk or server?

**Comment by mathiasrw** [comment]
All data òf table `example1` is located in `alasql.tables.example1.data`.

I do suggest you look into generating a file using `into`: https://github.com/agershun/alasql/wiki/Into

**Comment by alexwenbj** [comment]
Thank you sir,I will have a try. @mathiasrw
