### ISSUE TITLE
Alasql plugin 

### ISSUE THREAD

**Issue by kasthuriharitha** [agershun/alasql#1024]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Programming question?
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something not working as expected? 
- Describe the problem  
- Provide code that replicates the problem 
- We suggest to spawn a jsfiddle from http://jsfiddle.net/mtt9r7rx/

I used Alasql plugin for exporting html data to excel, In that table , in one row i have glyhpicon if i click glphicon the files what i am uploaded will open .(i.e if i click a icon it will list the files) when i am exporting the  table data to excel the data are exported but icon or hyperlinks are not exported . IT shows only empty space.
[hyperlink _icon is not exported.txt](https://github.com/agershun/alasql/files/2144777/hyperlink._icon.is.not.exported.txt)

**Comment by mathiasrw** [comment]
Please provide working code that demonstrates the problem.
