### ISSUE TITLE
Some bullets missing

### ISSUE THREAD

**Issue by cja000** [agershun/alasql#1026]
Hi,

In the wiki [Keyword SEARCH](https://github.com/agershun/alasql/wiki/SEARCH)

I think that the * members should be in a new line to be a bullet:

- AS  @team - save result into temporary variable team *members - take member property of previous result

It should be something like

- AS @team - save result into temporary variable team 
- members - take member property of previous result

The same happens two lines below with:
AS @member - save result into temporary variable member *categories - take category property of previous result

It should be:
- AS @member - save result into temporary variable member 
- categories - take category property of previous result

Br
CJ

**Comment by mathiasrw** [comment]
Thank you !
