### ISSUE TITLE
Alasql : Is alasql will export hyperlink to excel

### ISSUE THREAD

**Issue by kasthuriharitha** [agershun/alasql#1028]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Programming question?
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something not working as expected? 
- Describe the problem  
- Provide code that replicates the problem 
- We suggest to spawn a jsfiddle from http://jsfiddle.net/mtt9r7rx/

There is a html table, in that table there is a hyperlink , if i click export button to excel means the data with those hyperlink will export to excel??

**Comment by mathiasrw** [comment]
No.

**Comment by kasthuriharitha** [comment]
is there any way to export hyperlink to excel using alasql options?? or else any other way to do it

**Comment by mathiasrw** [comment]
HAve a look at the projekt xlsx.js
