### ISSUE TITLE
Showing error on npm install with v0.4.7 version

### ISSUE THREAD

**Issue by jogendrajangid1** [agershun/alasql#1029]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Programming question?
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something not working as expected? 
- Describe the problem  
Showing error on npm install with v0.4.7

- Provide code that replicates the problem
npm WARN enoent ENOENT: no such file or directory, open '/tmp/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
npm ERR! Linux 4.13.0-45-generic
npm ERR! argv "/home/jogendra/.nvm/versions/node/v7.10.0/bin/node" "/home/jogendra/.nvm/versions/node/v7.10.0/bin/npm" "install" "alasql@^0.4.0"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path /tmp/test/node_modules/alasql/bin/alasql-cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/tmp/test/node_modules/alasql/bin/alasql-cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/tmp/test/node_modules/alasql/bin/alasql-cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jogendra/.npm/_logs/2018-07-14T18_53_09_122Z-debug.log
 
- We suggest to spawn a jsfiddle from http://jsfiddle.net/mtt9r7rx/

**Comment by mathiasrw** [comment]
Hmm. Strange. 

what if you do the same for version 0.4.6 ?

**Comment by jogendrajangid1** [comment]
Its working fine for me on version 0.4.6.

**Comment by mathiasrw** [comment]
Can you please provide the exact command you are running?

**Comment by jogendrajangid1** [comment]
npm install alasql@^0.4.0(Please ensure you have clean npm cache and verify version after install)

**Comment by jogendrajangid1** [comment]
Thanks You @mathiasrw
