### ISSUE TITLE
loadFile during CSV parsing seems to swallow exceptions

### ISSUE THREAD

**Issue by elipalmer** [agershun/alasql#1030]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Hello, thanks for this excellent library.  I seem to be running into an issue found during testing.  I'm trying to load csv data from a string.  I noticed when a newline is not inside of the string, alasql assumes it is a file that needs to be loaded.  Since the string does not have a .csv member, loadFile throws an exception.  However, that exception seems to be swallowed and written to the console rather than returned as a rejected promise to the calling code.

Here is the jsfiddle: _http://jsfiddle.net/mtt9r7rx/38/_

The fiddle response only prints the version number (I am using v0.4.8),

Running this code locally I get this printed to the console:

_/testcode/ala/node_modules/alasql/dist/alasql.fs.js:3487
AlaSQL v0.4.8
							throw err;
							^

Error: ENOENT: no such file or directory, open 'a, a, a, a.csv'_

Am I using this wrong, or is there any path to getting the exception returned so I can handle this error on my end?

Thanks!

**Comment by elipalmer** [comment]
OK, thanks for taking a look.  I'll try to take a look to see if I can fix it.

**Comment by elipalmer** [comment]
I'm working on a fix for this now.  Just a heads up so I don't step on anyone elses toes looking at working on bugs.

**Comment by mathiasrw** [comment]
This is awesome. Thank you so much. Sorry for the long response time - was on vacation :)
