### ISSUE TITLE
Multiple JOIN on row takes a long time to finish

### ISSUE THREAD

**Issue by shawel** [agershun/alasql#1044]
Something not working as expected? 
- Query Using Index does not work on multiple joins. 

I have 3 datasets [a,b,c] that has a property r for row #.  
`alasql(SELECT a->name, b.val, c.val FROM ? as a  JOIN ? as b  JOIN ? as c ON  a.r = b.r AND a.r = c.r,a,b,c)`

The aim is to join 3 dataset by their row # and return select properties from each. If indexed I thought this should be linear time.

Thanks

**Comment by mathiasrw** [comment]
Please reopen the issue when you can provide a working example of the code providing the problem.
