### ISSUE TITLE
Import FROM CSV Error: alasql.min.js:11 Failed to load file: Cross origin requests 

### ISSUE THREAD

**Issue by LeonhardDiekmann2** [agershun/alasql#1046]
Hello,
 I want to export Data into a csv-Files (that works!) 
and i want to import Data from CSV-Files. That doesnt work.
I use Google Chrome.
The Import Function is:

function datenImportieren (){
ORTE.exec("CREATE TABLE IF NOT EXISTS cities (id number PRIMARY KEY ,city string, population number)");
alasql.promise('SELECT * INTO cities FROM CSV("orte.csv", {headers:false})')
            .then(function(data){
                 console.log(data);
            }).catch(function(err){
                 console.log('Error:', err);
            });
}
And i get the following error message: 

alasql.min.js:11 Failed to load file:///E:/Users/Leonhard/orte.csv: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

Can you help me please? Perhaps it is a problem of google chrome configuration?

Thanks a lot

Leonhard Diekmann

**Comment by mathiasrw** [comment]
You must serve your content from a http server. I suggest something like `npm install -g serve-static` and then do a 'serve-static' in your directory with files.

**Comment by LeonhardDiekmann2** [comment]
Hello!

Thanks a lot for your answer.
I decided to use alaSQL, because i want to use SQL whithout installing  
something else.
Therefore i tried an alternative solution.
The file-reader is used to read txt-File into an array (inputDaten)  and  
then the result is handled with split. It works without an http server.

Greetings from Leonhard Diekmann

Here's the code importing the csv-Data into the ORTE table.

var inputDaten = [];
var zeilen = [];
var werteliste = [];
let ort;
let ortsliste;

window.onload = function() {
     var asText = document.getElementById('asText');
     var textbox = document.getElementById('textbox');

     asText.addEventListener('change', function(e) {
         var file = asText.files[0];
         var textType = /text.*/;
         if (file.type.match(textType)) {
             var reader = new FileReader();
             reader.onload = function(e) {
                 inputDaten = reader.result;
             }
             reader.readAsText(file);
         } else {
             textbox.innerText = "Dateitype nicht unterstützt";
         }
     });
}
function datenImportieren (){
         zeilen = inputDaten.split("\n");
         console.log(zeilen);
         for (var i=0; i<zeilen.length-1; i++) {
             var zwischen = zeilen[i].split(';');
             werteliste.push(zwischen);
             console.log( i + " " + werteliste);
          }
          console.log(werteliste.length);
         for (var i=0; i < werteliste.length; i++){
                     var j=0;
                     ort = new Ort (werteliste[i][j].replace(/"/g,""),  
werteliste[i][j+1].replace(/"/g,""), werteliste[i][j+2].replace(/"/g,""));
                     ORTE.exec("Insert INTO cities VALUES (?,?, ?)", [  
ort.id, ort.city, ort.population]);
                     }
         console.log(ortsliste)

}





Am .08.2018, 07:41 Uhr, schrieb Mathias Rangel Wulff  
<notifications@github.com>:

>
> You must serve your content from a http server. I suggest something like  
> npm install -g serve->static and then do a 'serve-static' in your  
> directory with files.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Erstellt mit Operas E-Mail-Modul: http://www.opera.com/mail/
