### ISSUE TITLE
Syntax issue in Xlsx section of wiki

### ISSUE THREAD

**Issue by akumadare** [agershun/alasql#1053]
The examples of import in the wiki section: https://github.com/agershun/alasql/wiki/Xlsx#options are missing a close bracket for the xlsx fucntion of the SQL.

Should look like:

```
    alasql.promise('select * from xlsx("cities.xlsx",{sheetid:"Sheet2"})')
            .then(function(data){
                 console.log(data);
            }).catch(function(err){
                 console.log('Error:', err);
            });
```

This is the case for all 3 options listed in this section.

**Comment by mathiasrw** [comment]
How embarrassing. Its fixed now!
