### ISSUE TITLE
Question not issue: What is the best way to store data in phonegap with alasql?

### ISSUE THREAD

**Issue by peon501** [agershun/alasql#1056]
I know its not issue, but I think I will get more hits here :).
What is the best way to store data in PhoneGap/Cordova app for android with alasql, where can I find some kind of docs?
Where is better to store? to IndexedDB or to local filesystem?
https://stackoverflow.com/questions/52226525/what-is-the-best-way-to-store-data-in-phonegap-with-alasql

**Comment by craftpip** [comment]
@peon501 You can use the native sqlite plugin for cordova apps, however it is difficult to troubleshoot as it wont work on browser and android's live reload, you'll have to build to android for each change.
