### ISSUE TITLE
alasql : particular row

### ISSUE THREAD

**Issue by kasthuriharitha** [agershun/alasql#1061]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Programming question?
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something not working as expected? 
- Describe the problem  
- Provide code that replicates the problem 
- We suggest to spawn a jsfiddle from http://jsfiddle.net/mtt9r7rx/

Is that possible to get particular row and export the particular row data from the table to excel using alasql.

**Comment by mathiasrw** [comment]
Yes. If you want the 7th row you do a `row7 = alasql('select * from dataTable')[6]`
