### ISSUE TITLE
Fill all fields for Sparse Tables data import

### ISSUE THREAD

**Issue by aicioara** [agershun/alasql#1063]
## Issue

I have a CSV spreadsheet which contains a sparse matrix. When reading in the contents, cells with missing values do not produce values in the resulting JSON, which is expected. 

## Question 

Is there a way to enforce that? If not, is this a Pull Request you would accept (I expect it to be a property of the opts called `allowNull: true`).

## Usecase

Reading in a CSV which has an empty column, then writing it back. The code below would drop the empty columns

## Sample code

```es6
alasql('SELECT * FROM FILE(?, ?)', [event, {headers: true}], rows => {
    alasql('SELECT * INTO CSV("foo.csv", ?) FROM ?', [{headers: true}, rows]);
})
```

Please let me know if you prefer a jsfiddle to reproduce

**Comment by mathiasrw** [comment]
Sounds like it makes sense. Any chance you could make a jsfiddle with an example so im sure I understand?

**Comment by aicioara** [comment]
Is there a template JS fiddle I can start from?

**Comment by mathiasrw** [comment]
Sure! http://jsfiddle.net/98qL7m0c/

Its also part of the prefilled text when making a new issue:

```
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Question about how to ...
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something is not working as expected:
- Describe the problem  
- Provide code that replicates the problem 
- We suggest to spawn a jsfiddle from http://jsfiddle.net/98qL7m0c/
```

**Comment by aicioara** [comment]
Closing as I lost interest and did not manage to reproduce on small samples and latest version.
