### ISSUE TITLE
Search through multilevel structure

### ISSUE THREAD

**Issue by KyooMario** [agershun/alasql#1067]
Hello Mathias or Andrey,

We have the following multilevel structure (below just a simple example) and I want to extract some keys in a 1 level output. I tried the SEARCH approach but cannot succeed.
Can you advise?

```
[{
	"components" : [{
			"label" : "Date / Time",
			"format" : "yyyy/MM/dd",
			"mask" : false,
			"tableView" : true,
			"type" : "datetime",
			"input" : true,
			"key" : "dateTime"
		},
		{
			"label" : "Text Field",
			"allowMultipleMasks" : false,
			"showWordCount" : false,
			"showCharCount" : false,
			"tableView" : true,
			"type" : "textfield",
			"input" : true,
			"key" : "textField"
		},
			"components" : [{
				"input" : true,
				"key" : "number",
				"tableView" : true,
				"label" : "Number",
				"type" : "number"
				}]
			}]
		}]
``` 

Kind regards,
Mario

**Comment by mathiasrw** [comment]
Please let the world know what you are seeking to extrace (exact output from this input) and what you have  tried until now.

**Comment by mathiasrw** [comment]
Have you replicated the input data correctly? Its not valid JSON. (you are assigning a property to an array)

**Comment by KyooMario** [comment]
Hello Mathias,

Thanks. But then this is a typo: Where is it not correct?
But do you get what I mean? And is this doable with ALASQL?

Kind regards,
Mario

**Comment by mathiasrw** [comment]
Please provide valid JSON before we proceed. 

![image](https://user-images.githubusercontent.com/1063454/47015959-b0e12700-d14e-11e8-83e9-9c6fe590cec5.png)

**Comment by KyooMario** [comment]
Hello Mathias,

Here is the real life json. So What I would need is from each component the labe, key and type.
Kind  regards, Mario

`
[{
		"components" : [{
				"label" : "Date / Time",
				"format" : "yyyy/MM/dd",
				"mask" : false,
				"tableView" : true,
				"type" : "datetime",
				"input" : true,
				"key" : "dateTime",
				"suffix" : true,
				"widget" : {
					"type" : "calendar",
					"displayInTimezone" : "viewer",
					"language" : "en",
					"useLocaleSettings" : false,
					"allowInput" : true,
					"mode" : "single",
					"enableTime" : false,
					"noCalendar" : false,
					"format" : "yyyy/MM/dd",
					"defaultDate" : "",
					"hourIncrement" : 1,
					"minuteIncrement" : 1,
					"time_24hr" : false,
					"minDate" : "",
					"maxDate" : ""
				},
				"validate" : {
					"unique" : false,
					"customMessage" : "",
					"json" : "",
					"required" : false,
					"custom" : "",
					"customPrivate" : false
				},
				"conditional" : {
					"show" : "",
					"when" : "",
					"json" : "",
					"eq" : ""
				},
				"datePicker" : {
					"minDate" : "",
					"maxDate" : "",
					"showWeeks" : true,
					"startingDay" : 0,
					"initDate" : "",
					"minMode" : "day",
					"maxMode" : "year",
					"yearRows" : 4,
					"yearColumns" : 5
				},
				"properties" : {},
				"tags" : [],
				"customConditional" : "",
				"enableTime" : false,
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"multiple" : false,
				"defaultValue" : null,
				"protected" : false,
				"unique" : false,
				"persistent" : true,
				"hidden" : false,
				"clearOnHide" : true,
				"dataGridLabel" : false,
				"labelPosition" : "top",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"customDefaultValue" : "",
				"calculateValue" : "",
				"refreshOn" : "",
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"useLocaleSettings" : false,
				"allowInput" : true,
				"enableDate" : true,
				"defaultDate" : "",
				"displayInTimezone" : "viewer",
				"timezone" : "",
				"datepickerMode" : "day",
				"timePicker" : {
					"hourStep" : 1,
					"minuteStep" : 1,
					"showMeridian" : true,
					"readonlyInput" : false,
					"mousewheel" : true,
					"arrowkeys" : true
				},
				"id" : "eyu6ypd"
			}, {
				"label" : "Date",
				"allowMultipleMasks" : false,
				"showWordCount" : false,
				"showCharCount" : false,
				"clearOnHide" : false,
				"tableView" : true,
				"type" : "textfield",
				"input" : true,
				"key" : "date",
				"defaultValue" : "undefined",
				"customDefaultValue" : "value = moment(data.dateTime).format('YYYY/MM/DD');",
				"calculateValue" : "value = moment(data.dateTime).format('YYYY/MM/DD');",
				"refreshOn" : {
					"label" : "Date / Time",
					"value" : "dateTime"
				},
				"inputFormat" : "plain",
				"widget" : {
					"type" : ""
				},
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"suffix" : "",
				"multiple" : false,
				"protected" : false,
				"unique" : false,
				"persistent" : true,
				"hidden" : false,
				"dataGridLabel" : false,
				"labelPosition" : "top",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"validate" : {
					"required" : false,
					"custom" : "",
					"customPrivate" : false,
					"minLength" : "",
					"maxLength" : "",
					"minWords" : "",
					"maxWords" : "",
					"pattern" : ""
				},
				"conditional" : {
					"show" : null,
					"when" : null,
					"eq" : ""
				},
				"mask" : false,
				"inputType" : "text",
				"inputMask" : "",
				"id" : "e3p2wsp"
			}, {
				"label" : "Text Field",
				"allowMultipleMasks" : false,
				"showWordCount" : false,
				"showCharCount" : false,
				"tableView" : true,
				"type" : "textfield",
				"input" : true,
				"key" : "textField",
				"widget" : {
					"type" : ""
				},
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"suffix" : "",
				"multiple" : false,
				"defaultValue" : null,
				"protected" : false,
				"unique" : false,
				"persistent" : true,
				"hidden" : false,
				"clearOnHide" : true,
				"dataGridLabel" : false,
				"labelPosition" : "top",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"customDefaultValue" : "",
				"calculateValue" : "",
				"refreshOn" : "",
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"validate" : {
					"required" : false,
					"custom" : "",
					"customPrivate" : false,
					"minLength" : "",
					"maxLength" : "",
					"minWords" : "",
					"maxWords" : "",
					"pattern" : ""
				},
				"conditional" : {
					"show" : null,
					"when" : null,
					"eq" : ""
				},
				"mask" : false,
				"inputType" : "text",
				"inputMask" : "",
				"id" : "e1tgk4"
			}, {
				"input" : true,
				"key" : "number",
				"tableView" : true,
				"label" : "Number",
				"type" : "number",
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"suffix" : "",
				"multiple" : false,
				"defaultValue" : null,
				"protected" : false,
				"unique" : false,
				"persistent" : true,
				"hidden" : false,
				"clearOnHide" : true,
				"dataGridLabel" : false,
				"labelPosition" : "top",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"customDefaultValue" : "",
				"calculateValue" : "",
				"widget" : null,
				"refreshOn" : "",
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"validate" : {
					"required" : false,
					"custom" : "",
					"customPrivate" : false,
					"min" : "",
					"max" : "",
					"step" : "any",
					"integer" : ""
				},
				"conditional" : {
					"show" : null,
					"when" : null,
					"eq" : ""
				},
				"id" : "ej7ivl5"
			}, {
				"label" : "Select",
				"mask" : false,
				"tableView" : true,
				"type" : "select",
				"input" : true,
				"key" : "select",
				"data" : {
					"values" : [{
							"label" : "label 01",
							"value" : "label01"
						}, {
							"label" : "label 02",
							"value" : "label02"
						}
					],
					"json" : "",
					"url" : "",
					"resource" : "",
					"custom" : ""
				},
				"defaultValue" : "",
				"valueProperty" : "value",
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"suffix" : "",
				"multiple" : false,
				"protected" : false,
				"unique" : false,
				"persistent" : true,
				"hidden" : false,
				"clearOnHide" : true,
				"dataGridLabel" : false,
				"labelPosition" : "top",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"customDefaultValue" : "",
				"calculateValue" : "",
				"widget" : null,
				"refreshOn" : "",
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"validate" : {
					"required" : false,
					"custom" : "",
					"customPrivate" : false
				},
				"conditional" : {
					"show" : null,
					"when" : null,
					"eq" : ""
				},
				"dataSrc" : "values",
				"filter" : "",
				"searchEnabled" : true,
				"searchField" : "",
				"minSearch" : 0,
				"authenticate" : false,
				"template" : "<span>{{ item.label }}</span>",
				"selectFields" : "",
				"id" : "e10m5a"
			}, {
				"input" : true,
				"key" : "checkbox",
				"tableView" : true,
				"label" : "Checkbox",
				"type" : "checkbox",
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"suffix" : "",
				"multiple" : false,
				"defaultValue" : null,
				"protected" : false,
				"unique" : false,
				"persistent" : true,
				"hidden" : false,
				"clearOnHide" : true,
				"dataGridLabel" : true,
				"labelPosition" : "right",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"customDefaultValue" : "",
				"calculateValue" : "",
				"widget" : null,
				"refreshOn" : "",
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"validate" : {
					"required" : false,
					"custom" : "",
					"customPrivate" : false
				},
				"conditional" : {
					"show" : null,
					"when" : null,
					"eq" : ""
				},
				"inputType" : "checkbox",
				"value" : "",
				"name" : "",
				"id" : "ekk2buk"
			}, {
				"optionsLabelPosition" : "right",
				"values" : [{
						"label" : "label 01",
						"value" : "label01",
						"shortcut" : ""
					}, {
						"shortcut" : "",
						"label" : "label 02",
						"value" : "label02"
					}
				],
				"label" : "Radio",
				"inline" : false,
				"mask" : false,
				"tableView" : true,
				"type" : "radio",
				"input" : true,
				"key" : "radio",
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"suffix" : "",
				"multiple" : false,
				"defaultValue" : null,
				"protected" : false,
				"unique" : false,
				"persistent" : true,
				"hidden" : false,
				"clearOnHide" : true,
				"dataGridLabel" : false,
				"labelPosition" : "top",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"customDefaultValue" : "",
				"calculateValue" : "",
				"widget" : null,
				"refreshOn" : "",
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"validate" : {
					"required" : false,
					"custom" : "",
					"customPrivate" : false
				},
				"conditional" : {
					"show" : null,
					"when" : null,
					"eq" : ""
				},
				"inputType" : "radio",
				"fieldSet" : false,
				"id" : "e4dx3k"
			}, {
				"input" : true,
				"key" : "email",
				"tableView" : true,
				"label" : "Email",
				"type" : "email",
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"suffix" : "",
				"multiple" : false,
				"defaultValue" : null,
				"protected" : false,
				"unique" : false,
				"persistent" : true,
				"hidden" : false,
				"clearOnHide" : true,
				"dataGridLabel" : false,
				"labelPosition" : "top",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"customDefaultValue" : "",
				"calculateValue" : "",
				"widget" : null,
				"refreshOn" : "",
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"validate" : {
					"required" : false,
					"custom" : "",
					"customPrivate" : false,
					"minLength" : "",
					"maxLength" : "",
					"minWords" : "",
					"maxWords" : "",
					"pattern" : ""
				},
				"conditional" : {
					"show" : null,
					"when" : null,
					"eq" : ""
				},
				"mask" : false,
				"inputType" : "email",
				"inputMask" : "",
				"kickbox" : {
					"enabled" : false
				},
				"id" : "eg2ovzc"
			}, {
				"input" : true,
				"key" : "address",
				"tableView" : true,
				"label" : "Address",
				"type" : "address",
				"map" : {
					"key" : "",
					"region" : ""
				},
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"suffix" : "",
				"multiple" : false,
				"defaultValue" : null,
				"protected" : false,
				"unique" : false,
				"persistent" : true,
				"hidden" : false,
				"clearOnHide" : true,
				"dataGridLabel" : false,
				"labelPosition" : "top",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"customDefaultValue" : "",
				"calculateValue" : "",
				"widget" : null,
				"refreshOn" : "",
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"validate" : {
					"required" : false,
					"custom" : "",
					"customPrivate" : false,
					"minLength" : "",
					"maxLength" : "",
					"minWords" : "",
					"maxWords" : "",
					"pattern" : ""
				},
				"conditional" : {
					"show" : null,
					"when" : null,
					"eq" : ""
				},
				"mask" : false,
				"inputType" : "text",
				"inputMask" : "",
				"id" : "e7e26i6"
			}, {
				"questions" : [{
						"label" : "Question 01",
						"value" : "question01"
					}, {
						"label" : "Question 02",
						"value" : "question02"
					}
				],
				"values" : [{
						"label" : "Value 01",
						"value" : "value01"
					}, {
						"label" : "Value 02",
						"value" : "value02"
					}
				],
				"label" : "Survey",
				"mask" : false,
				"tableView" : true,
				"type" : "survey",
				"input" : true,
				"key" : "survey",
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"suffix" : "",
				"multiple" : false,
				"defaultValue" : null,
				"protected" : false,
				"unique" : false,
				"persistent" : true,
				"hidden" : false,
				"clearOnHide" : true,
				"dataGridLabel" : false,
				"labelPosition" : "top",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"customDefaultValue" : "",
				"calculateValue" : "",
				"widget" : null,
				"refreshOn" : "",
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"validate" : {
					"required" : false,
					"custom" : "",
					"customPrivate" : false
				},
				"conditional" : {
					"show" : null,
					"when" : null,
					"eq" : ""
				},
				"id" : "e4rra2"
			}, {
				"label" : "Panel",
				"title" : "Panel 01",
				"collapsible" : false,
				"mask" : false,
				"tableView" : false,
				"type" : "panel",
				"input" : false,
				"key" : "panel",
				"components" : [{
						"input" : true,
						"key" : "textField2",
						"tableView" : true,
						"label" : "Text Field",
						"type" : "textfield",
						"placeholder" : "",
						"prefix" : "",
						"customClass" : "",
						"suffix" : "",
						"multiple" : false,
						"defaultValue" : null,
						"protected" : false,
						"unique" : false,
						"persistent" : true,
						"hidden" : false,
						"clearOnHide" : true,
						"dataGridLabel" : false,
						"labelPosition" : "top",
						"labelWidth" : 30,
						"labelMargin" : 3,
						"description" : "",
						"errorLabel" : "",
						"tooltip" : "",
						"hideLabel" : false,
						"tabindex" : "",
						"disabled" : false,
						"autofocus" : false,
						"dbIndex" : false,
						"customDefaultValue" : "",
						"calculateValue" : "",
						"widget" : null,
						"refreshOn" : "",
						"clearOnRefresh" : false,
						"validateOn" : "change",
						"validate" : {
							"required" : false,
							"custom" : "",
							"customPrivate" : false,
							"minLength" : "",
							"maxLength" : "",
							"minWords" : "",
							"maxWords" : "",
							"pattern" : ""
						},
						"conditional" : {
							"show" : null,
							"when" : null,
							"eq" : ""
						},
						"mask" : false,
						"inputType" : "text",
						"inputMask" : "",
						"id" : "ewoxdkt"
					}
				],
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"suffix" : "",
				"multiple" : false,
				"defaultValue" : null,
				"protected" : false,
				"unique" : false,
				"persistent" : false,
				"hidden" : false,
				"clearOnHide" : false,
				"dataGridLabel" : false,
				"labelPosition" : "top",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"customDefaultValue" : "",
				"calculateValue" : "",
				"widget" : null,
				"refreshOn" : "",
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"validate" : {
					"required" : false,
					"custom" : "",
					"customPrivate" : false
				},
				"conditional" : {
					"show" : null,
					"when" : null,
					"eq" : ""
				},
				"theme" : "default",
				"breadcrumb" : "default",
				"id" : "ewvk67c"
			}, {
				"input" : false,
				"key" : "columns",
				"tableView" : false,
				"label" : "Columns",
				"type" : "columns",
				"columns" : [{
						"components" : [{
								"input" : true,
								"key" : "textField3",
								"tableView" : true,
								"label" : "Text Field",
								"type" : "textfield",
								"placeholder" : "",
								"prefix" : "",
								"customClass" : "",
								"suffix" : "",
								"multiple" : false,
								"defaultValue" : null,
								"protected" : false,
								"unique" : false,
								"persistent" : true,
								"hidden" : false,
								"clearOnHide" : true,
								"dataGridLabel" : false,
								"labelPosition" : "top",
								"labelWidth" : 30,
								"labelMargin" : 3,
								"description" : "",
								"errorLabel" : "",
								"tooltip" : "",
								"hideLabel" : false,
								"tabindex" : "",
								"disabled" : false,
								"autofocus" : false,
								"dbIndex" : false,
								"customDefaultValue" : "",
								"calculateValue" : "",
								"widget" : null,
								"refreshOn" : "",
								"clearOnRefresh" : false,
								"validateOn" : "change",
								"validate" : {
									"required" : false,
									"custom" : "",
									"customPrivate" : false,
									"minLength" : "",
									"maxLength" : "",
									"minWords" : "",
									"maxWords" : "",
									"pattern" : ""
								},
								"conditional" : {
									"show" : null,
									"when" : null,
									"eq" : ""
								},
								"mask" : false,
								"inputType" : "text",
								"inputMask" : "",
								"id" : "exstqnc"
							}
						],
						"width" : 6,
						"offset" : 0,
						"push" : 0,
						"pull" : 0,
						"type" : "column",
						"input" : true,
						"key" : "",
						"tableView" : true,
						"label" : "",
						"placeholder" : "",
						"prefix" : "",
						"customClass" : "",
						"suffix" : "",
						"multiple" : false,
						"defaultValue" : null,
						"protected" : false,
						"unique" : false,
						"persistent" : true,
						"hidden" : false,
						"clearOnHide" : true,
						"dataGridLabel" : false,
						"labelPosition" : "top",
						"labelWidth" : 30,
						"labelMargin" : 3,
						"description" : "",
						"errorLabel" : "",
						"tooltip" : "",
						"hideLabel" : false,
						"tabindex" : "",
						"disabled" : false,
						"autofocus" : false,
						"dbIndex" : false,
						"customDefaultValue" : "",
						"calculateValue" : "",
						"widget" : null,
						"refreshOn" : "",
						"clearOnRefresh" : false,
						"validateOn" : "change",
						"validate" : {
							"required" : false,
							"custom" : "",
							"customPrivate" : false
						},
						"conditional" : {
							"show" : null,
							"when" : null,
							"eq" : ""
						},
						"id" : "etmhene"
					}, {
						"components" : [{
								"input" : true,
								"key" : "textField4",
								"tableView" : true,
								"label" : "Text Field",
								"type" : "textfield",
								"placeholder" : "",
								"prefix" : "",
								"customClass" : "",
								"suffix" : "",
								"multiple" : false,
								"defaultValue" : null,
								"protected" : false,
								"unique" : false,
								"persistent" : true,
								"hidden" : false,
								"clearOnHide" : true,
								"dataGridLabel" : false,
								"labelPosition" : "top",
								"labelWidth" : 30,
								"labelMargin" : 3,
								"description" : "",
								"errorLabel" : "",
								"tooltip" : "",
								"hideLabel" : false,
								"tabindex" : "",
								"disabled" : false,
								"autofocus" : false,
								"dbIndex" : false,
								"customDefaultValue" : "",
								"calculateValue" : "",
								"widget" : null,
								"refreshOn" : "",
								"clearOnRefresh" : false,
								"validateOn" : "change",
								"validate" : {
									"required" : false,
									"custom" : "",
									"customPrivate" : false,
									"minLength" : "",
									"maxLength" : "",
									"minWords" : "",
									"maxWords" : "",
									"pattern" : ""
								},
								"conditional" : {
									"show" : null,
									"when" : null,
									"eq" : ""
								},
								"mask" : false,
								"inputType" : "text",
								"inputMask" : "",
								"id" : "em4tzio"
							}
						],
						"width" : 6,
						"offset" : 0,
						"push" : 0,
						"pull" : 0,
						"type" : "column",
						"input" : true,
						"key" : "",
						"tableView" : true,
						"label" : "",
						"placeholder" : "",
						"prefix" : "",
						"customClass" : "",
						"suffix" : "",
						"multiple" : false,
						"defaultValue" : null,
						"protected" : false,
						"unique" : false,
						"persistent" : true,
						"hidden" : false,
						"clearOnHide" : true,
						"dataGridLabel" : false,
						"labelPosition" : "top",
						"labelWidth" : 30,
						"labelMargin" : 3,
						"description" : "",
						"errorLabel" : "",
						"tooltip" : "",
						"hideLabel" : false,
						"tabindex" : "",
						"disabled" : false,
						"autofocus" : false,
						"dbIndex" : false,
						"customDefaultValue" : "",
						"calculateValue" : "",
						"widget" : null,
						"refreshOn" : "",
						"clearOnRefresh" : false,
						"validateOn" : "change",
						"validate" : {
							"required" : false,
							"custom" : "",
							"customPrivate" : false
						},
						"conditional" : {
							"show" : null,
							"when" : null,
							"eq" : ""
						},
						"id" : "e9sw1d"
					}
				],
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"suffix" : "",
				"multiple" : false,
				"defaultValue" : null,
				"protected" : false,
				"unique" : false,
				"persistent" : false,
				"hidden" : false,
				"clearOnHide" : false,
				"dataGridLabel" : false,
				"labelPosition" : "top",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"customDefaultValue" : "",
				"calculateValue" : "",
				"widget" : null,
				"refreshOn" : "",
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"validate" : {
					"required" : false,
					"custom" : "",
					"customPrivate" : false
				},
				"conditional" : {
					"show" : null,
					"when" : null,
					"eq" : ""
				},
				"autoAdjust" : false,
				"id" : "e0k9bhf"
			}, {
				"input" : false,
				"key" : "fieldSet",
				"tableView" : true,
				"label" : "Field Set",
				"type" : "fieldset",
				"components" : [{
						"input" : true,
						"key" : "textField5",
						"tableView" : true,
						"label" : "Text Field",
						"type" : "textfield",
						"placeholder" : "",
						"prefix" : "",
						"customClass" : "",
						"suffix" : "",
						"multiple" : false,
						"defaultValue" : null,
						"protected" : false,
						"unique" : false,
						"persistent" : true,
						"hidden" : false,
						"clearOnHide" : true,
						"dataGridLabel" : false,
						"labelPosition" : "top",
						"labelWidth" : 30,
						"labelMargin" : 3,
						"description" : "",
						"errorLabel" : "",
						"tooltip" : "",
						"hideLabel" : false,
						"tabindex" : "",
						"disabled" : false,
						"autofocus" : false,
						"dbIndex" : false,
						"customDefaultValue" : "",
						"calculateValue" : "",
						"widget" : null,
						"refreshOn" : "",
						"clearOnRefresh" : false,
						"validateOn" : "change",
						"validate" : {
							"required" : false,
							"custom" : "",
							"customPrivate" : false,
							"minLength" : "",
							"maxLength" : "",
							"minWords" : "",
							"maxWords" : "",
							"pattern" : ""
						},
						"conditional" : {
							"show" : null,
							"when" : null,
							"eq" : ""
						},
						"mask" : false,
						"inputType" : "text",
						"inputMask" : "",
						"id" : "ewkpwc"
					}
				],
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"suffix" : "",
				"multiple" : false,
				"defaultValue" : null,
				"protected" : false,
				"unique" : false,
				"persistent" : false,
				"hidden" : false,
				"clearOnHide" : true,
				"dataGridLabel" : false,
				"labelPosition" : "top",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"customDefaultValue" : "",
				"calculateValue" : "",
				"widget" : null,
				"refreshOn" : "",
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"validate" : {
					"required" : false,
					"custom" : "",
					"customPrivate" : false
				},
				"conditional" : {
					"show" : null,
					"when" : null,
					"eq" : ""
				},
				"legend" : "",
				"id" : "e180lmk"
			}, {
				"type" : "button",
				"label" : "Submit",
				"key" : "submit",
				"disableOnInvalid" : true,
				"theme" : "primary",
				"input" : true,
				"tableView" : true,
				"placeholder" : "",
				"prefix" : "",
				"customClass" : "",
				"suffix" : "",
				"multiple" : false,
				"defaultValue" : null,
				"protected" : false,
				"unique" : false,
				"persistent" : false,
				"hidden" : false,
				"clearOnHide" : true,
				"dataGridLabel" : true,
				"labelPosition" : "top",
				"labelWidth" : 30,
				"labelMargin" : 3,
				"description" : "",
				"errorLabel" : "",
				"tooltip" : "",
				"hideLabel" : false,
				"tabindex" : "",
				"disabled" : false,
				"autofocus" : false,
				"dbIndex" : false,
				"customDefaultValue" : "",
				"calculateValue" : "",
				"widget" : null,
				"refreshOn" : "",
				"clearOnRefresh" : false,
				"validateOn" : "change",
				"validate" : {
					"required" : false,
					"custom" : "",
					"customPrivate" : false
				},
				"conditional" : {
					"show" : null,
					"when" : null,
					"eq" : ""
				},
				"size" : "md",
				"leftIcon" : "",
				"rightIcon" : "",
				"block" : false,
				"action" : "submit",
				"id" : "efj1vkp"
			}
		],
		"Title" : "Form 01",
		"Folder" : "Team",
		"SPID" : 4
	}
]

`

**Comment by mathiasrw** [comment]
And what would the expected output be from this input?

**Comment by KyooMario** [comment]
Hello Mathias,

I should add "where input == true AND key != empty or null"
Then the result would be:

`
result : [
			{
			"label" : "Date / Time",
			"type" : "datetime",
			"key" : "dateTime"
			},
			{
			"label" : "Date",
			"type" : "textfield",
			"key" : "date"
			},
			{
			"label" : "Text Field",
			"type" : "textfield",
			"key" : "textField"
			},
			{
			"label" : "Number",
			"type" : "number",
			"key" : "number"
			},
			{
			"label" : "Select",
			"type" : "select",
			"key" : "select"
			},
			{
			"label" : "Checkbox",
			"type" : "checkbox",
			"key" : "checkbox"
			},
			{
			"label" : "Radio",
			"type" : "radio",
			"key" : "radio"
			},
			{
			"label" : "Email",
			"type" : "email",
			"key" : "email"
			},
			{
			"label" : "Address",
			"type" : "address",
			"key" : "address"
			},
			{
			"label" : "Survey",
			"type" : "survey",
			"key" : "survey"
			},
			{
			"label" : "Text Field",
			"type" : "textfield",
			"key" : "textField2"
			},
			{
			"label" : "Text Field",
			"type" : "textfield",
			"key" : "textField3"
			},
			{
			"label" : "Text Field",
			"type" : "textfield",
			"key" : "textField4"
			},
			{
			"label" : "Text Field",
			"type" : "textfield",
			"key" : "textField5"
			}
		]
`

Hope I didn't make a typo ;-)

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello Mathias,

With a bit of coding I got the desired result with the following lines. If you have a better approach please advise.

`
var resultJson = { result: []}

function getDesiredValues(json) {

	let components = json.components
	
	for (var index = 0; index < components.length; index++) {
        checkForDesiredKeys(components[index])
	}

    console.log(resultJson)
}

function checkForDesiredKeys(data) {

    let keys = Object.keys(data)
    var tempJson = {label: '', key: '', type: ''}

    for(var index = 0; index < keys.length; index++) {

        if(keys[index] == 'label') {
            tempJson['label'] = data.label
        }else if(keys[index] == 'key') {
            tempJson['key'] = data.key
        }else if(keys[index] == 'type') {
            tempJson['type'] = data.type
        }else {
            if(data[keys[index]]) {
                if(typeof data[keys[index]] == 'object') {
                    checkForDesiredKeys(data[keys[index]])
                }
            }
        }
    }

    if(tempJson.label != "" || tempJson.key != "" || tempJson.type != "") {
        resultJson.result.push(tempJson)
    }

}
`

Kind regards,
Mario

**Comment by mathiasrw** [comment]
This is what you are looking for

```
alasql('SEARCH components /  AS @c WHERE(@c->label AND @c->type AND @c->key) RETURN(@c->label AS label,@c->type AS type,@c->key AS key) FROM ?',data);
```

http://jsfiddle.net/w4sdx07n/

bonusinfo - please use 3 ``` ` ``` when providing multiline code instead of just one.

**Comment by KyooMario** [comment]
Hello Mathias,

Thanks. But your suggestion only covers the root element "components" not the nested "components".

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello Mathias,

I have a bit of a problem: Hope you can help.

When using the alasql script in a webpart on a Sharepoint Modern site page we get the following error message and thus the script is not loaded ;-(
Unexpected anonymous AMD define
Can you advise?
Kind regards,
Mario
