### ISSUE TITLE
RawGit is shutting down

### ISSUE THREAD

**Issue by reviewher** [agershun/alasql#1068]
https://rawgit.com/ "RawGit is now in a sunset phase and will soon shut down."

There are a few references in the codebase, but the ones that may cause some trouble are in [`test418.js`](https://github.com/agershun/alasql/blob/master/test/test418.js).  That test appears to pull files with XHR.

Should those test files find a new home with another host?

**Comment by mathiasrw** [comment]
Thank you for letting us know!

> Should those test files find a new home with another host?

Yes, for sure. Maybe we just wack them into alasql.org - then we have it all under control :)
