### ISSUE TITLE
Import multiple sheet pages in Excel single table. Do you support it now?

### ISSUE THREAD

**Issue by SuperTC** [agershun/alasql#1071]
Import multiple sheet pages in Excel single table. Do you support it now?

**Comment by SuperTC** [comment]
如果支持的话，要如何做到

**Comment by mathiasrw** [comment]
Do you mean many sheets in same file?

**Comment by SuperTC** [comment]
是的，一个工作表中，存在多个sheet页的数据，现在只支持一个sheet页数据的上传

**Comment by SuperTC** [comment]
what happened?

**Comment by mathiasrw** [comment]
Your 2 last comments where not in english, so I closed the issue. Please reopen when you respond to the question 

> Do you mean many sheets in same file?
