### ISSUE TITLE
Can alasql be used to create a new database within a usb

### ISSUE THREAD

**Issue by monsa12** [agershun/alasql#1076]
Can alasql be used to create a new database within a usb, and then edit, delete, or add information to it, each time the user wants?

**Comment by mathiasrw** [comment]
Well... AlaSQL needs javascript to run. Often you would use the browser - but you do not have access to the local file system from the browser. 

Another option is to use it from node, but that demands that node is installed on the computer where you put in the USB. SO - it could be done, but not optimal. 

Maybe the best solution is to look into how to make your interface in https://electronjs.org/ and using its API to interact with your local filesystem
