### ISSUE TITLE
AlaSQL UPDATE multi dimentional table value

### ISSUE THREAD

**Issue by furkangkhsn** [agershun/alasql#1078]
I have a problem with AlaSQL. My problem is, I have a table like:
```

[{
    "masa_id": 1,
    "masa_icerik": {
        "urunler": [{
            "id": 15,
            "adet": 5
        }, {
            "id": 16,
            "adet": 5
        }],
        "Adisyon ID": "afasda"
    }
}, {
    "masa_id": 2,
    "masa_icerik": {
        "urunler": [],
        "Adisyon ID": "K1543422069720"
    }
}]
```
I want to select one entry based on masa_id. Then get that entry and search if its masa_icerik->urunler array has an object with id=16. If found that id, I want to update that masa_icerik->urunler->adet. I tried the SEARCH but I can't make it work.

**Comment by furkangkhsn** [comment]
> Please provide a working example in jsfiddle.com of one or more examples of the code you have tested.

There is no working example sir. I want to update the `urunler` part using id.

maybe like this `alasql("UPDATE masalar SET masa_icerik->urunler->0=? WHERE masa_id=1", [{id: 12, adet: 5, fiyati: 5, odenen: 5}])` But this code didn't work either.

**Comment by mathiasrw** [comment]
You can not update dat that you are parsing in.

**Comment by furkangkhsn** [comment]
I soolve my problem by using for loop. I'm able to access my data from alasql.tables.tableName.data and then use for loop on the data. I guess there is no Query for this.
