### ISSUE TITLE
object inside object

### ISSUE THREAD

**Issue by r00nscapenab** [agershun/alasql#1080]
i have this data, 

var data = [{a:1,b:{amount: 10}, c:1}, {a:2,b:{amount: 20}, c:1}, {a:1,b:{amount: 30}, c:2}];

and i want to do something like this

SELECT SUM(b.amount) FROM ? , data GROUP BY a, c

any ideas?

**Comment by mathiasrw** [comment]
Please have a look at 
- https://github.com/agershun/alasql/wiki/json
- https://github.com/agershun/alasql/wiki/SEARCH
- https://github.com/agershun/alasql/wiki/How-to-search-deep-nested-JSON
