### ISSUE TITLE
Localstorage empty, stuck with "There is no any AlaSQL databases in localStorage" error msg

### ISSUE THREAD

**Issue by BillDietrich** [agershun/alasql#1097]
I just started using AlaSQL 0.4.11 with Node.js and Angular 7, running in Firefox browser 65.0.1.  I want to save the AlaSQL database in the browser's localstorage.  I got some basic create-db, create-table, insert-into-table, select-from-table, close-database, open-database, select-from-table code working.  But when I quit the browser, launched browser again, did open-database, and the database was gone.  It's not persistent.

I decided maybe the browser was clearing out local storage when it closed, so I went into Firefox's settings and whitelisted localhost for storage, etc.  Some site with no name had some data stored; is that AlaSQL ?  Restarted Firefox and my app a couple of times, still couldn't get the database to be persistent.

Then I emptied all site data and cookies out of Firefox.  Well, after that NOTHING in AlaSQL worked !  Everything I try gives a "There is no any AlaSQL databases in localStorage" error in the browser console.  Can't create a new database, drop a database, open a database, nothing.  I restarted my app and FF multiple times, no luck.

Is there some special initialization that happens some other way ?  How can I recover ?

If you want to see code, here is some:

    alasql("SET AUTOCOMMIT ON");

    alasql("DROP localStorage DATABASE matrixdashboard");

    alasql("CREATE localStorage DATABASE matrixdashboard");

    alasql("ATTACH localStorage DATABASE matrixdashboard AS matrixdashboard");

    alasql("USE matrixdashboard");

None of these work, no matter which is first, the first one throws "There is no any AlaSQL databases in localStorage" and things go downhill from there.

**Comment by BillDietrich** [comment]
Well, it's fixed now.  Maybe I forgot to try just starting with a CREATE after it got into this state ?  I quit everything, did "npm remove alasql", then "npm install alasql", DROP still gave the error if it was the first operation, but CREATE as first operation worked.  And now the database is persistent across quit/relaunch of Firefox, too.  I must have gotten the storage into some weird state or something.

**Comment by mathiasrw** [comment]
Glad to hear you sorted it out. Please remember that any interaction with localstorage is async, so your risk running into problems if you dont handle the async behavour. I recommend the promise notation from https://github.com/agershun/alasql/wiki/Async
