### ISSUE TITLE
RE: bad lib url in Live Demo 

### ISSUE THREAD

**Issue by weinerk** [agershun/alasql#1099]
on this page:
https://github.com/agershun/alasql

Live Demo link http://jsfiddle.net/agershun/oxv4rzzc/
points to a demo with a bad src for alasql js lib - 
http://alasql.org/console/alasql-worker.min.js

need to either fix the source  or change the lib url

**Comment by mathiasrw** [comment]
Oh! thank you for taking the time to letting us know. 

I cant find the link to http://jsfiddle.net/agershun/oxv4rzzc/ on https://github.com/agershun/alasql

Any chance you could pinpoint it more exactly?

Im going to swap it with this updated link: https://jsfiddle.net/3vnmu2fo/

**Comment by weinerk** [comment]
on this page:
https://github.com/agershun/alasql
there are 4 links called "live demo"
number 3 and number 4 are broken
