### ISSUE TITLE
ORDER BY does not support parameter

### ISSUE THREAD

**Issue by rophy** [agershun/alasql#1100]
It seems this has no effect: 

```javascript
alasql.promise( 'SELECT * FROM t ORDER BY ?', [ 'COL_NAME' ] )
```

While this works:

```javascript
alasql.promise( 'SELECT * FROM t ORDER BY COL_NAME'  )
```

Version: 0.4.11

**Comment by ronayumik** [comment]
hi, I want to help on this issue. Can you give me things to lead on before jumping to the code? @mathiasrw

**Comment by Peter-Takhar** [comment]
Do you mind if I take a crack at this?

**Comment by mathiasrw** [comment]
@Peter-Takhar SO sorry I only get back to you now. Yes, you are very welcome to dig in.

**Comment by biddwan09** [comment]
Hi @mathiasrw  please review the below pull request and let me know your feedback
https://github.com/agershun/alasql/pull/1141

**Comment by biddwan09** [comment]
Hi @mathiasrw  Please check the pull request as it is solving this issue and all the test cases are passing . Let me know if any further changes are required

**Comment by mathiasrw** [comment]
@biddwan09 Thank you so much. I will have a look!
