### ISSUE TITLE
User-defined  functions are broken

### ISSUE THREAD

**Issue by daffodilistic** [agershun/alasql#1110]
Hi, 
I'm currently developing a web app which uses alasql, but it seems that user-defined functions are broken. 

A sample project can be found here: http://jsfiddle.net/agesn9c1/3/

**Comment by nickdeis** [comment]
Hey @daffodilistic ,
I think `cube` may be a reserved word from OLAP stuff. `cubed` or `CUBED` works.
Cheers,
Nick

**Comment by mathiasrw** [comment]
Thank you @nick

**Comment by daffodilistic** [comment]
Thanks for the clarification! 👍
