### ISSUE TITLE
Export CSV data to Server file

### ISSUE THREAD

**Issue by scourby** [agershun/alasql#1116]
Hello All,

When I try to use AlaSQL to append a server-side CSV, it continues to create and download the CSV. Anyone know if it is possible to push it to server as opposed to local machine? 

I am working on a form where users will submit changes to be made. once they enter data into the form, I need that data to go to my server instead of exporting to local machine. Any help is appreciated.

CODE: 
(Note: having the script tag in the below was causing formatting issues)

```
function exportData(){ 
		alasql.promise('SELECT * INTO CSV("MyFile.csv", {headers:false}) FROM ?',[data])
            .then(function(){
                 window.alert('Data saved');
		reload();
            }).catch(function(err){
                 window.alert('Error: Contact Support', err);
            });;
		}
	var data = [document.getElementById("trackingId"), document.getElementById("AttribName"), document.getElementById("AttribValue"), document.getElementById("Dooeet")]
/*	var tid = document.getElementById("trackingId");
	var atn = document.getElementById("AttribName");
	var atv = document.getElementById("AttribValue");
	var act = document.getElementById("Dooeet");
	var data = [tid, atn, atv, act]  */

		<div class="wrapper">	
			<form action="#" class="w3-left-align">
				<label for="trackingId">Tracking ID:</label>
				<input type="text" name="trackingId" id="trackingId"></input>
				<label for="AttribName">Attribute Name:</label>
				<fieldset>
					<select name="AttribName" id="AttribName">
						<option value="Owner" selected="selected">Owner</option>
						<option value="Email">Email</option>
					</select>
				</fieldset>
				<label for="AttribValue">Attribute Value:</label>
				<textarea type="text" name="AttribValue" id="AttribValue" rows="4" cols="50" maxlength="150" placeholder="Text may not exceed 150 total characters.">
				</textarea>
				<label for="Dooeet">Action:</label>
				<fieldset>
					<select name="Dooeet" id="Dooeet">
						<option value="append" selected="selected">Append</option>
						<option value="revoke">Revoke</option>
					</select>
				</fieldset>
				<button onclick="exportData()">Update</button>
			</form>
                </div>
```

Also, when it does create the local CSV, I has no content. Not sure why it isn't posting either.

Thoughts?

**Comment by scourby** [comment]
`		<div class="wrapper">	
			<form action="#" class="w3-left-align">
				<label for="trackingId">Tracking ID:</label>
				<input type="text" name="trackingId" id="trackingId"></input>
				<label for="AttribName">Attribute Name:</label>
				<fieldset>
					<select name="AttribName" id="AttribName">
						<option value="Owner" selected="selected">Owner</option>
						<option value="Email">Email</option>
					</select>
				</fieldset>
				<label for="AttribValue">Attribute Value:</label>
				<textarea type="text" name="AttribValue" id="AttribValue" rows="4" cols="50" maxlength="150" placeholder="Text may not exceed 150 total characters.">
				</textarea>
				<label for="Dooeet">Action:</label>
				<fieldset>
					<select name="Dooeet" id="Dooeet">
						<option value="append" selected="selected">Append</option>
						<option value="revoke">Revoke</option>
					</select>
				</fieldset>
				<button onclick="exportData()">Update</button>
			</form>
                </div>`

**Comment by mathiasrw** [comment]
You are generating the csv in the browser = client side. If you want to push the file to the server you will have to upload it as any other file from JS. 

Not sure you can get the csv code directly from alasql. I suggest you construct a csv from the data using https://www.papaparse.com
