### ISSUE TITLE
"WHERE ? =" Command not working with Passed Value

### ISSUE THREAD

**Issue by scourby** [agershun/alasql#1117]
I am working with a very large Excel Spreadsheet that has a few unique columns that I am trying to do queries by. Currently, I am running into an issue where doing a LIKE query against one of these columns returns nothing. If I do a manual query of the same data as shown in the console from logging, it performs the query flawlessly. It seems to not be liking something about the value being passed.

Query Example:
`function getDetails(val){
		alasql.promise('SELECT * FROM xlsx("FileName.xlsx") WHERE Serial like ? ',[val])
			.then(function(deets){
				let fern = JSON.stringify(deets)
				console.log('Now comes the FUN:')
				console.log(deets); //getting nothing back from either log under the promise
				console.log(fern);
			}).catch(function(err){
				 console.log('There was an error reading the source file.:', err);
			})
		console.log('Now loading data for:')
		console.log(val); //Shows that val = "%123456789%"
};`

Value Pass:
`<button value="&quot;&percnt;[[Serial]]&percnt;&quot;" onclick="getDetails(this.value)">Details</button>` 

Console log comes back with nothing but a blank array. If I manually enter the value of (val) into the query in the console log it works.

Example:
`alasql.promise('SELECT * FROM xlsx("FileName.xlsx") WHERE Serial like "%123456789%" ')
			.then(function(deets){
				let fern = JSON.stringify(deets)
				console.log('Now comes the FUN:')
				console.log(deets); //getting full details on both of these when pushing this through the browser console.
				console.log(fern);
			})`

I am extremely confused by how this is not working. Since the console logging of the "val" value returns the correct search parameters, I am at a loss. I have tried it with passing everything from just the number, to the number and quotes/percents individually and both.. Just going in circles here. 

I just need a way to pass the value to do the WHERE query - any thoughts/suggestions appreciated.

**Comment by scourby** [comment]
I was trying to be too exact SQL on this. After removing the quotes and percent marks, I was able to get it to query correctly with just the data passed through. I am curious now, however, how to get it to where I can pass the information like this:

`        let x = document.getElementById("selector1").selectedIndex;
        let y = document.getElementById("selector1").options;
        let attribNam = y[x].text;
        let attribVal = document.getElementById("atval1").value;
        console.log(attribNam, attribVal);
		alasql.promise('select * from xlsx("File.xlsx") WHERE ? = ?',[attribNam,attribVal])`

When I try to do this it fails every time. If I manually enter "WHERE Name = ?" it works, but any time I try to pass the variable for the row name like "WHERE ? = James" or as the above script block shoes,, it does not return anything. Any thoughts?

**Comment by mathiasrw** [comment]
I feel like changing the last line to 

    alasql.promise('select * from xlsx("File.xlsx") WHERE '+attribNam+' = ?',[attribVal])

will make it run. Please reopen if this does not help.
