### ISSUE TITLE
Update: use parameters for set and where

### ISSUE THREAD

**Issue by Autoflow** [agershun/alasql#1127]
The example query i'm looking for is:
alasql("UPDATE events SET ? WHERE ?", [{synchronized:true}, {name:'myName']);

Is this possible with alasql?

**Comment by mathiasrw** [comment]
No. You will have to set the keys in the string

alasql("UPDATE events SET synchronized WHERE name = ?", [true, 'myName']);

If data is dynamic you would need to do some hangkypanky constructing the string.
