### ISSUE TITLE
Not getting proper response

### ISSUE THREAD

**Issue by vikash2696** [agershun/alasql#1128]
Hi I am using this code: 

 var items = [{
        2012: "237899273972397",
        2013: "237899273972397",
        dob: "1985-10-10"
      }, {
        2012: "237899273972397",
        2013: "237899273972397",
        dob: "1988-12-22"
      }, {
        2012: "237899273972397",
        2013: "237899273972397",
        dob: "2010-01-02"
      }, {
        2012: "237899273972397",
        2013: "237899273972397",
        dob: "2009-03-21"
      }, {
        2012: "237899273972397",
        2013: "237899273972397",
        dob: "2011-12-12"
      }, {
        2012: "237899273972397",
        2013: "237899273972397",
        dob: "2011-12-12"
      }, {
        2012: "237899273972397",
        2013: "237899273972397",
        dob: "2011-12-12"
      }, {
        2012: "237899273972397",
        2013: "237899273972397",
        dob: "2011-12-12"
      }, {
        2012: "237899273972397",
        2013: "237899273972397",
        dob: "2011-12-12"
      }, {
        2012: "237899273972397",
        2013: "237899273972397",
        dob: "2011-12-12"
      }, {
        2012: "237899273972397",
        2013: "237899273972397",
        dob: "2011-12-12"
      }, {
        2012: "237899273972397",
        2013: "237899273972397",
        dob: "2004-10-12"
      }];

      var opts = {
        sheetid: "FG Risk Analysis",
        header: true,
        style: 'background:#00FF00',
        column: {
          style: 'font-size:30px'
        },
        columns: [
          { columnid: 'dob', title: 'Birthday' }, { columnid: 'name', title: 'qqqq' }, { columnid: 'email', title: 'fsss' }]
      };
      console.log(opts);

      var name = 'FG_risk_analysis_report.xlsx';
      var res = alasql('SELECT INTO XLSX(' + '"' + name + '"' + ',?) FROM ?', [opts, items]);

But I am not getting proper response: I am not able to reorder the columns and also not able to remane the column header bu title configuration.

Can you please help me out.

**Comment by vikash2696** [comment]
There is no impact of columns in opts.

**Comment by mathiasrw** [comment]
Please make the shortes example you can replicating the issue and come back with a jsfiddle.
