### ISSUE TITLE
Add ES6 template strings and/or template-functions for SELECT

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#113]
The idea is to mix SQL and JavaScript variables in one string, like ES6 does:
```js
    var filename = 'myfile.xlsx';
    alasql('SELECT * FROM XLSX("${filename}")',[],function(res){ ... });
```
instead of:
```js
    alasql('SELECT * FROM XLSX("'+filename'+'")',[],function(res){ ... });
```

In this case Alasql will make this conversion at the parsing time, but not execution. In future versions will allow to have execution time JavaScript variables (with double backquotes):
```js
    alasql('SELECT * FROM XLSX("``filename``"',[],function(res){ ... });
```

Another idea - to have internal templater for SELECT output, like:
```js
    alasql.tmpl.mytmpl = '<div>{%= o.id %}</div>';
    var res = alasql('SELECT * TEMPLATE tmpl() FROM one');
```

**Comment by agershun** [comment]
This template function will be useful for XLSX export function.

**Comment by agershun** [comment]
Negative. Closed.

**Comment by mathiasrw** [comment]
(Agree on not implementing. This is an issue with the user and the "string creating" javascript engine used - hopefully ES6 will be the norm soon :) )

**Comment by agershun** [comment]
Multiline strings are already in Chrome, but not in Node...

**Comment by mathiasrw** [comment]
Seams like io.js and node.js is merging - so think multiline string are not far in the node world :)

**Comment by agershun** [comment]
Ok. I still think about templater, but probably we will keep it for plugins. I thnik that ORM is more in priority, that template-base SQL genereation
