### ISSUE TITLE
Node 12

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#1135]
One test is failing in node 12 

https://travis-ci.org/agershun/alasql/jobs/585543277

**Comment by forestfang-stripe** [comment]
looks like `assert.deepEqual` no longer think `{"0": 1}` is the same as `[1]`

https://github.com/agershun/alasql/blob/8b2fda7f912d7acc2babe5060f0643a0ba92bd06/src/424select.js#L133

we always returns array of objects. the simplest fix would be to update the expected value to be truthful what they actually are.

note: 

```js
console.log(alasql(sql, ['a,b,c\nd,e,f\none,two,three\n'])[0].slice());
```
throws the following error even in node 8
```
TypeError: alasql(...)[0].slice is not a function
```
even though the following passes
```js
assert.deepEqual(res, [
				['a', 'b', 'c'],
				['d', 'e', 'f'],
				['one', 'two', 'three'],
			]);
```
so they really weren't array. just assert being lenient

**Comment by mathiasrw** [comment]
You are awesome. Merged. Closed.
