### ISSUE TITLE
Compiled Statement - column-based array of arrays instead of row-based possible?

### ISSUE THREAD

**Issue by JYone3A** [agershun/alasql#1143]
Hi,

I am using the 'mysum' example from https://github.com/agershun/alasql/wiki/Compile but with arrays of arrays.

However, we have rather large datasets so we chose to store the data using column-based arrays of arrays, not row-based. So, our data structure would look like this:
````javascript
[
    [ 1, 2, 3, ...],  // id
    [ 'title 1', 'title 2', 'title 3', ... ], // title
    [ ...] // more columns
]
````

instead of
```javascript
[
    // id, title, ...
    [ 1, 'title 1', ...],
    [ 2, 'title 2', ...],
    [ 3, 'title 3', ...],
    ...
]
```

Is it possible to pass this type of data structure to a precompiled function? We cannot really convert the whole data to a row-based structure as that will take up too much memory.

Furthermore, is it possible to pass in a separate array of column names to allow column names in queries, instead of using the numeric array index?

**Comment by mathiasrw** [comment]
This is not supported. And even if it was it would be converting data into the object notation on the inside. 

I storngly suggest you make some loops to get out relevant data and do dataprocessing on a subset of your full dataset. 

> Furthermore, is it possible to pass in a separate array of column names to allow column names in queries, instead of using the numeric array index?

I dont get it. Can you make an example?

**Comment by JYone3A** [comment]
Based on the following example:

```javascript
var data = [{a:1},{a:2},{a:3},{a:4},{a:5}];
var mysum = alasql.compile("SELECT VALUE SUM(a) FROM ? WHERE a > 2");
var res = mysum([data])
````
https://github.com/agershun/alasql/wiki/Compile

I do not find the other example any more, but another possible way to write the above would be:
```javascript
var data = [ [1], [2], [3], [4], [5] ];
var mysum = alasql.compile("SELECT VALUE SUM([0]) FROM ? WHERE [0] > 2");
var res = mysum([data])
```

I would like to do a mix of those two, like this:
```javascript
var columns = [ 'a' ]
var data = [ [1], [2], [3], [4], [5] ];
var mysum = alasql.compile("SELECT VALUE SUM(a) FROM ? WHERE a > 2");
var res = mysum([data], columns) // or some similar API
```

or with more columns:
```javascript
var columns = [ 'a', 'b' ]
var data = [ [ 1, 12 ], [ 2, 22 ], [ 3, 32 ], [ 4, 42 ], [ 5, 52 ] ];
var mysum = alasql.compile("SELECT VALUE SUM(a) FROM ? WHERE b > 22");
var res = mysum([data], columns)
```

**Comment by mathiasrw** [comment]
Yes, it would be nice. I cant see an easy solution. Closing.
