### ISSUE TITLE
Help wanted: Alacon and Alaserver

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#115]
AlaSQL package includes two utilities:
* ```alacon``` - command -line AlaSQL version - very useful tool for simple ETL tasks
* ```alaserver``` - very simple Node.js server for quick prototyping and simple interface

Currently to run these utilities from command-line a have to write something like this:
```
    node alacon 'SELECT _ AS [Number], _*_ AS [Square] INTO XLSX("squares.xlsx",{headers:true}) FROM RANGE(1,10)'
```
or for Alaserver
```
    node alaserver
```
and then from browser:
```
    http://127.0.0.1:1337/?SELECT%201+1
```

**Question**

How to change ```package.json``` and other files for:

1. Running Alacon and Alaserver without ```node``` prefix, like:
```
    alacon 'SELECT 1+1'
    alaserver 8081 
```

2. Install Alasql package globally:
```
    npm install -g alasql
```

Thank you!

**Comment by agershun** [comment]
Found answer with help of StackOverflow:

* [In Engllsh](http://stackoverflow.com/questions/29483592/how-to-run-node-js-program-from-command-line-without-word-node)
* [In Russian] (http://ru.stackoverflow.com/questions/414030/%D0%97%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B-node-js-%D0%B8%D0%B7-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D0%BE%D0%B9-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B8-%D0%B1%D0%B5%D0%B7-%D1%83%D0%BA%D0%B0%D0%B7%D0%B0%D0%BD%D0%B8%D1%8F-node)

Will be included in version 0.0.44

**Comment by agershun** [comment]
Checked with Windows. Now is Ok.

**Comment by mathiasrw** [comment]
Nice - super nice...
