### ISSUE TITLE
Can alasql generate multiple arrays from an excel sheet?

### ISSUE THREAD

**Issue by thomasazdon** [agershun/alasql#1151]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Question about how to ...
take a single excel row and turn it into multiple arrays
Excel Row:

id | portfolioId | type | assetId | strategyId | quantity | cost | contractualSettleDate | actualSettleDate | commission | fee | managerId | basketId
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | Control | EQUITY_OPEN_LONG | A | 0 | 1000 | 100000 | SPECIAL |   | 2.06 | 1.03 | 0 |  

And my output needs to look like this:

```
{
  "records": [
    {
      "common": {
        "validTime": "20180101T121222",
        "knowledgeTime": "20180101T121222"
        
      },
      "eventHeader": {
      	"portfolioId": "Collect Acquisition Disposition Transactions",
        "type": "EQUITY_OPEN_LONG"
      },
      "details": {
        "assetId": 12,
        "custodianAccountId": 0,
        "strategyId": 0,
        "quantity": 150,
        "cost": 5001.23,
        "contractualSettleDate": "SPECIAL",
        "commission": 2.05,
        "fee": 1.03,
        "managerId": 0,
        "basketId": 0
      }
    }
```

**Comment by thomasazdon** [comment]
Just as an aside - I'm not looking for you to code it - but I can't seem to find an example that does this.  I find a lot of 'search the json to export to excel'  - but none on taking excel and turning it into nested arrays. If you can point me somewhere - I can solve.

**Comment by mathiasrw** [comment]
I think you need to come with a more detailed example. I cant see any of the data from common and event header - and some parts from details like custodianAccountID is not to be found.

**Comment by thomasazdon** [comment]
That is correct - the eventHeader, common, and details node keys are not in the data - they would need to be inserted with the proper data items after them.  This is what my data looks like that I receive:


knowledgeTime | validTime | eventHeader | portfolioId | type | assetId | strategyId | quantity | cost | contractualSettleDate | actualSettleDate | commission | fee | managerId | basketId
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
20180101T235959 | 20180101T235959 | Control | EQUITY_OPEN_LONG | A | 0 | 1000 | 100000 | SPECIAL |   | 2.06 | 1.03 | 0 |  
20180101T235959 | 20180101T235959 | Control | EQUITY_OPEN_LONG | A | 0 | 1000 | 100000 | SPECIAL |   | 2.06 | 1.03 | 0 |

**Comment by thomasazdon** [comment]
Essentially what I have to do is read in the excel file - and 'construct' the nested json from what I get.  This means pushing new keys into the structure and producing sub arrays

**Comment by mathiasrw** [comment]
Alasql is not the optimal tool to construct complex json structures. I suggest you use the vanilla javascript framework for this.
