### ISSUE TITLE
Alasql, Alasql.js, alasql, alasql.js, AlaSQL, AlaSql?

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#116]
Could you share your opinion on the best "canonical" name of the package:
a) Alasql
b) Alasql.js
c) alasql
d) alasql.js
e) AlaSQL
f) AlaSql

Which option is better?

Thank you!

**Comment by gregaubert** [comment]
I'd say __d)__ or __e)__

**Comment by agershun** [comment]
I also think about AlaSQL as a name of the database.

**Comment by wuxianliang** [comment]
AlaSQL +1. Community has use this name recently.
http://blog.glaucocustodio.com/2015/03/30/local-storage-with-alasql-in-cordovaionic-framework/
http://www.pdiniz.com/alasql/

**Comment by agershun** [comment]
Thank you for the responses. Let's use:
* ```AlaSQL``` for documentation as the official name of the library
* ```alasql.js``` as a main file name of AlaSQL library
* ```alasql``` as a main object and main function of AlaSQL library

**Comment by mathiasrw** [comment]
:+1: on the result.
