### ISSUE TITLE
If Key not exists create this

### ISSUE THREAD

**Issue by KyooMario** [agershun/alasql#1171]
Hello ALASQL,

Is there a way to create a key when there is not one in every record?
So like:
data = [{"key01":"value01","key02":"value02"},{"key01":"value03}]
result = alasql('SELECT   * FROM ? ', [data]);
result should become [{"key01":"value01","key02":"value02"},{"key01":"value03,"key02":""}]

Please advise,
Kind regards,
Mario

**Comment by mathiasrw** [comment]
I suggest adding it after (or before) with something like

    result = result.map(el=>({key02:'', ...el}))
