### ISSUE TITLE
Indexeddb Full example , select , Update , assigning result to variable

### ISSUE THREAD

**Issue by SathishRamV** [agershun/alasql#1182]
Indexeddb Full example , select , Update , assigning result to variable

**Comment by SathishRamV** [comment]
alasql('CREATE INDEXEDDB DATABASE IF NOT EXISTS SegmentDataUpload;\
	    ATTACH INDEXEDDB DATABASE SegmentDataUpload; \
	    USE SegmentDataUpload; \ ', [], function () {

                alasql('SELECT * FROM SegmentDataUpload'
                    ,
                    [], function (item) {
                        console.log(item);
                   
                    });
            });

How to get result in variable. so that i can use it for further manipulation

**Comment by mathiasrw** [comment]
As I recall you cant have the ';' in the async SQL when its create, attach and use. 

Please try separating them like 


```
console.log(await alasql(["CREATE INDEXEDDB DATABASE IF NOT EXISTS SegmentDataUpload;", "ATTACH INDEXEDDB DATABASE SegmentDataUpload;", "USE SegmentDataUpload;", "SELECT * FROM SegmentDataUpload" ]))
```

or maybe actually a more correct replica of your code:

```
await alasql(["CREATE INDEXEDDB DATABASE IF NOT EXISTS SegmentDataUpload;","ATTACH INDEXEDDB DATABASE SegmentDataUpload;", "USE SegmentDataUpload;"])

console.log(await alasql("SELECT * FROM SegmentDataUpload"]))
```

**Comment by report-zone** [comment]
This doesn't seem right, should the 'Select' be on a table and not the entire DB?

**Comment by mathiasrw** [comment]
OH - @report-zone You are right. SIlly me. 

Yes - select must be on the table - not the DB.

**Comment by SathishRamV** [comment]
@report-zone  & @mathiasrw  DB Name and Table name is same. but no worries i fixed the error.
