### ISSUE TITLE
Common functional on the AlaSQL library questions

### ISSUE THREAD

**Issue by lemkoleg** [agershun/alasql#1186]
Tell me, please, such questions on the AlaSQL library: 1. Does it work with BLOB objects? 2. The query result is returned only in JSON format? 3. Is there a limit on the size of blob objects in the browser?

**Comment by mathiasrw** [comment]
Not sure about blob. Let me know when you find out. 

Your browser memory is the limit to the size.

**Comment by lemkoleg** [comment]
As far as I know, IndexedDB should not have restrictions and should store blob.
