### ISSUE TITLE
IS it a issue in using LEFT JOIN in google script environment(google sheets)?

### ISSUE THREAD

**Issue by rao10** [agershun/alasql#1189]
I liked sql features, I am watching the you tube video https://www.youtube.com/watch?v=0KuSD5PGQF8 and wants to try it out.  I am exactly following the steps , character by character as shown in the video.  he copied  with alasql.js 5.5v code in the google script editor and  he created his own function called SUPERSQL.

I am trying with 6.0  for simple '=SUPERSQL("SELECT * FROM ? as tab1", A2:B5,A7:B9)" it works well. But when I tried with  "=SUPERSQL("SELECT * FROM ? as l LEFT JOIN ? as r  ON l.a = r.a", A2:B5,A8:B10)".   
_"TypeError: can't read property 'length' of undefined.( line 7308)_

I took 5.5 version of it and tried the same  I still get the same error and at the piece of code 
_"TypeError: can't read property 'length' of undefined.(line 7294)_

Is it a bug or some thing else?

**Comment by mathiasrw** [comment]
Well - if 5.5 is not working it seems like a bug in the implementation. 

If you need more help please share your code.

**Comment by rao10** [comment]
here is the code for the SUPERSQL  and screen shot of the error with data. This screenshot is on 6.0

![alasql_error](https://user-images.githubusercontent.com/6091176/81321816-0ea2d000-9061-11ea-9252-a619ef94959a.jpg)

[supersql_gs.txt](https://github.com/agershun/alasql/files/4594438/supersql_gs.txt)

same issue with 5.5 but just line nbr is slightly different , but the error line is same.

**Comment by mathiasrw** [comment]
let sqlData = arrayToObjectOfArrays (dataAsArray1) ;
    sqlData.push( arrayToObjectOfArrays (dataAsArray2)) ;
 
Looks like you are adding an array to sqlData and then you are pushing an array of data2 as if it was the last data of data1. 

I suggest doding something like 

    let sqlData = [dataAsArray1, dataAsArray2].map(arrayToObjectsOfArrays)

Please reopen if it does not work.

**Comment by rao10** [comment]
I will check. Appreciate your response. Thank you
