### ISSUE TITLE
percentage

### ISSUE THREAD

**Issue by carbuz** [agershun/alasql#119]
Hi,

I would like to be able to compute the percentage of a field. My db is something like this:

var db=[{a:3.5,b:{c:"label1"}},{a:0.5,b:{c:"label1"}},{a:6,b:{c:"label2"}}]

and I would like to obtain something like : 

  b->c       result
--------       ------- 
label1        0.4
label2        0.6

I tried:
alasql("SELECT FIRST(b->c) as [b->c], sum(a)/(select sum(a) from ?) from ? group by b->c",[db,db])

without success... May you please address me to the correct solution?

Thank you

**Comment by carbuz** [comment]
I figure out I can use the function AGGR():

alasql("SELECT FIRST(b->c) as [b->c], sum(a)/AGGR(select sum(a) from ?) from ? group by b->c",[db,db])

**Comment by agershun** [comment]
I think this is a bug... I reopen this issue to fix it. 

See error code [at jsFiddle](http://jsfiddle.net/agershun/81noowmn/1/)

Now AlaSQL returns the error:

    Uncaught ReferenceError: p is not defined

But this should be ```g``` (property of groupped record), but not ```p``` (property of source record).

**Comment by agershun** [comment]
I fixed it. Try in jsFiddle.

**Comment by carbuz** [comment]
thank you!
Il 13/apr/2015 17:10, "Andrey Gershun" <notifications@github.com> ha
scritto:

**Comment by agershun** [comment]
I just win my battle over Git :) and updated last version at GitHub and npm, so it should work.

Thank you for the bug!

**Comment by carbuz** [comment]
Ahahha nice! :)

May I suggest you also to create a bower version of your library? I saw
there is a bower.json file but the usual command "bower install alasql"
does not work. I addition, knowing that you love clean code, would be
possible to remove the reference to the .map file (alasql.js.map 404 (Not
Found))?

PS: I will ask my collegues to star you! :)

2015-04-13 17:34 GMT+01:00 Andrey Gershun <notifications@github.com>:

> I just win my battle over Git :) and updated last version at GitHub and
> npm, so it should work.
>
> Thank you for the bug!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agershun/alasql/issues/119#issuecomment-92419695>.
>



-- 

*Andrea Carbone*
*VP Enterprise Solution*

*Fincluster LTD*
Registered Office:
12, Bridewell Place,
EC4V 6AP, London (UK)
Registered in England & Wales no. 08359023
Operating Office:
3rd Floor, 28, Leman Street,
E1 8ER, London (UK)
*M UK*:                 +44 7557446765
*M IT*:                  +39 338 5938367
*E*:         a.carbone@fincluster.com
*Skype*:  andrea.carbone.fincluster

This e-mail contains confidential information or information belonging to
the Fincluster LTD entity sending it and is intended solely for the
addressees. Any views expressed in this message are those of the individual
sender and its contents do not constitute a commitment by Fincluster LTD unless
confirmed by letter or fax. The unauthorised disclosure, use, dissemination
or copying (either whole or partial) of this e-mail, or any information it
contains, is prohibited. E-mails are susceptible to alteration and their
integrity cannot be guaranteed. Internet communications are not secured and
therefore Fincluster LTD shall not be liable for this e-mail if modified or
falsified. If you are not the intended recipient of this e-mail, please
notify the sender of the wrong delivery and delete it immediately from your
system.

**Comment by agershun** [comment]
1. Bower - now I starting a battle with Bower :) I lost it a month ago, probably now I will more lucky.

2. For alasql.map: probably the easiest way to avoid this problem - to use ```alasql.min.js```. It is probably good topic to discuss how AlaSQL should use sourcemap file. If this annoying, I will remove it, of course.

I opened [new issue](https://github.com/agershun/alasql/issues/121) for this question.

3. Thank you for the stars! It is really inspiring ;)
