### ISSUE TITLE
Indexeddb database does not exist

### ISSUE THREAD

**Issue by lemkoleg** [agershun/alasql#1193]
Why code

   alasql ('CREATE INDEXEDDB DATABASE IF NOT EXISTS 'dbname';
            ATTACH INDEXEDDB DATABASE 'dbname';
            USE 'dbname'; ')

throw error:

   "Database 'dbname' does not exist"

**Comment by lemkoleg** [comment]
Need to use a promise

**Comment by yo-png** [comment]
> Need to use a promise

You mean to use await ?

**Comment by lemkoleg** [comment]
yes
await alasql.promise("CREATE INDEXEDDB DATABASE IF NOT EXISTS DabName");
await alasql.promise("ATTACH INDEXEDDB DATABASE DabName");
await alasql.promise("USE DabName");

ср, 3 июн. 2020 г. в 07:09, yo-png <notifications@github.com>:
