### ISSUE TITLE
ADD COLUMN does not use the given dbtypeid

### ISSUE THREAD

**Issue by RB-News-MailAccount** [agershun/alasql#1196]
Thank you for this nice library!

ADD COLUMN is not working as expected.
When I add a column to an existing table with name and type id, the type is not used. I veryfied it with SHOW COLUMNS on the same table.

--- Commands to reproduce, last gives as the result the incomplete column information from the table
CREATE TABLE IF NOT EXISTS info (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
)
ALTER TABLE info ADD COLUMN key TEXT
SHOW COLUMNS FROM info
--- End of commands

In my opinion in file **src/64altertable.js** (in the current version of May 19th, 2020) **line 63** has to be changed from 
dbtypeid: this.dbtypeid,
to 
dbtypeid: this.addcolumn.dbtypeid,

So that dbtypeid is fetched like the columnid from 'addcolumn' object.

**Comment by mathiasrw** [comment]
Ohhh - nice catch! 

Would you like me to fix the line or would you like to make a PR so you can get credited for your contribution?

**Comment by RB-News-MailAccount** [comment]
Thank you, Mathias!

I do not need credit. If you integrate the fix, I would be happy.

**Comment by mathiasrw** [comment]
Released as part of v0.6.1
