### ISSUE TITLE
Columns with space not working

### ISSUE THREAD

**Issue by sivaecekrr** [agershun/alasql#1201]
When i tried to do select from json which has space in the key is not working properly.

`var data = [{
  "NAME": "TEST1",
  "TOTAL_COST": 1500,
  "DYNAMIC COL1": 10,
  "DYNAMIC COL2": 10
}, {
  "NAME": "TEST1",
  "TOTAL_COST": 100,
  "DYNAMIC COL1": 15,
  "DYNAMIC COL2": 5
}, {
  "NAME": "TEST2",
  "TOTAL_COST": 100,
  "DYNAMIC COL1": 15,
  "DYNAMIC COL2": 5
}, {
  "NAME": "TEST1",
  "TOTAL_COST": 600,
  "DYNAMIC COL1": 5,
  "DYNAMIC COL2": 5
}]`

`var res1 = alasql('SELECT NAME, sum(TOTAL_COST), sum("DYNAMIC COL1"), sum("DYNAMIC COL2") from ? GROUP BY NAME', [data]);`

https://jsfiddle.net/sivamani/9tkc2ygv/

Any can please help on this. Thanks.

**Comment by sivaecekrr** [comment]
Never mind. Fixed using [...]

`var res1 = alasql('SELECT NAME, sum(TOTAL_COST), sum([DYNAMIC COL1]), sum([DYNAMIC COL2]) from ? GROUP BY NAME', [data]);`

https://jsfiddle.net/sivamani/9tkc2ygv/13/

Reference - https://github.com/agershun/alasql/issues/606

**Comment by mathiasrw** [comment]
Nice - you found it. It also works with using ``` ` ``` instead of ` " `
