### ISSUE TITLE
Sublabel adding In Excel Exporting

### ISSUE THREAD

**Issue by Rohan5696** [agershun/alasql#1203]
Basically I am searching the element from my json data and binding to excel as per labels but I am getting issue how to add sublabel. Like for example in attachment Monday under that R,O,C,SR??? Pls help someone for this issue.
![IMG-20200610-WA0027](https://user-images.githubusercontent.com/22433364/84355153-c2a6f600-abdf-11ea-9dc7-d7e7a9093e7e.jpg)

**Comment by mathiasrw** [comment]
You cant. You will have to use sheetjs to make the escel sheet cell by cell.
