### ISSUE TITLE
Question: Should AlaSQL supports sourcemaps?

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#121]

**Comment by mathiasrw** [comment]
I guess the point would be to help with debugging. Are you asking because the sourcemap issue is creating problems?

**Comment by agershun** [comment]
Yes, there are two problems:

a) alasql.js has a reference to sourcemap by default. Some people do not want to copy sourcemap with the library.
b) Actually, I test and debug most of features in Node.js, where the sourcemaps are useless.

**Comment by mathiasrw** [comment]
Hmmm... well... if its not helping - and creates issues it might not be important.

**Comment by mathiasrw** [comment]
So I guess its a "no" ?

**Comment by agershun** [comment]
No.
