### ISSUE TITLE
Merge develop into master branch

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#122]
Please help me to clean AlaSQL master and develop branches. 

1. I missed something with Git, and now can not merge ```develop``` into ```master```. See the picture from here:

https://github.com/agershun/alasql/network

2. Due I renamed branch ```version-0.0.41``` to ```master``` Git still update to ```version-0.0.41``` branch on GitHub.

Probably, we can do it together via Skype screen sharing procedure or in other way?

**Comment by mathiasrw** [comment]
Awwww... hmmm.... thinking...

**Comment by mathiasrw** [comment]
Its not so good to rename brances locally - as they will still point to the original branch remote. 

Please explain: locally, where are the latest changes? Have you created features with the git-flow, or what is the filosophy of your git-flow?

**Comment by agershun** [comment]
Ops, I did it again, la-la-la-la-la! Everything is fine now :)

**Comment by mathiasrw** [comment]
Hah - Good to hear :)

https://www.youtube.com/watch?v=CduA0TULnow#t=1m29s
