### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by realrecordzLab** [agershun/alasql#1222]
I want to use this nice library inside an electron app but I have some doubt about it. Is this database safe to use against SQL Injections attack? Will this library use prepared statements or other sanitization function?

**Comment by mathiasrw** [comment]
I dont think alasql is the rught way to go to protect anything. Its all just javascript and if you can run anything you can access all data. 

Yes, you have precompile statements - but there is no but there is no sanitazion of the actual value.
