### ISSUE TITLE
Convert Array to string using Select statement.

### ISSUE THREAD

**Issue by SathishRamV** [agershun/alasql#1223]
Convert Array inside array to string , pings is array object to string is it possible 

```
attachments: []
content: "@Administrator "
created: "2020-09-14T08:24:51.493Z"
created_by_admin: false
created_by_current_user: true
fullname: "V.Sathish Ram"
id: 1
modified: "2020-09-14T08:24:51.493Z"
parent: null
pings: {5: "Administrator"}
profile_picture_url: ""
upvote_count: 0
user_has_upvoted: false
```

**Comment by mathiasrw** [comment]
I would go with a custom function so you `select content, fullname, ARR2STR(pings), ...` having something like

    alasql.fn.ARR2STR = x=>x.join(", ")


https://github.com/agershun/alasql/wiki/User-Defined-Functions
