### ISSUE TITLE
Formal build process

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#123]
When I look at ```https://github.com/agershun/alasql/tree/develop/dist```I get the following:

```
alasql-worker.js	release changes	2 days ago
alasql-worker.js.map	release changes	2 days ago
alasql-worker.min.js	web worker minor bug	3 months ago
alasql.js	Master	13 hours ago
alasql.js.map	Fixed bug with localStorage DELETE FROM	17 hours ago
alasql.min.js	Releasr	16 hours ago
```

Looks like the min version of the worker is not build from the same src as alasql.js...

AlaSQL can benefit from formalizing the buildprocess so that *all* versions in the /dist folder always are built from the same src at the same time...

**Comment by agershun** [comment]
I just changed some comments in worker files, and there are no any other changes in ```worker``` for last couple months. As far as I understand, Gulp builds it if there any changes in source files.

**Comment by agershun** [comment]
But in general you are right! Plus we need rules for git/github work (see my adventures with git-flow)
