### ISSUE TITLE
Percentile function

### ISSUE THREAD

**Issue by akhaneev** [agershun/alasql#1237]
Is there a percentile function available?
If not, is it possible to create this one? I tried to create something like this
`PERCENTILE(ColumnName, percentValue)`
for example
`PERCENTILE(Values, 0.95)`
with this javascript
`alasql.aggr.PERCENTILE = function(value, percent, s, stage) {
      //...
    }`
But I get only the last value from the calling function  - percent, but not the column values and percent. Is it possible to get both values from the function?

**Comment by mathiasrw** [comment]
There is no percentile function as far as I recall. 

You approach looks right - how ever, I dont think you can pass other propeties than the first one. If you can accept having a function per pecentile you are good 

I guess it would be something like

```
alasql.aggr.percentile = function(value, accumulator, stage) {
        accumulator = accumulator || [];

             if(stage == 3) {
		return accumulator[Math.floor(accumulator.length*0.95)]  
	}

      return accumulator.push(value)
}
```
