### ISSUE TITLE
is type cast possible in alasql js?

### ISSUE THREAD

**Issue by DattatreyaDash** [agershun/alasql#124]
Hi,
I am trying to export a json into csv file. All the numeric values are also exported as string. So it is creating problem for excel operations. I tried cast & convert expression , but it is not possible to get the required result. Is there a solution for this ?

**Comment by agershun** [comment]
Try this example:

http://jsfiddle.net/agershun/81noowmn/8/

It stores numbers as numbers. Could you modify this example to explain the problem?

**Comment by agershun** [comment]
To cast types to Number you can use one of three forms:
```sql
    SELECT CAST(a AS NUMBER), FORMAT(NUMBER,a), a::NUMBER 
```

**Comment by DattatreyaDash** [comment]
Can I do it for xlsx format ? CSV format is fine, but it is not possible
for xlsx format.

**Comment by agershun** [comment]
I catch the bug

http://jsfiddle.net/agershun/ahkLochh/2/

Current version of AlaSQL does not save numbers 1.2 as numbers rather as string type. I will try to fix it.

Thank you!

**Comment by agershun** [comment]
Fixed. Will be available as version 0.0.47 in ```develop``` branch or from http://alasql.org/console/alasql.min.js

You can try it at http://jsfiddle.net/agershun/ahkLochh/2/

Thank you for the issue! Please let me know, if something wrong.

**Comment by DattatreyaDash** [comment]
Thanks Andrey. It's working fine.
