### ISSUE TITLE
The column could not be displayed twice.

### ISSUE THREAD

**Issue by makyo5** [agershun/alasql#1262]
version: 0.6.4
The column could not be displayed twice.

response.data:
[{ DEPT_CODE: 0001. DEPT_NAME: AA }, {DEPT_CODE: 0002, DEPT_NAME: BB},{......}],

I want the result: [{text: AA, value: AA },{text: BB, value: BB},......]

So I did:
var a= alasql("select DEPT_NAME text, DEPT_NAME value from ? group by DEPT_NAME" , [response.data]);

But the result a is :
[{aa: undefinedn bb:"AA" }.....]

Yes, the first column is undefined.

Please fix. thx.

**Comment by mathiasrw** [comment]
Check out a solution on https://jsfiddle.net/sxmy85o2/
