### ISSUE TITLE
sqllogictest 1:Should AlaSQL support INFORMATION_SCHEMA database?

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#127]
Sqllogictest requires INFORMATION_SCHEMA database. Should AlaSQL supports this? May be in compatibility mode?
```sql
    IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS 
               WHERE TABLE_NAME = 'view_1_tab0_153') DROP VIEW view_1_tab0_153
```

**Comment by mathiasrw** [comment]
Would be good if you put a few more words to the issue

**Comment by agershun** [comment]
Sqllogictest requires INFORMATION_SCHEMA database. Should AlaSQL supports this? May be in compatibility mode?

    IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS 
               WHERE TABLE_NAME = 'view_1_tab0_153') DROP VIEW view_1_tab0_153

As far as I understand, these schemas are different for SQLite, MS SQL, etc.

**Comment by mathiasrw** [comment]
Hmmm. what is the goal of AlaSQL? if one must be able to take any SQL application and run it on node it would be good to keep the data in a structured way that can be requested via sql. 

On the other hand, as I understand, the information can be retreeved via the alasql object - is that correct?

**Comment by agershun** [comment]
Good question... Let me think...It is good point, if we can provide compatibility as much as possible with SQLite to simplify the migration. This construction (````SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'view_1_tab0_153'``) is very standards for SQLite. So, AlaSQL can support it.

It is not so hard to check at compilation time, that user try to access INFORMATION_SCHEMA database and return the list of views or tables or other objects as an array.

Plus, it will help to AlaSQL to pass the test. I vote up.

**Comment by mathiasrw** [comment]
0 nay, 2 yay - go go go ! :)

**Comment by agershun** [comment]
Done. Please see ```develop``` branch or it will be available since version 0.0.52. The simple version of INFORMATION_SCHEMA with two virtual tables: TABLES and VIEWS. Now we can run sqllogic tests with constructions like this:
```js
     alasql('  IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS \
               WHERE TABLE_NAME = "view_one") DROP VIEW view_one');
```
Probably in the future we can think about more complicated version of INFORMATION_SCHEMA like in MySQL:
https://dev.mysql.com/doc/refman/5.0/en/information-schema.html

**Comment by agershun** [comment]
I also relized subversion of OBJECT_ID() function for T_SQL.

**Comment by mathiasrw** [comment]
:+1:
