### ISSUE TITLE
How can i replicate SQL's STRING_SPLIT to create more rows

### ISSUE THREAD

**Issue by Necmttn** [agershun/alasql#1300]
https://docs.microsoft.com/en-us/sql/t-sql/functions/string-split-transact-sql?view=sql-server-ver15#b-split-comma-separated-value-string-in-a-column

I would like to create more rows base on the comma-separated column values here's the example from SQL server documentation.

**Comment by mathiasrw** [comment]
Hmm. Alasql does not provide this at the moment, so you will need to manage that before adding the data.
