### ISSUE TITLE
[Feature Request] Streaming SQL Joins / Continuous Queries

### ISSUE THREAD

**Issue by benoitparis** [agershun/alasql#1306]
A new generation of server-side SQL engines are spawning a new kind of construct, Streaming SQL Joins: 

* Kafka's kSQL has the `EMIT CHANGES` keyword
* Spark has stream-stream JOINs
* Flink's default behavior ('time-varying relations') is to emit the changes
* Materialize's value proposition is centered around event-streaming, and has Live Materialized Views.

----

Feature description:

While doing: `SELECT * FROM orders o JOIN item i ON o.order_item_id = i.item_id`, we would be able to listen to the changes from either side of the join; Without having to use TRIGGERs on both sides and re-emitting a query.

Changes would only stream the updated rows, insertions and deletions.

It would work on aggregations as well, sending the updated rows with the new aggregated values.

----

Advantages / use cases:

* If you're doing event-streaming server-side and sending slices of a table to the client, you could have the same abstraction client-side, in the same language. 
* Moving business logic from client-side to server-side and vice-versa would be easier, as it would be expressed in the same language
* SQL rules, SQL everywhere!
* Reactive apps are easier b/c of cache management (there is none if you go full reactive).

----

This would be an ungodly amount of work, but I think AlaSQL is uniquely positioned to serve this use case, being the leader with sql.js in client-side SQL.

Out of curiosity: Is it something that could go on the long term roadmap?

**Comment by mathiasrw** [comment]
Interesting. 

What format are you thinking regarding the output for an event?

**Comment by Bessonov** [comment]
I'm not AlaSQL user yet and use currently [RxDB](https://rxdb.info/) and former [WatermelonDB](https://nozbe.github.io/WatermelonDB/) user. Both are great on reactivity. RxDB uses ATM [rxjs](https://rxjs.dev/). But lack of joins makes many parts a little bit ugly to work with.

For AlaSQL I can imagine following example:

```ts
const orders$: Observable<{
  id: number,
  user: string,
  name: string
}> = alasql.observe("SELECT o.id, o.user, i.name FROM orders o JOIN item i ON o.order_item_id = i.item_id")

orders$.subscribe(orders => console.log(orders))
```

If relevant data (~ filtered by `where`) is inserted, modified or deleted then the observer is fired.

What do you think @mathiasrw ? Is there any way to achieve that already?
