### ISSUE TITLE
Exported Excel empty column we apply ISBLANK Formula its return false

### ISSUE THREAD

**Issue by MohammedMubeen** [agershun/alasql#1363]
Hi Folks,

Alasql using we exported the excel file. In that excel we try to apply ISBLANK formula but its not working.
Please help me ASAP

NOTE : Before export We tried to replace null to empty like below

```js
function replacer(i, val) {
    if (val === null) {
        return ""; // change null to empty string
    } else {
        return val; // return unchanged
    }
}
```

Downloaded Excel File
[CustomerReport (2).xls](https://github.com/agershun/alasql/files/6877690/CustomerReport.2.xls)

**Comment by mathiasrw** [comment]
We cant help you with excel problems.
