### ISSUE TITLE
Running two promise with identic query somehow went wrong

### ISSUE THREAD

**Issue by niwasmala** [agershun/alasql#1368]
**Problem**
I have a google spreadsheet and want to load several sheets in paralel. But the result is not working as expected. 
Imagine the google sheet have 2 sheets, categories and products. 

Google Sheets
https://docs.google.com/spreadsheets/d/1iN8IsyPAJe8nFlBUvjEu1UX6mvxOORLIaG8CIyHkFGU/edit?usp=sharing

```javascript
async function loadCategory() {
  const url = 'https://docs.google.com/spreadsheets/d/1iN8IsyPAJe8nFlBUvjEu1UX6mvxOORLIaG8CIyHkFGU/gviz/tq?tqx=out:csv&gid=976108113';
  const res = await alasql.promise('SELECT * FROM CSV(?, {headers:true})', [url]);
  
  console.log('category', res[0]);
  
  return res;
}

async function loadProduct() {
  const url = 'https://docs.google.com/spreadsheets/d/1iN8IsyPAJe8nFlBUvjEu1UX6mvxOORLIaG8CIyHkFGU/gviz/tq?tqx=out:csv&gid=1160488713';
  const res = await alasql.promise('SELECT * FROM CSV(?, {headers:true})', [url]);
  
  console.log('product', res[0]);
  
  return res;
}

loadCategory();
loadProduct();
```

I'm expecting the console log would be like this

![image](https://user-images.githubusercontent.com/476869/128982177-fc3679f3-c011-4197-89eb-05d5c94c7721.png)

But I got

![image](https://user-images.githubusercontent.com/476869/128982241-f141e513-7c86-461f-8ce8-76cce8826bca.png)
which the result of category goes to loadProduct and no response from loadCategory

Please notice that the query are identic both in loadProduct and load Category, only the parameters are different
```javascript
const res = await alasql.promise('SELECT * FROM CSV(?, {headers:true})', [url]);
```

When I change the query so they are not identic, e.g adding alias
```javascript
async function loadCategoryWithAlias(){
  const res = await alasql.promise('SELECT * FROM CSV(?, {headers:true}) AS `Category`', [url]);
  ...
}

async function loadProductWithAlias(){
  const res = await alasql.promise('SELECT * FROM CSV(?, {headers:true}) AS `Product`', [url]);
  ...
}
```

It works as expected. 

**Code Replication**
https://jsfiddle.net/rsukb37o/

You can try to run it several times, and the results would be different.

**Comment by mathiasrw** [comment]
Your async function never returns because the scripts reaches the end and kills the process. 

You need to await the answer. 

To await the answer the need to run it inside a function. The following should do the trick, but I did not test it

```js

(async ()=>{
	  async function loadCategory() {
	    const url = 'https://docs.google.com/spreadsheets/d/1iN8IsyPAJe8nFlBUvjEu1UX6mvxOORLIaG8CIyHkFGU/gviz/tq?tqx=out:csv&gid=976108113';
	    const res = await alasql.promise('SELECT * FROM CSV(?, {headers:true})', [url]);
	    
	    console.log('category', res[0]);
	    
	    return res;
	  }
	  
	  async function loadProduct() {
	    const url = 'https://docs.google.com/spreadsheets/d/1iN8IsyPAJe8nFlBUvjEu1UX6mvxOORLIaG8CIyHkFGU/gviz/tq?tqx=out:csv&gid=1160488713';
	    const res = await alasql.promise('SELECT * FROM CSV(?, {headers:true})', [url]);
	    
	    console.log('product', res[0]);
	    
	    return res;
	  }
	  
	  await loadCategory();
	  await loadProduct();
})()

```

or you might want to do it a bit faster by initiating the requests with a `PRomise.all(loadCategory(), loadProduct())`

Let me know if it works.

**Comment by niwasmala** [comment]
Sorry for the late reply. Yep, it works! My bad for missing the promise and not waiting for the answer. 

Thanks! :+1:
