### ISSUE TITLE
Variable 'key' leaking into global namespace

### ISSUE THREAD

**Issue by ssimono** [agershun/alasql#137]
When executing an alasql query, a variable _key_ leaks into global namespace

```javascript
var alasql = require('alasql'),
    mytable = [ { name: 'Hello' }, { name: 'Wolrd' } ];

console.log(global.key); // undefined

alasql('SELECT * FROM ?', mytable);
console.log(global.key); // String "statements"
```

I found that when discovering very strange bugs in my big node js application

There must be some place in the code where key variable is set without __var__ statement ; I'll give a look at it when I can

**Comment by gregaubert** [comment]
:+1:

**Comment by agershun** [comment]
THANK YOU! 

BYW this function extend() is the most used function in the program :) 
Now it is fixed, I prepared test262.js to check this parameter.

I released version 0.0.49 with fixed bug. https://github.com/agershun/alasql/releases/tag/0.0.49

**Comment by agershun** [comment]
@gregaubert What technics did you use to catch this global.key assignments? I used this code:
```
      Object.defineProperty(global, 'key', {
        get: function(){ assert(false); },
        set: function(newValue){ assert(false); }
      });
```
Did you use the same approach ore something else?

**Comment by gregaubert** [comment]
Ah nice trick!
No I just searched for `key` in the `alasql.js` code.
