### ISSUE TITLE
Reusing builtin names as identifier

### ISSUE THREAD

**Issue by jcubic** [agershun/alasql#1376]
The problem is that AlaSQL doesn't support using some names as an identifier but this is (I'm not 100% sure) required by the standard. Any SQL database I know allows using some bultin names as identifiers.

Example SQLite:
```sql
SELECT integer, SUM(integer) AS sum from foo;
```

this is valid SQL but AlaSQL throws an error that requires an identifier. AlaSQL should allow using some times.
Example:

* column types
* builtin functions

Only a few base keywords are not allowed as user names, like `Select`, `where`, `from`, `as`.

There may be other names that should be allowed as identifiers.

**Comment by agershun** [comment]
Try to use `  (backquote):
```sql
     SELECT `integer`, SUM(`integer`) AS `sum` from foo;
```

**Comment by jcubic** [comment]
It works but it's just workaround, I think that you should be able to use function names and types as values like in other DBMS. I think it will improve the library.
