### ISSUE TITLE
Improve SELECT RECORDSET functions

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#139]
Analyze data and create proper columns list for SELECT statement. I think this very important and equal to bug status

**Comment by mathiasrw** [comment]
Is the documentation about the RECORDSET option written somewhere? If not lets find a god spot for it so I can place it there.

**Comment by agershun** [comment]
No, unfortunately still no... (I updated some wiki articles today, but if very far from the result), e.g. [SQL-99 compatibility report] (https://github.com/agershun/alasql/wiki/SQL-99)

**Comment by mathiasrw** [comment]
I would love to help making the documentation more conprehensive. 

Maybe you could have a document where you write examples of new things features - and then I can take them and place them nice ly with text and stuff. 

Do you normally always write a new test case for each feature? if so we could use the test cases as a way of going from whats implemented to "here is how you do it" - what do you say?

**Comment by agershun** [comment]
This would be great! 

I always start development of new feature with test. Now we have all working test in ```test``` directory and all temporary non-working tests in ```test/skipped```, so you can simply look through all new tests for last month to see what is new.

**Comment by agershun** [comment]
I am also worrying about three things:
a) documentation
b) visibility of the project 
c) and bugs

I have a plan how we can start to work with documentation:
a) I will review all closed issues and write wiki about all developed features
b) we can solit all 250 tests by two parts, and each can write corresponding wiki articles with examples from tests (we also can move them to jsFiddle as working examples)

**Comment by mathiasrw** [comment]
:+1:
