### ISSUE TITLE
Unknown problem with INNER JOIN in Meteor-Postgres project

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#140]
From here: https://github.com/meteor-stream/meteor-postgres/wiki/Database-Methods
<blockquote>
Please note that client side joins currently has an issue with inner join so we recommend using outer join whenever possible. This is a limitation of alasql, a package we are relying on.
</blockquote>

**Comment by agershun** [comment]
After analysis of [minisql.js](https://raw.githubusercontent.com/meteor-stream/meteor-postgres/master/packages/meteor-postgres/minisql/minisql.js) (mini ORM used for the project) I found unsupported command 
```
    DROP TABLE IF EXISTS one CASCADE
```
The implementation of this ```CASCADE``` story is linked to ```FOREIGN KEY``` feature.

**Comment by barbbella** [comment]
We are removing drop table method from miniSQL (client side implementation) because it shouldn't be done on the client, only the server. However, if a table is empty, inner join crashes our app and it doesn't come back up.

**Comment by agershun** [comment]
It is terrible, but I can not reproduce the bug. What is the size of joined data tables?

**Comment by mathiasrw** [comment]
@barbbella Version 0.2.0 just came out - so please update and let us know if the problem is still there.

**Comment by mathiasrw** [comment]
@barbbella any news on this?

**Comment by barbbella** [comment]
@mathiasrw Meteor Postgres is no longer maintained. Meteor had promised native support. I don't know what the status of that is.

**Comment by agershun** [comment]
We will open new issue for CASCADE operations, but this issue will be closed.
