### ISSUE TITLE
Character for parameters

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#141]
Now, SQLite supports five types of the representation of parameters:
```
?NNN		
?		
:AAAA		.
@AAAA		
$AAAA		
```
AlaSQL also supports two forms:
```
?
$[1]
```
I need a dollar sign ``` $ ``` or colon ``` : ```for other purposes. What is I leave only two representations of parameters and ```?```
```
?
?0, ?1, ?3...
```
What do you think?

**Comment by agershun** [comment]
Second question: In some SQL dialects (MS Access) this character is using for constants of date type, like ```#Jul 1, 2015#```.  I want to use number sign ``` # ``` for reference operator (refer to the object by it's id). Is it so important to have date constants? Or may be we can use another approach, like ``` D'Jul 1,2015' ``` ?

**Comment by mathiasrw** [comment]
Awwww - its not good to change the sqlite specification so one have to replace ? and $ in existing code. 

Hmm. Can we do something else? how are we using the $ and : now? could they be escaped? can we use a flag to set behavour? 

I think its a general discussin: will AlaSQL mimic a specific SQL falvour - or make its own? if we state that it supports SQLite or MS access (uhhffff) then we must obay implementation. If we make our own falvour, lets be creative and clever.

**Comment by agershun** [comment]
You are right...

1. Let's make AlaSQL own flavor in version 0.2 when we will have modular structure, and we can develop AlaSQL dialect without any references to other databases as a separate module.
2. How I would like to use ``` $ ```? Now $ sign is widely used by JavaScript libraries (e.g.jQuery), and we can use these variables and columns and function names without square brackets (now we have to use [$])
3. Colon... do not know yet.

Other ideas, how AlaSQL uses these signs:
4. At ``` @ ``` is used as variables names (like in T-SQL)
5. Number ``` # ``` can be used as date (like in MS Access) or I would like to use it for "reference" operator for document-storage/graph operators, Like:
```sql
    CREATE CLASS Person;
    CREATE CLASS City;
    CREATE CLASS Country;

    INSERT INTO Person SET name="John", city=
        (INSERT INTO City SET name = "Kuala Lumpur", country = 
             (INSERT INTO Country SET name = "Malasia"));
    SELECT name, city#name, city#country#name FROM Person;
     -- returns [{"name":"John","city#name":"Kuala Lumpur","city#country#name":"Malasia"}]
```
6. Plus, for graphs I would like to add something like ```-->``` and ```-->>``` operators:
```sql
    SET @john = (CREATE VERTEX SET name = "John");
    SET @mary = (CREATE VERTEX SET name = "Mary");
    CREATE EDGE FROM @john TO @mary SET name = "loves";
    SEARCH OUTE() OUTV() @mary FROM @john;
    -- returns [{name:"loves", $id:124, $in:[122],$out:[123], $onto:"edge"}]
    SEARCH OUTE() OUTV() FROM @john;
    -- returns [{name:"Mary", $id:123, $in:[124],$out:[], $onto:"vertex"}]
    SEARCH OUTV() FROM @john;
    -- returns [{name:"Mary", $id:123, $in:[124],$out:[], $onto:"vertex"}]
    SEARCH OUTE(name="loves")  FROM @john;
    -- returns [{name:"loves", $id:124, $in:[122],$out:[123], $onto:"edge"}]
    SEARCH INE(name="loves")  FROM @mary;
    -- returns [{name:"John", $id:122, $in:[],$out:[123], $onto:"vertex"}]
    PRINT @john, @mary;
    -- returns 122,123
```
PS. Sorry, I am all in this document/graph database idea right now. But I like the idea to extend AlaSQL with simple Graph syntax to make simple social network anaylysis.

**Comment by mathiasrw** [comment]
Go dive deep !

**Comment by mathiasrw** [comment]
closing - as its implemented...

```
> alasql('value of select $1', [4,5])
5
```
