### ISSUE TITLE
Substring doesn't work on column value

### ISSUE THREAD

**Issue by talicardozo** [agershun/alasql#1412]
I'm trying to use substring like this and it doesnt work, only works with direct strings
Am I doing something wrong?

`lista=[{estructura: 'AABCSD'},{estructura: 'ASDKJDKF'}];

var res = alasql(`select substring(estructura ,1,2) AS sup, COUNT(*) AS cant from ? WHERE estructura != ""`,[lista]);
print(res)`

http://jsfiddle.net/xu98m13c/

**Comment by gregja** [comment]
Hi @talicardozo , 
Because you use the count() function, you must declare a clause GROUP BY, like this :  

select substring(estructura ,1,2) AS sup, COUNT(*) AS cant from ? WHERE estructura != ""
   group by substring(estructura ,1,2) 

Best regards
Greg
