### ISSUE TITLE
AlaSQL + Angular.js

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#146]
I am thinking about more closely integration AlaSQL with Angular.js.

What kind of directive it can be? Possible candidates:
* advanced filter
* XLSX/CSV import/export functionality
* SQL service (like https://github.com/paulocaldeira17/angular-websql)

What else can be required?

**Comment by mathiasrw** [comment]
Created on http://feathub.com/agershun/alasql/+32 so closing
