### ISSUE TITLE
Exclude columns from results

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#149]
The idea to add special parameter to SELECT clause to remove columns from results, like"
```js
    var data = [{a:1,b:10},{a:2,b:20}];
    var res = alasql('SELECT * REMOVE b FROM ?',[data]);
```
returns [{a:1},{a:2}]

**Comment by mathiasrw** [comment]
:+1:

**Comment by agershun** [comment]
You can remove unused columns with ```REMOVE COLUMN``` clause

The syntax is:

    SELECT selected-columns REMOVE [COLUMNS] columns-to-be-removed

like in this example:

    alasql('SELECT * REMOVE COLUMNS b,c FROM ?',[data]);

You can also remove by mask:
```sql
    SELECT * REMOVE COLUMNS LIKE "b%" FROM one
```
