### ISSUE TITLE
Different OUTER JOIN and FULL OUTER JOIN

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#151]
1. By unknown reason OUTER JOIN and FULL OUTER JOIN are different, but should be the same.

2. OUTER JOIN gives wrong joined values if second table is empty (see test275.js for example):
```
    [ { a: 1, b: undefined, c: undefined },
      { a: 2, b: undefined, c: undefined },
      { a: 3, b: undefined, c: undefined },
      { a: 4, b: undefined, c: undefined } ]
```
but should be:
```
    [ { a: 1, b: "One", c: undefined },
      { a: 2, b: "Two", c: undefined },
      { a: 3, b: "Three", c: undefined },
      { a: 4, b: "Four", c: undefined } ]
```

**Comment by agershun** [comment]
This is because internal construction of AlaSQL, when data from empty table overwrite original table.

THis issue can be solved if rewrite construction like:
```js
    var res = alasql('SELECT one1.*, two0.* FROM one1 \
        OUTER JOIN two0 ON one1.b = two0.b');
```
to this:
```js
    var res = alasql('SELECT one1.*, two0.b AS bb, two0.c AS cc FROM one1 \
        OUTER JOIN two0 ON one1.b = two0.b');
```

**Comment by agershun** [comment]
Probably, this is not a bug.

**Comment by mathiasrw** [comment]
On MSDN ( https://msdn.microsoft.com/en-us/library/aa213228(v=sql.80).aspx )  it looks like they are stating that the full outer joinand full join returns the same: all rows from both tables, matching up the rows wherever a match can be made while placing NULLs in the places where no matching row exists.

so - if same select with ```full``` added in the second does not return same results we must consider it a bug.

**Comment by agershun** [comment]
Yes, for first question - it is a definitely bug to be discovered. I looked through the grammar file, but still did not find it. Will work on it.

**Comment by agershun** [comment]
I found the bug in the parser (keyword ```FULL``` was not defined). Now it was fixed.

**Comment by mathiasrw** [comment]
:+1:
