### ISSUE TITLE
Modifier 'RECORDSET' incorrectly works with IF EXISTS()

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#152]
Check all cases, where AlaSQL precompile queries like subqueries and exists queries.

**Comment by agershun** [comment]
Fixed. If the ```alasql.options.modifier = "RECORDSET"``` AlaSQL also set this flag by default for all SELECT subqueries and EXISTS subqueries. Now, all EXISTS subqueries by default run with ARRAY modifier.

**Comment by mathiasrw** [comment]
:+1:

**Comment by agershun** [comment]
Internally, I changed it again: Now all subqueries and exists subqueries run with 'RECORDSET' modifier. It is more consistent for all different cases.

In the case of EXISTS AlaSQL checks ```.data``` property, if subquery returns any values.
