### ISSUE TITLE
How to deal with errors

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#153]
How to deal with errors?.  For example:

    alasql('CREATE localStorage DATABASE IF NOT EXISTS Atlas');
    alasql('SET AUTOCOMMIT OFF');
    alasql('ATTACH localStorage DATABASE Atlas AS MyAtlas');
    alasql('USE MyAtlas;');
    alasql("CREATE TABLE transactions (transid, payee, amount)");

If I then write something like this...

    var res = alasql("SELECT * FROM addresses");

...where the table "addresses" clearly doesn't exist, I would somehow expect to get an error response that says "Table 'addresses' doesn't exist."

But as it is, if he above "var res = " line is executed, javascript just stops, and no code after it executes.  So how do I deal with errors?

This page contains a link for error processing, but it doesn't work:

https://github.com/agershun/alasql/wiki

**Comment by mathiasrw** [comment]
would this be handled with `.promise()`?

**Comment by mathiasrw** [comment]
This can now be handled with the .promise notation:

```js
alasql.promise([
		'CREATE localStorage DATABASE IF NOT EXISTS Atlas',
		'SET AUTOCOMMIT OFF',
		'ATTACH localStorage DATABASE Atlas AS MyAtlas',
		'USE MyAtlas;',
		'CREATE TABLE transactions (transid, payee, amount)'
	]).then(function(){
		return alasql.promise("SELECT * FROM addresses");
	}).catch(function(err){
		console.log('Error setting up DB:',err);
	}).then(function(res){
		console.log('The selected result was:', res)
	})
```
