### ISSUE TITLE
invalid bower json file 

### ISSUE THREAD

**Issue by carbuz** [agershun/alasql#162]
the file .bower.json contains an extra coma:

...
 "devDependencies": {
    "gulp":"3.8.11",
    "gulp-changed":"1.2.1",
    "gulp-concat-sourcemap":"1.3.1",
    "gulp-shell":"0.4.1",
    "jison":"0.4.15",
    "lodash":"3.7.0", // <-This extra coma makes the entire json file  invalide unfortunaletely...
  },
...

**Comment by agershun** [comment]
Thank you very much! Fixed. Will release tonight.

2015-05-05 11:36 GMT+03:00 carbuz <notifications@github.com>:

**Comment by carbuz** [comment]
Thank you Andrey, great job with bower!
Il 05/mag/2015 09:52, "Andrey Gershun" <notifications@github.com> ha
scritto:

**Comment by agershun** [comment]
May I ask you, should I use any additional bower commands to 'publish' AlaSQL changes on Bower, or it takes ```.bower.json``` from GitHub?

**Comment by carbuz** [comment]
it should take it directly from  .bower.json - just change the version...

2015-05-05 9:56 GMT+01:00 Andrey Gershun <notifications@github.com>:

> May I ask you, should I use any additional bower commands to 'publish'
> AlaSQL changes on Bower, or it takes .bower.json from GitHub?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agershun/alasql/issues/162#issuecomment-98999402>.
>



-- 

*Andrea Carbone*
*VP Enterprise Solution*

*Fincluster LTD*
Registered Office:
12, Bridewell Place,
EC4V 6AP, London (UK)
Registered in England & Wales no. 08359023
Operating Office:
3rd Floor, 28, Leman Street,
E1 8ER, London (UK)
*M UK*:                 +44 7557446765
*M IT*:                  +39 338 5938367
*E*:         a.carbone@fincluster.com
*Skype*:  andrea.carbone.fincluster

This e-mail contains confidential information or information belonging to
the Fincluster LTD entity sending it and is intended solely for the
addressees. Any views expressed in this message are those of the individual
sender and its contents do not constitute a commitment by Fincluster LTD unless
confirmed by letter or fax. The unauthorised disclosure, use, dissemination
or copying (either whole or partial) of this e-mail, or any information it
contains, is prohibited. E-mails are susceptible to alteration and their
integrity cannot be guaranteed. Internet communications are not secured and
therefore Fincluster LTD shall not be liable for this e-mail if modified or
falsified. If you are not the intended recipient of this e-mail, please
notify the sender of the wrong delivery and delete it immediately from your
system.

**Comment by agershun** [comment]
I updated current version to 0.1.1 with new bower file. Could you test it?

**Comment by carbuz** [comment]
sure, give me 1,5 hours and I will back to you.
Il 06/mag/2015 06:33, "Andrey Gershun" <notifications@github.com> ha
scritto:

**Comment by carbuz** [comment]
Hi, the json is valid.
However it seems DOM-storage does not have a version on bower...

2015-05-06 7:59 GMT+01:00 Andrea Carbone <a.carbone@fincluster.com>:

> sure, give me 1,5 hours and I will back to you.
> Il 06/mag/2015 06:33, "Andrey Gershun" <notifications@github.com> ha
> scritto:
>
>> I updated current version to 0.1.1 with new bower file. Could you test it?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/agershun/alasql/issues/162#issuecomment-99328418>.
>>
>


-- 

*Andrea Carbone*
*VP Enterprise Solution*

*Fincluster LTD*
Registered Office:
12, Bridewell Place,
EC4V 6AP, London (UK)
Registered in England & Wales no. 08359023
Operating Office:
3rd Floor, 28, Leman Street,
E1 8ER, London (UK)
*M UK*:                 +44 7557446765
*M IT*:                  +39 338 5938367
*E*:         a.carbone@fincluster.com
*Skype*:  andrea.carbone.fincluster

This e-mail contains confidential information or information belonging to
the Fincluster LTD entity sending it and is intended solely for the
addressees. Any views expressed in this message are those of the individual
sender and its contents do not constitute a commitment by Fincluster LTD unless
confirmed by letter or fax. The unauthorised disclosure, use, dissemination
or copying (either whole or partial) of this e-mail, or any information it
contains, is prohibited. E-mails are susceptible to alteration and their
integrity cannot be guaranteed. Internet communications are not secured and
therefore Fincluster LTD shall not be liable for this e-mail if modified or
falsified. If you are not the intended recipient of this e-mail, please
notify the sender of the wrong delivery and delete it immediately from your
system.

**Comment by agershun** [comment]
Probably, this is because DOM-storage is a pure Node.js package. I will remove it from ```.bower.json```.

**Comment by carbuz** [comment]
Hi,
in the dependencies I think you should replace "xlsx":"0.8.0" with  "js-xlsx":"0.8.0" (see https://github.com/SheetJS/js-xlsx/blob/master/bower.json ). 
xlsx does not have a bower version.

**Comment by agershun** [comment]
Ok. I will fix it now

Отправлено с iPhone

**Comment by carbuz** [comment]
thanks Andrey

**Comment by agershun** [comment]
Done in new published version 0.1.2. Please, check.

**Comment by carbuz** [comment]
Hi,
you should also replace "xlsjs":"0.7.15" with  "js-xls": "~0.7.5" I think  (if you use ~ it is looking for compatibility)

**Comment by agershun** [comment]
Probably we can eliminate this package (https://github.com/SheetJS/js-xls) from AlaSQL:
<blockquote>
XLS (BIFF5/BIFF8, Excel 95-2004 spreadsheet) and XML (Excel 2003/2004) parser, now merged into http://sheetjs.com/js-xlsx 
http://oss.sheetjs.com/js-xlsx
</blockquote>

I will make this change, but will review do we still need this package.

**Comment by carbuz** [comment]
You are right, it should not be necessary anymore as dependence

**Comment by agershun** [comment]
I changed Bower file (but did not finished the research yet). Thank you!

**Comment by carbuz** [comment]
Hi, it's fine now. Thanks!!!

**Comment by agershun** [comment]
I opened https://github.com/agershun/alasql/issues/171 for js-xls issue
