### ISSUE TITLE
Add security break and check for cycles for SEARCH over graph

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#163]
Now SEARCH operator has very simple security break and has now cycles checking.
This can be improved with:
* Checking cycles
* WHILE clause
* TIMEOUT feature

This functionality also includes realization of stack for paths and some path related selectors, like: PARENT(), ROOT(), etc.

**Comment by mathiasrw** [comment]
Is this on the plan?

Having security issues does not sound good...

**Comment by agershun** [comment]
No, this is not about regular security :) It just to prevent infinity loop into deep nested objects or related nodes in the graph.

**Comment by mathiasrw** [comment]
Put on the long list. Lets reopen when the time has come.
