### ISSUE TITLE
Use in meteor

### ISSUE THREAD

**Issue by vchigne** [agershun/alasql#168]
You might want to include in your documentation something like this for Meteor users:

"Use SQL in Meteor client-side querys.

Let's face it, Mongo sucks on common data operations, so having the ability to use SQL to query data (with JOINS, GRUP BY and so on) would relief a lot of pain.With  alaSQL you can do something like this in your helper:

    productsSold:function(){
     var customerSalesHistory=salesHistory.find({customerId:Session.get('currentCustomer')}).fetch();
       var items=products.find().fetch();
       return alasql("select items.name, sales.ordered as quantity from ? sales, ? items
        where items.Id=sales.itemId",[customerSalesHistory,items]);
     }
"
Also, you might want to create the json to make alaSql a meteor package. Meteor users can only use minimongo, so there is a real need of a reactive way to make reactive querys on teh client.
Also, minimongo is not persistent, while I see that alaSql is. So for Meteor users, alaSql is the best thing ever.

**Comment by wuxianliang** [comment]
@vchigne AlaSQL supports not only tables but also documents and graphs. Based on   Meteor-Postgres, we can produce a "Meteor-SQL" which make us sql tables, documents and graphs at the same time and use Postgres and OrientDB as backends. Months later OrientDB will release stable Live Query support, which make the reactivity of the database natively supported.

Publishing  AlaSQL as a Meteor Package is a good idea. "SQL ALL" is making history! @agershun

**Comment by agershun** [comment]
Many thanks for ideas! I will install Meteor and will learn how to create packages for it. Of course, it will take lot of  time to create and test it! I will make a research on this question and write about AlaSQL plans in Meteor area.

**Comment by agershun** [comment]
**Could you help me with this question?**
I tried to convert sample Meteor todo application [from here](https://www.meteor.com/try/3) with AlaSQL.

1. I stored ```alasql.min.js``` to the ```client/lib``` directory. This works fine.
2. Then I replaced the code:
```
   Template.body.helpers({
       tasks: function () {
       return Tasks.find({}, {sort: {createdAt: -1}});
  }
```
with this code:
```
   Template.body.helpers({
       tasks: function () {
       return alasql('SELECT * FROM ? ORDER BY createdAt DESC',[Tasks.find().fetch()]);
  }
```
This works fine.

3. I can add to AlaSQL this kind of logic: if the ```source instanceof Mongo.Collection```, then apply ```source.find().fetch()``` automatically by default. This will allow to write:
```
   Template.body.helpers({
       tasks: function () {
       return alasql('SELECT * FROM ? ORDER BY createdAt DESC',[Tasks]);
  }
```
Is this functionality required?

**Comment by vchigne** [comment]
Of course it is! I would result in less code and is a usual operation in meteor

**Comment by agershun** [comment]
I added this functionality.to the next version of AlaSQL (now you can download it from ```develop``` branch or from http://alasql.org/console/alasql.min.js.

Now you can simply write:
```
  Template.body.helpers({
       tasks: function () {
       return alasql('SELECT * FROM ? ORDER BY createdAt DESC',[Tasks]);
  }
```
May I ask you to test this function?

**Comment by agershun** [comment]
I will publish this functionality to ```master``` branch and ```npm```  to the next release 0.1.4 on Monday.

**Comment by vchigne** [comment]
Maybe yu might want to add a restriction to the collection, like:
 Tasks ({owner:idOwner})

That's common too

**Comment by agershun** [comment]
Could you explain this with more details or reference to the code or manual (Sorry, I am absolutely dilettante with Meteor). Should this restriction to be set by default or this code is user specific?

**Comment by vchigne** [comment]
Its user specific, Usually you use a scoped collection, You set the scope in the find clause with mongo usual sintax

**Comment by vchigne** [comment]
Your example could be 
   Template.body.helpers({
         tasks: function () {
         return alasql('SELECT * FROM ? ORDER BY createdAt DESC',[Tasks({condition})]);
    }

or 

    return alasql('SELECT * FROM ? ORDER BY createdAt DESC',[Tasks ("condition")]);

**Comment by agershun** [comment]
Some variants of the syntax to choose:
```
    1. alasql('SELECT * FROM METEOR(?,{condition}) ORDER BY createdAt DESC',[Tasks]);
    2. alasql('SELECT * FROM ? FIND {condition} ORDER BY createdAt DESC',[Tasks]);
    3. alasql('SELECT * FROM ? FIND ? ORDER BY createdAt DESC',[Tasks,{owner:idOwner}]);
```
Which one is better?

I already thought to add FIND clause to SELECT operator to work with Mongo-like queries (or on top of NoSQL databases.

**Comment by vchigne** [comment]
I like the first one but if you have thought about FIND for a consistent way to speak to NoSQL databases, then 2 is more flexible whlie 3 will break the current convention of having only query origins in the array.

**Comment by vchigne** [comment]
@wuxianliang  looks like a great idea but the team of meteor stream is doing something like that IIRC

**Comment by agershun** [comment]
Ok. I will try to construct something like this (you can use it in the both ways):
```
    alasql('SELECT * FROM METEOR(?,{condition}) ORDER BY createdAt DESC',[Tasks]);
    alasql('SELECT * FROM METEOR(?,?) ORDER BY createdAt DESC',[Tasks, {owner:idOwner}]);
```
10 minutes...

**Comment by vchigne** [comment]
Ok its important to check if reactivity is maintained. Blaze should be able to notice the new query

**Comment by agershun** [comment]
Could you try this code:

    Template.body.helpers({
    tasks: function () {
        alasql.from.METEOR = function(filename, opts, cb, idx, query) {
           var res = filename.find(opts).fetch();
           if(cb) res = cb(res, idx, query);
            return res;
         };
         return alasql('SELECT * FROM METEOR(?,?)',[Tasks,{text:"Hello world!"}]);
       }
    });

**Comment by vchigne** [comment]
Let me adapt this to my current query, BRB

**Comment by vchigne** [comment]
Do I need to install the development branch?

**Comment by agershun** [comment]
No, just copy ```alasql.min.js``` from [here](http://alasql.org/console/alasql.min.js) to the ```client/lib``` directory

**Comment by vchigne** [comment]
It workd and, ITS REACTIVE :)

**Comment by agershun** [comment]
:+1:  Should we include this METEOR from-function into release?

**Comment by agershun** [comment]
Is METEOR is a good name or it should be something like: MONGOLIKE() or else?

**Comment by agershun** [comment]
BTW: you can use it with and without conditions:
        return alasql('SELECT * FROM ?',[Tasks]);
        return alasql('SELECT * FROM METEOR(?)',[Tasks]);
       return alasql('SELECT * FROM METEOR(?,?)',[Tasks,{text:"Hello world!"}]);
```

**Comment by vchigne** [comment]
I think this is usefull for all the mongo ecosystem,so mongoLike could be a good bame, but actually I'm starting to like the FIND  name. 
But if you call it METEOR, then it will be clear that this querys are ALSO reactive :)
It's up to you

**Comment by agershun** [comment]
1. Ok, let it be METEOR(). I include this from-function and default converter into the next release 0.1.4. 
2. I will reserve FIND for future integration with Mongo-like systems (for example AlaSQL on top of Mongo or minimongo with translation to {}-like conditions).

Victor, thank you! Please, let me know if you have other ideas or issues in this integration. I also will add our research to the documentation.

**Comment by vchigne** [comment]
Thanks to you!
Actually, the biggest problems in meteor are:
- Server Side: No SQL backend, Numtel and meteor stream are trying to solve that.
- Client Side: - Minimongo! (alaSQL solves that)
                     - No persistent storage. That should be worked trying to define some connections as persistent and storing those in the client with automatic and manual syncronization.

**Comment by vchigne** [comment]
I forgot, it's very important to have alaSql in a meteor package. It's not hard but I never have done this.
This is  the relevant section of the manual

http://docs.meteor.com/#/full/writingpackages

**Comment by agershun** [comment]
Thank you! I will learn on weekends how to do it.

**Comment by vchigne** [comment]
I forgot something:
Minimongo has no transactions. If you can implement a set of upserts in a transactions, that would be crazy. Right now everyone is simply ignoring the issue, but it could be a huge problem specially in persistent collections. 
Thanks again, I'll try to test whatever yo send me this weekend (but this sunday is Mothers Day here)

Regards

**Comment by vchigne** [comment]
This should do the trick, but don't take my word on it :)

package.js

```javascript
/* Information about this package */
Package.describe({
    // Short two-sentence summary.
    summary: "SQL DML and DDL for meteor collections",
    // Version number.
    version: "1.1.4",
    // Optional.  Default is package directory name.
    name: "agershun:alasql",
    // Optional github URL to your source repository.
    git: "https://github.com/agershun/alasql.git",
});

/* This defines your actual package */
Package.onUse(function (api) {
    // If no version is specified for an 'api.use' dependency, use the
    // one defined in Meteor 0.9.0.
    api.versionsFrom('1.0.0');
    // Use Underscore package, but only on the server.
    // Version not specified, so it will be as of Meteor 0.9.0.
    //api.use('underscore', 'server');
    // Use iron:router package, version 1.0.0 or newer.
    //api.use('iron:router@1.0.0');
    // Give users of this package access to the Templating package.
    //api.imply('templating')
    // Export the object 'alasql' to packages or apps that use this package.
    api.export('alaSql', 'client');
    api.export('alaSql', 'server');
    // Specify the source code for the package.
    api.addFiles('alasql.js');
    api.addFiles('alasql.js');
});

/* This defines the tests for the package */
Package.onTest(function (api) {
    // Sets up a dependency on this package
    //api.use('username:package-name');
    // Allows you to use the 'tinytest' framework
    //api.use('tinytest@1.0.0');
    // Specify the source code for the package tests
    //api.addFiles('email_tests.js', 'server');
});

/* This lets you use npm packages in your package*/
Npm.depends({
    //simplesmtp: "0.3.10",
    //"stream-buffers": "0.2.5"});/**
```

**Comment by agershun** [comment]
:+1:

**Comment by agershun** [comment]
I seems that I finaly published the ```alasql``` package, but cannot test it.

**Comment by agershun** [comment]
https://atmospherejs.com/agershun/alasql

**Comment by agershun** [comment]
Sorry, it still is not working. I will check tomorrow.

**Comment by vchigne** [comment]
How is it going Andrey?

**Comment by agershun** [comment]
I put the source of Meteor package in /meteor directory, but still something wrong. Unfortunately, I cannot work on this issue until Friday .

**Comment by agershun** [comment]
Tested. I works (at least at my computer). It installs on the client and server side as well.

To install it, please use:
```
    meteor add agershun:alasql
```
Could you try it?

**Comment by wuxianliang** [comment]
Great! It works! Both sides.

**Comment by vchigne** [comment]
It rocks. Works in client and server :)

**Comment by agershun** [comment]
@wuxianliang @vchigne Many thanks for testing. May I ask you to test one more thing: how AlaSQL plugins system works.

1. Please, update current version of agershun:alasql package to version 0.1.13
```
    meteor update agershun:alasql
```
2. Try this code:
```
    alasql('REQUIRE ECHO');
    alasql('ECHO 123');
```

```ECHO``` is a simple command stored in separate plugin file: ```alasql-echo.js``` (you can see it in the ```develop``` branch [alasql-echo.js](https://github.com/agershun/alasql/blob/develop/src/echo/alasql-echo.js)). The same approach in Node.js and browser

I am going to put all aside functionality outside the core via this plugin system.

**Comment by agershun** [comment]
Now the same REQUIRE ECHO code should also should work in the Meteor server in version  0.1.14.

**Comment by agershun** [comment]
@wuxianliang I did all urgent things for AlaSQL (including SQLLOGICTEST, Meteor integration, and plug-in system). Now I put the OrientDB compatibility in the first priority. Hope, we can test something very soon.

**Comment by vchigne** [comment]
Sorry Andrey, I didn´t read your request to test on time.
It works well, but you already know it. 
Regards

**Comment by agershun** [comment]
:+1:

**Comment by mathiasrw** [comment]
Wow - so many things blooming - and I just looked away for 24 days. 

Love that there is meteor support now!

**Comment by agershun** [comment]
Can you test this package?

**Comment by mathiasrw** [comment]
Sure - I have been missing an excuse to get on the meteor (t)rain

**Comment by mathiasrw** [comment]
Regarding the 3 ways

    1. `alasql('SELECT * FROM METEOR(?,{condition}) ORDER BY createdAt DESC',[Tasks]);`
    2. alasql('SELECT * FROM ? FIND {condition} ORDER BY createdAt DESC',[Tasks]);`
    3. `alasql('SELECT * FROM ? FIND ? ORDER BY createdAt DESC',[Tasks,{owner:idOwner}]);`

Did we go with all 3 or what?

**Comment by agershun** [comment]
Now we have only two:
```js
    // Without search conditions
    alasql('SELECT * FROM ? ORDER BY createdAt DESC',[Tasks]);

    // With search conditions
    alasql('SELECT * FROM METEOR(?,{condition}) ORDER BY createdAt DESC',[Tasks]);
```
