### ISSUE TITLE
Add CREATE UNIQUE INDEX statement

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#175]

**Comment by mathiasrw** [comment]
Is this on the plan? Looks like a very useable feature :)

**Comment by agershun** [comment]
Yes, I want to rewrite all indexes in complex to support unique and not-unique indexed.

BTW. See the daily tasklist and priorities here:
https://trello.com/b/qxz65pVi/alasql-roadmap

**Comment by mathiasrw** [comment]
Trello is such an awesome tool. Glad you have found it useful. 

Looks really great. 

I was 


I just saw your work with the TESTLOG.md. Well done ! Are you autogenerating this from the output or is it manually? We could make a more - ehhh - computer readable format if you intent to use the KPIs a lot. 

The plan was to wrap Mocha around the tests. It that still central for the development? 

I was looking into the Readmw. There is a lot of awesome information - but some of it could use some love regarding where its placed. I might move a section here and there if its ok with you.

**Comment by agershun** [comment]
> Are you autogenerating this?

Great idea! We can improve improve SQLLOGIC and NIST test to autogenerate this page every time before release. Plus I want to put some technical information about size and memory usage.

> README.md
I appreciate it very much, if you can structure README.md!!!! 

We can restore ```doc``` directory to keep all related files and put these pages there. Let we do it on this way: For the next release 0.1.8 (it should be soon) if you will be ready with structuring this, we will update README and all subfiles.
