### ISSUE TITLE
Create simple TRIGGERS on INSERT/DELETE/UPDATE with calling SQL or JavaScript functions

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#177]

**Comment by mathiasrw** [comment]
Wow - so many ideas hit me reading the headline to implement reactive programming merging triggers with my own javascript function calls :)

**Comment by agershun** [comment]
:+1: Can you write a simple sample of the code, how this feature can be used in reality, We will use it for TDD.

**Comment by agershun** [comment]
Now you can use triggers with JavaScript:
```js
    alasql.fn.check = function(r) {
         if(r.n == 42) return false; // Do not insert on this number 
    };
    alasql('CREATE TRIGGER mytrigger BEFORE INSERT ON mytable check');
