### ISSUE TITLE
alasql distinct (lowercase) with group_concat

### ISSUE THREAD

**Issue by rameshrajagopalanbayer** [agershun/alasql#1776]
Fiddle Example:  https://jsfiddle.net/udynw6k9/

We see alasql('SELECT GROUP_CONCAT(**distinct** answeredDate) from ? does not work, where as SELECT GROUP_CONCAT(DISTINCT answeredDate) from ? does work. 

The thing is that it behaves like it no oped on `distinct`  in above query.

But queries like `SELECT distinct answeredDate from ?` or `SELECT DISTINCT answeredDate from ?` work fine.

The GROUP_CONCAT is just for example, It probably happens with any of other aggregations with distinct as I had same issue with a custom aggr.
.

**Comment by rameshrajagopalanbayer** [comment]
It feels like related to check in line https://github.com/AlaSQL/alasql/blob/develop/src/alasqlparser.js#L812 which is not case insensitive. But I dont know the project at all to say for sure. Atleast thats what it felt like to me when i changed that in local and tried.

The change was `$$[$0-2]?.toUpperCase() =='DISTINCT'`

**Comment by mathiasrw** [comment]
Looks like the right spot. Would you like to make a PR to get the credit?

**Comment by rameshrajagopalanbayer** [comment]
sure will create a PR with some tests and update this issue.

**Comment by rrameshkumar76** [comment]
@mathiasrw I have created  https://github.com/AlaSQL/alasql/pull/1778 
I created the PR from my main github account. Did not realize had created the issue my other account.

**Comment by rameshrajagopalanbayer** [comment]
created new PR https://github.com/AlaSQL/alasql/pull/1781
