### ISSUE TITLE
Fix example with es6-promises

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#179]
Now es6-promises package was excluded from alasql.js to minimize dependecies , so the example in README.md should be reqritten.

**Comment by agershun** [comment]
Now AlaSQL checks if Promises are available. To run async version of alasql use async() function:
```js
    alasql.async('SELECT * FROM one')
    .then(function(data){
        console.log(data);
    }).catch(functiion(err){
        console.log(err);
    });

**Comment by agershun** [comment]
```.async()``` was changes to ```.promise()```

**Comment by dmvianna** [comment]
I am unable to use promises, even in the `develop` branch. Is it present in your 0.2.0 release?

**Comment by mathiasrw** [comment]
Hmmm. Really strange. This has stopped working. Thank you for letting us know. 

I have opened https://github.com/agershun/alasql/issues/426 with the issue
