### ISSUE TITLE
Sub-queries/nested queries

### ISSUE THREAD

**Issue by kshitijnagpal** [agershun/alasql#1809]
How do I write sub-queries like below?

SELECT 
*
  FROM
      table1 tbl
  WHERE
     tbl.col1 < (SELECT MAX(serial_number) from table2)

I tried using `VALUE OF` in the sub-query as described here: https://github.com/AlaSQL/alasql/wiki/Value but couldn't get it to work

**Comment by mathiasrw** [comment]
> Question about how to ...
> - Please use http://stackoverflow.com/questions/ask?tags=alasql
