### ISSUE TITLE
How do I set column width when using alasql?

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#181]
By @MaxNoack from https://github.com/SheetJS/js-xlsx/issues/224

How can I set my output column width on my xlsx file to be as wide as the text in every column? I use the following code in my AngularJS controller:
```js
angular.module('myApp').controller("myController", function ($scope){
...
$scope.mydata = (some table data);
    $scope.exportData = function () {
         alasql('SELECT * INTO XLSX("Report.xlsx",{headers:true}) FROM ?',[$scope.mydata]);
    }
};
```

**Comment by agershun** [comment]
Unfortunately, this functionality is not realized in AlaSQL with js-xlsx library (XLSX() into-functions).You can do it with XLSXML() renderer:
```
$scope.mydata = (some table data);
    $scope.exportData = function () {
        var mystyle = {
          headers:true, 
          rows: {1:{style:{Font:{Color:"#FF0077"}}}},
            columns: [{columnid:'name',width:500},{columnid:'email',width:200}],
          cells: {1:{1:{
            style: {Font:{Color:"#00FFFF"}}
          }}}
        };
         alasql('SELECT * INTO XLSX("Report.xlsx",{headers:true}) FROM ?',[style, $scope.mydata]);
    }
};
```
In this case you do not need to include js-xlsx, because AlaSQL uses internal renderer.
You can try this example [in jsFiddle](http://jsfiddle.net/95j0txwx/21/).

Currently, I am working on this issue to allow use styles with js-xlsx and put this issue on le priority list.

**Comment by UtsavNathPandey** [comment]
@agershun Did you get the fix to apply styles to the exported "xlsx" file.
Thanks, Utsav

**Comment by akintundejr4** [comment]
@agershun  @UtsavNathPandey  Yes also using alasql and running into this same issue so update would be nice. 

Thanks,
