### ISSUE TITLE
Documentation update for options 

### ISSUE THREAD

**Issue by paulrutter** [agershun/alasql#1827]
While working on recent performance improvements, i noticed that the options available in alasql don't seem to be documented anywhere. 

Because some of these impact the performance, like the new `dateAsString`, i think it would make sense to document some of these options, and how to set them when using Alasql. 

If you agree, i could make a PR with some of these. 
Where would be the best place to do this, the README?

**Comment by paulrutter** [comment]
Ah i see https://github.com/AlaSQL/alasql/wiki/AlaSQL-Options, which i can extend and maybe link to in the README?

**Comment by mathiasrw** [comment]
Thanks for the PR. This is exactly how we do better together.
