### ISSUE TITLE
Add select over tree structures

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#185]

**Comment by mathiasrw** [comment]
Could you put more words to this?

**Comment by agershun** [comment]
Yes, sorry, I implemented SEARCH operator to traverse over JSON structures with XPath-similar syntax (bit different)

```sql
    SEARCH /+ a FROM [{a:1},{a:{a:2}}]
   -- returns [1,2]
```
See [new tests](https://github.com/agershun/alasql/blob/develop/test/test314.js). To de described...

**Comment by mathiasrw** [comment]
Really love that. 

Would be good with some words to what we are not using from XPath so we can help people understand what we are :)

**Comment by agershun** [comment]
We can implement XPath as well. I just wanted to preserve SQL-like syntax. Actually now SEARCH is a combination of OrientDB SELECT, jQuery selectors, XPath, and my fantasies. 

The good point - now I know how to do it. For example see below - it is a solution of "8 queens" problems (not working yet, but I will fix it soon):
```sql
    search times( -- repeat 8 times
        ^/ as @f     -- start from very beginning
        where(      -- go further only if condition is true
          @f not in @h -- if queen not in horizontal
          and (@f-@i) not in @d   -- and not in diagonal 1
          and (8-@i-@f) not in @g  -- and not in diagonal 2
        )
        @f to @h   -- push to horizontals array
        ex(@f-@i) to @d  -- push to diagonals 1 array
        ex(8-@i-@f) to @g, -- push to diagonals 1 array
      0,7,@i)  - repeat 8 times
      return @h -- put horizontals in the result array like [[1,5,3,6,8,3,2,7], ...]
    from range(1,8)  -- from array [1,2,3,4,5,6,7,8]
```

We can implement XPath on [Microsoft way](https://msdn.microsoft.com/en-us/library/ms256086(v=vs.110).aspx) as plugin. Plus, XPath is designed to work with XML, but not JSON.

**Comment by mathiasrw** [comment]
>    Actually now SEARCH is a combination of OrientDB SELECT, jQuery selectors, XPath, and my fantasies

As long as its for the better and we can communicate it clearly its good - but if we introduce a lot of confusion so people dont get it then its bad. The best part is your fantasies that can combine and take/make the best from the different worlds - the challenge is to get people boardet with the fantasies so they manifest in easy programming :)

**Comment by mathiasrw** [comment]
Any news on this?

**Comment by ohenrik** [comment]
Is there any documentation of `search`? I'm trying to get nested values, however if the deepest level of the nested values do not have value they are ignored.

Example: A team has team members, team members have categories. I want to get all team members, their team name and the team categories. The team members should be repeated for each  category if that is possible.

Any tips on how to solve this?

**Comment by agershun** [comment]
Here is the sample:
```js
var alasql = require('alasql');

var data = [
	{
		teamname:'Alpha',
		members: [
			{
				membername:'Andrey',
				categories: ['JavaScript','C++']
			},
			{
				membername:'Mathias',
				categories: ['JavaScript','Java']
			},
		]
	},
	{
		teamname:'Beta',
		members: [
			{
				membername:'Ole',
				categories: ['JavaScript']
			}
		]
	},
];

var res = alasql('SEARCH / AS @team \
		members / AS @member \
		categories / AS @category  \
		RETURN(@team->teamname AS team, @member->membername AS member, @category AS category) \
		FROM ?',[data]);
console.log(res);
```
returns
```json
[ { team: 'Alpha', member: 'Andrey', category: 'JavaScript' },
  { team: 'Alpha', member: 'Andrey', category: 'C++' },
  { team: 'Alpha', member: 'Mathias', category: 'JavaScript' },
  { team: 'Alpha', member: 'Mathias', category: 'Java' },
  { team: 'Beta', member: 'Ole', category: 'JavaScript' } ]
```

Here:
* `SEARCH` - search keyword
* `/` - walk over all members of array
* `AS @team` - save result into temporary variable `team`
*` members` - take member property of previous result
* `/` - walk over all members of members array
* `AS @member` - save result into temporary variable `member`
*` categories` - take category property of previous result
* `/`- walk over categories array
* `RETURN(...)` - pseudo-function to create result record
* `RETURN(@team->teamname AS team,...)` - take temporary variable 'team', take its teamname property and store it as team property of result object
* `FROM ?` - standard source from array clause
* `alasql('...',[data])` - take source data from `data` array

Hope this will help. 


Sorry for the lack of proper documentation... :(

**Comment by agershun** [comment]
Sorry, I missed `when a team member do not have a category they are not included in the result. I need them included but with an empty category column`, and modified the query:

```js
var alasql = require('alasql');

var data = [
	{
		teamname:'Alpha',
		members: [
			{
				membername:'Andrey',
				categories: ['JavaScript','C++']
			},
			{
				membername:'Mathias',
				categories: []
			},
		]
	},
	{
		teamname:'Beta',
		members: [
			{
				membername:'Ole'
			}
		]
	},
];

// Special function
alasql.fn.myfn = function(a) {
	if(!a) return [undefined];
	if(a.length == 0) return [undefined];
	return a;
}

var res = alasql('SEARCH / AS @team \
		members / AS @member \
		EX(myfn(categories)) / AS @category  \
		RETURN(@team->teamname AS team, @member->membername AS member, @category AS category) \
		FROM ?',[data]);
console.log(res);
```
returns:
```
[ { team: 'Alpha', member: 'Andrey', category: 'JavaScript' },
  { team: 'Alpha', member: 'Andrey', category: 'C++' },
  { team: 'Alpha', member: 'Mathias', category: undefined },
  { team: 'Beta', member: 'Ole', category: undefined } ]
```

**Comment by ohenrik** [comment]
@agershun Thank you! That works perfectly!

**Comment by ohenrik** [comment]
Is it possible to group these results? It seems like allot of the normal commands related to SELECT does not work with SEARCH. Also it seems like the search result is not possible to use as a subquery.

Currently the only way i have found to come around this is to return the result and then use that result in a new query. Is there a better way?

**Comment by agershun** [comment]
```SEARCH``` does not have ````GROUP BY``` clause, so you did it right way.

**Comment by mathiasrw** [comment]
I updated the wiki page for [RETURN](https://github.com/agershun/alasql/wiki/RETURN)

**Comment by icinemagr** [comment]
i try to find how to group json flat array first by categroy then by subcategory then by subsubcategory and so on.No where exists any example.Where can i search?
