### ISSUE TITLE
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive

### ISSUE THREAD

**Issue by elangoRamar** [agershun/alasql#1861]
I am trying to use alasql in an browser environment, when i try to load the script which has alasql bundled within it is giving 

`EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive`

Based on content security policy we can't use those JS functions mentioned in this [link](https://www.w3.org/TR/CSP3/#directive-script-src)

It seems alasql is using new Function() which triggers the CSP error. how can we resolve this?

**Comment by mathiasrw** [comment]
AlaSQL is built around creating code. for new functions. If you are not allowed to create new functions then AlaSQL cant help you (until we made a version that preprocesses the functions as part of the build step - but we are not there yet)

**Comment by githorse** [comment]
Duplicates #1482, #1489, and #1667.
