### ISSUE TITLE
Invalid query throws `n.Term is not a constructor`

### ISSUE THREAD

**Issue by jcubic** [agershun/alasql#1871]
I've noticed that the error message on the invalid token looks like this:

> n.Term is not a constructor

When executing:

```
> xxxx
```

It looks like the invalid token is not handled and it just throws an unhandled exception.

You can see this on my Terminal App:

https://codepen.io/jcubic/pen/dVBaRm

**Comment by mathiasrw** [comment]
What are you expecting from the query XXXX?

**Comment by jcubic** [comment]
I expected a different error message, like "Invalid Query" or "Invalid Token", but the error is not handled and it throws an internal error.

**Comment by vishal6557** [comment]
@mathiasrw  Can you assign this to me? Thanks!

**Comment by jcubic** [comment]
@vishal6557 Open Source project don't use assignment, especially for people that are outside the project. Where did you learn that project need to assign the task to you?

**Comment by vishal6557** [comment]
@jcubic Thank you for your feedback! You're right—open-source projects flourish through collaboration and volunteer efforts. My goal was simply to offer help with this issue, aiming to contribute positively without overstepping.

**Comment by mathiasrw** [comment]
Fix released as part of v4.3.1
