### ISSUE TITLE
Inconsistent error message for invalid table names (SELECT vs JOIN)

### ISSUE THREAD

**Issue by clarkd** [agershun/alasql#1885]
Usually when you run a query with an invalid table name, you get a good error message:
`Table does not exist`

But, if you try to do something like JOIN against an invalid table name, you get:
`Cannot read properties of undefined (reading 'columns')`

It would be great if there was a consistent error message for situations like this. 

See JSFiddle [here](https://jsfiddle.net/bmt4fj8L/)

**Comment by mathiasrw** [comment]
Released as part of v4.3.0
