### ISSUE TITLE
AlaSQL plugin system

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#189]
I added the plugin system to AlaSQL. All plugins are 'official' and 'custom'. 
To include official plugin call:
```js
    alasql('REQUIRE GRAPH, XML, INDEXEDDB');
    // ...
```

For custom plugins use the same command but with string path:
```js
    alasql('REQUIRE "myplugin.js");
```

The current list of official plugins include:
* Database backend: indexeddb, localstorage, filestorage, sqljs
* Compatibility: tsql, mysql, oracle, postgres, sqlite, orientdb
* Import-export: xml, xls
* Graphs and complex searches: graph, prolog

All these plugins still will be included in the full version of alasql.js and alasql.min.js, but will be excluded from alasql.js and alasql.min.js since version 0.2

**Comment by agershun** [comment]
Plugin system is ready. It should be improved and I have to prepare the list of official plugins. The system tested in browser, Node.js and Meteor (both sides).

**Comment by mathiasrw** [comment]
Must say - you are a machine - well done!

Do we have some description on how to make a plugin?

**Comment by agershun** [comment]
I will provide description.

The only example now is ```alasql-echo.js``` - see in dist directory.

**Comment by danielecr** [comment]
Sorry, I read this, but where are "official plugins"? I tried

> alasql("REQUIRE mysql")

I got error. Was those splitted? need a special parser?
