### ISSUE TITLE
Is AlaSQL suited to process untrusted SQL

### ISSUE THREAD

**Issue by KilianU** [agershun/alasql#1896]
Hi,

I'm searching for a SQL engine that can be safely used with untrusted SQL input.
The goal is to provide an SQL API to my users. They are allowed to see everything within the database, but they should not be able to load plugins on their own or execute their own Javascript.
Is AlaSQL suited for this usecase? Would be grateful for any input on this.

Kind regards

**Comment by mathiasrw** [comment]
AlaSQL was designed to work client side where there is no chance of you tampering with other peoples data. 

Never run untrusted SQL in an env. where they can access resources or other peoples data.
