### ISSUE TITLE
SELECT (SELECT 1) returns 'undefined'

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#191]
See also test333.js based on the query from [this article](http://www.bennadel.com/blog/85-why-null-values-should-not-be-used-in-a-database-unless-required.htm)

**Comment by mathiasrw** [comment]
I (really) like the article - but cant see how its directly related to 

    SELECT (SELECT 1)

(that I imagine will return ```1```)

**Comment by agershun** [comment]
yes. The query from this article does not work because of this bug:
```
SELECT
    (
        SELECT
            COUNT( * )
        FROM
            test t
        WHERE
            LEN( t.name ) = 0
    ) AS len_count
```

**Comment by mathiasrw** [comment]
```
>  alasql "select (select 1)"
[ { 'SELECT 1': 1 } ]
```

I will close the issue
