### ISSUE TITLE
xlsx.js CDN link is not reachable

### ISSUE THREAD

**Issue by yasenstar** [agershun/alasql#1916]
Hello all,

In the wiki page https://github.com/AlaSQL/alasql/wiki/XLSX, the xlsx CDN URL:

<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/X.Y.Z/xlsx.core.min.js"></script>

is 404 Not Found.

Thanks,
Xiaoqi

**Comment by mathiasrw** [comment]
Thanks. This has been fixed.
