### ISSUE TITLE
Does alasql have the MOD function (find a remainder after division)

### ISSUE THREAD

**Issue by pushkarone** [agershun/alasql#1917]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better.

Got ChatGPT?
- Try the AlaSQL Bot for answering questions and helping you out with your programming. It has all the documentation and heaps of examples.
- https://chat.openai.com/g/g-XcBL24WTe-alasql-bot

---

Question about how to...
- Please use http://stackoverflow.com/questions/ask?tags=alasql

---

Something is not working as expected:
- Describe the problem.
- Provide code that replicates the problem.
- We suggest spawning a jsfiddle from https://jsfiddle.net/63xjwo4s/

**Comment by pushkarone** [comment]
Does alasql have the MOD function (find a remainder after division)

**Comment by mathiasrw** [comment]
```
var result = alasql('SELECT VALUE MOD(10, 3)'); 
console.log(result); // Output: 1
```
