### ISSUE TITLE
Any way to use alasql on columnar/column-oriented data structure?

### ISSUE THREAD

**Issue by daviddabingu** [agershun/alasql#1938]
Hello.
I am trying to test alasql on my project.

I have my data stored in a columnar data structure in-memory, that is:
var data = {
  column1: [1,2,3],
  column2: [4,5,6],
  ...
}

However, it seems AlaSQL only supports a row-oriented data structure.
Is there any way I can directly use alasql on the column-wise data like that?
Thank you in advance.

------------------------------------------------------------------------------------------------------------
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better.

Got ChatGPT?
- Try the AlaSQL Bot for answering questions and helping you out with your programming. It has all the documentation and heaps of examples.
- https://chat.openai.com/g/g-XcBL24WTe-alasql-bot

---

Question about how to...
- Please use http://stackoverflow.com/questions/ask?tags=alasql

---

Something is not working as expected:
- Describe the problem.
- Provide code that replicates the problem.
- We suggest spawning a jsfiddle from https://jsfiddle.net/63xjwo4s/

**Comment by paulrutter** [comment]
Not to bash on alasql, as it does a great job, but for columnar based data you are probably better of with something like https://duckdb.org/docs/api/nodejs/overview.html, it can load columnar data in a native way via Apache Arrow.

It doesn't match the data ingestion speed from alasql, but makes up in query time over big tables.

**Comment by mathiasrw** [comment]
Thank you @paulrutter for helping out here. Always pick the right tool for the job. DuckDB is a great tool and for sure better in this case.
