### ISSUE TITLE
How to contribute wiki page improvements? 

### ISSUE THREAD

**Issue by paulrutter** [agershun/alasql#1941]
The current wiki is helpful but incomplete in a lot of places. Since we're in the process of integrating AlaSQL into a part of our product, we might want to improve the documentation in some areas (especially around using date functions and other basics).

https://github.com/AlaSQL/alasql/wiki

Is there a way to contribute PR's to the documentation?
@mathiasrw let me know.

**Comment by mathiasrw** [comment]
That sounds amazing!

We rely on the built in wiki feature and it does not have any PR available. Hmm. I guess I could make one. HOld on!

**Comment by mathiasrw** [comment]
I made https://github.com/AlaSQL/ala-wiki

It will not be synced in real time into the wiki, but better to offer PRs than not.

**Comment by paulrutter** [comment]
Thanks, will let you know when we have something to contribute.

**Comment by paulrutter** [comment]
@mathiasrw See https://github.com/AlaSQL/ala-wiki/pull/1 for an initial improvement on the date functions page.
If you think this is indeed an improvement, i might look into other pages as well.

**Comment by mathiasrw** [comment]
Neat. https://github.com/AlaSQL/alasql/wiki/Date has been update.
