### ISSUE TITLE
Fix HAVING bug

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#20]
Having function does not work properly.
See example at http://jsfiddle.net/5prbwtzy/
(for http://stackoverflow.com/questions/18052645/complex-sql-query-on-javascript-object?rq=1)

**Comment by agershun** [comment]
The example is adjusted http://jsfiddle.net/5prbwtzy/2/

**Comment by mathiasrw** [comment]
Is there written a test to make sure we dont reintroduce this issue?

**Comment by agershun** [comment]
Yes. [test174.js](https://github.com/agershun/alasql/blob/develop/test/test174.js)

**Comment by mathiasrw** [comment]
:+1:

**Comment by mathiasrw** [comment]
Question: I dont understand the command 

    var alasql = require('..');

in the tests. What does the two dots represent?

**Comment by agershun** [comment]
It takes module from upper directory. Node.js analyses package.json file and load ```dest/alasql.js```file

**Comment by mathiasrw** [comment]
Ahh !
