### ISSUE TITLE
Run NIST SQL tests

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#213]
I found [SQL Test Suite](http://www.itl.nist.gov/div897/ctg/sql_form.htm) tests from NIST institute. Hope, AlaSQL can comply with it except GRANTs.

**Comment by agershun** [comment]
NIST tests were added. According first estimates AlaSQL+NIST test parser passed about 50% of tests.

**Comment by mathiasrw** [comment]
Ahh, here is the NIST - Great!

Poked a bit in the options - looks like its an embedded C implementation ported to several modern platforms as COBOL, fortran and ada.

There is a nice description indicating that the "Test Suite may be used to evaluate conformance to the following SQL standards:
- FIPS 127-2
- ANSI X3.135-1992
- ISO/IEC 9075:1992
- X/Open XPG4 SQL

I have a feeling we should focus on the ISO/IEC 9075:1992 version. 

Had a short glimse into the test code. It looks like there is a strong focus on testing if the system truly separates data for different users logged in. This is not our focus, so have to look into how we "ignore" that part. 

The test suite _"has been developed by the Information Laboratory of the National Institute of
Standards and Technology in support of its federally mandated program of Federal Information
Processing Standards (FIPS).  The purpose of this test suite is to help evaluate conformance of SQL
implementations..."_ so hopefully its quality code that can be reused easily.

An idea came to my mind - I might be able to do some minor changes and compile it with clang -> emscripten -> asm.js so the original code can run in the browser. Besides being awesome it would also surpass to cherry pick the test scripts and expected results out from 365 files with SQL wrapped in comments containing instructions like this

```SQL

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:7066 Drop character set no granted privileges!

   CREATE CHARACTER SET TESTSET GET SQL_TEXT;
-- PASS:7066 If character set created successfully?

   COMMIT WORK;

   SELECT GRANTOR, GRANTEE, OBJECT_SCHEMA, OBJECT_NAME, OBJECT_TYPE
         FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES
         WHERE OBJECT_TYPE = 'CHARACTER SET'
         AND OBJECT_NAME = 'TESTSET';
-- PASS:7066 If GRANTOR = _SYSTEM?
-- PASS:7066 If GRANTEE = CTS1?
-- PASS:7066 If OBJECT_SCHEMA = CTS1?
-- PASS:7066 If OBJECT_NAME = TESTSET?
-- PASS:7066 If OBJECT_TYPE = CHARACTER SET?
   COMMIT WORK;

   DROP CHARACTER SET TESTSET;
-- PASS:7066 If character set dropped successfully?

   COMMIT WORK;

   SELECT COUNT(*) 
         FROM INFORMATION_SCHEMA.CHARACTER_SETS 
         WHERE CHARACTER_SET_SCHEMA = 'CTS1'
         AND CHARACTER_SET_NAME = 'TESTSET';
-- PASS:7066 If COUNT = 0?

   ROLLBACK WORK;
```

(still have to find out how we deal with the roll back / commit nature of the scripts)

**Comment by agershun** [comment]
You can try to compile, but do not spend to much time on this if this would not work. I wrote the test interpreter, may be this approach is easier. We will see.

For transactions: We need to do some things first:
a) rewrite indexes part (the main idea to struture current chaos of realization)
b) write BACKUP/RESTORE commands to store and restore data with indexes and table structures
c) after that we can implement simple ROLLBACK as a backup/restore to the memory. 

It is definitly slow, but can be optimized, for example we can store date only ihe table was touched.

**Comment by mathiasrw** [comment]
I am not sure the backup/restore is high priority at the moment. What do you think?

**Comment by agershun** [comment]
I think we will decide after solve the indexes mess

**Comment by mathiasrw** [comment]
I have a feeling the ROLLBACK feature should be part of the long list of things we could do after we zapped all the bugs :)

**Comment by agershun** [comment]
When we have restoreDatabase() then we will have ROLLBACK.

2016-01-13 12:58 GMT+03:00 Mathias Rangel Wulff <notifications@github.com>:

**Comment by mathiasrw** [comment]
Closed as its put on on hold on The Long List - only to be reopend when its time has come.

**Comment by mathiasrw** [comment]
Closed as its put on on hold on The Long List - only to be reopend when its time has come.
