### ISSUE TITLE
Create TypeScript header file

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#217]

**Comment by agershun** [comment]
Done. See it here: https://github.com/agershun/alasql/blob/develop/dist/alasql.d.ts

One more thing to do: how to add it into the repository https://github.com/borisyankov/DefinitelyTyped

**Comment by agershun** [comment]
Just added pull request to [DefinitelyTypes](https://github.com/borisyankov/DefinitelyTyped/pull/4559)

**Comment by agershun** [comment]
The first version of TypeScript header did not passed DT tests. This is the answer from there:

**Check list**
1.  is collect naming convention?
https://www.npmjs.com/package/alasql
http://bower.io/search/?q=alasql
others?
2.  has a test file? (alasql/alasql-tests.ts or others)
3.  pass the Travic-CI test?

and check this document. http://definitelytyped.org/guides/best-practices.html#ghost-modules.

**BTW** The Bower issue should be fixed... https://github.com/agershun/alasql/issues/271

**Comment by mathiasrw** [comment]
Where did you get this check list from?

1) I dont understand
2) it now initiates test with `npm test`
3) Its now integrated with travis-ci

**Comment by kaktus40** [comment]
Hello,
[ line 59 from alasql.d.ts](https://github.com/agershun/alasql/blob/develop/dist/alasql.d.ts#L59) should be
```
promise(sql:any,params?:any):Thenable<any>;
```
instead of 
```
promise(sql:any,params?:any):Thenable;
```
else I have the following error when I work with typescript:
```
node_modules/alasql/dist/alasql.d.ts(59,31): error TS2314: Generic type 'Thenable<T>' requires 1 type argument(s).
```
Also for your information,  DefinitelyTyped seems deprecated and you should use typings.
The registrings seems easier:
https://github.com/typings/registry
https://github.com/typings/typings/issues/322
https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

Thanks for your great library!!

**Comment by kaktus40** [comment]
I rearrange your definition file:
```

interface IAlaSQLCallback {
    (data?: any, err?: Error): void;
}

interface IAlaSQLOptions {
    errorlog: boolean;
    valueof: boolean;
    dropifnotexists: boolean; // drop database in any case
    datetimeformat: string; // how to handle DATE and DATETIME types
    casesensitive: boolean; // table and column names are case sensitive and converted to lower-case
    logtarget: string; // target for log. Values: 'console', 'output', 'id' of html tag
    logprompt: boolean; // print SQL at log
    modifier: any; // values: RECORDSET, VALUE, ROW, COLUMN, MATRIX, TEXTSTRING, INDEX
    columnlookup: number; // how many rows to lookup to define columns
    autovertex: boolean; // create vertex if not found
    usedbo: boolean; // use dbo as current database (for partial T-SQL comaptibility)
    autocommit: boolean; // the AUTOCOMMIT ON | OFF
    cache: boolean; // use cache
    nocount: boolean; // for SET NOCOUNT OFF
    nan: boolean; // check for NaN and convert it to undefined
    angularjs: boolean;
    tsql: boolean;
    mysql: boolean;
    postgres: boolean;
    oracle: boolean;
    sqlite: boolean;
    orientdb: boolean;
}

// compiled Statement
interface IAlaSQLStatement {
    (params?: any, cb?: IAlaSQLCallback, scope?: any): any;
}

// abstract Syntax Tree
interface IAlaSQLAST {
    compile(databaseid: string): IAlaSQLStatement;
}

// https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/es6-promise/es6-promise.d.ts
interface IThenable<T> {
    then<U>(onFulfilled?: (value: T) => U | IThenable<U>, onRejected?: (error: any) => U | IThenable<U>): IThenable<U>;
    then<U>(onFulfilled?: (value: T) => U | IThenable<U>, onRejected?: (error: any) => void): IThenable<U>;
    catch<U>(onRejected?: (error: any) => U | IThenable<U>): IThenable<U>;
}

interface IAlaSQL {
    options: IAlaSQLOptions;
    error: Error;
    (sql: any, params?: any, cb?: IAlaSQLCallback, scope?: any): any;
    parse(sql): IAlaSQLAST;
    promise(sql: any, params?: any): IThenable<any>;
}

declare var alasql: IAlaSQL;
```

**Comment by mathiasrw** [comment]
The `<any>` part has been added. 

Thank you for taking the time to rearrange the definition. What is the idea behind addid Ì`in front of all the interfaces? It is normal to prepend `I` to interface names to indicate its an interface or?

**Comment by kaktus40** [comment]
I use [tslint](https://github.com/palantir/tslint) to check my typescript files. One rule defined by default in tslint is prefix any interface with I but as you could see [here](https://github.com/panuhorsmalahti/typescript-style-guide#naming), it's not followed every where.

**Comment by mathiasrw** [comment]
Hi @kaktus40 

Thank you for your great help. I have updated the files with your rearranged file. 

As the coreteam of ts does not suggest interfaces starting with `I` I have removed the `I` and added a tslint config stating that its should be without `I`

Please pull latest changes and verify that its working out for you - if not let me know and we reopen the issue

**Comment by kaktus40** [comment]
Ok,
from [here](https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html), you should add the attributes
```
"typings": "./dist/alasql.d.ts"
```
into package.json.
With it, the link indicates that typescript should load automatically the typed definition file!

**Comment by mathiasrw** [comment]
Great !

Its added now :)

**Comment by RP4361** [comment]
I downloaded alasql npm package, added reference in my typecsript file as shown below 
`import  alasql = require('../node_modules/alasql/dist/alasql.min.js');`

Now if iam trying to do some pretty normal coding like 
`const testJson = '[{a:1,b:10}, {a:2,b:20}, {a:1,b:30}]';
const res = alasql('SELECT a, SUM(b) AS b FROM ? GROUP BY a',[testJson]);`

I get an error
TS2349: Cannot invoke an expression whose type lacks a call signature. Type '{ [x: string
]: any; Promise: { (e: any): void; all: (e: any) => any; race: (e: any) => any; resol...' has
 no compatible call signatures.

**Comment by mathiasrw** [comment]
@RP4361 
Please make a new issue with your question and add a link to this issues if its related
