### ISSUE TITLE
Link to `alasql.min.js` in README.md points to 404

### ISSUE THREAD

**Issue by Cjkjvfnby** [agershun/alasql#222]
> AlaSQL is easy to use! Just add [alasql.min.js](alasql.min.js) file to your project and call

**Comment by agershun** [comment]
:+1: Thank you! Relinked to [alasql.min.js](https://cdn.rawgit.com/agershun/alasql/master/dist/alasql.min.js)

**Comment by mathiasrw** [comment]
The idea of rawgit is awesome - but they state that 

>    Requests to cdn.rawgit.com are routed through MaxCDN's super fast content delivery network, and are cached permanently the first time they're loaded. This results in the best performance and reduces load on RawGit and on GitHub, but it means that reloading won't fetch new changes from GitHub.

So basically the link to ```https://cdn.rawgit.com/agershun/alasql/master/dist/alasql.min.js``` will always provide the same version of the script - also after the master branch is updated. 

A solution would be to put the version into the name of the file.

**Comment by agershun** [comment]
... it is bad... I do not want to use their test option in rawgit, because it gives CORS error sometime (especially in jsFiddle)... Probably, we need to use other CDN server

**Comment by mathiasrw** [comment]
Examples in readme and wiki now point to CDN
