### ISSUE TITLE
Possible to create multiple sheets in an xlsx workbook

### ISSUE THREAD

**Issue by DefinitelyCarter** [agershun/alasql#226]
Hi is it possible to create multiple worksheets into a workbook?  I tried a few things but was only able to get one sheet created.

**Comment by agershun** [comment]
Technically it is possible, and I can modify the export function. May I ask you to propose any syntax for this function, so we can program it today. Thank you!

Отправлено с iPhone

**Comment by DefinitelyCarter** [comment]
Thanks for reaching back.

This is what I'm using to prepare a single sheet of data.
```javascript
var data = [];
alasql('SELECT * INTO XLSX ("mydata.xlsx", { headers:true }) FROM ?', data);
```

Would it be okay to do something like below.
1. have an array of options (for each sheet)
2. an array of data (for each sheet)
```javascript
var bookData = [
     [] // data for sheet 1
     [] // data for sheet 2
];
alasql('SELECT * INTO XLSX ("mydata.xlsx", [ { sheetid: "Sheet 1", headers: true }, { sheetid: "Sheet 2" headers: true } ]) FROM ?', bookData);
```

Thanks!

**Comment by agershun** [comment]
Done. Please test it from ```develop``` branch. It will be released in version 0.1.8 soon.
```js
    var data1 = [{a:1,b:10},{a:2,b:20}];
    var data2 = [{a:100,b:10},{a:200,b:20}];
    var opts = [{sheetid:'One',header:true},{sheetid:'Two',header:false}];
    var res = alasql('SELECT INTO XLSX("restest344b.xlsx",?) FROM ?',[opts,[data1,data2]],
      function(){
        done();
      });
```
Please try this example [in jsFiddle](http://jsfiddle.net/ry8fq0dL/)

Please note, that by some reason I use this syntax ```SELECT FROM``` without star inside. This syntax is equvalent to ```SELECT COLUMN _ FROM```, that different from ```SELECT * FROM```, because second syntax creates new objects on the base of data. I will explain this later in documentation (sorry for delay with it).

May I ask you to test this functionality and give a feedback. Thank you!

I will also modify 'colored' version of parser on the similar way (XLSXML)

**Comment by DefinitelyCarter** [comment]
Thank you @agershun!  It works great.  I appreciate your help with this.

**Comment by forcewill** [comment]
And how about multiple spreadsheets but with different queries ? (i.e diferent SELECT expressions for each spreadsheet)

**Comment by agershun** [comment]
May I ask you to create new issue for this question?

**Comment by forcewill** [comment]
Done closing this one

**Comment by prem1014** [comment]
Hi Sir,

I want to save some data to an existing excel sheet.Could you please help me to achieve that.

Thanks
Prem Prakash

**Comment by philibin** [comment]
I have a javascript array that I am using to make a spreadsheet. I am using the following code:

[begin code]
var opts = {
  headers:true, 
	sheetid:"New"
};

window.exportExcel =     function exportExcel() {
alasql("SELECT [1] AS [Bill Account], \
               [2] AS [Case Number], \
							 [4] AS [Cust Name], \
							 [5] AS [Address] \
        INTO XLSX('testing.xlsx',?) FROM ? WHERE [38] = 'False'",[opts,masterArray]);										
    }
[end code]
What I would  like to do is, using the same array write to a spreadsheet with three tabs.

lets say the three tabs should be "New", "Previously Sent", "Paid" and I want to use the same Array to do this. The way I identify them is by using the same code above but changing the WHERE CLAUSE.

For Example: in the "New" sheet: FROM ? WHERE [38] = 'False'
 In the "Previously Sent" sheet: FROM ? WHERE [38] = 'True' AND [41] = 'False'
 and in the "Paid" sheet: FROM ? WHERE [38] = 'True' AND [41] = 'True'

I did see your post above that lets you use two arrays as datasets, and I could split the arrays I guess (but this would kill the memory in big tables)... and it would only do two sheets (not the three I need).

So, in my perfect world... I'd need to be able to write three "queries" and place each in a separate sheet in the same workbook. Could this be possible?

Thanks,
-Bill

ps - masterArray is a multidimensional javascript array with 45 columns and ~2500 rows.

**Comment by mathiasrw** [comment]
@philibin 

have a look at http://jsfiddle.net/ry8fq0dL/55/

fill data1 and data2 (and add data3) with the response from a alasql('select ...') with your criterias...

**Comment by sumitrap** [comment]
Hi @agershun 
Regarding the multiple worksheets in one Excel file, what is the limit on the number of records **data1** and **data2** take?

Refer: alasql('SELECT INTO XLSX("restest344b.xlsx",?) FROM ?',[opts,[data1,data2]])

**Comment by agershun** [comment]
We did not test it yet Logically there is no knowing limits, but memory. I think that about 50000 records should be ok.

**Comment by hoangnguyen115** [comment]
Hi guys,

How can I write special character (like &, _ \ ) to sheet name (sheetid)? I tried escape character (\) but it doesn't work.
Thanks for your help.

**Comment by mathiasrw** [comment]
Please make this as a new issue

**Comment by hoangnguyen115** [comment]
Hi guys,

I found the answer myself after looking at the excel standard. sheetid is coded in xml so I need to escape in xml format. It works now: http://jsfiddle.net/ry8fq0dL/125/

**Comment by mathiasrw** [comment]
Awesome! I have updated https://github.com/agershun/alasql/wiki/XLSXML
