### ISSUE TITLE
Modify XLSXML() export function to allow multiple spreadsheets

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#228]
Like https://github.com/agershun/alasql/issues/226 for XLSX()

**Comment by agershun** [comment]
Add Zip library to save data into XLSX format.

**Comment by mathiasrw** [comment]
> Add Zip library to save data into XLSX format.

How does this relate to multiple spreadsheets for XLSXML ?

**Comment by wei-nete** [comment]
Does it work now? Thanks.

**Comment by mathiasrw** [comment]
Nope - not yet...

**Comment by wei-nete** [comment]
Thanks for the reply.
Right now, I am facing a problem using Alasql. 
1. I need to export excel workbook with multiple sheets.
2. I need to set up column width for the columns in these sheets.

XLSXML() will satisfy number 2, but not number 1. XLSX() will work for number 1 but not number 2.
Does anyone know how to use alasql to achieve both targets? Or there is any other package I can use.
Thanks.

**Comment by mathiasrw** [comment]
aw... I see. 

I dont use the excel part of the lib so cant help you there...

**Comment by cheng-luo** [comment]
Also need XLSXML() to export workbook with multiple sheets. Is there any update on this?

**Comment by vlish** [comment]
I also need XLSXML() to export workbook with multiple sheets. Anybody here?

**Comment by mathiasrw** [comment]
It would be awesome to have. 

I will put this on the list of things to be implemented.

**Comment by nikzsaz** [comment]
Hii,
Is there any progress on this issue?
I have tried this but still.. this one is not working.  Can any one suggest me how can achieve this . 
`var data1 = [{a:1,b:10},{a:2,b:20}];
    var data2 = [{a:100,b:10},{a:200,b:20}];
    var opts = [{sheetid:'Good',header:true},{sheetid:'Two',header:false}];
    var res = alasql('SELECT INTO XLSXML("MyAwesomeData.xls",?) FROM ?',[opts,[data1,data2]]);`

**Comment by mathiasrw** [comment]
No progress...
