### ISSUE TITLE
Version written in min version

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#232]
It can be hard to figure out what you are using if its the min version of a js script. I suggest we add a the following as the first line

    /* AlaSQL v0.1.4 */

Just like jQuery does it http://code.jquery.com/jquery-2.1.4.min.js

**Comment by agershun** [comment]
Ok. I will do it. 
BTW you can get the version from  ```alasql.version``` variable

Probably, we also can generate individual Build Number for each gulp run.

**Comment by mathiasrw** [comment]
its done...
