### ISSUE TITLE
Performance, reliability, stress, and other tests

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#233]
Someone asked on StackOverflow a question to compare current JavaScript libraries ([link](http://stackoverflow.com/questions/30448004/how-does-lovefield-stand-out-from-other-in-browser-javascript-databases)). This question was put on hold, because it was opinion-based. But, probably, we need more reliable base to test AlaSQL and use it for target and priorities setting. 

Are there any more or less certified SQL tests which can be applied for JavaScript SQL and SQL-like databases? For example, "there are two tables and lets join them". Probably, these tests should nort be so advanced like SQLLOGICTEST or NIST SQL test, because we need to measure most typical operations (sorting, grouping, joining, insets/delete/updating).

These tests also can be used to measure database backends.

Are there any?

**Comment by mathiasrw** [comment]
Will look for it...

**Comment by mathiasrw** [comment]
I only found SQLlogic test from sqlite. 

Lets close and reopen if we find something else...
