### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#234]
Just letting you know - MSSQL is gonna implement JSON support.

http://blogs.msdn.com/b/jocapc/archive/2015/05/16/json-support-in-sql-server-2016.aspx

We might want to copy the syntax - or be aware of this when we implement MSSQL flavourd AlaSQL

**Comment by agershun** [comment]
Agree. Plus there are similar implementations in Postgres and Oracle. To be discovered.

**Comment by mathiasrw** [comment]
Postgres JSON functions and datatype:
- http://www.postgresql.org/docs/9.3/static/functions-json.html
- http://www.postgresql.org/docs/9.4/static/datatype-json.html

**Comment by mathiasrw** [comment]
check out this - it's important for our MySQL compliant flavour

http://mysqlserverteam.com/json-labs-release-native-json-data-type-and-binary-format/

Some more details on the mysql JSON date

http://mysqlserverteam.com/json-labs-release-json-functions-part-1-manipulation-json-data/

----

Agershun:

As far as I understand it is not so hard to realize MySQL and Prostres JSON functions and casting procedures. It wlll take day pr two. BTW IMHO original AlaSQL's JSON is better than MySQL/Postgres/SQL Server realizations. Ok, I will create issue and some code :)

**Comment by mathiasrw** [comment]
I put it on the long list so we can reopen when its time has come...
