### ISSUE TITLE
Change README.md 

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#237]
1. Restructure text from README and move some unneeded parts to Wiki in structured way. 
2. Change text on ```alasq;.org```

**Comment by mathiasrw** [comment]
I cant figure out the content of https://github.com/agershun/alasql/blob/master/TODO.md

Is this obsolite now that we have the trello? It feels like we are using more as a poersonal memo on what could be the next thing to implement. Would we link to the trello instead of the todo.md?

**Comment by agershun** [comment]
Yes. I will remove this file. Done.

**Comment by mathiasrw** [comment]
Bam !

**Comment by mathiasrw** [comment]
Would it be possible for you to write this example

````
    var data = {a:{a:{a:{a:{b:10}}}},b:20};
    var res = alasql('SEARCH a b FROM ?',[data]);
    var res = alasql('SEARCH (a)+ b FROM ?',[data]);
    var res = alasql('SEARCH (a a)+ b FROM ?',[data]);
    var res = alasql('SEARCH (a a a)+ b FROM ?',[data]);
    var res = alasql('SEARCH (/)+ b FROM ?',[data]);
    var res = alasql('SEARCH /+b FROM ?',[data]);
    var res = alasql('SEARCH a* b FROM ?',[data]);
    var res = alasql('SEARCH a+ b FROM ?',[data]);
    var res = alasql('SEARCH a? b WHERE(b>20) FROM ?',[data]);

```

with some data that makes more sense? I feel its not intuitive enough. I would like to make an example but I dont think I got it quite yet...

**Comment by mathiasrw** [comment]
Is https://github.com/agershun/alasql/wiki/SQL%20keywords truely updated?

**Comment by agershun** [comment]
It is actual as far as I know. The only trick here, that this is the SQL-99 keywords, but the list of AlaSQL keywords is diffrerent. This is it:
```
ABSOLUTE                                 		
ACTION                                      	
ADD                                      		
AGGR                                     		
ALL                                      		
ALTER                                    		
AND											
ANTI											
ANY											
APPLY											
ARRAY                                     	
AS                                      		
ASSERT                                      	
ASC                                      		
ATTACH                                      	
AUTOINCREMENT                               
AUTO_INCREMENT                               
AVG                                      		
BEGIN											
BETWEEN										
BREAK											
NOT BETWEEN									
NOT LIKE									    
BY											
CASE											
CAST											
CHECK											
CLASS											
CLOSE											
COLLATE										
COLUMN											
COLUMNS 										
COMMIT										
CONSTRAINT									
CONTENT										
CONTINUE										
CONVERT										
CORRESPONDING									
COUNT											
CREATE										
CROSS											
CUBE											
CURRENT_TIMESTAMP								
CURSOR										
DATABASE									
DECLARE                                       
DEFAULT                                       
DELETE                                        
DELETED                                       
DESC                                          
DETACH										
DISTINCT                                      
DOUBLE PRECISION								
DROP											
ECHO											
EDGE											
END											
ENUM											
ELSE											
EXCEPT										
EXISTS										
EXPLAIN                                       
FALSE											
FETCH											
FIRST											
FOREIGN										
FROM                                          
GO                                      		
GRAPH                                      	
GROUP                                      	
GROUPING                                     	
HAVING                                        
HELP											
IF											
IDENTITY										
IS											
IN											
INDEX											
INNER                                         
INSERT                                        
INSERTED                                      
INTERSECT                                     
INTO                                         	
JOIN                                         	
KEY											
LAST											
LET											
LEFT											
LIKE											
LIMIT											
LOOP											
MATCHED										
MATRIX											
MAX											
MERGE											
MIN											
MINUS											
MODIFY										
NATURAL										
NEXT											
NEW											
NOCASE										
NO											
NOT											
NULL											
OFF											
ON											
ONLY											
OFFSET										
OPEN											
OPTION										
OR											
ORDER	                                      	
OUTER											
OVER											
PATH                                        	
PARTITION										
PERCENT                                       
PLAN                                        	
PRIMARY										
PRINT                                        	
PRIOR                                        	
QUERY                                        	
READ		                                    
RECORDSET                                     
REDUCE                                        
REFERENCES                                    
RELATIVE                                      
REMOVE                                        
RENAME                                        
REQUIRE                                       
RESTORE                                       
RETURN                                       	
RETURNS                                       
RIGHT                                        	
ROLLBACK										
ROLLUP										
ROW											
SCHEMA(S)?                                      
SEARCH                                        
SELECT                                        
SEMI                                        	
SET 	                                       	
SETS                                        	
SHOW                                        	
SOME                                        	
SOURCE										
STRATEGY										
STORE                                        	
SUM											
TABLE											
TABLES										
TARGET										
TEMP											
TEMPORARY										
TEXTSTRING									
THEN											
TIMEOUT										
TO											
TOP											
TRAN											
TRANSACTION									
TRUE						  					
TRUNCATE					  					
UNION                                         
UNIQUE                                        
UPDATE                                        
USE											
USING                                         
VALUE                                      	
VERTEX										
VIEW											
WHEN                                          
WHERE                                         
WHILE                                         
WITH                                          
WORK         
```

**Comment by agershun** [comment]
Regarding example
Would it be possible for you to write this example
```
    var data = {a:{a:{a:{a:{b:10}}}},b:20};
    var res = alasql('SEARCH a b FROM ?',[data]);
    var res = alasql('SEARCH (a)+ b FROM ?',[data]);
    var res = alasql('SEARCH (a a)+ b FROM ?',[data]);
    var res = alasql('SEARCH (a a a)+ b FROM ?',[data]);
    var res = alasql('SEARCH (/)+ b FROM ?',[data]);
    var res = alasql('SEARCH /+b FROM ?',[data]);
    var res = alasql('SEARCH a* b FROM ?',[data]);
    var res = alasql('SEARCH a+ b FROM ?',[data]);
    var res = alasql('SEARCH a? b WHERE(b>20) FROM ?',[data]);
```
I wi;l rewrite with some more interesting data.

var catalog = { 
    Europe: {
      fruits: [
        {fruit:'Apple'},
        {fruit:'Peach'},          
      ]
    },
    Asia: {
        fruit:'Pineapple'          
    },
    Africa: {
        fruit:'Banana'          
    }
  };

     var res = alasql('SEARCH Europe FROM ?',[catalog]);
    assert.deepEqual(res, [{fruits: [
        {fruit:'Apple'},
        {fruit:'Peach'},          
      ]}]);
    done();    
  });
    var res = alasql('SEARCH /fruits/ FROM ?',[catalog]);
    assert.deepEqual(res, [{fruit:'Apple'}, {fruit:'Peach'}]);

    var res = alasql('SEARCH /fruits/fruit FROM ?',[catalog]);
    assert.deepEqual(res, ['Apple','Peach']);

    var res = alasql('SEARCH /fruits/WHERE(fruit="Apple") FROM ?',[catalog]);
    assert.deepEqual(res, [{fruit:'Apple'}]);

    var res = alasql('SEARCH ///WHERE(fruit="Apple") FROM ?',[catalog]);
    assert.deepEqual(res, [{fruit:'Apple'}]);
```

**Comment by mathiasrw** [comment]
:+1:

**Comment by mathiasrw** [comment]
lIs this information still valid?

----

> Known Bugs and Limitations
> ORDER BY clause on three or more UNIONS ( See example in AlaSQL console ) 
> Limited functionality for transactions (supports only for localStorage) - Sorry, transactions are limited, because AlaSQL started to use more complex approach for PRIMARY KEYS / FOREIGN KEYS. Transactions will be fully turned on again in one of the future version.

**Comment by agershun** [comment]
1. Meteor, SQL and other databases by https://www.compose.io/articles/author/dj/
https://www.compose.io/articles/meteor-sql-and-other-databases/

2/. I think we can move PEOPLE.md to Wiki. See [What people say about AlaSQL] (https://github.com/agershun/alasql/wiki/People) article

3. I created a page with lost of all [AlaSQL keywords](AlaSQL Keywords)

**Comment by mathiasrw** [comment]
interesting...

Was trying to improve on your example with

````
var catalog = { 
				Europe: {
					fruits: [
						{name:'Apple'},
						{name:'Peach'}          
					]
				},
				Asia: {name:'Pineapple'},
				Africa: {name:'Banana'}
			};

var res = alasql('SEARCH Europe FROM ?',[catalog]);
// res =  
// [{fruits: [
// {name:'Apple'},
// {name:'Peach'},          
// ]}]

var res = alasql('SEARCH /fruits/ FROM ?',[catalog]);
// returns [{name:'Apple'}, {name:'Peach'}]

var res = alasql('SEARCH /fruits/name FROM ?',[catalog]);
// returns ['Apple','Peach']

var res = alasql('SEARCH /fruits/WHERE(name="Apple") FROM ?',[catalog]);
// returns [{name:'Apple'}]

var res = alasql('SEARCH ///WHERE(name="Apple") FROM ?',[catalog]);
// returns [{name:'Apple'}]

// Pleae note that the "FROM ?" is to run the query on the data in the second parameter ```[catalog]``` - it could just as well be a normal ```FROM tableXYZ```
````

but realised we dont use the data in asia nor africa. 

Im not able to run alasql right here, but will come with a suggestion when I get back to my computer

**Comment by agershun** [comment]
1. I created a page with all AlaSQL keywords. Hope, this will help us to fill all keywords with documentation and examples.

https://github.com/agershun/alasql/wiki/AlaSQL-Keywords

2. I moved PEOPLE.md to the special page

https://github.com/agershun/alasql/wiki/People

**Comment by mathiasrw** [comment]
Good idea. 

Do you have the original drawing of http://www.slideshare.net/AndreyGershun/sql-and-nosql-in-alasql slide 2? its really great !

**Comment by agershun** [comment]
The picture: https://www.dropbox.com/s/fkpy09au70xt1qp/nosql.png?dl=0

:)

**Comment by agershun** [comment]
Can you write a post about AlaSQL in Danish to add to the list? :)

**Comment by mathiasrw** [comment]
Sure ! 

Thinking about where it would be good to post. Hmmm. Maybe just medium.com

**Comment by agershun** [comment]
AlaSQL ♥ README.md :)

**Comment by agershun** [comment]
I like new version of README.md! I will merge new version of README.md to master branch tonight with release 0.1.8. 

**Idea:** To do not interfere we can create special README page on Wiki with editable copy of README.md, and I will simply copy it every time before release (and also we will use it for alasql.org/index.html and README.md for Meteor package). What do you think? I do not want to merge README.md every time (it is more complicated the code merge  and we can keep a single editable master-copy of it).

**Comment by mathiasrw** [comment]
Glad you like it :)

Hmm - I dont quite get why its hard to merge - as it is not changed in master the merge should be automatic. Are you useing the git-flow features of source tree? Are you doing a log of things by hand when you place it into master? 

But its no problem. If you prefer we have a "readme" in wiki lets keep it there. I have only started restructuring the information. When the restructuring is done I will look into if we need new / better material and if some of the examples should be placed in wiki (balance detail with overview)

**Comment by mathiasrw** [comment]
Have made a copy at https://github.com/agershun/alasql/wiki/readme

- The wiki will now be the master I focus on. 
- Only the wiki version will be updated with changes. 
- On new releases the wiki will be copied into README.md of development and merged into master (or copied into both...)

**Comment by agershun** [comment]
Yes, thank you! I am still feel me a newby with git merge procedures :) 

BTW, if you find a time, can you look at the AlaSQL [jsDoc documentation](http://alasql.org/api/). I started to put JsDoc tags into the code, but it still requires more professional attention. If you have any experience with jsDoc, can you share ideas how to improve this part of documentation.

**Comment by mathiasrw** [comment]
I never met jsDoc - will take a look at it. 

Are you using git "raw" or are you using source tree?

**Comment by agershun** [comment]
Currently I use git from the command line + git flow for releases. I had some problems earlier with combination Source Tree + Dropbox + Mac (CRLF) + Windows (CR), so I decided temporary do it by hand, while I studying git. 

Of course, I know how to merge files by hand and in SourceTree, but still can not rely on it :) Plus, I want to avoid to merge text file (this is more difficult than the code)

**Comment by mathiasrw** [comment]
Awwwhhh - I had the exact same setup - and really fucked it all up once. 

It can be handled - by removing all ```\r``` from the code and asking git not to convert when one checkes out. 

But basically what I learnt was that its a bad idea to have git and dropbox mixed. Mainly if its big files (not really here) where you risk that dropbox will overwrite a file after you comitted changes offline. Well - its a mess - so I just sync over github now (usint source tree) and make sure to do changes in a feature branch that I always make sure to push when I leave the computer so I can pull changes on the other one...

**Comment by mathiasrw** [comment]
Nice with all the keywords in the wiki. Next thing will be to have examples of the specific use on all of them. Lets have that in mind for now and focus on getting them all in for now :)

**Comment by agershun** [comment]
YES! I will finish with all keywords articles today, and then we can walk through:
a) closed issues (there about 100 of them). Most part of them have jsFiddle examples.
b) test examples (about 300)

**Comment by agershun** [comment]
Git: I solved this problem and do not commit changes with my office (Windows) computer. That is why I always write 'I will do it tonight' instead 'today' :)

**Comment by mathiasrw** [comment]
Regarding the tagline and description:

> AlaSQL.js - JavaScript SQL database library for relational and graph data manipulation with support of localStorage, IndexedDB, and Excel

where is the noSQL part of this? I have a feeling the main gain it running traditional SQL agains schemaless data - would you agree?

But we also have the graph parts to be proud of. 

I also REALLY like that we have a vision about being vendor complient with different flavours - meaning that the migration from exsisting system go javascript setup is more easy...

Can you try to nail the fop 5 trais of AlaSQL that makes it lovable?

**Comment by mathiasrw** [comment]
Please also put some words to why there needs to be a second `@` in 

    @{yearid:@[2014,2015]}

**Comment by agershun** [comment]
**@ question:**
AlaSQL uses ```[``` without ```@``` for column names and other literals. For JavaScript arrays we have to use ```@[```.

BTW: Now we do not need to put ```@``` before ````{```. Simply: ```{yearid:@[2014,2015]}```

**Comment by mathiasrw** [comment]
hmm. OK. 

Can you write a tiny example that uses both notations in one query?

**Comment by agershun** [comment]
```sql
     SET @a=@[{a:1,b:10},{a:2,b:10}];
     SELECT SUM(a*b) FROM @a
```

**Comment by agershun** [comment]
5 phrases... 
* Pure JavaScript, can be easily extended and integrated
* Fast and optimized
* Has all necessary import and export filters for instant ETL
* Supports JSON
* SQL compatible

**Comment by agershun** [comment]
I just finished to create pages for all AlaSQL keywords. So we can fill all them with examples from tests and closed issues.

**Comment by mathiasrw** [comment]
:+1:

**Comment by agershun** [comment]
@mathiasrw Something wrong with ```AlaSQL ♥ d3.js see  why'`` links. Can you check?

**Comment by mathiasrw** [comment]
I cant replicate a problem on readme.md or wiki. 

Are you testing it at the npm page? 

They might not have the same abillity to auto make anchors. If not we must make hard links to github version.

**Comment by agershun** [comment]
Npm readme has similar problems

Отправлено с iPhone

**Comment by mathiasrw** [comment]
Ok. I will change it so they point to absolute GitHub path

**Comment by agershun** [comment]
:+1: Now README is the most important part of the AlaSQL

**Comment by mathiasrw** [comment]
Hah - im not sure about that. 

The links are working in wiki version now.

**Comment by agershun** [comment]
@mathiasrw Let's remove the SQL/NoSQL picture... It is not so positive... ![noSQL](http://i.imgur.com/0sVHEN6.png)

**Comment by mathiasrw** [comment]
its done!

**Comment by mathiasrw** [comment]
(but its still pretty fun...)

**Comment by mathiasrw** [comment]
Unrelated question: Is the alasql-codex repo ment as the source of alasql.org?

**Comment by agershun** [comment]
Yes. I think that we can develop codex as independt projects and place it at alasql.org/codex as a subpart. 

Now, we have many mosaic parts for a now:
*  alasql itself and its plugins (github.com/agershun/alasql)
*  alasql wiki (github.com/agershun/alasql/wiki)
*  alasql-org (at alasql.org)
*  alasql-codex (at alasql.org/codex) - I have very interesting ideas how to combine many tutorials and manual into one environment

And:
* alasql-manual after some investigation will be merged into alasql-wiki after we have more than 10 pages in it.

I still have some ideas about ```alacon``` as a separate command-line utility for ETL operations, but this is not urgent.

**Comment by mathiasrw** [comment]
:+1:

**Comment by agershun** [comment]
I feel. we have a problem with README.md: the ratio of stars to the number visitors was decreased in some times for a last two weeks. We need to finish with it. Is the wiki version is the last edition?

**Comment by mathiasrw** [comment]
The wiki is always the latest version. 

I have not focused on getting into the details with it. Ill hvae the readme as focus the next days. 

Where do you see visitors?

**Comment by agershun** [comment]
Traffic page: https://github.com/agershun/alasql/graphs/traffic It should be available to you (if not - write me please). 

#### Some ideas on README structure

I think we can put some simple examples on the top of the page and move news somewhere else. I will try to find best practices on this to compare with our page.

The structure can be like this:
* Header
* Buttons, Version info - 1 sentence
* What is AlaSQL 1-2 sentences
* Why AlaSQL is great - 3 points
* Very simple example 4-5 strings
* Performance and compatibility test results
* How to install
* Some simple examples and faetures (compilation, other libraries)
* Complex features
* Additional information (tests, etc.)
* References
 
I think we need to reduce README to 2-3 pages and include more references to Wiki.

**Comment by mathiasrw** [comment]
I really like this structure. I will implement this the next days!

**Comment by agershun** [comment]
:+1:

**Comment by mathiasrw** [comment]
What is the point of the * in https://github.com/agershun/alasql/wiki/SQL-99 ?

**Comment by agershun** [comment]
We can remove it

Отправлено с iPhone

**Comment by mathiasrw** [comment]
Note to self: use https://asciinema.org/ to show example of alacon

**Comment by agershun** [comment]
:+1:
