### ISSUE TITLE
Code quality 

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#239]
I have a feeling that we are at a stage where it would suit the project to focus on having high quality code in the main src of the library (im not talking about test and other 2nd level elements yet)

I suggest that we take a look at http://jshint.com/

Pasting the content from alasel.js it gives a lot of small things that could be changed. Mainly a lot of missing semicolon. 

I suggest we focus on getting rid of the issues so we can make sure we speed up the process for people using the none-min version of the library...

the jshint can also be used locally via npm - check out http://jshint.com/docs/

**Comment by agershun** [comment]
:+1:  Will learn it. There are also couple other tools, I will talk to JavaScript people, what they recomend us.

**Comment by mathiasrw** [comment]
Bithound also gives us some inputs on what we can change. 

Forexample 

https://www.bithound.io/github/agershun/alasql/blob/92ae293b40419e3bab0fe18893fc4873e0b72ade/src/17alasql.js

shows some minor semicolon elements. would you like me to help fix the super simple ones or do you prefer to fix them?
