### ISSUE TITLE
bower install fails with 0.1.7

### ISSUE THREAD

**Issue by jjair81** [agershun/alasql#242]
Hi, I'm trying to install 0.1.7 via bower into my project, however i'm running into an issue with es6-promise:

`bower alasql#0.1.7              cached git://github.com/agershun/alasql.git#0.1.7
bower alasql#0.1.7            validate 0.1.7 against git://github.com/agershun/alasql.git#0.1.7
bower es6-promise#2.1.1     not-cached git://github.com/components/es6-promise.git#2.1.1
bower es6-promise#2.1.1        resolve git://github.com/components/es6-promise.git#2.1.1
bower es6-promise#2.1.1   ENORESTARGET No tag found that was able to satisfy 2.1.1
Additional error details:
Available versions: 2.1.0, 2.0.1, 2.0.0, 1.0.0, 0.1.1, 0.1.0`

/github.com/components/es6-promise.git indeed only goes up to version 2.1.0, however github.com/jakearchibald/es6-promise goes to version 2.1.1.

Is there a way to specify which es6-promise repository is required in the bower.json file?

**Comment by agershun** [comment]
Sorry for that, I will fix it for the next version 0.1.8 tomorrow... Thank you!

**Comment by agershun** [comment]
I downgraded version to es6-promise to 2.1.0.

**Comment by agershun** [comment]
Hope this problem is solved. Please let us know in case if the problem is still exists.
