### ISSUE TITLE
How to release VALUE from the list of keyword?

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#246]
Currently AlaSQL uses ```VALUE``` keyword as SELECT modificator (see https://github.com/agershun/alasql/wiki/Value). But many people use 'value' as frequent names of columns. 

We have two options:
* Leave as it is (so people have to use square bracket for ```[value]```
* Change ```VALUE``` keyword to something else ?
* Play with parser and find a way to keep modifier as it is.

What is the best option?

**Comment by mathiasrw** [comment]
What other keywords do we have as select modificators?

To me it makes more sense that the implementation specific elements (like us modifying the select) would be the ones with a special syntax.

I must admit that to me it makes more sense if the SELECT modifyer would be placed before select - so it was a 'VALUE SELECT' or a 'ROW SELECT' on the following data. That would also make it easy to append to exsisting queries `console.log(alasql('value '+sql))`

How do you see it?

**Comment by agershun** [comment]
:+1: I like this solution!!! I will look, how to change parser to handle it (this could be not easy...). 

I got it: we just create new lexems:
```
%lex
VALUE\sSELECT        yytext = 'VALUE'; return 'SELECT'
/lex
Select
    : SELECT ...
        { if($1 == 'VALUE') modifier = 'VALUE'; ... }
     ;
```
Cool!

From the other hand it will require to change all previous examples in jsFiddle... :) Sorry, guys, version 0.1.8 will be without VALUE keyword and with changed modifier order. 

We need to warn about it.

BTW: AlaSQL now has many unused keywords, we need to clean it also.

**Comment by mathiasrw** [comment]
The correct version would be 0.2.0 as it introduces some breaking changes...

**Comment by mathiasrw** [comment]
:100: :+1:

**Comment by agershun** [comment]
Yes, you are right. I open wishlist for version 0.2.0 #250

There are two options:
```sql
    VALUE SELECT...
    MATRIX SELECT...
    ROW SELECT...
    COLUMN SELECT...
    TEXTSTRING SELECT...
```
or use a keyword like 'MODIFY' or 'AS' or similar:
```sql
    AS VALUE SELECT...
    MODIFY VALUE SELECT...
```
?

**Comment by mathiasrw** [comment]
'AS' could work - as its already a SQL word

What about `RETURN VALUE SELECT` ?

Hmmm. Too long

Ok. After thinking a bit - what about "FROM"

    VALUE FROM SELECT...
    MATRIX FROM SELECT...
    ROW FROM SELECT...
    COLUMN FROM SELECT...
    TEXTSTRING FROM SELECT...

**Comment by mathiasrw** [comment]
Some might not like to fiddle with the SQL. 

What about also having a function call for each? so you can 

    alasql.value.exec('SELECT a FROM TABLE')

First implementation could be to let the value.exec prepend "VALUE FROM " to the SQL and call the normal .exec - later we can implement that the flag to return value does not need to be converted to string and then parsed into AST

**Comment by agershun** [comment]
AS is not good... Because it used in CREATE VIEW ... AS...

RETURN we will use for PROCEDURES in future

Still thinking... :)

**Comment by mathiasrw** [comment]
(what about the FROM?)

**Comment by agershun** [comment]
```
    ::VALUE SELECT ... 
```
?

**Comment by mathiasrw** [comment]
Another approach would be to have another keyword for selecting that returns the first value. it could be called `VALUE_SELECT` - then its not the regular `SELECT` but a new keyword

**Comment by mathiasrw** [comment]
VALUE_SELECT name FROM people

Hmmm. Its kind of ugly...

**Comment by mathiasrw** [comment]
Mayby `OF` ?

    VALUE OF SELECT name FROM people
    ROW OF SELECT * FROM people

**Comment by agershun** [comment]
Your first variant is the best:
``
    VALUE SELECT a FROM one;
```

**Comment by agershun** [comment]
```OF```` is good. We can use it as optional word :)
```
VALUE\s+(OF)?\s*SELECT
```

**Comment by mathiasrw** [comment]
So be it.

**Comment by agershun** [comment]
:+1:

**Comment by mathiasrw** [comment]
Are you sure you want to make the `OF` be optional? 

Optional things often create confusion.

**Comment by agershun** [comment]
```
    ROW OF SELECT a FROM b;
    RECORDSET SELECT 1;
    MATRIX OF SELECT @[1,2]
    TEXT SELECT "Mermaid";
```
Looks harmonic.

**Comment by agershun** [comment]
OF version  looks more SQueLish...

**Comment by agershun** [comment]
I added this functionality. Now we have two option:
```sql
    SELECT VALUE ...
    VALUE OF SELECT...
```


We will keep both options in version 0.1.8 and other 0.1.x until version 0.2 where we clean keyword list.

**Comment by mathiasrw** [comment]
Good call !
