### ISSUE TITLE
AlaSQL 0.2.0 wishlist

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#250]
Here is the check-list for version 0.2.0

1. Documentation from all tests and issues moved to wiki
2. Changed SELECT VALUE to VALUE SELECT (or similar. see #246 )
3. SQLTEST page automatically generated
4. NIST SQL page automatically generated

What else...?

**Comment by mathiasrw** [comment]
We got most of these. 

* Documentation from all tests and issues have not been moved to wiki
* NIST SQL not generated automatically 

Will create 2 new issues and close this one.
