### ISSUE TITLE
CDN for alasql.js

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#251]
AlaSQL sould be on a CDN where we can be sure it always has the last version. Rawgit is easy bug the URL will change. 

I am looking into getting us into https://cdnjs.com/ where we has to config something for https://github.com/cdnjs/cdnjs - still investigating...

**Comment by mathiasrw** [comment]
I made a pull request to cdnjs with https://github.com/cdnjs/cdnjs/pull/4681

The idea is that alasql will be placed in 

    //cdnjs.cloudflare.com/ajax/libs/jquery/0.1.7/alasql.min.js

When you push a new update to master a new url will be created with version in url as written in package.json

**Comment by agershun** [comment]
Cool!

**Comment by mathiasrw** [comment]
AlaSQL is now on jsDelivr http://www.jsdelivr.com/#!alasql

So - the latest stable version of the script can **always** be included with

    <script src="//cdn.jsdelivr.net/alasql/latest/alasql.min.js"></script>

I will change examples accordingly. We can also link to a specific version:

- http://cdn.jsdelivr.net/alasql/0.1.9/alasql.min.js

or if we just want to link to the latest patch of a version:

- http://cdn.jsdelivr.net/alasql/0.1/alasql.min.js
