### ISSUE TITLE
Do we need to rename $0 to $1 (like in Postgres)

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#253]
See examples in Postgres docs: http://www.postgresql.org/docs/9.2/static/sql-prepare.html
```sql
PREPARE fooplan (int, text, bool, numeric) AS
    INSERT INTO foo VALUES($1, $2, $3, $4);
EXECUTE fooplan(1, 'Hunter Valley', 't', 200.00);
```
The start parameters number with $1, but not $0 (like in AlaSQL).

From another point we keep JavaScript. If you want to start with $1 you can do:
```js
    alasql('SELECT $1',{1:100});
```

**Comment by mathiasrw** [comment]
I beleave that is a good thing. 

Also breaking change - so must be for 0.2.0

**Comment by agershun** [comment]
I still not sure. Let's postpone a little bit. This is not JavaScript way...

Отправлено с iPhone

**Comment by mathiasrw** [comment]
No problem. Let's postpone. 

Bfor when we look at it again: It's not really an array index - but specification to what argument to use. It reminds a bit of how to use regexp in is where first (...) is \1 second is \2 and so on. Another strong argument is the Postgres syntax

Do we use $0, $1 ... in other parts of the syntax?

**Comment by agershun** [comment]
I tried always change 0 to 1 (for example, for string functions). But here... The parameter object can be array, but can be object with named properties... Let"s think...

**Comment by mathiasrw** [comment]
Any new inputs?

**Comment by agershun** [comment]
Let's close it.

**Comment by pke** [comment]
Missed opportunity, imho, to change this early to be compatible with one of the biggest RDMS out there (Postgres).
I manually construct an object from my param array now to support that.

**Comment by mathiasrw** [comment]
I suggest making this as a config option. PRs welcome.

**Comment by pke** [comment]
I'll do just that beginning of next year ;)
