### ISSUE TITLE
$$hashkey field in download and commas within field

### ISSUE THREAD

**Issue by joewired** [agershun/alasql#26]
I get an extra field "$$haskey" in my xlsx download. How can I get rid of it?

Also, cells with strings that have commas in them trigger a new cell.

**Comment by joewired** [comment]
Thank you. I'll give it a try and let you know if I got it working.

**Comment by alex-p-crest** [comment]
Is this example is relevant? http://jsfiddle.net/agershun/efmhcnu8/1/

This example is not working for me in Safari.

I am geeting below error

'[object BlobConstructor]' is not a constructor (evaluating 'new Blob([t],{type:"text/plain;charset=utf-8"})')
https://cdn.jsdelivr.net/alasql/0.3/alasql.min.js:11

**Comment by mathiasrw** [comment]
I made a new example with latest versions of alasql and xlsx: http://jsfiddle.net/gf490vfj/

I dont get any errors on chrome. Are you still getting something thats not working? what browser are you using?

**Comment by alex-p-crest** [comment]
It is working fine in Chrome. I have mentioned Safari. Getting error in Safari.
'[object BlobConstructor]' is not a constructor (evaluating 'new Blob([t],{type:"text/plain;charset=utf-8"})')
https://cdn.jsdelivr.net/alasql/0.3/alasql.min.js:11
