### ISSUE TITLE
The best tagline ever

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#265]
I have a feeling we could have a tagline that better describe most of the awesomenes.

What do you think about 

> Versatile javaScript SQL database library for relational data, noSQL (schemaless) data, and graph manipulation supporting localStorage, IndexedDB, and Excel files for import/export

Are we missing the JSON part? Are we missing the "select your SQL flavour" ?

Come with inputs

**Comment by agershun** [comment]
May be "... relational tables and nested JSON data"

**Comment by mathiasrw** [comment]
What about 

> Versatile javaScript SQL database for both your (traditional) relational tables or nested JSON data (noSQL) - supporting localStorage, IndexedDB, and Excel files for import/export

**Comment by mathiasrw** [comment]
Hmmm. Perfection is when there is nothing more to remove.... but... Thinking this might be more spot on:

> Versatile SQL database for browser or node. Handles both your (traditional) relational tables and nested JSON data (noSQL). Export, store, and import data from localStorage, IndexedDB, or Excel.

**Comment by mathiasrw** [comment]
Future versions could add

> Choose your SQL compliant flavor: Postgress, MSSQL, MySQL, OrientDB.

(and so on...)

**Comment by agershun** [comment]
Ok.

**Comment by mathiasrw** [comment]
Great - can you put it as the header of the Repo? (I dont have access)

Ill place it in the package.json file

**Comment by mathiasrw** [comment]
I am such an idiot.... I merged the change of description into master. awwww. Sorry for that :-/

**Comment by agershun** [comment]
Don't worry. No problem! I did not touch README anywhere. I will just replace it when we will release new version. Please, move all changes to wiki, so we can change it together.

**Comment by mathiasrw** [comment]
Check !

**Comment by agershun** [comment]
I updated the tag line in repository

**Comment by mathiasrw** [comment]
:+1:
