### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#269]
Lets clean up the unused branches (old versions and branches)

Idially we only keep master, develop and feature branches that we are still using. 

If you like the debug branch for your workflow we could leave it. 

I can be responsible for this if you feel like it.

**Comment by agershun** [comment]
Ok. Please do it.

**Comment by mathiasrw** [comment]
Are you using the old-master branch for something?

Last commit was 18. april

**Comment by agershun** [comment]
No. We do not need it.

**Comment by mathiasrw** [comment]
:+1:
