### ISSUE TITLE
Error in bower file

### ISSUE THREAD

**Issue by carbuz** [agershun/alasql#271]
hi , there is no "xlsx":"0.8.0" package(see bower file). The correct name is  "js-xlsx":"0.8.0" (https://github.com/SheetJS/js-xlsx/blob/master/bower.json).

**Comment by agershun** [comment]
Thank you! Just  updated ```.bower``` in ```master``` and ```develop``` branches.

**Comment by prdn** [comment]
Can you please increase the version number?
Otherwise the change has no effect.

Thank you

**Comment by mathiasrw** [comment]
@prdn 

What is the correct version number?

**Comment by agershun** [comment]
Ours is 0.1.10

**Comment by agershun** [comment]
@prdn Paolo, sorry for this bug. We will republish new version tonight,

**Comment by prdn** [comment]
Thank you very much

On 2 June 2015 at 13:57, Andrey Gershun <notifications@github.com> wrote:

> @prdn <https://github.com/prdn> Paolo, sorry for this bug. We will
> republish new version tonight,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agershun/alasql/issues/271#issuecomment-107945104>.
>



-- 
--
Paolo Ardoino

**Comment by agershun** [comment]
Updated to version 0.1.10. Can you test it?

**Comment by prdn** [comment]
When I run bower update I receive this warning: 
alasql: Available versions: 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0, 0.0.51, 0.0.50, 0.0.49, 0.0.48, 0.0.47, 0.0.46, 0.0.45, 0.0.44, 0.0.43, 0.0.41, 0.0.40
It seems that bower does not find the 0.1.10 version

**Comment by agershun** [comment]
Sorry again fo this problem and thank you again for ther report. 

I updated versions to 0.1.10 in Github and NPM yesturday evening. It seems that all files are ok and with correct version.  May be Bower still did not update it cache?... Is there any special procedure to update Bower repository (I didnot find it)?

I just tried to install AlaSQL with Bower  and received another error:
```
> bower install alasql

bower alasql#*              not-cached git://github.com/agershun/alasql.git#*
bower alasql#*                 resolve git://github.com/agershun/alasql.git#*
bower alasql#*                 ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/agershun/alasql.git", exit code of #128 fat
al: unable to connect to github.com: github.com[0: 192.30.252.128]: errno=No such file or directory

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=No such file or directory
```
. . . I will try to unregister and register the package again with Bower.

**Comment by prdn** [comment]
Thanks for the quick answer.

I think you're right about bower caching.
Your issue installing alasql instead is that the bower command failed to
resolve github.com

On 3 June 2015 at 14:15, Andrey Gershun <notifications@github.com> wrote:

> Sorry again fo this problem and thank you again for ther report.
>
> I updated versions to 0.1.10 in Github and NPM yesturday evening. It seems
> that all files are ok and with correct version. May be Bower still did not
> update it cache?... Is there any special procedure to update Bower
> repository (I didnot find it)?
>
> I just tried to install AlaSQL with Bower and received another error:
>
> > bower install alasql
>
> bower alasql#*              not-cached git://github.com/agershun/alasql.git#*
> bower alasql#*                 resolve git://github.com/agershun/alasql.git#*
> bower alasql#*                 ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/agershun/alasql.git", exit code of #128 fat
> al: unable to connect to github.com: github.com[0: 192.30.252.128]: errno=No such file or directory
>
> Additional error details:
> fatal: unable to connect to github.com:github.com[0: 192.30.252.128]: errno=No such file or directory
>
> . . . I will try to unregister and register the package again with Bower.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agershun/alasql/issues/271#issuecomment-108402526>.
>



-- 
--
Paolo Ardoino

**Comment by sovanna** [comment]
bower install alasql give me

    bower xlsx#0.8.0          ENORESTARGET No tag found that was able to satisfy 0.8.0
    Additional error details:
    No versions found in git://github.com/stephen-hardy/xlsx.js.git

**Comment by agershun** [comment]
Sorry, I do not understand what is going on with Bower. We already have changed these line yesturday to:
```
  "js-xlsx":"0.8.0",
```
in ```.bower.json``` file.  May be it is bower cache problem? 

Unfortunately, I cannot try it right now, because bower does not work in my office network. Hope, can find the source of the problem and fix it tonight.

**Comment by sovanna** [comment]
not a real big deal, for the moment, I download the project and use it in hard way,

thank anyway ;)

(for the bower cache, I've tried using cache clean)

**Comment by mathiasrw** [comment]
Hmm. looks like we are still not flying - no results on alasql on bower.io

http://bower.io/search/?q=alasql

does anyone have experience with bower?

**Comment by agershun** [comment]
I will try to unregister and reregister it again. May be this will help?

**Comment by agershun** [comment]
1. Bower command-line search works OK:
```
    >bower search alasql
    Search results:
    alasql git://github.com/agershun/alasql.git
```

I just re-register bower package, and tried to install it. Everything was ok. 

Unfortunately, the bower.io does not seach it from the web-page http://bower.io/search/?q=alasql (command-line search is ok)

**Comment by agershun** [comment]
Just opened the issue at Bower's github: https://github.com/bower/search/issues/72

**Comment by desandro** [comment]
First try waiting a couple days for the search registry to be updated. The problem may be due to using `.bower.json` as opposed to the standard `bower.json`.

**Comment by agershun** [comment]
Thank you! We are already more than month in the line, so the problem probably is in filename:) 

We will try to keep a two files with same content: ```.bower.json``` and ```bower.json```

**Comment by agershun** [comment]
Now AlaSQL in the Bower search list.
