### ISSUE TITLE
JavaScript performance tricks

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#274]
We have a lot of ```typeof v ==="undefined"```, but according [jsPerf](http://jsperf.com/type-of-undefined-vs-undefined) we can replace it with (which is 3 times faster):
```
    v === undefined
```

**Comment by agershun** [comment]
I am like the caring granny:
> Please, be sure that the variable is already defined before the check. The undeclared variables are of for ```typeof v === "undefined"``` variant, and thros errors for simple ```=== undefined```

**Comment by mathiasrw** [comment]
Love Javascript - but does have its #¤%#¤"%¤#" moments :)
