### ISSUE TITLE
CREATE returns undefined 

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#277]
Had time to look into the 2 errors we get when we `npm test` 

The function 

    alasql('CREATE TABLE one (id SERIAL, name STRING)');

and

    alasql('INSERT INTO one (name) VALUES ("One"), ("Two"), ("Three")');
    
both gives `undefined` instead of expected 1 and 3

when console.log of response I get

```
 Test 350 SERIAL data type
    ✓ 1. CREATE DATABASE
undefined
    1) 2. CREATE TABLE
undefined
    2) 3. INSERT
    ✓ 4. SELECT
    ✓ 99. DROP DATABASE
```

I beleave the test is correct and there is something wrong with the implementation of responses from create and insert.

**Comment by agershun** [comment]
If you run this test independently:
```
    > mocha test350
```
everything passed OK, that is why I passed it to release. So, this is a problem of interference one test to another. But ok, anyway it is a bug.

**Comment by agershun** [comment]
I understand what is it. We set ```NOCOUNT``` parameter to off in earlier tests. 

I will change test and addone of two lines either:
```js
    alasql('SET NOCOUNT OFF');
```
or
```js
    alasql.options.nocount = false;
```

**Comment by mathiasrw** [comment]
Great. Just push it to development so I can get the fresh test files

**Comment by agershun** [comment]
Pushed/

**Comment by mathiasrw** [comment]
Hmm. I can see you edited test 352 - but its in test 350 im getting the problem in

```javascript
 it('2. CREATE TABLE',function(done){
    var res = alasql('CREATE TABLE one (id SERIAL, name STRING)');
    assert.deepEqual(res,1);
    done();
  });

  it('3. INSERT',function(done){
    var res = alasql('INSERT INTO one (name) VALUES ("One"), ("Two"), ("Three")');
    assert.deepEqual(res,3);
    done();
  });
```

Could you look into making sure res is not undefined?

**Comment by agershun** [comment]
I walked through all tests and put ```NOCOUNT OFF```  in proper places (in the end part of each "nocount" test).Commit  af718b1

**Comment by mathiasrw** [comment]
:+1:
