### ISSUE TITLE
variable not declared

### ISSUE THREAD

**Issue by carbuz** [agershun/alasql#279]
Could you please change in your code:

compileSearchOrder = function (order){ //variable not declared

with

function compileSearchOrder (order) {

Thanks

**Comment by mathiasrw** [comment]
Sure !

Thanks for letting us know - we really need to focus on getting clean lint checks on the code.

I have soved the variable not declared, but slightly different than suggested: https://github.com/agershun/alasql/commit/c0745fc0fb6b257d3771fc93f22d489ccc295daa

Will be merged into the next release.

**Comment by carbuz** [comment]
thanks
Il 04/giu/2015 13:22, "Mathias Rangel Wulff" <notifications@github.com> ha
scritto:

**Comment by agershun** [comment]
Thank you! I will release it to ```master``` in version 0.1.11 tonight.
