### ISSUE TITLE
Promise for compiled statement

### ISSUE THREAD

**Issue by gregaubert** [agershun/alasql#285]
I recently saw the new `promise` interface for executing query, that's great! And I thought it would be even greater to be able to use `promise` with compiled statements, something like that : 

```javascript
var data = [{ field: 1}, {field: 2}, {field: 3}];
var compiledStmt = alasql.compile('SELECT * FROM ? WHERE field = ?');
compiledStmt.promise([data, 2])}).then(function(res){
    // Process data
}).catch(function(err){
    // Process errors
});
```

**Comment by agershun** [comment]
@gregaubert thank you for idea! 

I think we can create a special version of ```compile()``` function or add special parameter, for example:
```js
    // Variant A
    var st = alasql.compileWIthPromise('SELECT * FROM ?');
    // Variant B
    // or with parameter
    var st alasql.compile('SELECT * FROM ?', 'promise');
  
    st([data]).then(...).catch(...);
```
Another option - to compile ```.promise()``` function as you wrote...
```
    // Variant C
    st.promise([data]).then(...).catch(...);
```

Let me review internals of ```compile()``` function and think about these variants.

What do you think, which syntax is better: A, B, or C?

**Comment by gregaubert** [comment]
I don't really know which one would be better, tough I don't really like option A.
Option B or C seems nice, they would also allow to do this : 

```javascript
var st = alasql.compile('SELECT * FROM ?', 'async');
st([data], function(data) {...});

// Or like this
st.async([data], function(data) {...});
```

**Comment by agershun** [comment]
You can call async version of compiled statement even right now:
```
    var st = alalsql.compile('SELECT * FROM ?');
    st([data],function(data,err){ . . . });
```
Let we keep consitency and use variant C:
```
    var st = alalsq.compile('SELECT * FROM ?');
    st.promise([data]).then(...).catch(...);
```
In this case we will use almost the same interface as original ```alasql()``` function.

I will see tonight how e can realize this. Thank you!

**Comment by gregaubert** [comment]
Ok nice!

**Comment by agershun** [comment]
Done. Now in ```develop``` branch. See [test353.js](https://github.com/agershun/alasql/blob/602a0251a1885714e1a1f3ec4cf7040715c21a5c/test/test353.js)
