### ISSUE TITLE
Complete test stubs

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#291]
The following tests are only stubs. It would be really good if they got expanded to make sure changes dont break functionality (for example when I am bithounding the files...)

- test0058
- test0064
- test0065
- test0066
- test0067
- test0068
- test0069
- test0070
- test0071
- test0072
- test0073
- test0074
- test0075
- test0076
- test0077
- test0078
- test0079
- test0080
- test0081
- test0082
- test0083
- test0084
- test0085
- test0086
- test0087
- test0088
- test0089
- test0090 (named Test 91)
- test0091 (identical to test0090)
- test0093
- test0094
- test0095
- test0096
- test0097
- test0098
- test0099
- test0100
- test0101
- test0102
- test0103
- test0105

another question. test222.js is depricated and wrapped in if(false) - Cant we just delete it?

**Comment by agershun** [comment]
I opened special directory for temporary skipped tests: ```/tests/skipped```. I offer to move all these tests to this directory, and then take with care from there one by one (like i did before with other tests). As you can see every of these tests has header with proposed functionality, hope we will create it for each of everyone test.

**Comment by mathiasrw** [comment]
Sounds great. Are you gonna move them or would you like me to do it? (just so we dont both do this... :) )

**Comment by agershun** [comment]
Please, move them. 
I have added tests 254-360 for PIVOT, but not yet finished. 
Can you also copy ```.bower.json``` to ```bower.json```?

**Comment by mathiasrw** [comment]
I will move the tests mentioned into skipped. I will also move test345 that is not a stub, but always calls `done()` (maybe you can call done depending on some select value from the db)

When I look at http://bower.io/docs/creating-packages/ It looks like the `bower.json` is the correct way of naming the bower file. Are you sure you want to have same content in 2 files with and without prepending dot?

**Comment by agershun** [comment]
1. test345 - ok.

2. Bower: honestly, I do not know. It was a recomendation to crename this file to ```.bower.json```, but what is right way ... Let's try with two files and we will see.
