### ISSUE TITLE
Add multiple table for DROP TABLE statement

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#293]
See:
```sql
    DROP TABLE IF EXISTS users,hobbies,users_hobbies; 
```

**Comment by mathiasrw** [comment]
:+1:

**Comment by agershun** [comment]
Unfortunately, there many small issues like this from [this MySQL samples list](http://www.artfulsoftware.com/infotree/mysqlquerytree.php). So, we will fix problems along with preparing samples for start page.

**Comment by agershun** [comment]
Done. Will be merged soon. Test358.js
