### ISSUE TITLE
alasql & web worker

### ISSUE THREAD

**Issue by partok** [agershun/alasql#30]
Very impressive library Andrey.
I tried to use alasql in web workers: I had to remove some references to 'window' with indexedDB and disable FileSaver.js because of 'createElementNS'.
It seems to work quite well but I may have overlooked something.
I have seen WebWorker on your TODO : is it planned to be supported any time soon?

**Comment by agershun** [comment]
Thank you! I will try fix this issue on the next week

**Comment by partok** [comment]
That is very soon!
Thanks.

**Comment by agershun** [comment]
I created WebWorker version of Alasql. It will be included in version 0.0.36. Unfortunately, I have no Internet here until January 8.

**Comment by partok** [comment]
Thanks for being so responsive!

**Comment by agershun** [comment]
Hi, 

I created two different versions of webworkers for Alasql. Could you give a feedback?

### Option 1:
```html
    <script src="alasql-worker.js"></script>
   <script>
        alasql('SELECT VALUE 1+1', [], function(res){
            console.log(res);
        });
    </script>
```

Include file ```alasql-worker.js``` on the page, and it will download ```alasql.min.js``` as a webworker. After that alasql() function will post message to webworker, and then return result value back. The webworker version of alasql() is async.

Try this example [here](http://alasql.org/demo/012worker/).

If you want to load scripts into webworker you can use REQUIRE statement:
```sql
    alasql('REQUIRE "script1.js", "script2.js" ',[],function(){
        // sql used script1.js
    });
```
### Option 2:
```html
    <script src="alasql.js"></script>
   <script>
        alasql.worker();
        alasql('SELECT VALUE 1+1', [], function(res){
            console.log(res);
        });
    </script>
```

Include file ```alasql.js``` on the page, and then run alasql.worker(). It will create new Worker based on the alasql.min.js. After that you can use Alasql as shown before. Again, the webworker version of alasql() is async.

Try this example [here](http://alasql.org/demo/012worker/index2.html).

alasql.worker() function has three parameters:
```js
    alasql.worker() - start worker
    alasql("alasql.min.js") - start worker from specified path
    alasql("alasql.min.js",["script1.js","script2.js"], callback) - load additional javascript files.
```

What do you think, which option is more adopted to your need? Should I change anything in this approach?

**Comment by agershun** [comment]
Done! :)

Try these three examples:
* [http://alasql.org/demo/012worker/index.html](http://alasql.org/demo/012worker/index.html) - option 1 - include alasql-worker.min.js, which loads alasql.min.js as webworker. Alasql catches messages
* [http://alasql.org/demo/012worker/index1.html](http://alasql.org/demo/012worker/index1.html) - option 2 - just load importScripts("alasql.min.js") inside webworker. Alasql does not catch messages
* [http://alasql.org/demo/012worker/index2.html](http://alasql.org/demo/012worker/index2.html) - option 3 - run alasql.worker() function, which loads alasql.min.js as webworker. Alasql catches messages

Your option is number 2. Can you check it?

HTML file:
```html
    <h1>Worker demo: simple worker</h1>
    <p>See Console for worker results</p>
    <script>
        var worker = new Worker('other-worker.js');
    </script>
```
Webworker:
```js
    importScripts('../../console/alasql.min.js');
    if(alasql) {
        console.log('Alasql is here?',alasql('SELECT VALUE TRUE'));
        console.log('self.onmessage is free?',!self.onmessage);
    }
```;

**Comment by agershun** [comment]
PS. All fixed files are at branch [version-0.0.37](https://github.com/agershun/alasql/tree/version-0.0.37)

**Comment by partok** [comment]
I agree with you on option 3.
And option 2 solved my problem.
Thank you very much Andrey!

**Comment by thekennysong** [comment]
@agershun is there a way to use this with React?

**Comment by mathiasrw** [comment]
Yep. You can use it with react.

**Comment by tdehollain** [comment]
Is there an example somewhere of using alasql in a web worker in a React app? 
I added `alasql.worker()` to the file where I run my alasql commands, but it throws an error: Path to alasql.js is not specified
