### ISSUE TITLE
gitignore and test16a.xlsx

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#301]
By unknown reason these files do not rejected by ```.gitignore``` rule ```test/res*``` and added to commit every time when test run.

* test/restest169a.xlsx
* test/restest251.xlsx
* test/restest255.xlsx

**Comment by mathiasrw** [comment]
Added test/*.xls* to the gitignore. Lets see if that helps...

**Comment by agershun** [comment]
No, unfortunately, it does not...
```
        modified:   test/restest169a.xlsx
        modified:   test/restest255.xlsx
```

**Comment by mathiasrw** [comment]
Ahh, its because the files are still tracked. 

Please do the following

```
git rm -r --cached .

git add .

git commit -m "fixing .gitignore"
```

now gitignore should work :)
