### ISSUE TITLE
Avoiding .exec for node

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#303]
At the moment in node we write

    var db = new alasql.Database();
    db.exec("CREATE TABLE example (a INT, b INT)");

In the browser the `.exec` is not mandatory. Could you look into if it would be possible to have it like the browser where one would be able to call 

    db("CREATE TABLE example (a INT, b INT)");

Effectively having db() as alias for db.exec(). 

This would make it easier to port code from the browser to node

**Comment by agershun** [comment]
1. The syntax for Node and browser is similar. You can use any of these constructions either for browser and Node programs, so there is no need to port the code - it should be the same.

2. I like the syntax you proposed: 
```
var db = new alasql.Database();
var r = db('SELECT 100');
db.promise('SELECT 100').then(...);
```

**Comment by mathiasrw** [comment]
Closed and continue the discussion on https://github.com/agershun/alasql/issues/329 where I found out what I am talking about here...
