### ISSUE TITLE
alasql bin file - alacon 

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#307]
I was of the impression that alacon would be a binary file to be executed. I find only .js files in `bin/` and `console/` folders (its not  totally clear to me that the difference is). I see no installation information in wiki about how to proceed. So I have a feeling one needs Node to run AlaSQL from the commandline in the moment. 

**If that is true** I have an idea for future emprovements:

- Check if AlaSQL runs correctly with http://duktape.org/ (200kb javascript engine written in c)
- (If it does) wrap duktape and alasql in a bin executable of alasql.js 

I suggest Go as wrapper as it compiles to mac, freebsd, linux and windows (both 386 and 64bit version for all) with one command. 

(if we use Go we can use www.github.com/mitchellh/cli or www.github.com/tcnksm/cli-init/ to implement console )

**Comment by agershun** [comment]
1. ```alacon``` is a small file in ```bin``` folder. It requires alasql.js and passes own parameters to it.

If you install alasql globally:
```
    npm install -g alasql
```
it will install alacon to command line.

2. ducktape: not sure... let's try!

3. I thought to merge alacon and alaserver into one utility and create something like REST interface.

**Comment by mathiasrw** [comment]
That is really awesome. Did not know that installing globally would give you the commandline interface. do you call the command `alacon` or `alasql` in the commandline?

If it works lets just skip the wrapping thing and focus on node...

Idea: call alacon with parameters will start the http server - so one cool but 2 functions ?

Im not sure REST interface is the best solution when we dont know anything about the data.

**Comment by mathiasrw** [comment]
Ok. I totally get it now. 

Question: when I write alacon purely I get this instruction

  alacon - Alasql command-line utility (version 0.1.9) 

  Usage:
    node alacon "sql-statement" [ param0 ]... - run SQL statement
    node alacon -f file.sql [ param0 ]...     - run SQL from file

  Samples:
    node alacon 'select 2+2'
    node alacon 'select count(*) from txt()' <city.txt
    node alacon 'select * into xlsx("city.xlsx") from txt("city.txt")'

  matmac:alasqltest mrw$ alacon
  alacon - Alasql command-line utility (version 0.1.9) 

  Usage:
    node alacon "sql-statement" [ param0 ]... - run SQL statement
    node alacon -f file.sql [ param0 ]...     - run SQL from file

  Samples:
    node alacon 'select 2+2'
    node alacon 'select count(*) from txt()' <city.txt
    node alacon 'select * into xlsx("city.xlsx") from txt("city.txt")'


All the examples have `node` i front - but as its installed globally its not needed. Should we remove node from the examples as its more ment to be used with global install?

Question 2 - how some you ended up with the name alacon for "Alasql command-line utility" It makes sense to call it alacom (or just alasql) - but cant figure the connection to the 
'n'

it states (version 0.1.9) - we must remember to update

**Comment by agershun** [comment]
Q1: We need to remove ```node``` from documentation. 

Q2: What if we call this utility ```alasql```? We can modify alasql.js to check if the word ```alasql``` is in ```process.argv[1]```?

Numbers: ... I will write templater to put proper number in all places.

PS. Sorry, I am inactive in this week, hope I will have more time on the next week.

**Comment by mathiasrw** [comment]
No problem. We all contribute when we can...

**Comment by mathiasrw** [comment]
Must say that to me it makes more sense that when you globally install AlaSQL from npm - then you can call `> alasql 'SELECT 3+4'` afterwards.

**Comment by agershun** [comment]
Added to the next release. From the next version this should work:
```bash
    > alasql 'SELECT 2+3'
```

**Comment by mathiasrw** [comment]
sweeeeet!
