### ISSUE TITLE
writing Xls file 

### ISSUE THREAD

**Issue by ranoy** [agershun/alasql#309]
Hi, 
 I have just started with this library , seems a great library(except the IE9 issue ,which is known).
Is there any way to write xls files with this library . I have the requirement for xls.

**Comment by agershun** [comment]
You can write XLS files even with IE9:
```js
    alasql('SELECT * INTO XLS("name.xls",{headers:true}) FROM ?',[data]);
``` 

For XLSX is the same (sorry, no IE9 here):
```js
    alasql('SELECT * INTO XLSX("name.xlsx",{headers:true}) FROM ?',[data]);
``` 

Currently, we are working on improving this functionality.

**Comment by ranoy** [comment]
Hi,
 I am sorry , I guess I was sleepy , I was supposed to raise this question on a different library page.
I will just close this issue. Thanks for your reply. :)
