### ISSUE TITLE
Format Dates

### ISSUE THREAD

**Issue by lonnieCross** [agershun/alasql#31]
I'm trying to format dates in the select statement:

CONVERT(VARCHAR(10),GETDATE(),110) returns an error. How should this be handled?

Thanks!

**Comment by agershun** [comment]
1. Unfortunately, the CONVERT() and CAST() functions are not realized yet. I will include them in version 0.0.36 on January 9, 2014

By default Alasql keeps all dates in string format like YYYY.MM.DD HH:MM:SS, so I will prepare conversion number 110 in next realization.

**Comment by agershun** [comment]
1. I fixed CONVERT() function.

You can see the example of different CONVERT styles [in jsFiddle]((http://jsfiddle.net/agershun/qytn1n0L/)) or [in test212.js](https://github.com/agershun/alasql/blob/version-0.0.36/test/test212.js):

2. BTW Use ```GETDATE()``` instead ```GETDATE```.(see [another example](http://jsfiddle.net/agershun/v22cm0cv/))

Does this solve the problem?

**Comment by agershun** [comment]
Another options:

1. You can use Moment.js and Numbers.js libraries togeather with Alasql to format dates and numbers (see examples in Wiki: [dates](https://github.com/agershun/alasql/wiki/Moment.js) and [numbers](https://github.com/agershun/alasql/wiki/Numeral.js)).

2. You can use [sprintf()](https://github.com/agershun/alasql/wiki/Sprintf.hs) for other type of formatting. 

3. You can write formatting function yourself:

```js
    alasql.fn.fmt = function(n) {return ((n/100)|0) + '.'+ (n%100)}
    var res = alasql(SELECT fmt(RANDOM(10000)) FROM RANGE(1,10)');
```

See the example [in jsFiddle](http://jsfiddle.net/agershun/n2z46Ljf/).

**Comment by vivekratnavel** [comment]
CONVERT() function does not work with group by clause.

```SELECT count(*), CONVERT(STRING,DATE(FIRST(date)),1) FROM table group by MONTH(date), DAY(date)```

I am getting this as output:
```{CONVERT(STRING,DATE(FIRST(date)),1): "aN/aN/aN", 
COUNT(*): 332}```

**Comment by mathiasrw** [comment]
@vivekratnavel Thanks for letting us know - Ill create an issue with it...

**Comment by mathiasrw** [comment]
@vivekratnavel I would love if you could share the table and some demo data that creates the problem

**Comment by vivekratnavel** [comment]
You can use the javascript in this fiddle to insert values into the table.
http://jsfiddle.net/vivekratnavel/31n7f2qz/

Jsfiddle becomes slow when the table is loaded with 200000+ rows. My advice is to use the script locally.

**Comment by agershun** [comment]
This is not a problem of CONVERT but the statement:
```sql
    SELECT count(*), CONVERT(STRING,DATE(FIRST(date)),1) FROM table group by MONTH(date), DAY(date)
```
Here AlaSQL does not know where to take ```date``` variable, because there is no such data in GROUP BY clause.
