### ISSUE TITLE
Export To Excel With Column Options Not Working

### ISSUE THREAD

**Issue by hemantsavkar** [agershun/alasql#310]
Hi ,
I'm using below configuration to Export to Excel....But Column mapping Not Working

var opts = {
            headers: true,
            sheetid: 'Users',
            caption: {
                title: 'All Users',
            },
            style: 'background:#00FF00',
          columns: [
                   columnid:'name',
                   title:'Name'
            ]
        };

alasql("SELECT * INTO XLSX('Users.xlsx',?) FROM ?", [opts, $scope.gridConfiguration.data]);

Data Exported with column header as "name" and not "Name" (Expected),
No Background Applied
No Caption.

version I'm using v0.1.9

**Comment by agershun** [comment]
This function now works only for XLS() output functions:
```js
alasql("SELECT * INTO XLS('Users.xlsx',?) FROM ?", [opts, $scope.gridConfiguration.data]);
```
Sorry, we have not finished it yet for XLSX() export function.

**Comment by hemantsavkar** [comment]
Do i need to add refrence to any new .js for XLS ? Or is it in alasql.js or xlsx.js ?

**Comment by hemantsavkar** [comment]
Whola !!!!  Worked Perfect for me ......You Saved Life man.......

**Comment by hemantsavkar** [comment]
Thanks Worked !!!

On Jun 18, 2015 10:09 AM, Andrey Gershun <notifications@github.com> wrote:
This function now works only for XLS() output functions:
```js
alasql("SELECT * INTO XLS('Users.xlsx',?) FROM ?", [opts, $scope.gridConfiguration.data]);
```
Sorry, we have not finished it yet for XLSX() export function.

---

**Comment by MaximMakulski** [comment]
@hemantsavkar hey do you now,how caption style Options get to run ??
