### ISSUE TITLE
try catch for indexeddb backend not working properly

### ISSUE THREAD

**Issue by dusanmiloradovic** [agershun/alasql#311]
![image](https://cloud.githubusercontent.com/assets/706290/8229397/62899d80-15c7-11e5-9b49-dfa9420042af.png)

The error is throw from IDB onsuccess event handler , and is not visible from the outside

**Comment by agershun** [comment]
Thank you for the iissue!

Unfortunately, it happens because all IndexedDB operations are asyncronous, and  ```try catch``` construction does not catch them. 

We will upgrade the error catching functionality for IndexedDB backend to use constructions like this:
```js
alasql.options.errorlog = true; 
alasql('ATTACH INDEXEDDB DATABASE NN'.[].function(data,err){
    if(err) // do something with error;
});
// or 
alasql.options.errorlog = function(err){console.log(err)}; // Error function 
alasql('ATTACH INDEXEDDB DATABASE NN'.[].function(data,err){
    //...
});


```

Hope we can upgrade it in the next version of the library.

**Comment by mathiasrw** [comment]
Question to @agershun 

Would it also be possible to use this ?

    alasql.promise(sql).then(...).catch(...);

**Comment by mathiasrw** [comment]
@agershun have you had time to look at the 2 questions?

**Comment by mathiasrw** [comment]
@agershun have you had time to look at the 2 questions?

**Comment by cepm-nate** [comment]
5 years later, do we have consistent way to catch errors from indexeddb yet?

**Comment by mathiasrw** [comment]
@cepm-nate Sure. Please use [promise notation](https://github.com/agershun/alasql/wiki/promise) and it will all work out smoothly.
