### ISSUE TITLE
equalDeep vs deepEqual

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#318]
Can you elaborate on the difference of equalDeep and deepEqual in 15utility?

**Comment by agershun** [comment]
It should be only one functions. Let it be ```deepEqual()``` (like in ```assert``` module).

**Comment by mathiasrw** [comment]
Great. 

Would you prefer if I put every question in a new issue or is it ok with a bunch in https://github.com/agershun/alasql/issues/243 ?

**Comment by agershun** [comment]
One question - one issue. So we can keep track on each even smallest part.
When we have too many issues to maintain here we can migrate to Jira.

2015-06-23 17:28 GMT+03:00 Mathias Rangel Wulff <notifications@github.com>:

**Comment by mathiasrw** [comment]
:+1:

**Comment by mathiasrw** [comment]
`equalDeep` has been eleminated

**Comment by agershun** [comment]
:+1:
