### ISSUE TITLE
Functions like L, N, NL, ID, KK

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#328]
Are you using the functions in 12pretty.js for debugging during development? Calls to functions like L, N, NL, ID, KK are spread out in the code a lot of places, and I dont quite get the point

---- 

Agershun: 

1. AlaSQL uses ```.toString()``` to reconstruct names for expressions to create expression column names. For example:
```sql
    SELECT a+b FROM @[{a:1,b:2}]
```
generates:
```
    [{"a+b":3}]
```
Here ```"a+b"``` was reconstructed from AST with ```.toString()``` function. It is better than uses original sql text, because people can add spaces, line break, etc. And this is important for GROUP BY and ORDER BY clauses.

2. I had the idea to have prettifyer inside AlaSQL, But, probably, this function is not demanded.

So, we can:
1. Remove (or move to plugin) all ```.toString()``` functions for all non-expressions.
2. Remove all ```K()```, ```L()```, etc. calls and functions from ```.toString()```

**Comment by mathiasrw** [comment]
Just to confirm - its OK to remove all the L, N, NL, ID, KK and so on calls from the code for Prittyfication?

**Comment by agershun** [comment]
Let's remove them. We can restore them when decided to add prettifier to AlaSQL. Now it is not demanede.

**Comment by mathiasrw** [comment]
Done. 

Please pull develop
