### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#330]
In 

https://github.com/agershun/alasql/blob/master/src/50expression.js#L276

and 

https://github.com/agershun/alasql/blob/master/src/50expression.js#L281

The core of the return statement is  

     (a).valueOf()===(b.valueOf())

For consistency I have changed it to 

     (a).valueOf()===(b).valueOf()

Please let me know if the original structure was intentional...

**Comment by agershun** [comment]
You are right.
