### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#332]
Is it an error that the two lines both contain !tbid? is first one ment to be overwritten?

https://github.com/agershun/alasql/blob/master/src/424select.js#L118-L119

**Comment by agershun** [comment]
No. This intentionally done on this way.
```
    if(!tbid) tbid = query.defcols[col.columnid];
    if(!tbid) tbid = query.defaultTableid;
```
If after first line we have ```undefined``` AlaSQL puts ```defaultTableid``` into the variable

**Comment by mathiasrw** [comment]
Makes good sense...
