### ISSUE TITLE
+res

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#334]
in 84from.js I found this line

```js
if(res[i] == +res[i]) res[i] = +res[i];
`````

Can you elaborate on the idea?

**Comment by agershun** [comment]
Here AlaSQL checks if ```res[i]``` is a string with numeric value, then AlaSQL convert it to the number.

```+res[i]``` is a conversion to ```number``` type. From JavaScript point of view this conversion is ok, because if it is required (for example, for comparision) JS will convert it back to ```string``` type.
