### ISSUE TITLE
Options on new alasql.Database

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#337]
I am trying to find out if I need to 

```
	var db = new alasql.Database(name);
	db.options.cache = false;
```

for each instance or if options are global. 

Question: Are AlaSQL options like `alasql.options.cache = false;` global for all instances of `new alasql.Database(name);`?

**Comment by agershun** [comment]
All ```alasql.options``` are global. 

Are there any cases where we need to have separate options for each database?

**Comment by mathiasrw** [comment]
Hmmm. No. 

It was just for clarification. I will put it into the wiki documentation.
