### ISSUE TITLE
order by bug?

### ISSUE THREAD

**Issue by pasapsi** [agershun/alasql#341]
TypeError: Cannot read property 'owner' of undefined
```
order by  table_kpi.owner->name asc (It leads to error)
order by  owner->name asc (all right)
```
http://jsfiddle.net/8mobrL3o/3/

**Comment by agershun** [comment]
Here ORDER BY is the last clause in the sequence and it performs after the SELECT clause performed, so it sorts data from the final table, where we do not have original table names (like table_kpi).

**Comment by pasapsi** [comment]
Got it, thanks for the reply
