### ISSUE TITLE
Lonely ")"

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#342]
In 

https://github.com/agershun/alasql/blob/2a04c4fe5fd4ba161b24ddd0dafc11d1b84bac6a/src/77declare.js#L17-L19

it looks like we can end with a `)` without `(` if both `this.dbsize` and `this.dbprecision` are evaluated to false. 

If its a mistake I just fix it. 

If all is good lets put some comments around the code.

**Comment by agershun** [comment]
Yes, this is mistake.
