### ISSUE TITLE
output of 2 tables in select?

### ISSUE THREAD

**Issue by pasapsi** [agershun/alasql#344]
```
alasql('select table_kpi.owner->name from ? as table_kpi inner join ? as table_brand on table_brand.owner->id = table_kpi.owner->brand where table_kpi.owner->type=?  order by owner->name asc', [kpiTable.body, list, 'shop'])
```
```
so select owner->name... or select owner.name It gives an error message
```
how to overcome the attack?

```
Uncaught TypeError: Cannot read property 'name' of undefined(anonymous function) 
@ VM200596:1queryfn3
@ alasql.js?debug-16:6154queryfn2 
@ alasql.js?debug-16:5994(anonymous function) 
@ VM200590:1(anonymous function) 
@ alasql.js?debug-16:5943queryfn 
@ alasql.js?debug-16:5939yy.Select.compile.statement 
@ alasql.js?debug-16:6986alasql.dexec 
@ alasql.js?debug-16:4046alasql.exec 
@ alasql.js?debug-16:4028alasql 
@ alasql.js?debug-16:120(anonymous function) 
@ VM200734:1InjectedScript._evaluateOn 
@ VM199717:883InjectedScript._evaluateAndWrap 
@ VM199717:816InjectedScript.evaluateOnCallFrame 
@ VM199717:942(anonymous function) 
@ kpi-table.controller.js?debug-16:53$get.Scope.$emit 
@ angular.js?debug-16:14714(anonymous function) 
@ kpi-table-filter.directive.js?debug-16:51$get.Scope.$digest 
@ angular.js?debug-16:14310$get.Scope.$apply 
@ angular.js?debug-16:14573(anonymous function) 
@ ui-bootstrap.js?debug-16:371jQuery.event.dispatch
@ jquery.js?debug-16:4642jQuery.event.add.elemData.handle 
@ jquery.js?debug-16:4310
````

**Comment by agershun** [comment]
1. Probably, there are some ```owner``` fields with ```undefined``` value. Could you check the data?

If so, you can modify the code to something like:
```
ORDER BY (owner OR {})->name
```

2. What are your expectations: how AlaSQL should react in this case, when ```owner``` field is ```undefined```?

**Comment by pasapsi** [comment]
I want SELECT data from 2 tables, but alasql not know how to do it. realy?

**Comment by agershun** [comment]
@mathiasrw I think we can change a behavior of ```->``` function. If left part is ```undefined``` this function will return ```undefined``` instead throwing error. 

For example:
```
     SELECT owner->name FROM one
```
if ````owner```` is ```undefined``` AlaSQL will return ```undefined```. 

Internally it will be realized as ```(owner || {})['name']```

**Comment by mathiasrw** [comment]
@agershun I believe returning `undefined` is the preferred behaviour.

@pasapsi Please verify provide example data so you can be helped. Regarding your example I believe you are missing what table to join with

```
select
   table1.name,
   table2.text
from table1
   inner join 
   table2
      on table2.parent_id = table1.id
;
```

**Comment by agershun** [comment]
Ok, I will add it tomorrow morning.

**Comment by agershun** [comment]
Added (https://github.com/agershun/alasql/commit/59244c50de0f09dc64355f21ca40ed865db4864b). 

@pasapsi Could you try the last version from ```develop``` branch. It should protect from this collisions.

**Comment by pasapsi** [comment]
Example
http://jsfiddle.net/8mobrL3o/6/

**Comment by agershun** [comment]
Add ```AS``` clause to SELECT:
```js
var sql = alasql('select table1.name, table2.name as name2 from ? as table1 inner join ? as table2 on table1.id = table2.id', [table1, table2]);
```

See the example: http://jsfiddle.net/8mobrL3o/7/

**Comment by agershun** [comment]
Here you have two fields with same ```name``` name, so we need to rename one of them to be shown in result.

**Comment by pasapsi** [comment]
understood thanks

**Comment by pasapsi** [comment]
http://jsfiddle.net/8mobrL3o/9/

**Comment by pasapsi** [comment]
you have added support table1.name->sql, cool
http://jsfiddle.net/8mobrL3o/9/
