### ISSUE TITLE
Last Insert ID

### ISSUE THREAD

**Issue by TheDeadCode** [agershun/alasql#345]
Hi!

I'm currently using Node.JS. Here is my code.
    db.memory = require('alasql').Database();
    db.memory.exec('CREATE TABLE session (id INT AUTOINCREMENT, sessid STRING)');
    db.memory.exec('INSERT INTO session (sessid) VALUES ("TEST")');

How to get the last insert ID of the last query executed?

Thanks!

**Comment by agershun** [comment]
I your case it will be:
```
    db.memory.tables.session.identities.id.value
```
Here:
* ```db.memory``` - is a name of database
* ```tables.session``` - session table
* ```identities``` - collection of counters
* ```id``` - counter
* ```value``` - current value of counter

**Comment by agershun** [comment]
Please, look at this example: http://jsfiddle.net/ht3xqdd4/

**Comment by TheDeadCode** [comment]
Excellent! That means I need to ` db.memory.tables.session.identities.id.value - 1`

**Comment by Tobiaqs** [comment]
`db.memory.tables.session.identities.id.value - db.memory.tables.session.identities.id.step` would be a more robust way to obtain it :wink:
