### ISSUE TITLE
like in where

### ISSUE THREAD

**Issue by pasapsi** [agershun/alasql#349]
like things in alasql in select queries, examples below

SELECT * FROM pet WHERE name LIKE '?%'
or 
SELECT * FROM pet WHERE name LIKE '%?'
or 
SELECT * FROM pet WHERE name LIKE '%?%'

**Comment by agershun** [comment]
@pasapsi Could you specify the question? The problem is in ```?``` character?

**Comment by pasapsi** [comment]
http://jsfiddle.net/8mobrL3o/10/

Uncaught Error: Parse error on line 1:
....description like ?%
-----------------------^

This type of error occurs :(

**Comment by mathiasrw** [comment]
Good catch!

The '?' is in a string but looks like the parser thinks it's a '?' To be replaced with data from next argument.

**Comment by agershun** [comment]
This is a problem how AlaSQL translates string from LIKE to regular expression. It did not translate '?' to '.'. I already fix it and will publish tonight.

**Comment by pasapsi** [comment]
Ок, Thanks!

**Comment by mathiasrw** [comment]
Bam! One more dooooown...

**Comment by agershun** [comment]
Fixed (https://github.com/agershun/alasql/commit/611fd7f609882afcc4276484ec9a53653a8cc709). Please test

**Comment by mathiasrw** [comment]
:+1:
