### ISSUE TITLE
label in alasql

### ISSUE THREAD

**Issue by pasapsi** [agershun/alasql#350]
alasql have any labels in a query?
example
select if(:label=1, 1,0) from table where table.id=:label

because how to do it using the '?' i do not know

**Comment by agershun** [comment]
You can write with $ like:

alasq("SELECT a FROM one WHERE b = $name", {name:"Anna"});


Отправлено с iPhone

**Comment by mathiasrw** [comment]
Interesting. Did not know that. 

How is the syntax to mix this with inputting '?' data in the query? (as that demands 2nd parameter to be arrays of input)

**Comment by mathiasrw** [comment]
Ok - just thinking a bit here: guess its:

    alasql("SELECT a FROM $data WHERE b = $name", {name:"Anna", data:MyAwesomeObj});

**Comment by agershun** [comment]
Exactly!

There some options to use parameters:
a) use array of parameters (you can refer to them as $0, $1, etc.)
b) use ? (you can refer to them ?, ?, ?)
c) use object as parameter ($opt1, $opt2, etc.)

**Comment by mathiasrw** [comment]
Will find a good spot for this in the wiki

**Comment by pasapsi** [comment]
realized thanks
