### ISSUE TITLE
90 Mb size of alasql package

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#352]
We have a lot of overhead in test-sql directory. How to remove it?

**Comment by mathiasrw** [comment]
Just delete it and have SQL tests in another repo - just like the SQLlogictest

**Comment by mathiasrw** [comment]
Would you like me to do it?

**Comment by agershun** [comment]
Отправлено с iPhone

**Comment by agershun** [comment]
Yes, please

Отправлено с iPhone

**Comment by mathiasrw** [comment]
Des dude it was better to move it to its own branch so we keep things together. 

I have moved test-SQL to the branch other/testsuite and I have move the folder "stuff" to its own branch too.

I have a feeling we could do the same with utils - what do you say?

I have a feeling node_modules are not ment to go into npm eighter so we might git ignore them - but have not found the perfect solution yes

**Comment by agershun** [comment]
Ok, let's move ```stuff``` & ```utils```

```npm_modules``` - let me first review what is required for development and for run-time

**Comment by mathiasrw** [comment]
The thing is that the modules needed should be set as dependencies in package.json - so it must be set so deleting `node_modules` followed by a `> npm install` makes it work

**Comment by mathiasrw** [comment]
ohhhhh - found https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

added `.npmignore` and kept `utils`

**Comment by mathiasrw** [comment]
is the console folder important now that we have codeplex?

What about the lib folder?

**Comment by agershun** [comment]
...
1. I will replace console with Codex, and we will remove console directory.
2. lib... I will check

2015-07-08 8:43 GMT+03:00 Mathias Rangel Wulff <notifications@github.com>:

**Comment by mathiasrw** [comment]
Great!

Another option is to have codeplex in its own branch

**Comment by agershun** [comment]
I do not like branches to much, because the interfere with Dropbox.

**Comment by mathiasrw** [comment]
hmmm. Ok. Well, then I suggest that we make a repo for codeplex and a repo for testsuite (together with the folder stuff)

Will that work out for you?

**Comment by agershun** [comment]
Yes. I think this approach is better.

2015-07-08 13:21 GMT+03:00 Mathias Rangel Wulff <notifications@github.com>:

**Comment by mathiasrw** [comment]
`test-sql` and `stuff` are now placed in https://github.com/mathiasrw/alasql-testsuite

Reading on npm, gitignore and the whole ecosystem it seams like the node_module should not be included in the gitrepo, but must be `npm install` when cloning the repo (a new developer)

So its important that we keep the correct names in package.json for what other packages we use. 

If you upgrade the version in package.json just `npm update`
