### ISSUE TITLE
csv export on ipad not working

### ISSUE THREAD

**Issue by isaeed** [agershun/alasql#355]
it is working great on desktops but on ipad it only shows a blank window, any idea why ?

**Comment by mathiasrw** [comment]
You cant download files to the ipad. 

How would you like it to work?

How does og work with other files?

**Comment by mathiasrw** [comment]
Og = it

**Comment by isaeed** [comment]
it should work like any other file (excel or csv) we send as an email attachment and ipad browser successfully open/view that file.

**Comment by mathiasrw** [comment]
Could you post some example code?

**Comment by agershun** [comment]
I affraid that this is possible with Safary only for files generated from the server, not for the client. AlaSQL uses FileSaver.js library, and this problem is still not solved for iOS ([see here](https://github.com/eligrey/FileSaver.js#ios)). Sorry for that!

**Comment by mathiasrw** [comment]
Hmm. It says 

>  saveAs must be run within a user interaction event such as onTouchDown or onClick; setTimeout will prevent saveAs from triggering. 

isaeed: are you useing it async or on a interaction event? Its much easyer to help out if you post your code.

**Comment by mathiasrw** [comment]
@isaeed are you useing it async or on a interaction event? Its much easyer to help out if you post your code.

**Comment by isaeed** [comment]
sorry guys for late response, here is my scenario, 

user clicks a button on screen 'Export' , an async ajax request is sent to server (to fetch data), when data is fetched from server in a callback method, alasql.js export to csv method is called. and this is it , i guess it is much clearer now ? or need more clarification ?

**Comment by mathiasrw** [comment]
> saveAs must be run within a user interaction event such as onTouchDown or onClick

My best suggestion is that you fetch the data and when you have the response you show the user a nutton saying "Open CSV on Ipad" and based on the click on the button executes the export to excel command
