### ISSUE TITLE
idx not defined

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#356]
in https://github.com/agershun/alasql/blob/19f20ca8be0fe644ac27748394df7102a312aa0f/src/831xls.js#L129 the `idx` is not defined. Is the line to be deleted or corrected?

**Comment by agershun** [comment]
Fixed

**Comment by mathiasrw** [comment]
@agershun How do you compile the code? When I `gulp` (or just `npm test` to gulp + test) the version within alasql.js gets updated - but its not in https://github.com/agershun/alasql/commit/d0449d160977b6c723173ba07645c848c728ee50

Is it long time agoe you `git pull`ed ?

**Comment by agershun** [comment]
Three hours before. Sorry, I will check this tonight.

2016-01-11 16:39 GMT+03:00 Mathias Rangel Wulff <notifications@github.com>:

**Comment by mathiasrw** [comment]
3 hours should not be a problem... hmmm

**Comment by mathiasrw** [comment]
Must admit I have not checked the changes on windows. Do you compile on windows?

**Comment by agershun** [comment]
No. Now I use Mac only.

**Comment by mathiasrw** [comment]
hmmmmmmmmm

**Comment by agershun** [comment]
What is wrong?

**Comment by mathiasrw** [comment]
(im thinkin abaout whats wrong :) )
