### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#361]
@agershun I have prepared the travis-ci intergration. Please add alasql to travis-ci (only owners can add) 

https://travis-ci.org/profile/agershun

**Comment by agershun** [comment]
Done. See the mail. DO we need to do something more to turn it on?

**Comment by mathiasrw** [comment]
It will initiate the building as soon as we push new things to the different branches. I can already see that it's working for their develop branch. https://travis-ci.org/agershun/alasql

**Comment by mathiasrw** [comment]
https://travis-ci.org/agershun/alasql.svg?branch=develop

**Comment by agershun** [comment]
Cool!

2015-07-13 16:48 GMT+03:00 Mathias Rangel Wulff <notifications@github.com>:
