### ISSUE TITLE
help with AlaSQL

### ISSUE THREAD

**Issue by scotthathaway** [agershun/alasql#362]
Hi - I am not sure where to post questions for help.  If this is not the right area, please let me know.

I have the following code:

```
data = [{
    "Project":"proj1",
    "Baseline":{
        "Duration":34
    },
    "Timephasing":[
        {
            "Date":"2015-01-02",
            "Hours":{
                "Budget":350
            }
        },
        {
            "Date":"2015-01-03",
            "Hours":{
                "Budget":500
            }
        }
    ]
}]

result = alasql("select sum(Baseline->Duration) as dur, sum(Timephasing->Hours->Budget) as budget from ?",[data]);
```

The budget will not sum properly without specifying Timephasing->[0]->Hours->Budget, but I cannot know how many recs will be in the Timephasing area.  How can I sum all the timephasing records?  I also realize that I can pass in data['Timephasing'] to get at this lower level, but that requires two queries instead of one.  

Can you please help me?

Thanks,
Scott

**Comment by mathiasrw** [comment]
What are you expecting `sum(Baseline->Duration)` to return?

**Comment by scotthathaway** [comment]
Thanks for the fast reply!  the duration summation works fine.  It was only included to show that I need to sum multiple levels in the json.  The real problem I have is that I cannot figure out how to get all the Timphasing->Hours->Budget summed.  It gives an error.  I cannot specify the [0] position because I want all the records summed.  How can I do the budget summation?  The above example will only add 1 timephasing record instead of all of them.  I need them all included without knowing how many there will be.  I assume alasql can do this, but I cannot find any examples that are multiple levels deep in the json.

By the way, alasql is amazing.  You guys rock!

Thanks,
Scott

**Comment by mathiasrw** [comment]
We love feedback - thanks for letting us know that the library helps you :)

----

OK. I get it. You expect the result to be 

    [{dur: 34, budget: 850}]

right? 

I makes sense. Hmm. Think the best approach is to make your own function that returns the summed budget per row. Example: 

```js
alasql.fn.myfn = function(a,b) { return a*b+1; } 
alasql(‘SELECT myfn(a,b) FROM one’);
```

You need your own function to sum the budget -There are many ways to itterate an array, but it could be  something along the lines with:

```js
alasql.fn.sumBudget = function(row) { 
	var sum  = 0;
	row.forEach( function(item) {
		sum += item.Hours.Budget;
	});
	return sum;
}


data = [{
    "Project":"proj1",
    "Baseline":{
        "Duration":34
    },
    "Timephasing":[
        {
            "Date":"2015-01-02",
            "Hours":{
                "Budget":350
            }
        },
        {
            "Date":"2015-01-03",
            "Hours":{
                "Budget":500
            }
        }
    ]
}]

result = alasql("select sum(Baseline->Duration) as dur, sumBudget(Timephasing) as budget from ?",[data]);
```

Hmm. Tested the code and looks like nothing is passed to sumBudget. I think I need an input here...

Created https://github.com/agershun/alasql/issues/363 and will get back to you as soon as I figure it out.

**Comment by scotthathaway** [comment]
Thank you!  Let me know.

**Comment by mathiasrw** [comment]
OK - so looks like we need to tell alasql that there is a external `GROUP` - so the solution is to wrap `sumBudget` with `FIRST()` 


```sql
... FIRST(sumBudget(Timephasing)) as budget  from ?
```



Check a working example: http://jsfiddle.net/bc0r9ewy/1/

**Comment by mathiasrw** [comment]
Hmmm... this will merge all the results into one.... Its not solved yet. Ill dig deeper...

**Comment by mathiasrw** [comment]
Think what you are looking for is at 

http://jsfiddle.net/bc0r9ewy/5/
