### ISSUE TITLE
Passing array or object to user-defined function

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#363]
@agershun : Is there a special syntax for passing an array or object as parameter to a user defined function?

Please see http://jsfiddle.net/bc0r9ewy/ for example where the passed argument is undefined

**Comment by agershun** [comment]
Please see the working version [example](http://jsfiddle.net/bc0r9ewy/1/)

```sql
    select SUM(Baseline->Duration) as dur, FIRST(sumBudget(Timephasing)) as budget  from ?
```

The source of the problem that this is SELECT with hidden GROUP BY statement (because we use SUM() aggregator). Please, use FIRST() aggregator.

**Comment by mathiasrw** [comment]
Thanks ! :+1:

**Comment by mathiasrw** [comment]
This will merge all the results into one.... 

http://jsfiddle.net/bc0r9ewy/2/

It must output a row per input row.

**Comment by agershun** [comment]
Please, do not use aggregator for first column:
```js
    var res = alasql("select Baseline->Duration as dur, sumBudget(Timephasing) as budget  from ?",[data]);
```


See here: http://jsfiddle.net/bc0r9ewy/3/

**Comment by agershun** [comment]
My last example works in Chrome, but not in iPhone. To be analyzed

**Comment by mathiasrw** [comment]
Omg... so embarresing. Thanks for your help to see clear...
