### ISSUE TITLE
Alasql not working on Chrome and IE. Work perfectly in firefox

### ISSUE THREAD

**Issue by varungarg25** [agershun/alasql#370]
Hi,

I am trying to parse XLSX file using alasql.js but it only works with firefox. While running on Chrome and IE, it throws exception as "Cross Origin request not supported" and "Access Denied".Error is coming from XMLHttpRequest part of alasql.js code.Even if i access file using http://localhost, there is no data read. Works perfectly in firefix though. Any suggestions?

**Comment by nickdeis** [comment]
To my knowledge, Firefox is the only browser that allows reading via the file:// protocol.
How do you serve the file? Are you using a static file server?

**Comment by varungarg25** [comment]
I am trying to read excel files on my local machine. I have tried reading file via http://localhost as well. This way there is no error but there is no data read.

**Comment by mathiasrw** [comment]
It should work. Can you provide a sample of the code that is not working?

**Comment by mathiasrw** [comment]
@varungarg25 

If you already are having success with getting you HTML site with `http://localhost` I suggest you make sure to have the files you are trying to read in the same dir as your HTML to make sure you can access the files via `http://localhost/myAwesomeFile.zyx`
