### ISSUE TITLE
Data not remain on Postback of the page

### ISSUE THREAD

**Issue by alpeshpatel02** [agershun/alasql#372]
i have stored the data in different tables but when i refreshed the page all the tables is just deleted from the alasql. How can i worked with the tables that i have created until the browser closed down?

**Comment by agershun** [comment]
AlaSQL stores all information in memory. The only option to share the tables between different pages is to use LocalStorage or IndexedDB backend. 

Please see this part of documentation https://github.com/agershun/alasql/wiki/ATTACH
