### ISSUE TITLE
Get version from alacon

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#373]
Would be geat to be able to get the version of the alasql used at the commandline with 

    alasql -v

or 

    alasql -version

**Comment by agershun** [comment]
Currently AlaSQL stores the version in ```alasql.version``` variable. I will update alasql to perform this.

We can have two variant of the this option (we can use ```--``` like in git and other utilities.:
```bash
    > alasql -v
    > alasql --version
```

**Comment by mathiasrw** [comment]
:+1:

**Comment by agershun** [comment]
Done. To be tested.

I also added ```--file``` long version of the flag

**Comment by mathiasrw** [comment]
Cool!

It required `alasql.js` instead of `alasql` - so it could not run. I have pushed an updated version to develop. 

The -v and --version works perfect.

I have added that if wrong filename / no filename is given after -f/--file it will give you a kind "`File not found`"

Can I ask you to do a `git rm -r --cached node_modules/` on your local machine in the alasql folder in the develop branch?

**Comment by agershun** [comment]
1. Thank you for refreshing the code and ```process.exit()``` addictions :+1:  
2.  I performed:
```bash
    git rm -r --cached node_modules/
```

but the node_modules directory is still there. Should I clean it manually?

**Comment by mathiasrw** [comment]
Woop woop !

The `git rm -r --cached node_modules/` does not remove the files - but makes sure that files in `node_modules` are not tracked. 

As `node_modules/` are in the .gitignore the `node_modules` folder will be ignored when you `git add` 

So no need to delete - you actually need it to run :)

**Comment by mathiasrw** [comment]
Awwww - just saw that I had left a hardcoded path to the file to include. 

Hah...

Its fixed now :)
