### ISSUE TITLE
Download feature for excel: "We found a problem with some content..."

### ISSUE THREAD

**Issue by mg1075** [agershun/alasql#376]
When I run the download excel example, and then I open the excel file, excel (2013) is always giving me a warning that, 
> We found a problem with some content in '....xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes.

http://jsfiddle.net/agershun/00nfeq12/

**Comment by mathiasrw** [comment]
Thanks for a well documented error. 

@Agershun have you seen this before?

**Comment by miszczu** [comment]
I see the same warning as @mg1075 .
Also, after I click Yes, and click 'Enable editing' there is a popup with a message:
> Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.
> Repaired Records: Worksheet properties from /xl/workbook.xml part (Workbook)

**Comment by mathiasrw** [comment]
Thanks for letting us know. Looks like we have a general bug not related to the specific example. 

We are looking into it. 

Any help on what's wrong with the generates file is much appreciated...

**Comment by miszczu** [comment]
I found what is wrong in generated Excel file. 
Its worksheet is named `Sheet[object Object]`, which contains prohibited characters `[` and `]`.

I am not sure if it is supposed to be named like that (maybe a bug somewhere).
The file will open ok, when the worksheet has a proper name.

**Comment by mathiasrw** [comment]
You are awesome !!!

**Comment by miszczu** [comment]
You are welcome :) 

I have no time to prepare a proper pull request for this issue right now, I leave it to you guys.

Before it is implemented, a workaround is to just provide name (sheetid option) when calling export.
Like this:
> alasql('SELECT * INTO XLSX("filename.xlsx",{sheetid:"Sheet name",headers:true}) FROM ?',[data]);

**Comment by mathiasrw** [comment]
Found the source to the bug: https://github.com/agershun/alasql/commit/20ac08ca84cb0993d3060f0a13fdf5f8b8a1a780

Please use 
https://rawgit.com/agershun/alasql/11eb8f8a7424a5eb90c4c3a5cc41b1f55f239ef0/dist/alasql.min.js
while we prepare a new release

**Comment by mathiasrw** [comment]
Hmmm... this will merge all the results into one.... Its not solved yet. Ill dig deeper...

**Comment by jhoncue7** [comment]
@mathiasrw, Thank you for providing a link to a fixed version of the code.  Do you have any idea when a release including the fix will be pushed?

**Comment by mathiasrw** [comment]
Hmmm. Right now should be a good time. Ill have a chat with @agershun about pushing the updates.

**Comment by jhoncue7** [comment]
@mathiasrw, Thanks for pushing that release.

**Comment by mathiasrw** [comment]
👍🏼

**Comment by boygraceful** [comment]
hhhhhhhh kkkkkkkkk

**Comment by ShaikMoulali3** [comment]
Hey guys, 
Even I got the same issue while exporting the data to Excel using alasql.

The issue was with the null columns, I replaced the null columns with "NA" or "". 
Surprisingly the issue has resolved.

**Comment by mathiasrw** [comment]
omg!
