### ISSUE TITLE
Cannot ORDER BY a column that's not in the SELECT clause

### ISSUE THREAD

**Issue by workmad3** [agershun/alasql#379]
If you run a query like
```
alasql('SELECT a FROM ? ORDER BY id', [[{id:2,a:123},{id:1,a:null}]]))
```
the expectation is that the results should be ordered by the `id` value, even though they're not included in the result set. The reality is that the result will be unordered.

I've done some initial investigation into this, and the cause appears to be down to AlaSQL's ORDER BY function being passed a result row after it has been processed and only the columns in `SELECT` are left. This means that the compiled ORDER BY sorting function AlaSQL uses returns 'undefined' for all values, and an end result of no sorted columns.

**Comment by mathiasrw** [comment]
This is terrible. Thanks for the bug repport

```
JSON.stringify(alasql('SELECT a FROM ? ORDER BY id', [[{id:2,a:123},{id:1,a:null}]]))
"[{"a":123},{"a":null}]"
JSON.stringify(alasql('SELECT a, id FROM ? ORDER BY id', [[{id:2,a:123},{id:1,a:null}]]))
"[{"a":null,"id":1},{"a":123,"id":2}]"
```

@agershun any inputs on this?

**Comment by workmad3** [comment]
Just wondering if there's any idea on a solution or workaround for this? I've attempted to dig into the issue myself, but my understanding of what's happening under the hood for the `ORDER BY` compilation isn't good enough to figure out a solution :(

**Comment by mathiasrw** [comment]
I have heard nothng. Will ask Agershun again...

**Comment by agershun** [comment]
The only way to make this sort operation is to select and then remove unnecessary columns with ```REMOVE COLUMNS``` clause like below:
```js
    alasql('create table sun (a int, b int); insert into sun values (1,10),(2,5),(3,20);');
    var res = alasql('select a,b remove columns b from sun order by b');
```
or in your case:
```js
    var res = alasql('SELECT a, id REMOVE id FROM ? ORDER BY id', [[{id:2,a:123},{id:1,a:null}]]);
```
Here ```REMOVE```, ```REMOVE COLUMN``` and ```REMOVE COLUMNS``` are identical.

Sorry about that, but currently I see no way how to implement it... Probably, we can check these lost columns and then add them in SELECT and remove after ORDER BY operations...

**Comment by agershun** [comment]
@workmad3 Thank you very much and sorry for late answer! I did not know how to solve this issue before, but now I have got idea :)

**Comment by mathiasrw** [comment]
Nice work. 

I have updated the testcase so that we use Mocha as its ment. [Have a look](https://github.com/agershun/alasql/commit/b75a29b95664971dfd1155bba40e03f214a1080a)

I placed the setup and teardown like this:


```js
  before(function(){
    alasql('CREATE DATABASE test412; USE test412');
  });

  after(function(){
     alasql('DROP DATABASE test412');
  });
```

by placing them together in the beginning it makes it easy to see if we are cleaning everything up that we created

**Comment by agershun** [comment]
Yahoo! I didi it! Now your example works fine! See [test412.js](https://github.com/agershun/alasql/blob/develop/test/test412.js)

**Comment by mathiasrw** [comment]
Niiiice :)

**Comment by workmad3** [comment]
@agershun Awesome! Thanks for not giving up, I'll be sure to pull down the next version and let my users know the issue is fixed :)

**Comment by agershun** [comment]
@workmad3 David, thank you for this. Believe me, I did not know how to do it, before your right question :)

**Comment by digeomel** [comment]
Uhm, maybe I didn't understand this, but why is this issue closed? I just tried a query with "SELECT *" and ordering doesn't work. So, imho the issue should remain open with the suggested workaround (i.e. using REMOVE COLUMNS).
