### ISSUE TITLE
FETCH is not working

### ISSUE THREAD

**Issue by seal713** [agershun/alasql#391]
Hi,

It seems that fetch is not supported for alasql? Can anyone help confirm here?

Example:
select * from cities limit 10 fetch 0

Console error:
Uncaught Error: Parse error on line 1:
...rom cities limit 10 fetch 0
-----------------------^
Expecting 'LITERAL', 'BRALITERAL', 'EOF', 'EndTransaction', 'WITH', 'COMMA', 'AS', 'LPAR', 'RPAR', 'SEARCH', 'REMOVE', 'LIKE', 'ORDER', 'ARROW', 'CARET', 'EQ', 'WHERE', 'CLASS', 'NUMBER', 'STRING', 'SLASH', 'VERTEX', 'EDGE', 'EXCLAMATION', 'SHARP', 'MODULO', 'GT', 'LT', 'DOLLAR', 'DOT', 'AT', 'SET', 'TO', 'VALUE', 'ROW', 'COLON', 'NOT', 'IF', 'UNION', 'ALL', 'ANY', 'INTERSECT', 'EXCEPT', 'AND', 'OR', 'PATH', 'RETURN', 'REPEAT', 'PLUS', 'STAR', 'QUESTION', 'FROM', 'DISTINCT', 'UNIQUE', 'SELECT', 'INTO', 'CROSS', 'OUTER', 'NATURAL', 'JOIN', 'INNER', 'LEFT', 'RIGHT', 'FULL', 'SEMI', 'ANTI', 'ON', 'USING', 'GROUP', 'HAVING', 'DIRECTION', 'COLLATE', 'LIMIT', 'OFFSET', 'CURRENT_TIMESTAMP', 'JAVASCRIPT', 'NEW', 'CAST', 'CONVERT', 'SUM', 'COUNT', 'MIN', 'MAX', 'AVG', 'FIRST', 'LAST', 'AGGR', 'ARRAY', 'TRUE', 'FALSE', 'NSTRING', 'NULL', 'EXISTS', 'BRAQUESTION', 'CASE', 'END', 'WHEN', 'THEN', 'ELSE', 'NOT_LIKE', 'MINUS', 'GE', 'LE', 'EQEQ', 'EQEQEQ', 'NE', 'NEEQEQ', 'NEEQEQEQ', 'IN', 'BETWEEN', 'NOT_BETWEEN', 'IS', 'DOUBLECOLON', 'UPDATE', 'DELETE', 'INSERT', 'DEFAULT', 'CREATE', 'IDENTITY', 'CHECK', 'PRIMARY', 'FOREIGN', 'REFERENCES', 'DROP', 'ALTER', 'RENAME', 'ATTACH', 'DETACH', 'USE', 'SHOW', 'HELP', 'SOURCE', 'ASSERT', 'ATLBRA', 'LCUR', 'RCUR', 'RBRA', 'COMMIT', 'ROLLBACK', 'BEGIN', 'WHILE', 'CONTINUE', 'BREAK', 'PRINT', 'REQUIRE', 'ECHO', 'DECLARE', 'TRUNCATE', 'MERGE', 'OUTPUT', 'CONTENT', 'COLONDASH', 'QUESTIONDASH', 'SEMICOLON', 'GO', 'PERCENT', got 'FETCH'

Many thanks,
Seal

**Comment by agershun** [comment]
Try to use LIMIT instead FETCH

Отправлено с iPhone

**Comment by agershun** [comment]
I will add FETCH as standard keyword here

Отправлено с iPhone

**Comment by agershun** [comment]
Sorry, it should be LIMIT 10 OFFSET 20 or OFFSET 20 LIMIT 10

Отправлено с iPhone

**Comment by agershun** [comment]
The correct answer is
```sql
    SELECT c1 FROM table LIMIT 2 OFFSET 2 
```
Please, see [the example](http://jsfiddle.net/efn1yoer/1/)

If it a realy required we can implement more T-SQL expression, like:
```sql
    SELECT DepartmentID, Revenue, Year
    FROM REVENUE
    ORDER BY Year, DepartmentID ASC
    OFFSET 10 ROWS
    FETCH NEXT 10 ROWS ONLY;
```

**Comment by agershun** [comment]
I changed parser file (now it is in ```develop``` branch), now you can also use T-SQL notation
```sql
    SELECT * FROM cities OFFSET 10 FETCH 0
    -- or
    SELECT * FROM cities OFFSET 10 ROWS FETCH NEXT 20 ROWS
```

**Comment by seal713** [comment]
Looks like it is working!! Appreciated for such quick feedback, Agershun!

**Comment by mathiasrw** [comment]
:+1:
