### ISSUE TITLE
Add REGEXP and LIKE_REGEXP functionality

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#396]

**Comment by agershun** [comment]
Just added REGEXP operator and REGEXP_LIKE() functions.

**Comment by mathiasrw** [comment]
Is one an alias or is the result different?

**Comment by agershun** [comment]
No, they are different (REGEXP is an operator, but REGEXP_LIKE(string, pattern, options) is a function)
```sql
    SELECT "abcd" REGEXP "a.c."
    SELECT REGEXP_LIKE("ABCD","ab","i")
```

**Comment by mathiasrw** [comment]
In the test you made I see

    	assert(!alasql('= REGEXP_LIKE("abcdef","^d")'));

What is that notation with '='?

Does it always work?

Will I be able to do a 

    WHERE name REGEXP_LIKE ".*sen$"

?

**Comment by agershun** [comment]
```
       = expression
```
is AlaSQL operator. It is equavalent of
```sql
    VALUE OF SELECT expression
```
It simply returns the result of evaluation of expression.

**Comment by agershun** [comment]
No, you can not do:
```sql
WHERE name REGEXP_LIKE ".*sen$"
```
Please use this:
```sql
    WHERE REGEXP_LIKE(name, ".*sen$")
```
or 
```sql
```sql
    WHERE name REGEXP  ".*sen$"
```

**Comment by mathiasrw** [comment]
Ahhhh - i get ik. 

Are you sure we dont want to switch the two so regexp is the funktion while regexp_like has the same notation as LIKE

**Comment by mathiasrw** [comment]
Another input: coul have regexp as funktion but then the keywords LIKE_REGEXP for the expression because it begaves like LIKE but its a special case where the styring is a regexp?

**Comment by agershun** [comment]
The reason is simple:
* REGEXP is MySQL notation
* REGEXP_LIKE() is Oracle one

Also Postgres has some other operators, like: ```SIMILAR TO``` and ```~``` (see [here](http://www.postgresql.org/docs/9.3/static/functions-matching.html)). Let's do it but only after user requests?

**Comment by mathiasrw** [comment]
Makes perfect sense. 

Good work !

**Comment by mathiasrw** [comment]
Interesting woth the ~ notation. 

And also the POSIX pattern language - never heard of it before
