### ISSUE TITLE
NPM install dependency on JSzip

### ISSUE THREAD

**Issue by kcsang** [agershun/alasql#399]
Hi,

I am trying to install the latest version of alasql using npm but it had dependency on jszip 2.4.0 which is not available in npm. Can you please let me know how to resolve this?

Because of the dependency, I have to use version  0.0.49 which doesn't allow export in xlsx format. Can you please suggest on that also?

**Comment by mathiasrw** [comment]
Hmmm. Interesting. 

Would it be possible for you to copy the output from the npm installation. It must be a subdependency and would really like to know what dependencie is creating trouble...

**Comment by kcsang** [comment]
hi,

Below is the output of npm install 

npm ERR! fetch failed http://npm.software.services.gs.com/nexus/content/groups/npm/jszip/-/jszip-2.4.0.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (c:\PROGRA~1\nodejs\node_modules\npm\lib\utils\fetch.js:58:12)
npm ERR!     at WriteStream.emit (events.js:117:20)
npm ERR!     at evalmachine.<anonymous>:1610:14
npm ERR!     at c:\PROGRA~1\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:108:15)

With version - 0.0.49,  I couldn't export to xlsx, that threw "Cannot read property 'write' of undefined"

**Comment by mathiasrw** [comment]
Sorry for not getting back to you. The real world was calling. 

It looks to me like there a global module called graceful-fs that has a depricated dependency. 

Could I ask you to 

     npm update -g

to see if the problem persists?

When I make a clearn install this is what I get

```bash
➜  tmp  npm install alasql
alasql@0.2.0 node_modules/alasql
├── dom-storage@2.0.1
├── es6-promise@2.3.0
├── lodash@3.10.1
├── xlsjs@0.7.5 (cfb@0.10.3, commander@2.8.1, ssf@0.8.2, codepage@1.3.8)
└── xlsx@0.8.0 (adler-32@0.2.1, crc-32@0.3.0, cfb@0.10.3, commander@2.8.1, ssf@0.8.2, jszip@2.4.0, codepage@1.3.8)
➜  tmp
```

**Comment by mathiasrw** [comment]
Closed due to inactivity. Please reopen if it still relevant.
