### ISSUE TITLE
Add CSS properties for HTML() into-function

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#40]
Based on question from StackOverflow: [Set condition for innerHTML of a table](http://stackoverflow.com/questions/27889605/set-condition-for-innerhtml-of-a-table)

If you use HTML() function it is a good idea to give a functionality to change a color or alignment of result cells. Something like:

```js
    alasql('SELECT TOP 10 City \
                    TH {style:{textAlign:"right",textContent:"Town"}}  \
                    TD {color:(CASE WHEN Population > 1000000 THEN "red" ELSE "green" END)} \
               INTO HTML("#res") FROM ? ORDER BY Population DESC',[cities]);
```

The information, required for table formatting:

* Column width
* Column header
* TH class
* TD class

Another option: use Alasql together with [Handsontable grid](http://handsontable.com/), like:
```js
    alasql('SELECT * INTO HOT("#res") FROM ?',[City]);
```

**Comment by agershun** [comment]
"And i want to ultimately achieve the exported excel file's header format like changing color, font style etc,. Is it possible by using alasql to do this. Expecting your valuable response as soon as possible."

I have got great idea how to change Excel file, and will write this later. It will looks like this:
```
    var x = alasql('SELECT * INTO XLSX() FROM ?'.[data]);
    x.Sheets['Sheet1'].cells['A1'].value = 10;
    alasql.saveBinaryFile(x);
```

**Comment by mathiasrw** [comment]
Mixing css and SQL. Hmmm. Would it be better to be able to set class of the table, the header row, the header cells (according to content), the data row and the data cells (according to content)?

**Comment by agershun** [comment]
I already have some insights this night :))))) To solve this problem (it was requested by many people) I opened another repository, for the library which can export data to XLS file with formats and colors.

https://github.com/agershun/alaxls

This library will work with AlaSQL something like:
```js
    alasql('SELECT a TH {class:"header"} TD {class:IF(a>=0,"positive","negative")} \
             INTO ALAXLS('myfile.xls',{headers:true, headerrange:"B1", rowsrange:"D1" }) FROM ?',[data]);
```
Plus people can save JavaScript arrays without ```alasql.js``` on AlaSQL manner (with SaveFile buttons support):
```js
    alaxls.saveFile('myfile.xls',data,options);
```
And it can work together with [js-xlsx.js](https://github.com/SheetJS/js-xlsx) library as export function with colors and formats.

Hope it will take day or two to rewrite existing code to the library.

**Comment by agershun** [comment]
Alternative idea of syntax:
```js
    var opts = {
         sheetid: 'Sheet1',
         thclass: 'header',
         tdclass: 'cell',
         columns: [
              { 
                   columnid: 'a', tdstyle: function(row, column, value) {
                         if(value < 0) return "background-color:red; color:white"
                    },
                   width: 200
              } ,
             {
                   columnid: 'b', title: 'Amount', style: 'font-wight: bold'
             }
         ],
         caption: 'My Data',
         caprange: 'A1',
         thrange: 'B1',
         tdrange: 'D1',
         css: '.header {color:yellow} .cell {color:blue} .caption: {font-size:200px}'
    };
    
    var data = [{a:1, b:10},{a:2,b:20}];
    alasql('SELECT * INTO ALAXLS("myfile.xlsx",?) FROM ?',[data,opts]);
```

**Comment by mathiasrw** [comment]
Really like this approach

**Comment by agershun** [comment]
Agree, it is more universal than to extend SQL and it can live without AlaSQL and js-xlsx. 

Plus it can be used outside AlaSQL with one simple function:
```js
    var xml = alaxls(undefined, options); // return XML with data
    var xml = alaxls(options);                   // return XML with data
    alaxls(filename, options);                   // save file to the disk
```
Where filename is:
* path to the file (in Node.js)
* in browser it will open a Save File dialog
* if starts with # then send result to the proper DIV of DOM

Options:
* caprange
* thrange
* tdrange
* caption
* capclass
* thclass
* tdclass
* class
* capstyle
* thclass
* tdstyle
* columns
 * width
 * title
 * class/style...
* format
* formatStyle: - Excel format

Each element can be a function or value (string or number).

    tdstyle: function(row,columnid, value) {
          return 'color:red';
    }

Other options:
* format: 'xml'/'html table'
* sourcexml: xml-string
* query: '#id' - place in source xml where to put table

**Comment by agershun** [comment]
Another option: use as a source [ExcelJS](https://github.com/guyonroche/exceljs) library. Unfortunately, it works with Node.js only.

**Comment by agershun** [comment]
I think that there is no need to create additional XLSX function. Probably, It is better to:
a) replace js-xlsx for export function (this is not to hard)
b) create an option to use js-xlsx or alaxls, like: 
```js
    alasql('SELECT * INTO XLSX("mydata.xlsx",{engineid:"ALAXLS",headers:true})");
```
or 
```js
    alasql.options.XLSX.engineid = "ALAXLS";
    alasql.options.XLSX.engineid = "js-xlsx";
    alasql('SET XLSX = ALAXLS;");
```

**Comment by SheetJSDev** [comment]
@agershun have you looked at how Excel represents the HTML?  On OSX, we have a neat little tool to inspect the clipboard: https://www.npmjs.com/package/pb -- you can play with it in Excel 2011 by copying a block of cells and running `pb html` to see the html clipboard.

You don't actually have to generate inline styles for every cell.  Excel actually emits CSS classes and uses them in the code (with names like `.xl63` -- that number actually corresponds to the internal style number in XLS and XLSX).  This way, the user could supply his or her own template CSS with standard class names like `col1`

**Comment by agershun** [comment]
@SheetJSDev Thank you for the  link!  I need to think about it a little, and write you. I just have finished night run for coloring cells, and have many questions to discuss after day sleep :)

Great news!
===
Yes, yes, yes, I did it:, I add colors to XLS() function on very primitive way. 

 http://jsfiddle.net/agershun/95j0txwx/2/

How it works:
* XSL() uses own very simple engine with many restrictions and does not use js-xlsx library. Actually it simply saves table in one HTML format without GZIpping, etc.
* XLSX() uses more advanced engine (js-xlsx), but it does not support colors and styles (probably, i would like to discuss it with SheetJS developers how to implement this functionality with library) 

This is example of style syntax:
```js
    var opts = {
        sheetid: 'My Big Table Sheet',
        headers: true,
        caption: {
          title:'My Big Table',
          style:'font-size: 50px; color:blue;' // Sorry, styles do not works
        },
        style:'background:#00FF00',
        column: {
          style:'font-size:30px'
        },
        columns: [
          {columnid:'email'},
          {columnid:'dob', title: 'Birthday', width:300},
          {columnid:'name'},
          {
            columnid:'name',
            title: 'Number of letters in name',
            width: '300px',
            cell: {
              value: function(value){return value.length}
            }
          },
        ],
        row: {
          style: function(sheet,row,rowidx){
            return 'background:'+(rowidx%2?'red':'yellow');
          }
        },
        rows: {
          4:{cell:{style:'background:blue'}}
        },
        cells: {
          2:{
            2:{
              style: 'font-size:45px;background:pink',
              value: function(value){return value.substr(1,3);}
            }
          }
        }
    };

    var res = alasql('SELECT * INTO XLS("restest257b.xls",?) FROM ?',[opts,items]);
```
Friends, any feedback is very appreciated!

**Comment by agershun** [comment]
@SheetJSDev I installed the package. Thank you! Now many things looks more clearly.

In this simple realization I used very lazy approach (without styles, gzipping, etc.). It is rather a simple concept of spreadsheet template.I still didn't learn how to add colors and styles to js-xlsx, but would like to to move this 'temporary realization' back to js-xlsx to reduce support work.

**Comment by agershun** [comment]
Now AlaSQL can save files to Excel and LibreOffice formats with colors and other
Excel formatting functions. This function also work in IE9. This is a code sample:

```js
    var mystyle = {
      headers:true, 
      column: {style:{Font:{Bold:"1"}}},
      rows: {1:{style:{Font:{Color:"#FF0077"}}}},
      cells: {1:{1:{
        style: {Font:{Color:"#00FFFF"}}
      }}}
    };
    alasql('SELECT * INTO XLSXML("restest280b.xls",?) FROM ?',[mystyle,data]);
```
See the working example in [jsFiddle](http://jsfiddle.net/95j0txwx/7/)
