### ISSUE TITLE
SELECT with INNER JOIN always gets same result (even after new inserts)

### ISSUE THREAD

**Issue by pboos** [agershun/alasql#402]
It seems like if doing joins the result will get cached. It has to do with the source.optimization='ix'. So even after inserting new items, the result will not show them. It will just return the first one always. 

#### Reproduce

Here is an example [run on jsfiddle](http://jsfiddle.net/9fnq9a15/1/):
```
alasql('CREATE localStorage DATABASE IF NOT EXISTS test');
alasql('ATTACH localStorage DATABASE test');
alasql('USE test');

alasql('CREATE TABLE IF NOT EXISTS users (id number PRIMARY KEY, name string)');
alasql('CREATE TABLE IF NOT EXISTS user_items (id number PRIMARY KEY, user_id number, item string)');

alasql('DELETE FROM user_items;');
alasql('DELETE FROM users;');

alasql('INSERT INTO users (id, name) VALUES(1, \'test\')');

alasql('INSERT INTO user_items (id, user_id, item) VALUES(1, 1, \'item1\')');

console.log(alasql('SELECT users.*, user_items.* FROM users JOIN user_items ON user_items.user_id=users.id'));

alasql('INSERT INTO users (id, name) VALUES(2, \'test2\')');

alasql('INSERT INTO user_items (id, user_id, item) VALUES(2, 2, \'item2\')');

console.log(alasql('SELECT users.*, user_items.* FROM users JOIN user_items ON user_items.user_id=users.id'));
console.log(alasql('SELECT * from users;'));
```

In this example you see exactly, that the select after the insert just returns exactly the same result and just ignores the newly inserted rows.

#### Our current workaround:
We currently fixed it for us by just uncommenting the lines containing the following:
```
source.optimization = 'ix';
```
*0.2.0 - alasql.js - lines 8054 + 8061*

Of course this might have negative effects on speed, but for us better than not being able to retrieve the new data.

**Comment by agershun** [comment]
@pboos Thank you! I will check this problem.

**Comment by mathiasrw** [comment]
@agershun 

I see that `source.optimization` set to `'ix'` at both 

https://github.com/agershun/alasql/blob/f0fcd1d8e9edd29b4035ccd3ddd46cd0cd554e78/src/421join.js#L284

and 
https://github.com/agershun/alasql/blob/f0fcd1d8e9edd29b4035ccd3ddd46cd0cd554e78/src/421join.js#L291

what is the relation? Is there any other value `source.optimization` can have?

**Comment by bjornblomqvist** [comment]
I am having the same problem. Here is maybe a bit simpler code snippet to trigger the bug.

    alasql("create table someNames (name string)");
    alasql("create table otherNames (name string)");

    alasql('select * from otherNames join someNames on someNames.name = otherNames.name');

    alasql('insert into someNames values ("Lars"), ("Erik")');
    alasql('insert into otherNames values ("Lars"), ("Erik")');

    console.debug(alasql('select * from otherNames join someNames on someNames.name = otherNames.name').length == 2);

Comment out the first query to have it print true on the console.

**Comment by bjornblomqvist** [comment]
@mathiasrw it looks like indexs are created if ```source.optimization``` is set to ```'ix'```.

The problem looks to be that indexs are not discarded when tables are set as dirty.

**Comment by mathiasrw** [comment]
@bjornblomqvist I have merged in your pull request - thanks for the time you took to look into it...

Let me know if its too early to close
