### ISSUE TITLE
IE8 issue

### ISSUE THREAD

**Issue by umer-farooq** [agershun/alasql#403]
I am using alasql.min.js on IE 8 browser,it throwing me an error 'Expected identifier', but it working fine on IE10, chrome and firefox, is it a compatibility issue or do you have the workaround for this

**Comment by agershun** [comment]
Could you provide the sample of the code or SQL statement where AlaSQL raise the error?

**Comment by umer-farooq** [comment]
Here is the sample below, you can include alassql.min.js and path on line 4

<html>
<head>
<title>Alas Hello World</title>
<script type="text/javascript" src="scripts/alasql.min.js"></script>
</head>
<body>
TEST JOIN
<span id="testjoin"></span>
<br/>
TEST MULTIPLE JOIN
<span id="testmultiplejoin"></span>
<br/>
TEST WHERE
<span id="testwhere"></span>
<br/>
TEST UNION
<span id="testunionjoin"></span>
<br/>
TEST LEFT JOIN
<span id="testleftjoin"></span>
<br/>
TEST AGGREGATE
<span id="testagg"></span>
<br/>
<script type="text/javascript">
        var cars = {'Models' : [{model:'Mazda', price:20000}, {model:'Toyota', price:25000}, {model:'Ford', price:22000},{model:'Suzuki',pirce:50000}],'Cars' : [{model:'Mazda', color:'Blue'}, {model:'Toyota', color:'Red'},{model:'Ford', color:'White'}]};

	   var employee = {'Employee' : [{emp_id:1,emp_name:'James',salary:2000},{emp_id:2,emp_name:'Jack',salary:4000},{emp_id:3,emp_name:'Henry',salary:6000},{emp_id:4,emp_name:'Tom',salary:8000}],'Department': [{dept_id:101,dept_name:'Sales'},{dept_id:102,dept_name:'Marketing'},{dept_id:103,dept_name:'Finance'}],'Register': [{emp_id:1,dept_id:101},{emp_id:2,dept_id:102},{emp_id:3,dept_id:103},{emp_id:4,dept_id:104}]};
	   
	   var supplier = {'Supplier' : [{supplier_id : 1000,supplier_name : "Microsoft"},{supplier_id : 2000,supplier_name : "Oracle"},{supplier_id : 3000,supplier_name : "Apple"},{supplier_id : 4000,supplier_name : "Samsung"}], 'Orders': [{order_id : 1,order_date : '2015-08-01',supplier_id : 1000},{order_id : 2,order_date : '2015-08-01',supplier_id : 2000},{order_id : 3,order_date : '2015-08-02',supplier_id : 7000},{order_id : 4,order_date : '2015-08-03',supplier_id : 8000}]};
	   
	   
	   var phase = { 'Phase' : [ { Phase: "Phase 1", Step: "Step 1", Task: "Task 1", Value: "5" },{ Phase: "Phase 1", Step: "Step 1", Task: "Task 2", Value: "10" },{ Phase: "Phase 1", Step: "Step 2", Task: "Task 1", Value: "15" },{ Phase: "Phase 1", Step: "Step 2", Task: "Task 2", Value: "20" },{ Phase: "Phase 2", Step: "Step 1", Task: "Task 1", Value: "25" },{ Phase: "Phase 2", Step: "Step 1", Task: "Task 2", Value: "30" },{ Phase: "Phase 2", Step: "Step 2", Task: "Task 1", Value: "35" },{ Phase: "Phase 2", Step: "Step 2", Task: "Task 2", Value: "40" }]};
	   
       var res1 = alasql("SELECT * FROM ? set1 JOIN ? set2 on set1.model=set2.model",[cars.Models,cars.Cars]);
	   var res2 = alasql("SELECT emp_name, dept_name FROM ? e JOIN ? r ON e.emp_id=r.emp_id JOIN ? d ON r.dept_id=d.dept_id",[employee.Employee,employee.Register,employee.Department]);
	   
	   var res3 = alasql("SELECT * FROM ? set1 JOIN ? set2 on set1.model=set2.model where set1.price > 20000",[cars.Models,cars.Cars]);
	   
	   var res4 = alasql("SELECT supplier_id FROM ? set1 UNION select supplier_id FROM ? set2 ORDER BY supplier_id",[supplier.Supplier,supplier.Orders]);
	   
	   var res5 = alasql("SELECT CASE WHEN set2.supplier_id IS NULL THEN '' ELSE supplier_id END as supplier_id,order_date FROM ? set1 LEFT OUTER JOIN ? set2 on set1.supplier_id=set2.supplier_id",[supplier.Orders,supplier.Supplier]);
	   
	   var res6 = alasql('SELECT Phase, Step, SUM(CAST([Value] AS INT)) AS [Value] FROM ? GROUP BY Phase, Step',[phase.Phase]);
	   
	   
       var test1= JSON.stringify(res1);
       var test2= JSON.stringify(res2);
	   var test3= JSON.stringify(res3);
	   var test4= JSON.stringify(res4);
	   var test5= JSON.stringify(res5);
	   var test6= JSON.stringify(res6);
	   
 document.getElementById("testjoin").innerHTML = test1;
 document.getElementById("testmultiplejoin").innerHTML = test2;
 document.getElementById("testwhere").innerHTML = test3;
 document.getElementById("testunionjoin").innerHTML = test4;
 document.getElementById("testleftjoin").innerHTML = test5;
 document.getElementById("testagg").innerHTML = test6;
</script>
</body>
</html>

**Comment by agershun** [comment]
Thank you! Unfortunately, I have no IE 8 at the moment, hope I can check this problem on this week.

**Comment by umer-farooq** [comment]
Thanks, looking forward for your response

**Comment by nickdeis** [comment]
If you have IE, you can switch the JS VM version by using the F12 dev tools.
Seems like there could be a few issues, but I'm picking up on this one:
When an object has a property that's a keyword:
```js
case 425:
 this.$ = new yy.Insert({into:$$[$0-2], default: true}) ; 
```
it breaks.
The workaround is simple
```js
case 425:
 this.$ = new yy.Insert({into:$$[$0-2], "default": true}) ;
```

**Comment by mathiasrw** [comment]
I have implemented your suggestion - please see if this file works out better

https://github.com/agershun/alasql/blob/1cd5b7949f3e244dfcd9afa88b57aa6e9f62fb9f/dist/alasql.js

(had no idea that `default` was a js keyword...)

**Comment by nickdeis** [comment]
Not sure how to test this (other than running tests in IE8, which I tried to do) but I added gulp-dereserve to the build.
