### ISSUE TITLE
How can I customize header with chinese?

### ISSUE THREAD

**Issue by alexcc4** [agershun/alasql#404]
Hello, I'm using alasql to export data to XLSX now。 When I want to customize column title with chinese, using plain sql like 'SELECT id AS 身份' INTO XLSX("test.xlsx", ?) FROM ?'   or 'select id as "身份"', it raises error:  "Error: Parse error on line 1:" or "s.replace is not a function". Any solution? Thanks.

**Comment by mathiasrw** [comment]
Hmmm. Interesting. 

Seams like we have an UTF8 issue here. 

Thanks for letting us know. I will try to make some tests to see where the problem is located

**Comment by agershun** [comment]
Could you try this ( ```[ ]``` with your name):
```
    SELECT id AS [身份]' INTO XLSX("test.xlsx", ?) FROM ?
```

**Comment by alexcc4** [comment]
@agershun Awesome. It works! Maybe it's a trick rarely known, caused by UTF8. For more language supporting(for me , Chinese, haha), I do hope UTF8 issue solved.
Thanks all.

**Comment by agershun** [comment]
This is not a trick, but the standard functionality. You can use this approach to use spaces, other punctuation characters, and other UTF8 characters. Thank you for the question!

Отправлено с iPhone

**Comment by mathiasrw** [comment]
@agershun I getting this into the documentation. I dont understand the ´'´ after `[身份]'` what is the point of this one?

**Comment by agershun** [comment]
This is a mistake... Just square-brackets ``` [lalala] ``` or back-quotes ``` `lalala` ```

**Comment by mathiasrw** [comment]
:+1:
