### ISSUE TITLE
We have facing a problem while reading dates column from xls/xlsx files.

### ISSUE THREAD

**Issue by cksiva2007** [agershun/alasql#405]
Hi, 
      We have facing a problem while reading dates column from xls/xlsx files. I am using the following query to read data from xls but all the date column of xls data automatically converted into numeric.

alasql query:

alasql('SELECT * FROM FILE(?,{headers:true})', [event], function (res) { });

**Comment by mathiasrw** [comment]
Please provide an example file - it might be the file that contains the value af number and not text

**Comment by mathiasrw** [comment]
Closed due to inactivity. Please reopen if still relevant.
