### ISSUE TITLE
IN (SELECT ...)

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#407]
for AlaSQL 

    alasql 'select 1 in (select 1) as x'

gives an error but I would have expected `true` 

----

Bonusinfo: For SQLite the command

    select 1 in (select 1) as x

returns `1`

**Comment by agershun** [comment]
Fixed (same problem as https://github.com/agershun/alasql/issues/469). Test was added to the test387.js

**Comment by mathiasrw** [comment]
:+1:
