### ISSUE TITLE
MAX/MIN function not working for words

### ISSUE THREAD

**Issue by trittberg** [agershun/alasql#411]
Apparently, using JSON table data, and aggregating the entire table into one record (no GROUP BY):
the SUM function works fine, but
the MAX/MIN functions return "undefined"
and the GREATEST/LEAST functions return 0.

Here is a sample of the data I use:

```
[ {field1: value1, field2:value2} ],
[ {fieldA: valueA, fieldB: valueB} ]
```

Am I doing something wrong or are the functions incomplete?

Thanks,
Timm

**Comment by trittberg** [comment]
Sorry, by data example was wrong ... more like

[ {field1: value1, field2: value2} ],
[ {field1: valueA, field2: valueB} ]

Sorry,
Timm

**Comment by mathiasrw** [comment]
Hey @trittberg - please provide your SQL so we can help you debug...

**Comment by trittberg** [comment]
Hi Mathias

Here is my dilemma.

SQL: "SELECT MAX(text) AS text FROM ?"
DATA: [{"text":"ConfigPanel","value":"ConfigPanel"},{"text":"ConfigPanelEdit","value":"ConfigPanelEdit"},
... ]
RESULT: alasql(SQL, [data])[0].text = undefined

Please see the attachment for SQL, data and result details.

Thanks,
Timm

On 14 September 2015 at 02:47, Mathias Rangel Wulff <
notifications@github.com> wrote:

> Hey @trittberg <https://github.com/trittberg> - please provide your SQL
> so we can help you debug...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agershun/alasql/issues/411#issuecomment-140019955>.
>



-- 
Cheers,
Timm

**Comment by mathiasrw** [comment]
The implementation does not let  `min`and `max` handle other values than numbers

```
sql = "SELECT max(text) as text FROM ?"
data = [{"text":"2","value":"ConfigPanel"},{"text":"5","value":"ConfigPanelEdit"}]
console.log(JSON.stringify(alasql(sql, [data])))
// [{"text":5}]

sql = "SELECT max(text) as text FROM ?"
data = [{"text":"abc","value":"ConfigPanel"},{"text":"def","value":"ConfigPanelEdit"}]
console.log(JSON.stringify(alasql(sql, [data])))
// [{}]
```

Im not sure how other databases handles `min`and `max` - but we will have to look into it. 

I recommend you order and limit to one to get the same result with text 

``` 
sql = "SELECT text as text FROM ? ORDER BY text DESC LIMIT 1"
data = [{"text":"abc","value":"ConfigPanel"},{"text":"def","value":"ConfigPanelEdit"}]
console.log(JSON.stringify(alasql(sql, [data])))
// [{"text":"def"}]
```

**Comment by trittberg** [comment]
Ah, that's the issue. I am also an ms sql server guy, so i didn't know
about the limit command.  I'm used to select top. I will try your
solution.  Thank you.

Timm

**Comment by mathiasrw** [comment]
Good to know you could use the answer... AlaSQL also supports the MSSQL notation:

```
sql = "SELECT TOP 1 text FROM ? ORDER BY text DESC"
data = [{"text":"abc","value":"ConfigPanel"},{"text":"def","value":"ConfigPanelEdit"}]
console.log(JSON.stringify(alasql(sql, [data])))
// [{"text":"def"}]
```

**Comment by rahulraj-120799** [comment]
MONTHNAME(), GETDATE is not working in alasql
