### ISSUE TITLE
alasql is not defined with requireJS, can anyone please let me know what is the Exact issue.

### ISSUE THREAD

**Issue by hsHemant** [agershun/alasql#417]
I am using this code:

define(
		[ 'angular', 
		  'controllers-module',		  
		  '../../../../../bower_components/alasql/dist/alasql.js'],
		function(angular,
				controllers,
				alasql
				) {

**Comment by hsHemant** [comment]
further if I trigger alasql function that error comes.

TypeError: Cannot read property 'write' of undefined.
I am using AngularJS with RequireJS. I think RequireJS here unable to load the dependency.

**Comment by ThinklabsGbR** [comment]
please see:

https://github.com/agershun/alasql/wiki/Angular.js

"You can use AlaSQL together with Angular.js framework. Please include the file normally and not via requireJS"

**Comment by hsHemant** [comment]
Thanks ThinklabsGbR, Its working for me.

But, one suggestion for the guys who will gonna use it in the same scenario.
Please include alasql before requireJS. Like This:

<script src="../../bower_components/alasql/dist/alasql.js"></script>
<script src="../../bower_components/js-xlsx/dist/xlsx.core.min.js"></script>

<script src="../../bower_components/requirejs/require.js"></script>

Otherwise, that will cause a issue of "Mismatched anonymous define() module". This issue is with requireJS.

ThinklabsGbR, I hop soon we will see this awesome JS library with requireJS compatibility.

**Comment by mathiasrw** [comment]
@ThinklabsGbR  thanks for a quick answer...
