### ISSUE TITLE
SQL keyword and row names (eg. "count")

### ISSUE THREAD

**Issue by dirtyequi** [agershun/alasql#419]
Hi,

assume there's a table row named "count".

When executing a query that uses this row name, I get this same error: Expecting 'LPAR', got 'RPAR'. 
It does not help to prepend the table name (like `table.count`).

This should be reproduceable easily.

**Comment by agershun** [comment]
Could you use ```[count]``` or ``` `count` ``` in the query:
```sql
    SELECT * FROM [count]
    SELECT * FROM `count`
```

**Comment by dirtyequi** [comment]
Oops...

I already tried square brackets but that did not work properly (results for the row were undefined). Using backticks solves the problem.

Thank you!

**Comment by agershun** [comment]
According grammar rules you can use ``` [tablename].[columnname]```

**Comment by dirtyequi** [comment]
Please add `count` to this page: https://github.com/agershun/alasql/wiki/Quirky

**Comment by agershun** [comment]
Done. Thank you!
