### ISSUE TITLE
How to insert object

### ISSUE THREAD

**Issue by megabait1212** [agershun/alasql#420]
Hello, how to insert object into the table
ex.
           `
alasql("CREATE TABLE IF NOT EXISTS table_settings");
My object is state ex. 
{"columns":[{"name":"Event","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Transaction ID[TXN_ID]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Attendee ID[ATT_ID]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Registration ID[REG_ID]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Time registration occurred[REG_date]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Unique Code for this registration[REG_code]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Count of this registration in the group registration [REG_count]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Final Price of registration[REG_final_price]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Currency","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Registration Status","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Transaction Status","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Transaction Amount Due","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Amount Paid","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Payment Date(s)","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Payment Method(s)","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Gateway Transaction ID(s)","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Check-Ins","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Ticket Name","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Datetimes of Ticket","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"First Name[ATT_fname]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Last Name[ATT_lname]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Email Address[ATT_email]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Address Part 1[ATT_address]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Address Part 2[ATT_address2]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"City[ATT_city]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"State[STA_ID]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Country[CNT_ISO]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"ZIP/Postal Code[ATT_zip]","visible":true,"width":"*","sort":{},"filters":[{}]},{"name":"Phone[ATT_phone]","visible":true,"width":"*","sort":{},"filters":[{}]}],"scrollFocus":{},"selection":[],"grouping":{},"treeView":{}}

I tried different ways like:
            var state = {};
            state = $scope.gridApi.saveState.save();
            string = JSON.stringify(state);
            console.log(state);
            console.log(string);
            alasql('INSERT INTO table_settings VALUES ?', [state]);
            console.table(alasql("SELECT * FROM table_settings"));
or
            var state = {};
            state = $scope.gridApi.saveState.save();
            string = JSON.stringify(state);
            console.log(state);
            console.log(string);
            alasql('INSERT INTO table_settings VALUES @' + string);
            console.table(alasql("SELECT * FROM table_settings"));
or
            var state = {};
            state = $scope.gridApi.saveState.save();
            string = JSON.stringify(state);
            console.log(state);
            console.log(string);
            alasql('INSERT INTO table_settings VALUES (@' + state + ')' );
            console.table(alasql("SELECT * FROM table_settings"));
`
What is right way to insert object into the table. Thank you

**Comment by agershun** [comment]
> Could you try construction like this:

alasql('INSERT INTO a VALUES ?',[obj]);

Or for array of objects

alasql('SELECT * INTO a FROM ?',[arr]);

**Comment by megabait1212** [comment]
I dropped table and created it again and tried you method and it's working. Thank you

**Comment by seb-ster** [comment]
With 'arr' being an array of objects like this:
`var arr = [`
`   {productId:1, price:2, stock:3000},`
`   {productId:2, price:500, stock:40},`
`   {productId:3, price:10, stock:1000}`
`]`
I have to put 'arr' into another array to use it in the statement like this:
`alasql('SELECT` * INTO a FROM ?',[arr])

Which gives me an array containing an array, containing the actual objects that represent the data rows.
This seems like one array too many?
I would expect the statment to function like this:
`alasql('SELECT` * INTO a FROM ?',arr)
