### ISSUE TITLE
TypeScript Definition Remove from Latest Release?

### ISSUE THREAD

**Issue by cdensmorelytx** [agershun/alasql#428]
Can't seem to find alasql.d.ts in dist anymore. Was it removed on purpose?

**Comment by mathiasrw** [comment]
No it was not....

Thanks for letting us know...

**Comment by mathiasrw** [comment]
ITs back: https://github.com/agershun/alasql/tree/251c04fffd98b6c54f668db9126b2a33534afb84/dist

**Comment by cdensmorelytx** [comment]
Thanks!
