### ISSUE TITLE
aggregation query with custom CONCAT_WS does not work

### ISSUE THREAD

**Issue by dirtyequi** [agershun/alasql#429]
Hi,

I created a custom function CONCAT_WS (works like the well-known mysql [CONCAT_WS](http://www.w3resource.com/mysql/string-functions/mysql-concat_ws-function.php) function):

```js
    alasql.fn.CONCAT_WS = function() {
        args = Array.prototype.slice.call(arguments);
        return args.slice(1, args.length).join(args[0]);
    };
```

When using this in a simple query everything works:

```sql
    SELECT CONCAT_WS(" ", "prepended string", `Ticket-Kategory`,`Ticket-Typ`) as series_name FROM ? 
```

But when I add an aggregator (like SUM()) everything breaks.

```sql
Query:
    SELECT
    CONCAT_WS(" ", "Anzahl Bearbeitungen", `Ticket-Kategory`,`Ticket-Typ`) as series_name, 
    `Datum` AS report_date,
    SUM(`Anzahl Bearbeitungen`) AS `count` 
    FROM ? 
    GROUP BY report_date, series_name;

Result:
    [Object { series_name="Anzahl Bearbeitungen  ",  count=5805,  report_date=undefined}]
```

The data I use (partially):

```js
[
{
"Datum":1441058400000,
"Ticket-Kategorie":"category2",
"Ticket-Typ":"type1",
"Anzahl Bearbeitungen":3
},
{
"Datum":1441058400000,
"Ticket-Kategorie":"category1",
"Ticket-Typ":"type4",
"Anzahl Bearbeitungen":126
},
{
"Datum":1441058400000,
"Ticket-Kategorie":"category1",
"Ticket-Typ":"type2",
"Anzahl Bearbeitungen":47
},
{
"Datum":1441058400000,
"Ticket-Kategorie":"category1",
"Ticket-Typ":"type3",
"Anzahl Bearbeitungen":85
},
{
"Datum":1441058400000,
"Ticket-Kategorie":"category1",
"Ticket-Typ":"type6",
"Anzahl Bearbeitungen":4
},
{
"Datum":1441144800000,
"Ticket-Kategorie":"category2",
"Ticket-Typ":"type3",
"Anzahl Bearbeitungen":2
},
{
"Datum":1441144800000,
"Ticket-Kategorie":"category1",
"Ticket-Typ":"type4",
"Anzahl Bearbeitungen":163
},
{
"Datum":1441144800000,
"Ticket-Kategorie":"category1",
"Ticket-Typ":"type2",
"Anzahl Bearbeitungen":30
}
]
```

**Comment by mathiasrw** [comment]
Greatly described issue. 

Could you please let me know what you would expect as result when using the data you give as example?

**Comment by dirtyequi** [comment]
I took the example data to MySQL and fired the same query (just slightly renamed the column names for MySQL):

```
mysql> select report_date, concat_ws(' ', ticket_category, ticket_type) as data_series, sum(count) as sum from test group by report_date, data_series;
+---------------+-----------------+------+
| report_date   | data_series     | sum  |
+---------------+-----------------+------+
| 1441058400000 | category1 type2 |   47 |
| 1441058400000 | category1 type3 |   85 |
| 1441058400000 | category1 type4 |  126 |
| 1441058400000 | category1 type6 |    4 |
| 1441058400000 | category2 type1 |    3 |
| 1441144800000 | category1 type2 |   30 |
| 1441144800000 | category1 type4 |  163 |
| 1441144800000 | category2 type3 |    2 |
+---------------+-----------------+------+
```

I hope that this would help.

**Comment by mathiasrw** [comment]
@agershun any inputs to this one?

**Comment by dirtyequi** [comment]
Update: What I'm trying to do is (so that you can easily understand why I'm doing this):

Let's say there is source data from where I want to generate chart data. Every aggregatable column must be a data series that has a timestamp (x-axis) and a time-specific value (y-axis).
As there can be non-aggregatable columns (like ticket-category and ticket-type) I need to join each aggregatable column on all non-aggregatable columns to generate a series.

The query above solves this requirement - but unfortunately it does not work properly, or I did something wrong =(

**Comment by mathiasrw** [comment]
I dont think you did something wrong - I think you found an area where AlaSQL can be improved...

**Comment by agershun** [comment]
Everything worked fine. The problem was in different column names in the query and in data:
* `Ticket-Kategory`
* "Ticket-Kategorie"

I just added ```CONCAT_WS()``` to the list of standard functions of AlaSQL.

@dirtyequi Thank you and sorry for late answer!

**Comment by mathiasrw** [comment]
:+1:
