### ISSUE TITLE
Error msg: Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by Cyberider** [agershun/alasql#432]
Chrome 45
Full msg: **Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.**
Line 7: alasql.min.js

I envoked this console error msg when doing this:
alasql('SOURCE "myfile.sql"');
As described here:
https://github.com/agershun/alasql/wiki/How-to-run-SQL-script-from-text-file

I thought you could never use Synchronous with an XHR. Can this be fixed to not only use Async but Promises?

**Comment by agershun** [comment]
Please use this construction for async call of ```SOURCE``` statement:
```js
    alasql('SOURCE "myfile.sql"', [], function() {
         // do the rest of the program here...
    });
```

**Comment by mathiasrw** [comment]
I have updated https://github.com/agershun/alasql/wiki/How-to-run-SQL-script-from-text-file - closing the issue

**Comment by Cyberider** [comment]
Wow you guys are on it! Very active development. Great work guys!

**Comment by mathiasrw** [comment]
😊👍
