### ISSUE TITLE
export JSON to xlsx: capturing all keys as headers

### ISSUE THREAD

**Issue by kanethal** [agershun/alasql#433]
Hello! This looks like a great project and I can't wait to dive in deeper. I'm starting with something relatively simple, converting JSON into an .xlsx worksheet. I have been having a hard time with getting all the keys present in my data to generate a new column. It seems that during conversion, only the keys present in the first object in the array get assigned columns. I'm sure there's a simple solution for this, but didn't see it when I searched the current issues for 'headers'. I appreciate any advice!

```javascript
//accs.json
[{
        "avail": false,
        "cat": "catagory",
        "colors": [],
        "detail": "details",
        "id": "0201",
        "images0": "image 1",
        "manuf": "x",
        "price": "$43.00",
        "url": "url"
    },
    {
      "avail": true,
      "cat": "category",
      "colors": "Green",
      "detail": "detail",
      "id": "6017",
      "images0": "image 1",
      "images1": "image 2",
      "images10": "image 3",
      "images2": "image 4",
      "images3": "image 5",
      "images4": "image 6",
      "images5": "image 7",
      "images6": "image 8",
      "images7": "image 9",
      "images8": "image 10",
      "images9": "image 11",
      "price": "$23.00",
      "url": "url"
  }]
//end accs.json

var alasql = require('alasql');
var xlsx = require('xlsx');

var accs = JSON.parse(fs.readFileSync("accs.json","UTF8"));
console.log(accs)
var exportData = function () {
        alasql("SELECT * INTO XLSX('newaccs.xlsx',{headers:true}) FROM ? ",[accs]);
    }

exportData()
//export only has a single image column

**Comment by mathiasrw** [comment]
Its an interesting use of the library. 

It will take the headings from the first result - so please make sure that the first element has all fields set.

**Comment by agershun** [comment]
There is a flag:
```js
    alasql.options.columnlookup = 10
```
By default it has value of 10 rows. AlaSQL look through first 10 records to collect infomation about all columns. You can change the flag to be sure that AlaSQL collect information about all columns in all records (it may take a time for large recordsets).
```js
    alasql.options.columnlookup = 10000000;
```

**Comment by mathiasrw** [comment]
@agershun will it help if the SQL included the names of the headers?

alasql("SELECT avail, cat, colors, detail, ...... url INTO XLSX('newaccs.xlsx',{headers:true}) FROM ? ",[accs]);

**Comment by agershun** [comment]
@mathiasrw This works only for result recordset after all records were selected. So, in your case AlaSQL will create columns avail, cat, etc. before apply this procedure:

https://github.com/agershun/alasql/blob/develop/src/40select.js#L403-L419

**Comment by mathiasrw** [comment]
Ahh - thanks :+1:

**Comment by kanethal** [comment]
Thanks for the reply, ended up doing just that :)
