### ISSUE TITLE
importing xls files with file upload

### ISSUE THREAD

**Issue by accessdev** [agershun/alasql#434]
Hello,

I try to use alasql & xls import with a file upload in my project.

commands " SELECT * FROM XLSX("srcfile.xlsx " is looking for a file on the server, but in my case I have a string contains the xls file, is it possible to import it with alasql ?

**Comment by mathiasrw** [comment]
I am sure we can find a good way to place the data directly into the machine

But to help you I need to know if its a .xls or .xslx file you are working with...

**Comment by accessdev** [comment]
I'm working with .xslx file , I find a way to handle this with onchange event + alasql('SELECT * FROM FILE(?,{headers:true})',[event] , callback)

but I'm intersted if there is another way because for other uploads I'm using angularJS + app-filereader and I can't use it in this case.

**Comment by mathiasrw** [comment]
I found https://github.com/agershun/alasql/blob/324a8c07ee5739477779e7bae222f3f9ef17ee21/dist/alasql.js#L15512-LL15526 where it looks like you cant avoid `loadBinaryFile` that always fetches a file path. 

Hmm. 

If this is trouely the only part you need you could use XLSX without alasql - play around with 

    XLSX.read(data,{type:'binary'});

**Comment by accessdev** [comment]
thanks for your help !

**Comment by agershun** [comment]
You can pass the object as a Blob:
```js
    alasql('SELECT * FROM XLSX(?,{headers:true}',[myblob]);
```

**Comment by mathiasrw** [comment]
Closing - please reopen if you have more questions
