### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rovantara** [agershun/alasql#446]
I've browse for days, trying to figure out whats wrong, ive enter this code

             var data;
		 alasql('SELECT MATRIX Nama, Lat, Long, icon, Type, Ketinggian, Pemilik, Lokasi, Pengguna FROM CSV("'+csvUrl+'",{headers:true}) WHERE Pengguna LIKE "TELKOMSEL%"',[], function(db){
				data = db;
			}); 
			
 		var infowindow = new google.maps.InfoWindow(), marker, i;

		var marker, i;
	
		for (var i = 0; i < data.length; i++) {  
		  data[i][9] =
		  marker = new google.maps.Marker({
			position: new google.maps.LatLng(data[i][1], data[i][2]),
			map: map,
			icon: data[i][3]
		  });
		
		  google.maps.event.addListener(marker, 'click', (function(marker, i) {
			return function() {
				infowindow.setContent(content);
				infowindow.open(map, marker);
			}
		  })(marker, i));
		  }

it keeps returning error : Uncaught TypeError: Cannot read property 'length' of undefined

what  do i do wrong??? i dont want to enter async mode, because the complexity of the other codes.

**Comment by mathiasrw** [comment]
welllllll - you are putting content into data async - meaning that a) data is defined b) alasql is called c) the rest of the code is executed d) data gets assigned to data

Not sure why you get the lenght of undefined, but try to put the rest of the code into the callback function in the alasql call...

**Comment by rovantara** [comment]
Okay.. Ive already figure it out, i put the at the top before
'function'.....

Then its working
Pada tanggal 24 Okt 2015 21.22, "Mathias Rangel Wulff" <
notifications@github.com> menulis:

**Comment by mathiasrw** [comment]
Please post the solution so others can benefit :)

**Comment by rovantara** [comment]
//==== this first====
var data;
		 alasql('SELECT MATRIX ....................................................... FROM ............... WHERE .... LIKE "T%"',[], function(db){
				data = db;
			}); 

//==== then this to call the data======
function addTelkomsel() {
			
 		var infowindow = new google.maps.InfoWindow(), marker, i;
		
		var marker, i;
		
		for (var i = 0; i < data.length; i++) {  
		  data[i][12] =
		  marker = new google.maps.Marker({
			position: new google.maps.LatLng(data[i][1], data[i][2]),
			map: map,
			icon: data[i][3]
		  });
		
		  google.maps.event.addListener(marker, 'click', (function(marker, i) {
			return function() {
			var content = (....)
				infowindow.setContent(content);
				infowindow.open(map, marker);
			}
		  })(marker, i));
		  }
	  
		 };

**Comment by mathiasrw** [comment]
:+1:
