### ISSUE TITLE
Error in IndexedDb and Safari/Firefox

### ISSUE THREAD

**Issue by colmsjo** [agershun/alasql#447]
This simple code snippet causes errors in both Safari and Firefox:

```
> alasql('CREATE INDEXEDDB DATABASE IF NOT EXISTS geo');
< undefined
[Error] TypeError: r is not a function. (In 'r(s?0:1)', 'r' is undefined)
	onsuccess
```

More details:
`onsuccessalasql.min.js:22573TypeError: r is not a function. (In 'r(s?0:1)', 'r' is undefined)`

I'm running Safari Version 9.0 (11601.1.56)

I also tested in Firefox with the same result:

```
alasql('CREATE INDEXEDDB DATABASE IF NOT EXISTS geo');
undefined
TypeError: r is not a function alasql.min.js:11:22045
```

Firefox version 40.0.3

**Comment by mathiasrw** [comment]
Hmmm. Interesting. 

Thanks for letting us know. 

Ill make sure it gets marked as a bug

**Comment by anthonyboutinov** [comment]
I suppose, this issue can be closed. 
No problems with this code in Safari 9.0.3.
In Firefox 38.0.5 for Mac, no error is thrown either.
