### ISSUE TITLE
ATTACH SQLITE DATABASE: Create a SQLite database which alaSQL can read

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [agershun/alasql#448]
Hello alaSQL team,

The main issue is that we cannot create a working example for the "ATTACH SQLITE DATABASE" method.
We would appreciate a working example.

Among others we have tried code below. It uses sql.js but that is not a real requirement for us. Plain javascript + alaSQL would also do.
The main purpose is to have the code working in iOS (iPhone) and Android.

```
//Create the database
var db = new SQL.Database(sqlTest01.sqlite);
// Run a query without reading the results
db.run("CREATE TABLE test (col1, col2);");
// Insert two rows: (1,111) and (2,222)
db.run("INSERT INTO test VALUES (?,?), (?,?)", [1,111,2,222]);
 
    
alasql('ATTACH SQLITE DATABASE sqlTest01("sqlTest01.sqlite");\
    USE sqlTest01; \
    SELECT * FROM test',[],function(res){
        console.log("result:",res.pop());
});
```
Kind regards,
Mario

**Comment by mathiasrw** [comment]
@MarioVanDenEijnde 

Is `sqlTest01` an object with a property  `sqlite` ?

Should it be `var db = new SQL.Database("sqlTest01.sqlite");` instead?

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

Thanks but still leaves me with "file is encrypted or is not a database"
I thought maybe I have to enter also the path to the database but there is no way I can find out what that path is.

I have tested the following javascript code to write and read a SQLite database with success: https://developer.apple.com/library/safari/documentation/iPhone/Conceptual/SafariJSDatabaseGuide/UsingtheJavascriptDatabase/UsingtheJavascriptDatabase.html#//apple_ref/doc/uid/TP40007256-CH3-SW12

So the "only" thing left is have alaSQL be able to connect to the data(base).
Any help is appreciated.

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

Question: Why actually do you use sql.js and not just "plain" javascript to connect to the data(base)?

Kind regards,
Mario

**Comment by mathiasrw** [comment]
Im confused - are you asking me why your coding example is as it is?

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

What we try to achieve is to use alaSQL with SQLite. We tried using code from your wiki but also from a post you replied to. But we cannot succeed. That is why we call in for help.
So the question is can you help us with a working code sample (with or without sql.js).

Kind regards,
Mario

**Comment by mathiasrw** [comment]
@MarioVanDenEijnde 

SO you would like to store a db in a SQLite format?

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

As I have understood alaSQL works in memory which makes queries and such faster.
But to rely only on in memory storage of data is not an option for us We want to have a persistent storage and on top of that use alaSQL for processing.
Because we also don't want to be limited in storage such as the 50Mb WebSQL (iOS) we want to use SQLite.
As I understand we need the SQLite adapter to use alaSQL on top of SQLite.
Storing data in SQLite format is not the real requirement. We don't need sql.js or even alaSQL for this but can use other javascript.

Does this make sense?

Kind regards,
Mario

**Comment by mathiasrw** [comment]
Regarding WebSQL - are you thinking browser or an app based on javascript?

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

An App based on javascript.

By the way: I received a reply from sql.js (Ophir Lojkine):
"sql.js doesnt read files. The only way to open an existing database is to read it into memory (by your own means) and then giving the array of bytes to sql.jq."

With this remark I don't know what your sql "ATTACH" using sql.js actually is meant to do?
Note: I am not interested in sql.js as such. I only want to use alaSQL to process sqlite database files

Kind regards,
Mario

**Comment by mathiasrw** [comment]
I cant test it here - but try this approach: 

```js
alasql('ATTACH SQLITE DATABASE mytable ("abc.sqlite")') ;
alasql('USE mytable;') ;
alasql("CREATE TABLE test (col1, col2);");
alasql("INSERT INTO test VALUES (?,?), (?,?)", [1,111,2,222]);
alasql("SELECT * FROM test",[],function(res){
        console.log("result:",res.pop());
});
```

**Comment by kurtkincaid** [comment]
I am having a very similar problem to @MarioVanDenEijnde. When following the method you describe here and elsewhere, using the _Chinook_Sqlite.sqlite_ database, I get the following:

```javascript
> var alasql = require( 'alasql' );
undefined
> alasql( 'ATTACH SQLITE DATABASE mytable ("Chinook_Sqlite.sqlite");' );
1
> ReferenceError: SQL is not defined
    at c:\nodejs\node_modules\alasql\dist\alasql.js:17373:31
    at c:\nodejs\node_modules\alasql\dist\alasql.js:3261:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
> alasql( 'USE mytable;' );
1
> alasql( 'SELECT * FROM Genre', [], function( res ) { console.log( "Genres: ", res.pop() ); } );
TypeError: Cannot read property 'columns' of undefined
    at c:\nodejs\node_modules\alasql\dist\alasql.js:9494:13
    at Array.forEach (native)
    at yy.Select.compileDefCols (c:\nodejs\node_modules\alasql\dist\alasql.js:9485:13)
    at yy.Select.compile (c:\nodejs\node_modules\alasql\dist\alasql.js:7179:23)
    at Function.alasql.dexec (c:\nodejs\node_modules\alasql\dist\alasql.js:4225:38)
    at Function.alasql.exec (c:\nodejs\node_modules\alasql\dist\alasql.js:4190:17)
    at alasql (c:\nodejs\node_modules\alasql\dist\alasql.js:121:18)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
>
```
I tried manually including _sql.js_, and all that happens is that it changes the error message I get following the ATTACH statement:

```javascript
> TypeError: cb is not a function
    at c:\nodejs\node_modules\alasql\dist\alasql.js:17392:7
    at c:\nodejs\node_modules\alasql\dist\alasql.js:3261:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
>
```

Thoughts?

Kurt

**Comment by MarioVanDenEijnde** [comment]
Hello Kurt,

Because I want to use sqlite for the local mobile database I needed a solution that works.
After some searching I found an excellent solution to work with sqlite:
https://github.com/SchizoDuckie/CreateReadUpdateDelete.js 

I don't think it works the same as alasql but I needed to step forward.
I still use some of alasql query features though ;-)

Hpefully in the future alasql has got a working sqlite adapter and we will investigate again.

Kind regards
Mario

**Comment by mathiasrw** [comment]
@MarioVanDenEijnde Good to know you found a solution that worked for you. AlaSQL has a lot to work - sorry I could not help you right now.

**Comment by kurtkincaid** [comment]
Thanks, @MarioVanDenEijnde, I am looking at the solution you found as we speak.

To the AlaSQL team, AlaSQL is _extremely_ impressive. Thanks for your hard work. I look forward to seeing how it evolves and gets even better.

Kurt

**Comment by mathiasrw** [comment]
@kurtkincaid Thank you for taking the time to express your opinion :+1:

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

Question: We have an sqlite database and we can query the database to deliver a json array.
We would like to use your "extend and merge two arrays containing objects" function.
This function delivers a VAR we can use to query and populate a search box list.

I am not familiar with the "in memory" way to handle this but am I right that it would work as follows:
1.) I check for updates in the sqlite database tables in function A (regularly or as part of a update function)
2.) When there is a table data change I will call the alasql function that updates the VAR
3.) I query VAR to populate the search box list.

And by doing it this way get a performance gain while executing the search query.

Please advise.

Kind regards,
Mario

**Comment by mathiasrw** [comment]
I would love if you could write something about what you are trying to achieve

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

We have sqlite data and we want to populate a search result list based on a search box entry filtering the sqlite data while we type. The search will be used multiple times after each other so I thought if we could "cache" the data in memory the search will execute faster.
That is basically the idea.
As I understand the "magic" of using alasql is it executes "in memory".
So I presumed the best way to do this is using alasql to generate and maintain the search data and use alasql queries the filter the result.

Is this more helpfull?

Kind regards,
Mario

**Comment by mathiasrw** [comment]
> We have sqlite data and we want to populate a search result list based on a search box entry filtering the sqlite data while we type.

so... sqlite is located on server and the search autosuggest is on a client somewhere?

How often is the central data updated? How long are the clients having the page open?

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

No sorry. The data is on the client.

Kind regards,
Mario

**Comment by mathiasrw** [comment]
@MarioVanDenEijnde Would it be possible for you to post your a working example of "ATTACH SQLITE DATABASE" so @kurtkincaid could get inspired?

**Comment by MarioVanDenEijnde** [comment]
No not yet. Because I have this approach only in my head.
But i presume the basic question should be clear by now and I kinda hoped you could answer this.

If I would be more basic the question would be "why did you build alasql?"
Again I thought the "magic" of using alasql is it executes "in memory" and therefore is faster.

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

I am trying to build a working example. Can you modify code below so I also can get columns from hotels in the result?
```
res = alasql('SELECT id, FIRST(Name) AS Name, COUNT(*) AS [Count] FROM ? facilities \
            JOIN ? hotels ON facilities.id IN hotels.WebFacilities \
            GROUP BY id', [facilities,hotels]);
```

**Comment by MarioVanDenEijnde** [comment]
I think I get it in your example: Changed id into to "FIRST(hotels.id) AS id"
But in my code below I get the message: p.favColl.ID_Food.indexOf is not a function
Can you advise please?

```
res = alasql('SELECT ID_Food, FIRST(favColl.id) AS id FROM ? foodColl \
JOIN ? favColl ON foodColl.ID_Food IN favColl.ID_Food \
GROUP BY ID_Food', [foodColl,favColl]);

```

**Comment by MarioVanDenEijnde** [comment]
Could it be that not in all favColl records the ID_Food is filled with data?

**Comment by MarioVanDenEijnde** [comment]
No I tested with only filled field data  ID_Food but the same error.

**Comment by MarioVanDenEijnde** [comment]
I mangeld your code a bit and now I get the same error. It look slike a simple join though.
Can you explain what is wrong?
```
     var hotels = [
        { id: 8, Name: "Hotel 101" },
        { id: 8, Name: "Hotel 101" },
        { id: 9, Name: "Hotel 101" }
    ];

    var facilities = [
        { id: 8, Name: "Facility 8" },
        { id: 9, Name: "Facility 9" },
        { id: 10, Name: "Facility 10" }
    ];

    var res = alasql('SELECT FIRST(hotels.id) AS id, FIRST(Name) AS Name FROM ? facilities JOIN ? hotels ON facilities.id IN hotels.id GROUP BY id', [facilities,hotels]);
```

**Comment by mathiasrw** [comment]
I would really like to help you, but I need to understand your data. 

So you have a table of hotelts and a table of facilities 

is it an autosuggest you are trying to make?

Are you trying to have a autosuggest / selection of facilities after you have selected a hotel?

**Comment by MarioVanDenEijnde** [comment]
Thanks. Can you write the join / aggr for below? the join = id

```
var arr1 = [{
    id: 1,
    name: 'fred',
    title: 'boss'
}];

var arr2 = [{
    id: 1,
    uid: 1
},
    id: 1,
    uid: 2
}];
```
And the result should be:
```
var res= [{
    id: 1,
    name: 'fred',
    title: 'boss',
    uid: 1 (or 2)
}];
```

**Comment by mathiasrw** [comment]
```
SELECT * from arr1 JOIN arr2 ON id Where 1 LIMIT 1
```

(not really a good answer as you you are not in controle if its uid1 or 2 - but really need more information to help you out)

**Comment by MarioVanDenEijnde** [comment]
I hoped you would drop in a Group with an aggregate with FIRST or MAX

**Comment by mathiasrw** [comment]
@MarioVanDenEijnde I cant help you if you are not providing me the info about what you are doing.

**Comment by MarioVanDenEijnde** [comment]
OK. The thing is that the joins I have tested will return 2 objects but I only want 1. I only want the rows of arr1 extended with an item in arr2.
So your 1 LIMIT 1 example gives me exactly that but I want to have a little more playroom.
So If you can give me a group and aggregate I can chhose myself if I want the 2 or the 1.

**Comment by mathiasrw** [comment]
You hold me in the dark.

So given a uid, you would like to have the data from both arr1 and arr2?

> I hoped you would drop in a Group with an aggregate with FIRST or MAX
it does not make sense to make a GROUP if data does not need to agregate. Please provide meaningful data and a question formulated as "Given I have the value XXXX of the field YYYY, how can I get the output to be ZZZZZ"

**Comment by MarioVanDenEijnde** [comment]
I am not trying to hold you in the dark. Just want to know how to do it. And from that on I can use it in different ways.
I tried the 1 LIMIT 1 but that is not what I need. It limits the result in only 1 row.
When I update the demo data it would look like below. Does this make more sense?
```
var arr1 = [{
    id: 1,
    name: 'fred',
    title: 'boss'
},{
    id: 2,
    name: 'max',
    title: 'bossanova'
}];

var arr2 = [{
    id: 1,
    uid: 1
},{
    id: 1,
    uid: 2
},{
    id: 2,
    uid: 3
}];
```
And the result should be:
```
var res= [{
    id: 1,
    name: 'fred',
    title: 'boss',
    uid: 1 (or 2) -> MAX or MIN
},{
    id: 2,
    name: 'fred',
    title: 'boss',
    uid: 3
}];
```

**Comment by MarioVanDenEijnde** [comment]
Sorry. The res should be:
```
var res= [{
    id: 1,
    name: 'fred',
    title: 'boss',
    uid: 1 (or 2) -> MAX or MIN
},{
    id: 2,
    name: 'max',
    title: 'bossanova',
    uid: 3
}];
```

**Comment by mathiasrw** [comment]
> Please provide meaningful data and a question formulated as "Given I have the value XXXX of the field YYYY, how can I get the output to be ZZZZZ"

I see a XXXX and a ZZZZ - but what is YYYYY?

(are you aware that you can edit your posts in this thread by clicking on the little pen icon at the top right corner of each post?)

**Comment by MarioVanDenEijnde** [comment]
Hum. I think I cannot make it any easier but you are missing something.

**Comment by MarioVanDenEijnde** [comment]
Would it help if I would ask for a group/aggregate function together with a join?

**Comment by mathiasrw** [comment]
OK - I think I get it - you are trying to 

> Find the whole data for the row with some max value in a column per some group identifier

Try this approach

```js
var res = alasql('WITH all AS ( SELECT * from $arr1 JOIN $arr2 ON id ) SELECT a.* FROM all a
LEFT OUTER JOIN all b ON a.id = b.id AND a.uid < b.uid WHERE b.id IS NULL;', {arr1:arr1, arr2:arr2});
```

If its not working have a look on google for something like "SQL select rows with max value"

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

It seems the LEFT OUTER JOIN works as a FULL OUTER JOIN.
Can we fix this?

Kind regards,
Mario

**Comment by mathiasrw** [comment]
Is this a New issue or the same? If its New I would really really livebook you could create a New issue with samplecode of what you experience and what result you expected to support the bug hunt.

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

Before answering that question I have to excuse myself. The issue is not an issue. I included a field in the select from table B which has got multiple values and thus returns multiple rows.

Thanks for the quick response.
Kind regards,
Mario

**Comment by mathiasrw** [comment]
No problem
