### ISSUE TITLE
Tabletop

### ISSUE THREAD

**Issue by rovantara** [agershun/alasql#449]
Could someone guide me for the tabletop features,  I've already put in the src javascript and all, 
but i dont want to assign the value the #res html (like in the example code)

when i do this:

	var url= googlespreadsheetkey;

	var data;
		 alasql('SELECT MATRIX______________FROM TABLETOP("'+url+'",{headers:true}) WHERE Pengguna LIKE "%P%"',[], function(db){
				data= db;
			}); 

it returns error

.
tabletop.js:5 Uncaught ReferenceError: process is not defined
alasql.min.js:11 Uncaught ReferenceError: Tabletop is not defined

(index):618 Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by mathiasrw** [comment]
Please have a look at https://github.com/agershun/alasql/wiki/TABLETOP - i think you are not having an url string in `url` (`var url= googlespreadsheetkey;`)

What is the `MATRIX______________FROM`part about?

**Comment by rovantara** [comment]
I think its the tabletop issue, ive already managed the "process is
undefined" error, the err is on the tabletop.js, they have corrected it,
but maybe forgot to submit. I'll give the link later on.

For now there's no error, but the data still dont show up (already tried
the console.log)
Maybe its the gdocs, ill try make another new file.
Pada tanggal 25 Okt 2015 01.32, "Mathias Rangel Wulff" <
notifications@github.com> menulis:

**Comment by mathiasrw** [comment]
Have you made the data public so it looks like https://docs.google.com/spreadsheets/d/12VlQDuE1hgArpsJFBHlVbe4XN3CX5qwHvo-58ClMGzU/pubhtml ?

**Comment by rovantara** [comment]
Yes.. here is my code

	var pemda;
		 alasql('SELECT MATRIX Nama, Lat, Long, icon, Type, Ketinggian, Pemilik, Lokasi, Pengguna FROM TABLETOP("https://docs.google.com/spreadsheets/d/1TYLBVhVzrS6cHlghu9d709V1wTyGKKCJ5AsHO0o18TU/pubhtml") WHERE Pengguna LIKE "%PEMDA%"', function(db){
				console.log(db);
			}); 

btw the tabletop thing, is reffered to here ;
https://github.com/jsoma/tabletop/pull/106/files?diff=split
it seems the " " is left behind in the late code.

**Comment by rovantara** [comment]
Ive already create new gdocs, still the data wont show. no bugs whatsoever

**Comment by mathiasrw** [comment]
Please post the link to your data (if they are public) for me to help you out

**Comment by rovantara** [comment]
it is the link
just click it


On Sun, Oct 25, 2015 at 2:03 AM, Mathias Rangel Wulff <
notifications@github.com> wrote:

> Please post the link to your data (if they are public) for me to help you
> out
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agershun/alasql/issues/449#issuecomment-150841492>.
>



-- 
Rovantara sent

**Comment by mathiasrw** [comment]
I see no link - sorry...

**Comment by rovantara** [comment]
just click https://docs.google.com/spreadsheets/d/1ysJfMOi2Tct5tHhKkTkMhfbBPn9RnLu1meJVphZNtms/pubhtml

the same data, the latter, ive just create new

**Comment by mathiasrw** [comment]
Please try to run 

    console.log(alasql('SELECT * FROM TABLETOP("https://docs.google.com/spreadsheets/d/1ysJfMOi2Tct5tHhKkTkMhfbBPn9RnLu1meJVphZNtms/pubhtml")'))

and tell me whats in the console log

**Comment by rovantara** [comment]
nothing on my console

**Comment by rovantara** [comment]
just this []

**Comment by mathiasrw** [comment]
awww- its async...

try :

```
alasql('SELECT * FROM TABLETOP("https://docs.google.com/spreadsheets/d/1ysJfMOi2Tct5tHhKkTkMhfbBPn9RnLu1meJVphZNtms/pubhtml")',[],function(res){
console.log(res)
})
```

**Comment by rovantara** [comment]
ok.. its on now.. thanks
it seems there's an error on my code.. sorry, 
its all working now.

**Comment by mathiasrw** [comment]
:+1:
