### ISSUE TITLE
MySQL syntax errors

### ISSUE THREAD

**Issue by kahluagenie** [agershun/alasql#452]
Running in nodejs 4.2.1.
I have `alasql.options.mysql = true;`

Trying to execute the following MySQL query:

```SQL
CREATE TABLE `org` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `createUser` VARCHAR(100),
  `updateUser` VARCHAR(100),
  `createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdateTime` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleteId` CHAR(36) NOT NULL DEFAULT "",
  PRIMARY KEY (`id`),
  UNIQUE KEY `org_u1` (`name`, `deleteId`)
 )  CHARSET=utf8 COLLATE=utf8_bin;
```

I get multiple syntax errors. Some I am able to fix, some I am not sure how to...

##### ON UPDATE

>Parse error on line 8:
... TIMESTAMP NOT NULL ON UPDATE CURRENT_TI
-----------------------^
Expecting 'EOF', 'COMMA', 'RPAR', 'NOT', 'UNIQUE', 'NULL', 'END', 'ELSE', 'DEFAULT', 'IDENTITY', 'CHECK', 'PRIMARY', 'FOREIGN', 'REFERENCES', 'SEMICOLON', 'GO', got 'ON'

It doesn't seem to accept ON UPDATE statements? The only way I got past it was by removing ON UPDATE CURRENT_TIMESTAMP

##### UNQIUE KEY

>Parse error on line 11:
  UNIQUE KEY `org_u1` (`name`
----------------------^
Expecting 'LITERAL', 'BRALITERAL', 'LPAR', got 'KEY'

Fixed by removing KEY in "UNIQUE KEY"

##### COLLATE

>Parse error on line 12:
 )  CHARSET=utf8 COLLATE=utf8_bin;
----------------------^
Expecting 'LITERAL', 'EOF', 'END', 'ELSE', 'DEFAULT', 'IDENTITY', 'SEMICOLON', 'GO', got 'COLLATE'

Not sure how to fix this one.

Cheers and thanks!

**Comment by mathiasrw** [comment]
Thanks for a really(!) well written description. 

I feel the parser might need a little love to handle the 3 cases. We need to get @agershun into the loop.

(bonus info: please note that setting the charset and collate has no effect if using AlaSQL with the default backend))

**Comment by kahluagenie** [comment]
Awesome thanks!

Yeah, I suspected as much about charset and collate. I was writing unit tests for a production query, so I kept it as it is :)

**Comment by mathiasrw** [comment]
@agershun Any inputs on this?

**Comment by agershun** [comment]
Fixed. Added ```ON UPDATE``` column constraint.

**Comment by mathiasrw** [comment]
Confirmed!

**Comment by kahluagenie** [comment]
Much appreciated!
