### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by glaucocustodio** [agershun/alasql#453]
Hi, I was reading this wiki page https://github.com/agershun/alasql/wiki/Update and I've missed some more examples when performing parameterized `UPDATE` like the following:

`alasql("UPDATE events SET synchronized = ? WHERE name = ?", [true, event.name]);`

I tried to add, but I think I dont have permission. Could you add please? Thanks.

**Comment by mathiasrw** [comment]
Sure !
