### ISSUE TITLE
Bug in CSV example?

### ISSUE THREAD

**Issue by sirrice** [agershun/alasql#454]
When I use a period (".") after the csv filename, I get a parse error.  

        alasql('SELECT * INTO CSV("my.csv". {headers:true}) FROM ?',[data]);

I don't get the error when using a comma,

        alasql('SELECT * INTO CSV("my.csv", {headers:true}) FROM ?',[data]);

**Comment by mathiasrw** [comment]
I imagine we have an error in an example - where have you found a dot in the CSV() and not a `,`?

**Comment by mathiasrw** [comment]
Anything new on this?

**Comment by mathiasrw** [comment]
@sirrice Where did you find this example?
