### ISSUE TITLE
"Refusing to install alasql as a dependency of itself"

### ISSUE THREAD

**Issue by ph-hs** [agershun/alasql#455]
Command:
   npm install alasql --save 

Has unexpected results :-( .......

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install" "alasql" "--save"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ENOSELF

npm ERR! Refusing to install alasql as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /scm/alasql/npm-debug.log

**Comment by mathiasrw** [comment]
hmmmm... interesting

this is what I get

```
>  npm install alasql --install
npm WARN prefer global alasql@0.2.1 should be installed with -g
alasql@0.2.1 node_modules/alasql
├── dom-storage@2.0.1
├── es6-promise@3.0.2
├── lodash@3.10.1
├── xlsjs@0.7.5 (cfb@0.10.3, commander@2.9.0, ssf@0.8.2, codepage@1.3.8)
└── xlsx@0.8.0 (adler-32@0.2.1, crc-32@0.3.0, cfb@0.10.3, commander@2.9.0, jszip@2.4.0, ssf@0.8.2, codepage@1.3.8)
> ls node_modules 
alasql
> ls node_modules/alasql
CHANGELOG.md	README.md	dist		package.json
LICENSE		bin		node_modules	utils
```

The warning part about installing as -g is not related to this.

What other files are there in the folder from where you are running `npm install alasql --save`?

**Comment by ph-hs** [comment]
I'm in the directory I cloned. I'm trying to work out the getting-started steps for this technology.

I've brew installed nodejs (etc), already, and was just carrying into the list in the readme.

**Comment by mathiasrw** [comment]
Ahh - I get it. 

You only need to clone the repo if you want to develop on alasql. 

If you only want to use AlaSQL you 
- make sure node is working (type `node -v` to get last version)
- make a folder where you want to have your node project
- If the project does not have a package.json file you run `npm init`
- now you can `node install alasql --save` 
- Make a test.js file and place into the file `alasql=require(`alasql`);console.log(alasql('select 1+2'))`
- run `node test.js` and see it spit out the result...

**Comment by ph-hs** [comment]
No I was trying to build it, before going into WebStorm to make contribs.

**Comment by mathiasrw** [comment]
Ohh, sorr

**Comment by ph-hs** [comment]
Thanks :)
