### ISSUE TITLE
readasbinarystring not working with ie11

### ISSUE THREAD

**Issue by touletan** [agershun/alasql#456]
I had to change it to readasarraybuffer and then move to buffer to string. Is there a better way to do it?

       } else if(path instanceof Event) {
            // console.log("event");
            var files = path.target.files;
            var reader = new FileReader();
            var name = files[0].name;
            reader.onload = function(e) {
                
				var data = e.target.result;
                success(ArrayBufferToString(data));
            };
            reader.readAsArrayBuffer(files[0]);    
			
        } else if(path instanceof Blob) {
        	success(path);
        } 
    }
};
function BinaryToString(binary) {
    var error;

    try {
        return decodeURIComponent(escape(binary));
    } catch (_error) {
        error = _error;
        if (error instanceof URIError) {
            return binary;
        } else {
            throw error;
        }
    }
}

function ArrayBufferToString(buffer) {
    return BinaryToString(String.fromCharCode.apply(null, Array.prototype.slice.apply(new Uint8Array(buffer))));
}

**Comment by mathiasrw** [comment]
Hey - thanks for reaching out...

I cant find `readAsArrayBuffer` in the code: https://github.com/agershun/alasql/search?utf8=%E2%9C%93&q=readAsArrayBuffer

Would love if you could give som inputs about where you suggest the changes?

Do you have some code that fails so we can put it into a test?

**Comment by mathiasrw** [comment]
Hi @touletan 

I have a feeling this question is related to another repo

If not please reopen this post and let me know where the issue is located
