### ISSUE TITLE
Strange $0$1 in generated query

### ISSUE THREAD

**Issue by raarts** [agershun/alasql#457]
I use storeness:meteor-postgres  0.2.1 in Meteor. The query I execute is constructed as follows:

`return contacts.select().where("id != ? and status != ?", 1, 'deleted').order('firstname DESC').fetch();`

this results in:

`result = alasql(input, this.dataArray);`

with input "'SELECT * FROM contact  WHERE id <> ? and status <> ? ORDER BY firstname ASC'", and the array having values 1 and 'deleted'.

this somehow results in the postgresql query:

`SELECT * FROM contact  WHERE $0$1id != '1' and status != 'deleted' ORDER BY firstname DESC;`

which obviously get rejected. For some reason I cannot de-minify the source in chrome or firefox, so cannot trace it.

 btw leaving out the question marks makes no difference. how can i troubleshoot this further?

**Comment by raarts** [comment]
I'm sorry. I'm stupid. This is not an alasql problem of course.

**Comment by mathiasrw** [comment]
Hope you found the solution.
