### ISSUE TITLE
JS Fiddle for this example doesn't seem to be running

### ISSUE THREAD

**Issue by huyettcp** [agershun/alasql#459]
http://jsfiddle.net/agershun/xzawkr9v/2/

This is the error that I got "Uncaught ReferenceError: alasql is not defined"
I am using Chrome, if that helps.

**Comment by nickdeis** [comment]
Use
http://cdn.jsdelivr.net/alasql/latest/alasql.min.js
for the script src instead

**Comment by mathiasrw** [comment]
@nickdeis thanks :+1: 

@huyettcp have updated the jsfidle source at http://jsfiddle.net/aumnfpt1/
