### ISSUE TITLE
ROLLUP() - error: undefined is not a function

### ISSUE THREAD

**Issue by drjackson** [agershun/alasql#46]
error when running ROLLUP():

var testData = [
    { Phase: "Phase 1", Step: "Step 1", Task: "Task 1", Val: 5 },    
    { Phase: "Phase 1", Step: "Step 2", Task: "Task 2", Val: 20 },
    { Phase: "Phase 2", Step: "Step 1", Task: "Task 1", Val: 25 },    
    { Phase: "Phase 2", Step: "Step 2", Task: "Task 2", Val: 40 }
];

res = alasql('SELECT Phase, Step, SUM(Val) AS Val FROM ? GROUP BY ROLLUP(Phase,Step)', [testData]);

I just want to say that this project is incredible.  Thanks so much for sharing it.

**Comment by agershun** [comment]
Thank you! I will fix this problem in about two hours.

**Comment by agershun** [comment]
Now it was fixed in version 0.0.38

See [jsFiddle example](http://jsfiddle.net/agershun/1nccgs6n/2/) for ROLLUP(), CUBE(), and GROUPING SETS()

**Comment by drjackson** [comment]
Great.  Thanks again!
