### ISSUE TITLE
field name “action” cause issues alasql export to Excel

### ISSUE THREAD

**Issue by chaitujil** [agershun/alasql#460]
I am using alasql to export to excel and I am trying to do custom headers like this below. All other field names are fine except when it is "action"

function myCtrl($scope) {
$scope.exportData = function () {
    alasql('SELECT name as MY_NAME, action as MY_ACTION INTO XLSX("john.xlsx",{headers:true}) FROM ?',[$scope.items]);
};

$scope.items = [{
    name: "John Smith",
    action: "j.smith@example.com",
    dob: "1985-10-10"
}, {
    name: "Jane Smith",
    action: "jane.smith@example.com",
    dob: "1988-12-22"
}, {
    name: "Jan Smith",
    action: "jan.smith@example.com",
    dob: "2010-01-02"
}, {
    name: "Jake Smith",
    action: "jake.smith@exmaple.com",
    dob: "2009-03-21"
}, {
    name: "Josh Smith",
    action: "josh@example.com",
    dob: "2011-12-12"
}, {
    name: "Jessie Smith",
    action: "jess@example.com",
    dob: "2004-10-12"
}];
};
is giving me this below error

Error: Parse error on line 1:
...CT name as MY_NAME, action as MY_ACTION 
-----------------------^
Expecting 'LITERAL', 'BRALITERAL', 'LPAR', 'NUMBER', 'STRING', 'SHARP',     'DOLLAR', 'AT', 'COLON', 'NOT', 'PLUS', 'STAR', 'QUESTION', 'CURRENT_TIMESTAMP', 'JAVASCRIPT', 'NEW', 'CAST', 'CONVERT', 'SUM', 'COUNT', 'MIN', 'MAX', 'AVG', 'FIRST', 'LAST', 'AGGR', 'ARRAY', 'TRUE', 'FALSE', 'NSTRING', 'NULL', 'EXISTS', 'BRAQUESTION', 'CASE', 'MINUS', 'ATLBRA', 'LCUR', got 'ACTION'
at Object.parseError (alasql.min.js:3)
at Object.parse (alasql.min.js:3)
at Function.alasql.parse (alasql.min.js:3)

**Comment by agershun** [comment]
Here ```action``` is a keyword for AlaSQL, so please use:
```sql
    SELECT name as MY_NAME, [action] as MY_ACTION INTO XLSX("john.xlsx",{headers:true}) FROM ?
```

**Comment by chaitujil** [comment]
That worked. Thanks
