### ISSUE TITLE
How to convert date string to my own date time format

### ISSUE THREAD

**Issue by chaitujil** [agershun/alasql#461]
Hi, I am using this following way while doing an export to excel

alasql.fn.Date = Date;
alasql('SELECT new Date(mydateString) AS CUSTOM_DATE INTO XLS("' + filename + '.xls",{headers:true}) FROM ?', [items]);

Those above lines are printing in this below date format
Sat Jun 06 2015 00:00:00 GMT-0500 (Central Daylight Time)

but I want to format mydateString as "MM-DD-YYYY hh:mm:ss". How can I do that?

**Comment by agershun** [comment]
You can define your own format function and use it in SELECT statement inside AlaSQL:
```js
    alasql.fn.myformat = function(d) { return ./* formatting code here */... }
    alasql('SELECT myformat(d) ...');
```

**Comment by chaitujil** [comment]
Got it. I figured that out after I posted the question. Just waiting to know if there is an in-built function already.

**Comment by agershun** [comment]
Could you try this code:

SELECT d::DATETIME

where d is your time expression

Отправлено с iPhone

**Comment by chaitujil** [comment]
It printed this for Jun 6th 12 AM
2015.06.06 00:00:00.000

But I was able to use alasql-fn-XXX way to create more customized way of displaying.

Thanks.

**Comment by rchawdhari** [comment]
I want to format mydateString as "hh:mm:ss". How can I do that?

**Comment by mathiasrw** [comment]
@rchawdhari 

What data do you have? String? date obj?

**Comment by mathiasrw** [comment]
@rchawdhari ?
