### ISSUE TITLE
AUTO_INCREMENT and LocalStorage

### ISSUE THREAD

**Issue by error39** [agershun/alasql#462]
When using localstorage, AUTO_INCREMENT doesn't seem to function, as though without specifying a storage method it does work, is this intended behaviour or am I implementing it incorrect?

my implementation of A_I with localstorage: http://jsfiddle.net/gym7L42r/

**Comment by mathiasrw** [comment]
Nice catch - a clear bug...

Made a version making it easy to compare expected and actual output

http://jsfiddle.net/hfcpcnxt/

**Comment by error39** [comment]
okay, glad I did report it, then, will make alasql a tiny bit better then!
Really appreciate all the work that has gone into this GREAT project, thumbs up!

**Comment by mathiasrw** [comment]
:+1:

**Comment by glaucocustodio** [comment]
Same problem here, it does not generate id...

**Comment by error39** [comment]
I was wondering, will this be fixed?

**Comment by mathiasrw** [comment]
Sorry my short answer from a phone. Yes it will be solved - it's an error - but can't tell you when. In this moment we are transforming the code base to ES6. It depends on when people like @agershun take the time to get into the nitty gritty...

**Comment by error39** [comment]
Okay, I understand the problem.
But do you have a slight idea when this (kind of basic) functionality will be added/fixed then?
In - like - a month or more likely 6 months or a year?
You've all done a great job with this library and for future projects I'd be happy to know if it's actively maintained, or if it's just a more or less finished project?

Wish I could be of some help on the subject, but my Javascript skills are far from suited for these kind of projects.

Good luck with the codebase rewrite, a huge job, I guess..

**Comment by mathiasrw** [comment]
Sorry - I really dont know when someone feel in the mood to dig into issue. 

From November 27 to December 27 we had the following activity: 

- 6 authors have pushed 44 commits (4 Pull requests)
- 86 files have changed 
- 19 Issues created
- 10 Issues closed

So guess some people still seek to improve the library. 

I am sure that if you have an urgent need you can hire @agershun to spend the time needed to fix this.

**Comment by error39** [comment]
Thanks, I'll wait till someone will pick up the issue.
In the mean time I'll stick to a custom workaround which auto-increments at every INSERT statement

**Comment by agershun** [comment]
Sorry for late answer, I will try to fix it in one or two days.

Отправлено с iPhone

**Comment by error39** [comment]
Thanks a lot @agershun!

**Comment by agershun** [comment]
It was harder than expected... Sorry for delay

**Comment by seb-ster** [comment]
Is there any progress on this issue?
It's not working in on W10, FF45 with AlaSQL v0.2.5 and local storage.

**Comment by ellisgl** [comment]
Same thing for FileStorage.

**Comment by mathiasrw** [comment]
#722 is also having the problem. 

Any help on this one would be aprechiated.

**Comment by seb-ster** [comment]
So, i tracked it down, at least for Local Storage:

Normal ('memory') storage, uses the table.insert() method.
This method has a for loop which checks if an IDENTITY (Autoincrement) is defined for any of the columns that are being inserted. If this is so, it sets the column value accordingly.

Local Storage uses the LS.intoTable() method.
This method has no such for loop.
I got it to work by inserting a slightly modified version of the table.insert() for loop, just after the table is selected with LS.restoreTable().

` for(var columnid in tb.identities){`
`    var ident = tb.identities[columnid];`
`    value[0][columnid] = ident.value++;`
` }`

The main difference is the need for an increment operator on ident.value

file: alasql.js
version: 0.3.2
system: FF 48.0.2 on W10

**Comment by mathiasrw** [comment]
@seb-ster 

Really really awesome - thanks :)

Would you like to [make a pull request](https://github.com/agershun/alasql/blob/develop/CONTRIBUTING.md) so the code can correctly be attributed to you? 

If not, let me know and Ill implement your suggesting here...

**Comment by seb-ster** [comment]
@mathiasrw
My solution is still a little hackish. Especially the increment  operator should atleast be replaced by the identity step value. 
I did it this way because the table (and identity) is loaded via LS.restoreTable() ,  I didn't have direct access to the identity value as in the table.insert() for-loop. 
Also,  this solution probably also needs implementing in other DB engines. 

Would you review and implement the solution for me? 
Thanks!

**Comment by mathiasrw** [comment]
Sure!

**Comment by kanghj** [comment]
It looks sufficient to increment `ident.value` in LS.restoreTable. We can obtain the value of the step using ident.step, so the solution should look something like:

```
for (var columnid in tb.identities) {
	  var ident = tb.identities[columnid];

	  for (var index in value) {
	    value[index][columnid] = ident.value;
	    ident.value += ident.step;
	  }      
}
```
?

**Comment by alshdavid** [comment]
Still an issue for me. Chrome & local storage

**Comment by calebeaires** [comment]
Version alasql 0.4.8 still have this issue. Auto increment does not work. My project is using FILESTORAGE DATABASE

**Comment by classofoutcasts** [comment]
Solved? Great! I left Alasql a while ago as it didn't seem to be actively maintained any more, might reconsider that now though.

**Comment by calebeaires** [comment]
@mathiasrw Very thanks to that. 

Our team were considering use alasql as some of the repositories of a PowerBI alternative. We stopped becouse of this index issue and another one: we tried to do a left join, but it dident bring results using FILESTORAGE DATABASE

We will keep our eyes on it, it is a amzing project.

**Comment by mathiasrw** [comment]
Its driven by people contributing - if you need the features fixed it would help greatly if you look into where the problem is located. Like https://github.com/agershun/alasql/issues/1013 - so that we together can improve the quality.

**Comment by mayae29** [comment]
guys... is it working now?

**Comment by mathiasrw** [comment]
Looks like Dontar fixed it in july 2024
