### ISSUE TITLE
Issue in this demo example while select .xlsx file from browser

### ISSUE THREAD

**Issue by prmkishor** [agershun/alasql#464]
Hi,

I am not able to get any data in res variable if I select .xlsx file from chrome browser. It works with txt file. Can someone please help that how it works for xlsx file.

Thanks in advance.

Prem

**Comment by mathiasrw** [comment]
Are you using it locally on your machine?

**Comment by prmkishor** [comment]
Hi Agershun,

Thank you very much and now my issue has been resolved by calling XLSX
method rather than FILE.

thanks,
Prem
