### ISSUE TITLE
REPLACE without SELECT

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#467]
From running https://github.com/mathiasrw/alasql-logictest/blob/master/sqllogic/test/evidence/slt_lang_replace.test I found that

```sql
REPLACE INTO t1 VALUES(2, 'replace')

Parse error on line 1:
REPLACE INTO t1 VALU
^
Expecting 'LITERAL', 'BRALITERAL', 'EOF', 'EXPLAIN', 'EndTransaction', 'WITH', 'SEARCH', 'EQ', 'SET', 'IF', 'SELECT', 'JAVASCRIPT', 'UPDATE', 'DELETE', 'INSERT', 'CREATE', 'DROP', 'ALTER', 'RENAME', 'ATTACH', 'DETACH', 'USE', 'SHOW', 'HELP', 'SOURCE', 'ASSERT', 'COMMIT', 'ROLLBACK', 'BEGIN', 'WHILE', 'CONTINUE', 'BREAK', 'PRINT', 'REQUIRE', 'ECHO', 'DECLARE', 'TRUNCATE', 'MERGE', 'COLONDASH', 'QUESTIONDASH', 'CALL', 'SEMICOLON', 'GO', got 'REPLACE'
```
Looking at http://www.techonthenet.com/sql_server/functions/replace.php it looks like the correct syntax is to have `SELECT`in front - but seams like all other DBs should be able to handle this without select in fornt - sooooo - I dont know. Should we expand to support `REPLACE`with no `SELECT` in front?

**Comment by agershun** [comment]
Added. Please test.

**Comment by mathiasrw** [comment]
The issue has been confirmed eliminated...
