### ISSUE TITLE
IN undefined context subquery: SQLite + MySQL

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#469]
Running https://github.com/mathiasrw/alasql-logictest/blob/master/sqllogic/test/evidence/in1.test i found that AlaSQL does not yet handle the following correctly mimicing SQLite and MySQL

With an undefined `t1` the statement 

```sql
SELECT 1 IN (SELECT * FROM t1)
```
states that `context is not defined`. Makes sense as t1 is undefined, but for both SQLite and MySQL the subquery will be considered and empty list so the whole statement returns false as 1 is not `IN` the list (of 0 elements) - meaning it handles the request as `SELECT 1 IN ( )` (returning `false`)

**Comment by agershun** [comment]
Fixed. Please see the [test387.js](https://github.com/agershun/alasql/blob/develop/test/test387.js).

**Comment by mathiasrw** [comment]
Solution confirmed - nice job !

**Comment by agershun** [comment]
:+1: I love our small team!

**Comment by mathiasrw** [comment]
I know exactly what you mean...
