### ISSUE TITLE
CREATE INDEX on table with data

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#470]
Looks like there is a bug preventing a creation of an index on tablse already populated with data. 

```sql
CREATE TABLE t1( x INTEGER, y VARCHAR(8) ); 
INSERT INTO t1 VALUES(1,'a'); 
CREATE INDEX tmp ON t1(x);
```
will give `TypeError: rightfns is not a function` while if there is no insert it does not rase an error

**Comment by agershun** [comment]
Fixed.

**Comment by mathiasrw** [comment]
Strange. When I am testing with node I get no error, but when I run [same code](https://github.com/agershun/alasql/blob/f894c0e8bb7e507a4b0d5f5aa90cde44fa93c7b8/test/test403.js#L20-L22) in the browser I get:

![skaermbillede 2016-01-05 23 20 59](https://cloud.githubusercontent.com/assets/1063454/12129310/0e5a0d3c-b403-11e5-94cc-45eb1285bb61.png)

I remember you said some other bug was also present in browser but not node - do you remember?

**Comment by mathiasrw** [comment]
I just tested https://github.com/agershun/alasql/issues/506 and I also get an error in the browser. 

I am wondering - have you pushed the last changes?

**Comment by agershun** [comment]
Yes. Please let me know if the problem still occur.

**Comment by mathiasrw** [comment]
Ough ! I think I had the wrong version on my computer. Its totally working now :+1:
