### ISSUE TITLE
NOT NULL error when copying from another table. 

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#471]
Trying to populate a table with data from another table gives the error 
`Wrong NULL value in NOT NULL column pk` 
when the receiving table has a `NOT NULL` - even if no null value exists... 

```sql
CREATE TABLE tab0 (pk INTEGER NOT NULL);
CREATE TABLE tab1 (pk INTEGER NOT NULL);
INSERT INTO tab0 VALUES(3);
INSERT INTO tab1 SELECT * FROM tab0;
```

Removing the `NOT NULL` from the tab1 creation will remove the error. 

Update: This only occurs when its in several calls to alasql. Having it all in one statement or running it from the console will not produce the error.

Update update: The error is thrown at https://github.com/agershun/alasql/blob/324a8c07ee5739477779e7bae222f3f9ef17ee21/src/60createtable.js#L326 - I am not sure yet why createtable.js is involved in populating data in an existing table.

**Comment by agershun** [comment]
@mathiasrw Sorry, I can not reproduce this bug... See the [test384.js](https://github.com/agershun/alasql/blob/develop/test/test384.js). Could you modify this test or generate jsfiddle fot it?

AlaSQL defines insert() function for each table at the creation table time.

**Comment by mathiasrw** [comment]
Thank you for taking time to look into this. 

I will make a Jsfiddle as soon as possible to illustrate the issue. 

Merry Christmas :)

**Comment by agershun** [comment]
Marry Christmas! I was flying like Santa over your home yesterday (on the flight from Istanbul to San-Francisco) :)

**Comment by mathiasrw** [comment]
Ahhh, I did see all these babushka dolls flying down from the sky - it all makes perfect sense now ;-)

I must admit I cant reproduce the bug at (tried at http://jsfiddle.net/9rey6z2a/ ). I will look into my notes to find out how to replicate this. 

I will apply a please-provide-a-jsfiddle-demonstrating-the-bug policy  for both me and others so you dont have to waste time finding out what the problem is...

**Comment by agershun** [comment]
Let's close it?

**Comment by mathiasrw** [comment]
Got the difference !

The problem apply when

```js
alasql.options.modifier = "MATRIX";
```

a jsfiddle demonstrating the issue: http://jsfiddle.net/a42pv3L9/

I have not checked with other modifier options.

**Comment by agershun** [comment]
Fixed.

**Comment by mathiasrw** [comment]
You. are. awesome!
