### ISSUE TITLE
Node.js FILESTORAGE not working?

### ISSUE THREAD

**Issue by djMax** [agershun/alasql#477]
This throws an error in node:
```
alasql('CREATE FILESTORAGE DATABASE test1("./test1.json")');
alasql('ATTACH FILESTORAGE DATABASE test1("./test1.json")');
```
However, if I just have the first CREATE line, it works and a file is created. How is this supposed to be done?

**Comment by mathiasrw** [comment]
When you create it includes an attach - so you are attaching it twice with the second line

**Comment by djMax** [comment]
That doesn't seem to work either. Combining it with my other issue.
