### ISSUE TITLE
FILESTORAGE index not working?

### ISSUE THREAD

**Issue by djMax** [agershun/alasql#478]
This throws an error in node:

```
    db('ATTACH FILESTORAGE DATABASE foo("./foo.db"); USE foo;');
    db('CREATE INDEX purchaserEmail on purchaser (email)')
```

```
		table.inddefs[indexid] = {rightfns:rightfns, hh:hh};
		                       ^
TypeError: Cannot set property 'purchaserEmail' of undefined
```

**Comment by mathiasrw** [comment]
Interesting. 

Could you share the content of foo.db ?

**Comment by djMax** [comment]
Empty - fresh after a create

**Comment by djMax** [comment]
(I left out the create table - it's just a table with an email field)

**Comment by mathiasrw** [comment]
Would be great to see the create table part also and where you plce it in the flow of attach and create index

**Comment by mathiasrw** [comment]
@djMax Anything new on this?

**Comment by djMax** [comment]
Here's a contained test that shows either my confusion about the docs, which are a bit sparse for filestorage, or two bugs.

```
var db = require('alasql');
var fs = require('fs');

if (!fs.existsSync('foo.db')) {
  db('CREATE FILESTORAGE DATABASE IF NOT EXISTS foo("./foo.db");');
} else {
  db('ATTACH FILESTORAGE DATABASE foo("./foo.db");');
}
db('USE foo;');
db('CREATE TABLE purchaser (email string)');
db('CREATE INDEX purchaserEmail on purchaser (email)');
```

First, if the file doesn't exist, this will fail because USE foo; will fail. So if you run a version with just the "CREATE FILESTORAGE..." command and nothing else, you will end up with an empty foo.db. And then you'll see the issue I reference here, which is the create index failing. Note that if you do something like this:

```
var db = require('alasql');
db('CREATE FILESTORAGE DATABASE IF NOT EXISTS foo("./foo.db");');
process.exit(0);
```

The file will not get created.

**Comment by mathiasrw** [comment]
Please have a look at this example:

```js
alasql.promise([
    'CREATE FILESTORAGE DATABASE IF NOT EXISTS test1("./test1.json")', 
    'ATTACH FILESTORAGE DATABASE test1("./test1.json")', 
    'USE test1', 
    'CREATE TABLE IF NOT EXISTS `preferences` (`id` int(11) NOT NULL, `tab` varchar(45) DEFAULT NULL, `tab_id` int(11))', 
    'INSERT INTO `preferences` (`id`, `tab`, `tab_id`) VALUES (1, "where", 1), (2, "when", 8)',
    'SELECT * FROM preferences'    
]).then(function(res){
    console.log('Result from last query:',res)
}).catch(function(reason){
    console.trace(reason)
})
```

Im closing. Please reopen if you have questions.
