### ISSUE TITLE
GROUP BY MONTH () is not executed in the manner Desire

### ISSUE THREAD

**Issue by cbugari** [agershun/alasql#480]
Hello, run the following query and not get the desired result. I think the problem is GROUP BY.
Here I leave the query and the result

source example:

```js
var data = [{"fecha_Venta":"2012-09-28","hora_venta":"23:35:17","CantVenta":1,"Sales":12500,"Product_Cost":8250,"Objetivo":12500,"gender":"M","Age_rango":"36-45","marital_status":"soltero","localidad":"La Lucila","provincia":"Buenos Aires","Product_desc":"Corola ","Product_Family":"Sedan","Product_Marca":"Toyota","Canal_Venta_desc":"Concesionarias Oficiales","mes":"September"}]


var res = alasql('SELECT MONTH(fecha_Venta) AS meses, SUM(Sales) Sales FROM ? GROUP BY MONTH(fecha_Venta)',[data]);
document.getElementById("res").textContent = JSON.stringify(res);
```

result:

```
[{"Sales":849824},{"Sales":1126408},{"Sales":1211116},{"Sales":1172557},{"Sales":745719},{"Sales":263809},{"Sales":418610},{"Sales":472700},{"Sales":645412},{"Sales":410607},{"Sales":700525},{"Sales":777375}]
```

**Comment by agershun** [comment]
I believed I fixed this issue. Please test it with last version of alasql.js from develop branch. 

At least, it works in this [test](https://github.com/agershun/alasql/blob/develop/test/test373.js)

**Comment by mathiasrw** [comment]
I replicated the problem at 

http://jsfiddle.net/hguw3LLk/

updated the library to [latest development version](https://cdn.rawgit.com/agershun/alasql/eb409edf297dcf53cac8ed8c434c1eb8d151c3fe/dist/alasql.js) and now it works like a charm...

**Comment by cbugari** [comment]
Surely he was using an older version. Now it is running correctly. Thank you for the prompt response and solution to my problem.

**Comment by mathiasrw** [comment]
And thank you for taking the time to write about the issue so we could improve the library
