### ISSUE TITLE
SELECT ASCII('\');

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#482]
The SQL

`"SELECT ASCII('\');"`

throws an error when ran by node (not CLI -  Browser not tested)

**Comment by agershun** [comment]
According our parser specification this regexp thinks that ``` \' ``` is a string (like in JavaScript:
```
(['](\\.|[^']|\\\')*?['])+              return 'STRING'
```

**Comment by mathiasrw** [comment]
Dived into it. 

for an expression like `ASCII('\\')` we are not escaping correctly in 

```js
var escapeq = utils.escapeq = function(s) {
//    console.log(s);
    return s.replace(/\'/g,'\\\'');
};
```

The thing is that `"'\\'".replace(/\'/g,'\\\'');` will give you `"\'\\'"` but I would expect `"\'\\\'"`

Looks strange that it does not get the last single quote - untill I realised that it does get the last quote, but the original `\\` loses its escaping in the proces (so the second `\` is the correctly inserted escape of the single quote)

So we need to first `.replace(/\\/g, '\\\\')` 

now... this could also be an issue with other escaped chars. So have changed utils.escapeq to be

```js
var escapeq = utils.escapeq = function(s) {
//    console.log(s);
    return s.replace(/\\/g, '\\\\').
        replace(/\u0008/g, '\\b').
        replace(/\t/g, '\\t').
        replace(/\n/g, '\\n').
        replace(/\f/g, '\\f').
        replace(/\r/g, '\\r').
        replace(/'/g, '\\\'');
};
```

update:

hmmmm - Now I have fucked up test 125 regarding escaping the output from 

```js
		var res = alasql('select \"Cote d\\"Ivoir\"');
		assert.deepEqual(res,[{'\'Cote d"Ivoir\'':"Cote d\"Ivoir"}]);
```

ok... we might have too split so we keep the old function for output and have a new one for when we generate the commands
