### ISSUE TITLE
Export to excel (xls format) being saved in html format

### ISSUE THREAD

**Issue by chaitujil** [agershun/alasql#484]
![image](https://cloud.githubusercontent.com/assets/13523941/11666606/f3e2c2f2-9db2-11e5-87d8-650b8d855ffa.png)

In IE9 I get this above window before saving though the file is being saved as filename.xls. Also when I try to open the saved file it gives me this below popup message though I can continue by clicking yes

![image](https://cloud.githubusercontent.com/assets/13523941/11666636/13687054-9db3-11e5-92a8-728767b6e334.png)

Is there anyway that I can avoid this?

**Comment by mathiasrw** [comment]
Would be great if you could give us the code that replicates this error

**Comment by nickdeis** [comment]
The bottom part is expected behavior I think. Most "export to excel" are really "export to a HTML3 table with inline styling" which excel can convert into a table.

**Comment by chaitujil** [comment]
I have this

// This below line will create the xls file
            alasql('SELECT ' + tableheaders + ' INTO XLS("' + filename + '.xls",{headers:true}) FROM ?',
                [items.sort(excel_comparator)]);

**Comment by nickdeis** [comment]
The latter part is more than likely a mime type issue.
IE9 has it's own SaveAs method

**Comment by mathiasrw** [comment]
I dont have accesss to IE 9

Could I ask you to click "export" in the jsfiddle here and tell me if you experience the same problem?

http://jsfiddle.net/2f1vz2cm/

**Comment by chaitujil** [comment]
Yes. same

![image](https://cloud.githubusercontent.com/assets/13523941/11688912/eadabaaa-9e54-11e5-8ba8-072d1d1389e1.png)

**Comment by mathiasrw** [comment]
I found that the library we use to save the file only supports ie10+

https://github.com/eligrey/FileSaver.js#supported-browsers

sorry...

**Comment by chaitujil** [comment]
:(

**Comment by chaitujil** [comment]
Some online research says if you can change the type of file being saved to "application/vnd.ms-excel" it will be saved as an excel file instead of html. Is it possible?

**Comment by chaitujil** [comment]
I have issue#2 even with latest Chrome. Some online research says if you can change the type of file being saved to "application/vnd.ms-excel" it will be saved as an excel file instead of html. Is it possible?

**Comment by mathiasrw** [comment]
Hmm. Looks like there is something wrong with the excel formatter. What version of excel are you using?

**Comment by chaitujil** [comment]
Excel 2013

**Comment by mathiasrw** [comment]
OK - I have created a new issue with this specifik topic
