### ISSUE TITLE
SQL date type?

### ISSUE THREAD

**Issue by agerard** [agershun/alasql#486]
Not so much an issue as requesting info - very excited to see if I can make this work for my project. I've searched around a bit but not yet found much on the use of dates, date formats, and clauses (like 'between') which is something I'll need to deal with if using alasql. Is there a resource you can point me to? Thanks!
(p.s. after another search I did find this:https://github.com/agershun/alasql/wiki/Date, which may be all I need....)

**Comment by mathiasrw** [comment]
Great. Ill close this issue. Just create a new one if needed. Its always best to state an issue as a clear question so we can be as helpfull as possible...
