### ISSUE TITLE
Multiple positional operator in alasql ?

### ISSUE THREAD

**Issue by Mcfloy** [agershun/alasql#495]
Hi, i'd like to change a specific value of a nested array, but in mongodb the way to do this is to use a positional operator, unfortunately it works for a one dimension array and not multiple levels.

For some example, that's what some people like me expect to have : https://jira.mongodb.org/browse/SERVER-831

But i don't know how to make it in SQL (i mean, from a mongodb database).

I work on the Meteor.users database, that looks like (if i do a find method with only the "playlist" field)
```
{
    "_id" : "2mA82CTSeeTrvMxfR",
    "playlists" : 
    [
        {
            "name" : "Electro",
            "songs" : 
            [
                {
                    "id" : "dMEwEdkoPLw",
                    "name" : "Moe Shop - You Look So Good",
                    "position" : "1" 
                },
                {
                    "id" : "S927n1xUkAM",
                    "name" : "Vexento - Magenta",
                    "position" : "2"
                }
            ]
        }
    ]
}
```

(What i want to just to swap the "position" value of this two items, but considering that the playlist could contains a lot of songs)

For the security question : each name of playlists are unique, and the id of songs is the id of the youtube video (and unique)

I tried: 
```
Meteor.users.update({_id: Meteor.userId(), "playlists.name": playlistName, "playlists.$.songs.id": src.id}, {$set: {"playlists.$.songs.$.position": tgt.position}});
Meteor.users.update({_id: Meteor.userId(), "playlists.name": playlistName, "playlists.$.songs.id": tgt.id}, {$set: {"playlists.$.songs.$.position": src.position}});
```
but i got an error because MongoDB don't handle multiple positional operator.

Thanks to take your time to answer me :)

**Comment by agershun** [comment]
AlaSQL has a special operator for nested search in JSON objects. I prepared the example with data you provided (see this file [test385.js](https://github.com/agershun/alasql/blob/develop/test/test385.js) with yor data). This is non-standard SQL extension, but we hope, it will be helpful in complex JSON searches and modifications.

The core AlaSQL statement is:
```sql
    alasql('SEARCH playlists/songs/WHERE(id=$1) SET(position=$2) FROM $0',[data1,"S927n1xUkAM","1"]);
```

Here:
* ```SEARCH ... FROM ...``` is JSON search operator
* ```$0, $1, $2``` are parameters (you can use ```?``` as well - I just wanted to change the order of parameters in the query)
* ```playlist``` - is the propery (it is kind of ```a.playlist``` in JavaScript)
* ```/``` - search over all array elements
* ```songs``` - find element with this property 
* ```/WHERE(id=?)``` -  find all elements where id is equal to parameter
* ```SET(position=1)``` - set property ```position``` to ```1```

You can find other examples of SEARCH operator in test files (test300.js - test329.js). Sorry for poor documentation :(

**Comment by agershun** [comment]
I just added [test386.js](https://github.com/agershun/alasql/blob/develop/test/test386.js) with AlaSQL solution for the [MongoDB request page](https://gist.github.com/durran/342738)

Here the key statements are:
```sql
    -- search record at second level
    SEARCH /medications/prescriptions/WHERE(id=77) SET(quantity=30) FROM ?

    -- search record at any nested level started with 1
    SEARCH /+ WHERE(id=77) SET(quantity=31) FROM ?

    -- search record at any nested level started with base level
    SEARCH / * WHERE(id=77) SET(quantity=31) FROM ?
```

Note: I use space between ```/``` and ```*``` to prevent mix with comment ```/*```

**Comment by mathiasrw** [comment]
Test confirmed !
