### ISSUE TITLE
Export to excel - How to just open the file instead of saving it?

### ISSUE THREAD

**Issue by chaitujil** [agershun/alasql#498]
This is just a question to know if alasql has a way to show a prompt to "open or save" the .xls file created in IE. Correct me if this is completely out of scope for alasql.

I am creating a .xls file like below

// This below line will create the xls file
            alasql('SELECT ' + tableheaders + ' INTO XLS("' + filename + '.xls",{headers:true}) FROM ?',
                [items.sort(excel_comparator)]);

In IE I see this below

![image](https://cloud.githubusercontent.com/assets/13523941/12026149/e51d3512-ad7b-11e5-9f4a-352787ac86d6.png)

Only "Save" button :(. How can I make IE to show "Open" button too?

**Comment by mathiasrw** [comment]
The library does not support to open files for you. 

I recommend that you take a look at http://www.html5rocks.com/en/tutorials/file/dndfiles/ to get closer to what you are looking for.
