### ISSUE TITLE
DELETE FROM statement for LOCALSTORAGE

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#50]
Does not work without WHERE clause

**Comment by ypogeios** [comment]
Any progress with the delete command?

**Comment by agershun** [comment]
Sorry, not yet.

**Comment by agershun** [comment]
Fixed. Sorry for delay. See test240.js

**Comment by mathiasrw** [comment]
I cant find the new test running ```DELETE * FROM one```

I have looked in the following branches

https://github.com/agershun/alasql/blob/develop/test/test240.js

https://github.com/agershun/alasql/blob/version-0.0.41/test/test240.js

Have you pushed the change?

**Comment by agershun** [comment]
Wonderful... SourceTree simply overwrite my changes. 
Fortunately the copy was  saved. I will resotre it.

**Comment by mathiasrw** [comment]
Losing changes is NOT cool...

SourceTree normally dont do anything but calling git - but sometimes Git can get a little funny. 
If you would like to avoid this in the future you can click the create feature (first press git flow button) - and then just have changes in a feature - and when it works merge it into develop...

Let me know when the change is up

**Comment by agershun** [comment]
I used git-flow. Probably one Udacity course is not enough... I will fix it.

**Comment by agershun** [comment]
The ```develop``` branch looks Ok, but ```master``` still does not want to updates...

**Comment by agershun** [comment]
Original question is solved.

For master branch I opened https://github.com/agershun/alasql/issues/127
