### ISSUE TITLE
SELECT 1 bug

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#501]
First bug to fix from [here](https://github.com/agershun/alasql/blob/97cfde1ec26c53f1d776a827895ea9ccaeae6141/TESTLOG.md)
```sql
    SELECT 1 FROM t1 WHERE 1 IN (SELECT 1)
```
Error message:
```
context is not defined
```

**Comment by agershun** [comment]
Very strange error. It occurs from command line:
```bash
    alasql 'SELECT 1 FROM @[1,2] WHERE 1 IN (SELECT 1)'
```
but does not inside the Mocha test....

**Comment by agershun** [comment]
Fixed. Hope now we can pass at least one SQLLOGICTEST file [in2.test](https://github.com/mathiasrw/alasql-logictest/blob/master/sqllogic/test/evidence/in2.test). 

@mathiasrw May I ask you to run the test again?

**Comment by mathiasrw** [comment]
Sure !

**Comment by mathiasrw** [comment]
ZAP - you have done it again!

Solution to this issue tested and confirmed...

The rest of the tests are still running. Ill update the repo as soon as they are done. 

Regarding  [in2.test](https://github.com/mathiasrw/alasql-logictest/blob/master/sqllogic/test/evidence/in2.test) we get the following at the moment:

---- ---- ---- ---- ---- ---- ----
### 2/125 [`./test/evidence/in2.test`](https://github.com/mathiasrw/alasql-logictest/blob/master/sqllogic/./test/evidence/in2.test)

_Mimic sqlite_

```sql
SELECT 1 FROM t1 WHERE 1 IN (SELECT 1,2)

No exception thrown
```

_Fail found for statement setting up data so skipping rest of tests_

#### ☓ Ran 53 tests as sqlite

* 3 skipped
* 1 failed
* 92% was OK

Time: 465ms

**Comment by mathiasrw** [comment]
So basically its expecting to get an error on the following 4 statements

```sql
statement error
SELECT 1 FROM t1 WHERE 1 IN (SELECT 1,2)

statement error
SELECT 1 FROM t1 WHERE 1 IN (SELECT x,y FROM t1)

statement error
SELECT 1 FROM t1 WHERE 1 IN (SELECT * FROM t1)

statement error
SELECT 1 FROM t1 WHERE 1 IN (SELECT min(x),max(x) FROM t1)
```

**Comment by agershun** [comment]
I will check this tonight after LegoLand (try to get some inspiration there:) )...

**Comment by mathiasrw** [comment]
No stress :)

**Comment by agershun** [comment]
Just remember that Lego is from Denmark )))

**Comment by mathiasrw** [comment]
It iiissss - and we are very proud of it. I have a feeling its not the one in Denmark you are at :)

**Comment by mathiasrw** [comment]
https://github.com/agershun/alasql/blob/develop/TESTLOG.md is updated.
