### ISSUE TITLE
Problem with the test and REPLACE

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#505]
_Moving issues from https://github.com/mathiasrw/alasql-logictest_

This is a the part of the [test file](https://github.com/mathiasrw/alasql-logictest/blob/master/sqllogic/test/evidence/slt_lang_replace.test)

Last lines are:
```
REPLACE INTO t1 VALUES(4, 'replace (new)')

query IT rowsort
SELECT x, y FROM t1 WHERE x=4
----
4
replace (new)
```

But here there are no any lines with ```x=4```. How ```REPLACE INTO``` should work here? Should it insert new value or just skip?

**Comment by mathiasrw** [comment]
Well.... its a good question. It seem a bit counter intuitive to insert when replace is requested. 

To comply with the other DBs I recommend that `REPLACE` would be implemented as a short version of `INSERT OR REPLACE`

**Comment by agershun** [comment]
Fixed.

**Comment by mathiasrw** [comment]
ZAP !

# SQLlogictest results for AlaSQL 0.2.2-pre-develop+151231.53429

_2016-01-02T16:53:43.138Z_

This is a subset of the total 622 tests.
Results from 1 test files:

---- ---- ---- ---- ---- ---- ----
### 1/1 [`./test/evidence/slt_lang_replace.test`](https://github.com/mathiasrw/alasql-logictest/blob/master/sqllogic/./test/evidence/slt_lang_replace.test)

_Mimic sqlite_
#### ★ Ran 14 tests as sqlite

* 100% was OK

Time: 208ms

-----------------------------

## Final result

* Skipped tests: 0
* Failed tests: 0
* Total tested: 14
* Final score: 100 % was OK

Total script time: 278ms
