### ISSUE TITLE
IndexedDb is broken

### ISSUE THREAD

**Issue by mbektimirov** [agershun/alasql#512]
``` javascript
alasql('CREATE INDEXEDDB DATABASE IF NOT EXISTS geo;\
        ATTACH INDEXEDDB DATABASE geo; \
        USE geo; \
        DROP TABLE IF EXISTS cities; \
        CREATE TABLE cities;')
```

This simple code from the test produces errors:
![image](https://cloud.githubusercontent.com/assets/918009/12076266/a7f51d32-b1c5-11e5-8c20-4d9a7a9cf3bf.png)

**Comment by mathiasrw** [comment]
Can you please tell me the output of the following?

```js
alasql('CREATE INDEXEDDB DATABASE IF NOT EXISTS geo;\
        ATTACH INDEXEDDB DATABASE geo;')
```

**Comment by mbektimirov** [comment]
![image](https://cloud.githubusercontent.com/assets/918009/12078743/70a61db0-b240-11e5-89b7-5cfb10b95ab9.png)

**Comment by agershun** [comment]
You fix it with callback function:
```js
alasql('CREATE INDEXEDDB DATABASE IF NOT EXISTS geo;\
        ATTACH INDEXEDDB DATABASE geo; \
        USE geo; \
        DROP TABLE IF EXISTS cities; \
        CREATE TABLE cities;',[],function(){ 
             // done
        })
```
I will try to eliminate this requirement.

**Comment by adrienlochon** [comment]
Did this ever got fixed?

I really, really need to use sync functions, so the callback workaround doesn't do it for me.

Thanks!!!

**Comment by mathiasrw** [comment]
IndexDB is always always async for AlaSQL because IndexDB itself is async. I suggest you have a look at https://github.com/agershun/alasql/wiki/Async#lazy-promise-notation and combine it with the `await` statement of ES6
