### ISSUE TITLE
|| operator

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#514]
```||``` in SQLite is string concatination.

```sql
    SELECT 'wolf' || 'hound';
    wolfhound
```

Currently. in AlaSQL ```||``` is like JavaScript ```||```. Should we keep current behaviour or change it to SQLite way?

**Comment by mathiasrw** [comment]
Interesting. 

I dont see it as a problem in the simple version of `SELECT` part - as it does not makes good sense to only white `wolf`  - but when we are comparing elements its suddenly an issue. 

I found some interesting aspects:

- Running `SELECT 'ab' == 'a' || 'b'` in sqlite returns `1``
- Running `SELECT 'ab' == 'a' || 'b'` in postgres give a parse error (operator does not exist: unknown == unknown)
- Running `SELECT 'ab' = 'a' || 'b'` in postgres gives `t`(`true`?)
- Running `SELECT 'ab' == 'a' || 'b'` in mysql gives a parse error
- Running `SELECT 'ab' = 'a' || 'b'` in mysql gives a parse error
- Running `` in alasql gives ``.
- Running `` in alasql gives ``.
- Running `` in alasql gives ``.
- Running `SELECT 'wolf' || 'hound';` in alacon gives `[ { '\'wolf\' OR \'hound\'': 'wolf' } ]` (interesting with the `OR`)

in an ideal world we support the good parts - but stay sane

**Comment by agershun** [comment]
Now AlaSQL uses JS ```||```. I am going to replace it with:
```js
    alasql.stdlib.merge = function(a,b) {return ''+a+b}
```

**Comment by mathiasrw** [comment]
This might be a good  case to differentiate the different engine flavours?

**Comment by agershun** [comment]
Let's keep it simple...

**Comment by mathiasrw** [comment]
:+1:

**Comment by agershun** [comment]
Done

**Comment by mathiasrw** [comment]
I have tested all queries and placed the result here. 

Looks good - I am a bit surprised about row `1` - I have a feeling that result is not really useful. could it return `undefined` or `true`?

 # | Query 						| SQLite | Postgres 	| MySQL | AlaSQL
----|----------- | ------------- | ------------- | ------------- | -------------
1 | `SELECT null || true`		|	error	|	`null`		|	`1`		|	`undefinedtrue`
2 | `SELECT true || 'a'`	|	error 	|	`truea` 	|	`1`		|	`truea`
3 | `SELECT 'a' || 'b'`	|	`ab`	|	`ab`			|	`0`		|	`ab`
4 | `SELECT 'ab' = 'a' || 'b'`		|	`1`	|	`t`			|	`0` |	`true`
5 | `SELECT 'ab' = 'ab' || 'b'`	|	`0`	|	`f`			|	`1`		|	`false`
6 | `SELECT 'ab' = ('a' || 'b')`	|	`1`	|	`t`			|	`1` 		|	`true`
7 | `SELECT 'ab' = ('a' || 'ab')`	|	`0`	|	`f`			|	`1`		|	`false`

**Comment by agershun** [comment]
I would prefer if test ```SELECT NULL || "a"``` and ```SELECT "a" || NULL``` will return ```a```. 

What other SQL databases gives here?

**Comment by mathiasrw** [comment]
a is also a good solution

I have no access to oracle, mssql or db2

**Comment by agershun** [comment]
I will check with SQL Server on Monday

**Comment by mathiasrw** [comment]
> I would prefer if test SELECT NULL || "a" and SELECT "a" || NULL will return a.

I agree with the `a` as result makes the most sense. 

For MsSQL 2015 `||` gives parse error

For DB2 `null` is not really a `null` but i found that 
- `SELECT CAST(NULL AS INT) || "a"` gives `--` 
- `SELECT "a" || CAST(NULL AS INT)` gives `------------`

**Comment by mathiasrw** [comment]
> I will check with SQL Server on Monday

Did you find out anything?

**Comment by agershun** [comment]
```SELECT  'a'+NULL``` and ```SELECT  NULL+'a'``` returns ```NULL```.

There is no ```||``` operator.

**Comment by mathiasrw** [comment]
Ok. Lets keep the plan about returning "a"

**Comment by agershun** [comment]
So. we will translate ```a||b``` in the something like this in JavaScript: 
```js
     ''+(a||'')+(b||'')
```
ok?

**Comment by mathiasrw** [comment]
:+1:
