### ISSUE TITLE
GLOB operator

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#515]
Does AlaSQL really need [BLOB operator](http://www.tutorialspoint.com/sqlite/sqlite_glob_clause.htm)?

**Comment by mathiasrw** [comment]
I cant see why not if we want to be compatible.

I see it as a simple regexp test with something along the lines

```js
function isGlobFound(glob,str){
	var globRe = glob
					.replace(/[^0-9A-Za-z\?\*]/g, "\\$1")
					.replace(/\?/g, ".")
					.replace(/\*/g, ".*");
	var re = new RegExp("^"+globRe+"$", "");
	return re.test(str);
}
isGlobFound("xxx","xxxx")
false
isGlobFound("xxx*","xxxx")
true
isGlobFound("xxx?","xxxx")
true
isGlobFound("?xxx?","xxxx")
false
isGlobFound("?xxx*","xxxx")
true
```


lets make sure we only create the `re` variable once - and only have the `.test` part invoked for each str value

**Comment by agershun** [comment]
Done.

**Comment by mathiasrw** [comment]
Awesome !

Hmm, found that 

````js
alasql("value of select 'xx??' glob 'xxyx'")
````

gives `false` but I would have expected `true`

I have to dig a bit more to find info

**Comment by agershun** [comment]
Question: how it should work:
```
pattern GLOB string
```
or vice verse
```
string GLOB pattern
```
?

**Comment by mathiasrw** [comment]
Ohh - you are very very right ! its string first. Im sorry that I did not check that. 

The tests are all good :+1:
