### ISSUE TITLE
Test in browser

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#519]
To avoid hidden browser specific issues (as #517) it would be good to be able to run all the tests from a .html file that can be opened in different browsers. 

It could be inspired by something like https://nicolas.perriault.net/code/2013/testing-frontend-javascript-code-using-mocha-chai-and-sinon/ (I am sure there are many other options)

We need to be able to reuse the same test files as when testing node.

**Comment by agershun** [comment]
There is a special file: test/index.html which runs mocha tests in browsers. I did not updated for some time, but now it is more or less updated.  Unfortunately, AlaSQL produces some errors into it, so it is a new set of challenges for us.

I usually run local server in ```/alasql``` directory:
```bash
    > cd alasql
    alasql> http-server
```
Then run this page from browser:
```
    http://localserver:8080/test
```

@mathiasrw Could you adjust test374 and test376, so they can work in browser?

**Comment by agershun** [comment]
We have 42 (!) failures in browser test. It is time to fix them (including IndexdDB problems)

**Comment by mathiasrw** [comment]
I got the following stats:

### Firefox 42
- `alasql@0.2.2-pre-develop+160105.205858`
- Passes 898
- Failures: 22


### Safari 9
- `alasql@0.2.2-pre-develop+160105.205858`
- Passes 900
- Failures: 20


### Chrome 47
- `alasql@0.2.2-pre-develop+160105.205858`
- Passes 863
- Failures: 54

**Comment by mathiasrw** [comment]
> Could you adjust test374 and test376, so they can work in browser?

Only saw this now. Yes for sure!

**Comment by agershun** [comment]
I have changed browsers tests and fixed IndexedDB. @mathiasrw Could you pull the changes?

**Comment by mathiasrw** [comment]
Sure!

**Comment by mathiasrw** [comment]
### Firefox 42
 - `alasql@0.2.2-pre-develop+160105.205858`
 - Passes 903
 - Failures: 17


### Safari 9
- `alasql@0.2.2-pre-develop+160105.205858`
- Passes 905
- Failures: 15



### Chrome 47
- `alasql@0.2.2-pre-develop+160105.205858`
- Passes 920
- Failures: 0

**Comment by agershun** [comment]
Thnx! It is a good time to study debugger tools for Safary/FF/IE. BTW we need to check with IE also (I will run tests tomorrow)

**Comment by mathiasrw** [comment]
:+1:

**Comment by agershun** [comment]
There is a big difference how FF and Chrome treat ```new Date(value)``` expression. 

FF is more sensitive to incoming date formats...

**Comment by mathiasrw** [comment]
When we build a modular system we could make it possible to use the date time magic from [momentsjs](http://momentjs.com/)

**Comment by mathiasrw** [comment]
Made a solution so we dont need to remember to add new tests to the browser test.  

If we dont want a test to be included in the browser we can add `if(window) return;` inside `describe(...` function of test. 

Please pull and run `npm run test:browser` 

There is a - ehh - funny feature when you run it in safari - im working on it. 

Last stats: 

### Chrome 47
- `alasql@0.2.2-pre-develop+160105.205858`
- Passes 1043
- Failures: 0 (!)

### Firefox 16
 - `alasql@0.2.2-pre-develop+160105.205858`
- Passes 970
- Failures: 73

### Safari 9
- `alasql@0.2.2-pre-develop+160105.205858`
- Passes 1007
- Failures: 36

**Comment by agershun** [comment]
Please, use:
```js
   if(typeof exports != 'object') {...}
```
instead of:
```js
   if(window) {...}
```
Try to run ```mocha .``` in Node.js now :)

**Comment by mathiasrw** [comment]
:+1:

**Comment by mathiasrw** [comment]
Ran the full SQLlogictest - and last version make sure that 3 new test files are 100% ok - woohooo !!!

So now we have 135 out of 622 files 100% OK

**Comment by agershun** [comment]
:+1: 

Now if you run ```mocha .``` it opens the browser with empty page. How to eliminate this?

**Comment by mathiasrw** [comment]
Hmm. That is strange. 

I have changed no files that I did not create for the new setup. 

I have to look into that.

**Comment by mathiasrw** [comment]
Can reproduce error any more.
