### ISSUE TITLE
Looking for various statistical operations

### ISSUE THREAD

**Issue by agerard** [agershun/alasql#521]
Hi, I'm wondering if median (not average) or standard deviation are available as alasql query aggregators or would I need to build them (or use other libraries for this)? If so, any tips would be appreciated, since the documentation on aggregators seems a bit slim. Thanks!

**Comment by agershun** [comment]
You can use:
* AVG()
* MEDIAN()
* VAR()
* STDEV()
* VARP()
* STD()

Please, let us know if you need other functions.

**Comment by mathiasrw** [comment]
I will expand the wiki with this info

**Comment by agerard** [comment]
Great, thanks for the prompt reply. I had tried those - but I apparently also had some data problems. Now that I've corrected them it's working!
