### ISSUE TITLE
How change alasql separator for csv file

### ISSUE THREAD

**Issue by thamerbelfkihthamer** [agershun/alasql#522]
hello every one , i want change ' , ' csv separator to ' ;  ' . 

how i can do it ?

**Comment by agershun** [comment]
You can specify ```separator``` property in CSV function:
```sql
   SELECT * FROM CSV("a.csv",{separator:";"});
```

**Comment by mathiasrw** [comment]
You can see more here: https://github.com/agershun/alasql/wiki/Csv

Please reopen if you have more questions

**Comment by thamerbelfkihthamer** [comment]
ok think you
