### ISSUE TITLE
bin/alasql1.js

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#526]
I see that the bin for `alasql>` is set to `bin/alasql.js` in https://github.com/agershun/alasql/blob/develop/package.json#L63

but in the [`bin/` folder](https://github.com/agershun/alasql/tree/develop/bin) the `alasql.js` file is updated 6 monts ago while the `alasql1.js` file got updated 9 days ago. 

Is there any reason the changes to `alasql1.js` are not implemented into `alasql.js` ?

**Comment by agershun** [comment]
1. Sorry, it was temporary file to test some functionality locally (it
loads 'alasql.min.js' from local repository, not the global one). I thought
I cleaned it.

Let's create a special flag for local debugging, e.g.

alasql --local "SELECT..."

so we can test it without installing globally.

2. What do you think if we merge alasql and alaserver into one file, so  we
can start local server with flag?

> alasql --server 8081




2016-01-11 17:10 GMT+03:00 Mathias Rangel Wulff <notifications@github.com>:

**Comment by mathiasrw** [comment]
I like the idea of getting it all together in one file. 

I suggest using the [yargs](https://github.com/agershun/alasql/blob/e055d4d43ec6087cff40ff9eccbe305feb82451e/test/test374.js) modules as used in https://github.com/agershun/alasql/blob/e055d4d43ec6087cff40ff9eccbe305feb82451e/test/test374.js for getting the arguments structured.

**Comment by agershun** [comment]
Agree. I never used it before, Can you change a structure of this file?

2016-01-11 17:44 GMT+03:00 Mathias Rangel Wulff <notifications@github.com>:

**Comment by mathiasrw** [comment]
I will !
