### ISSUE TITLE
Variable do a select

### ISSUE THREAD

**Issue by cbugari** [agershun/alasql#530]
Hello good day. Variable I need to do a query. If the WHERE condition is met will be another one and if the WHERE condition is met will be another .No can achieve, try concatenating the string of SELECT ... It may be feasible. Copy example below. Thank you...

Example: 

var data = [
  {"fecha_Venta":"2012-02-28","product":"pepe", "Sales":12500}
  , {"fecha_Venta":"2012-12-28","product":"pepa", "Sales":800}
  , {"fecha_Venta":"2012-09-20","product":"pepi", "Sales":1}
  , {"fecha_Venta":"2012-12-20","product":"pepo", "Sales":1}
           ]
var wdata = " WHERE product IN (\" pepe\") ";

var res = alasql('SELECT YEAR(fecha_Venta) AS meses, Sales, product FROM ?' + "'" + wdata + "'" ,[data]);

showResult(res)

function showResult(x){
    document.getElementById('result').textContent += JSON.stringify(x,  null, '\t');
}

**Comment by agershun** [comment]
You need to remove a space inside the string (```\" pepe\"``` to ```\"pepe\"```).

See the [jsFiddle example](http://jsfiddle.net/agershun/sfmm18pp/2/)

**Comment by cbugari** [comment]
Excelente. Muchas Gracias por su pronta respuesta.
Cesar

**Comment by cbugari** [comment]
Excellent. Thank you for your prompt response.
Cease

**Comment by agershun** [comment]
¡Con mucho gusto! 

https://www.youtube.com/watch?v=Kuynu_0ZvlU :)
