### ISSUE TITLE
Performance: Use ECMA6 template strings/[...].join(""), not +

### ISSUE THREAD

**Issue by nickdeis** [agershun/alasql#535]
[First tip on how to improve js performance](https://developers.google.com/speed/articles/optimizing-javascript) from google dev is how using + to build strings is very slow

This isn't true in Firefox because Firefox uses [ropes](https://blog.mozilla.org/javascript/2014/07/21/slimmer-and-faster-javascript-strings-in-firefox/) instead of strings.

I often see this in the codebase:
```javascript
''
+ 'alasql.databases[alasql.useid].objects['
+ 	leftJS()
+ ']["'
+	this.right
+ '"]';
```
When what we should be doing is using Babel like so
```javascript
`alasql.databases[alasql.useid].objects[${leftJS()}]["${this.right}"]`
```
Which may transpile to
```javascript
['alasql.databases[alasql.useid].objects[',leftJS(),']["',this.right, '"]'].join("");
```
I say "may" because sometimes it transpile to former expression.

Either way, it's far more readable.
-Nick

**Comment by agershun** [comment]
:+1: Thank you! I will read about this.

**Comment by mathiasrw** [comment]
Have been playing with babel in https://github.com/agershun/alasql/tree/feature/babel

Its about 2 minutes to compile from `src`. I have a feeling its not ment to compile very large chunks of code. We might want to focus on this when we are in a post-monolith-`src/`-structure period.

**Comment by nickdeis** [comment]
Probably the jison output. That thing can hardly be minified

**Comment by mathiasrw** [comment]
:+1:

**Comment by mathiasrw** [comment]
For all of us to read when we will write ES6: https://github.com/DrkSephy/es6-cheatsheet

**Comment by mathiasrw** [comment]
Was wondering if it made sense to make a alasql.es6.js version that is not compiled to es5.the idea was to let the npm version be .es6 and the src/ using only what is suppoerted: https://nodejs.org/en/docs/es6/

but then i found https://kpdecker.github.io/six-speed/ where its very clear that there is more a performance hit than not of using the es6  syntax - so guess we will postpone e6 things until things got more mature?

**Comment by nickdeis** [comment]
I'm also learning that Array#join is no longer the fastest way to concat strings.
Apparently almost all modern browsers now optimize string concatenation using either ropes or internal arrays that are basically StringBuilder's.
Maybe this issue should be closed?
Cool discussion never the less.

**Comment by mathiasrw** [comment]
Lets close it and keep an eye on when ES6 is more supported.

**Comment by mathiasrw** [comment]
Just found this: https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016

leaving it here so I can find it again
