### ISSUE TITLE
XLS File path Parse Errors

### ISSUE THREAD

**Issue by Cyberider** [agershun/alasql#542]
[AlaSQL_ParseErrors_FilePath.js.zip](https://github.com/agershun/alasql/files/93517/AlaSQL_ParseErrors_FilePath.js.zip)
* Windows 10
* Javascript vES6
```
C:\Users\Public\DEV\Dev\nodes\orientdb\v0.0.1>node --version
v5.4.0
```
```json
// found in C:\Users\Public\DEV\Dev\nodes\orientdb\v0.0.1\node_modules\alasql\package.json
  "_id": "alasql@0.2.2",
  "_inCache": true,
  "_installable": true,
  "_location": "/alasql",
  "_nodeVersion": "5.3.0",

  "_npmVersion": "3.3.12",

  "dependencies": {
    "dom-storage": "^2.0.1",
    "es6-promise": "^3.0.2",
    "lodash": "^3.10.0",
    "xlsjs": "^0.7.5",
    "xlsx": "^0.8.0"
  }
```

**ERROR 1**
```javascript
"use strict";
var alasql = require('alasql');

// ERROR 1
var fileXLS = "http://www.iso15022.org/MIC/ISO10383_MIC.xls";
alasql('SELECT * FROM XLS(' + fileXLS + ', {headers:true})',[],function(data){
    console.log(data);
});
```
```
        throw new Error(str);
        ^

Error: Parse error on line 1:
...LECT * FROM XLS(http://www.iso15022.org/
-----------------------^
```

**ERROR 2**
```javascript
// ERROR 2
alasql('SELECT * FROM XLS("http://www.iso15022.org/MIC/ISO10383_MIC.xls", {headers:true})',[],function(data){
    console.log(data);
});
```
```
                    throw err;
                    ^

Error: ENOENT: no such file or directory, open 'c:\Users\Public\DEV\Dev\nodes\orientdb\v0.0.1\http:\www.iso15022.org\MIC\ISO10383_MIC.xls'
    at Error (native)
```

**ERROR 3**
```javascript
// ERROR 3
var fileXLS = "C:\\Users\\Public\\DEV\\Dev\\Data Sets\\Financial\\MIC\\2016-01-25 ISO10383_MIC.xls";
alasql('SELECT * FROM XLS(' + fileXLS + ', {headers:true})',[],function(data){
    console.log(data);
});
```
```
        throw new Error(str);
        ^

Error: Parse error on line 1:
SELECT * FROM XLS(C:\Users\Public\DEV\D
-------------------^
```

**ERROR 4**
```javascript
// ERROR 4
alasql('SELECT * FROM XLS("C:\\Users\\Public\\DEV\\Dev\\Data Sets\\Financial\\MIC\\2016-01-25 ISO10383_MIC.xls", {headers:true})',[],function(data){
    console.log(data);
});
```
```
                    throw err;
                    ^

Error: ENOENT: no such file or directory, open 'C:\UsersPublicDEVDevData SetsFinancialMIC6-01-25 ISO10383_MIC.xls'
    at Error (native)
```

**ERROR 5** (THIS HACK WORKS... but look at the backslash escape pattern hack I had to use)
```javascript
// ERROR 5 (THIS HACK WORKS... but look at the backslash escape pattern hack I had to use)
alasql('SELECT * FROM XLS("C:\\Users\\\\Public\\\\DEV\\\\Dev\\\\Data Sets\\\\Financial\\\\MIC\\\\2016-01-25 ISO10383_MIC.xls", {headers:true})', [], function (data) {
    console.log(data);
});
```

**ERROR 6**
```javascript
// ERROR 6
var fileXLS = "C:\\Users\\\\Public\\\\DEV\\\\Dev\\\\Data Sets\\\\Financial\\\\MIC\\\\2016-01-25 ISO10383_MIC.xls";
alasql('SELECT * FROM XLS(' + fileXLS + ', {headers:true})',[],function(data){
    console.log(data);
});
```
```
        throw new Error(str);
        ^

Error: Parse error on line 1:
SELECT * FROM XLS(C:\Users\\Public\\DEV
-------------------^
```

**ERROR 7**
```javascript
// ERROR 7
var fileXLS = "C:\\Users\\Public\\DEV\\Dev\\Data Sets\\Financial\\MIC\\2016-01-25 ISO10383_MIC.xls";
alasql('SELECT * FROM XLS(' + fileXLS + ', {headers:true})',[],function(data){
    console.log(data);
});
```
```
        throw new Error(str);
        ^

Error: Parse error on line 1:
SELECT * FROM XLS(C:\Users\Public\DEV\D
-------------------^
```

**Comment by mathiasrw** [comment]
Thanks for a great error report !

The final string must be of the location must be in `'` or `"` so error 1, 3, 6 and 7 makes sense that they do not work. If you use the following notation you can avoid to remember to escape the string of the location:

`alasql('SELECT * FROM XLS(?, {headers:true})',[fileXLS],function(data){...`

Error 2: nice input - lets make it so it can handle a url here!

Regarding error 5 - we do have a double layer of escaping backslash. It's a nasty parser thing we are having on the roadmap to kill. Only workaround right now is that you can often use slash instead of backslash on most systems.

**Comment by Cyberider** [comment]
@mathiasrw 
Thank you for the quick reply.

**A)** My bad on forgetting to put back in the double quotes. However even when I now try that it still throws errors because of that double layer of escaping backslash.

**B)** Trying your suggested notation/syntax fails as well because if a directory of file name starts with numbers it thinks it is special character encoding or octal literals, etc.
```javascript
// ERROR 8 (using different suggested syntax)
var fileXLS = "C:\Users\Public\DEV\Dev\Data Sets\Financial\MIC\2016-01-25 ISO10383_MIC.xls";
alasql('SELECT * FROM XLS(?, {headers:true})',[fileXLS],function(data){
    console.log(data);
});
```
```
var fileXLS = "C:\Users\Public\DEV\Dev\Data Sets\Financial\MIC\2016-01-25 ISO10383_MIC.xls";
                                                               ^^
SyntaxError: Octal literals are not allowed in strict mode.
```

**ERROR 2** (Url to file)
I tried using URL's because I have seen others use it on stackexchange and Andrey's fiddle example here:
http://jsfiddle.net/agershun/1o2xq1yh/2/
Or does that only work with CSV and not JSON, XLS and others?
BTW his example doesn't work because of 404 error on the URL and maybe cross-site-scripting problems from other URL's I tried.

**C)** (forward slash "/")
This works and I'm on a Windows system! You NEVER use forward slashes in a Windows path so I doubt a windows user would even think of trying this.
```javascript
// ERROR 3.1 (using forward slashes in a Windows path!)
var fileXLS = "C:/Users/Public/DEV/Dev/Data Sets/Financial/MIC/2016-01-25 ISO10383_MIC.xls";
alasql('SELECT * FROM XLS("' + fileXLS + '", {headers:true})',[],function(data){
    console.log(data);
});
```
Thank you for your help @mathiasrw

**Comment by mathiasrw** [comment]
> A) My bad on forgetting to put back in the double quotes. However even when I now try that it still throws errors because of that double layer of escaping backslash

Its realy on the list of shitty things to fix. 

> ERROR 2 (Url to file)

This works when you use it in the browser, but for some reason its was not implemented for node. 

We implemented it today, so If you get the last version in https://github.com/agershun/alasql/tree/develop/dist it will work.


> C) (forward slash "/")
Check out http://superuser.com/questions/176388/why-does-windows-use-backslashes-for-paths-and-unix-forward-slashes

Can I close this issue?

**Comment by Cyberider** [comment]
Thank you. You guys are awesome. Close.
:+1:

**Comment by mathiasrw** [comment]
Woohoo !
