### ISSUE TITLE
Url to file

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#543]
for node: If the string passed as location can be tested positive with `/^[a-z]+:\/\//i` It should be treated as url and AlaSQL should download the content of the file. This would make is possible to do something like

```js
alasql('SELECT * FROM XLS("http://www.iso15022.org/MIC/ISO10383_MIC.xls", {headers:true})',[],function(data){
    console.log(data);
});
```

_Spawned from #542_

**Comment by agershun** [comment]
Sorry, I did not understand the issue. Now when browser version of AlaSQL loads file, it checks the ```path``` variable type, and  if this is a ```string```, it genereate ```GET``` request for this URL. Why do we need to make this additional check, could you explain?

Or you mean in Node.js? Now AlaSQL reads file with ```fs.readFile()```.

**Comment by mathiasrw** [comment]
Yes - the issue was from a node related question :)

**Comment by agershun** [comment]
I will use this ```request``` module, ok? Are there any other options?

https://www.npmjs.com/package/request

**Comment by mathiasrw** [comment]
Looks perfect.

**Comment by agershun** [comment]
Done.

**Comment by agershun** [comment]
Please, see the [test418](https://github.com/agershun/alasql/blob/52c975d6adb3f42e686c820b2d32b5bff5bc1df6/test/test418.js)

**Comment by agershun** [comment]
BTW You need to ```npm install```, because I changed ```package.json``` for ```require``` module.

**Comment by Cyberider** [comment]
:+1:
