### ISSUE TITLE
Last release to Meteor 

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#545]
_Spawned from #533_

> We have a problem with updating Meteor (because they changed API). 

How do we get alasql deployed to Meteors atmospherejs ?

**Comment by keyscores** [comment]
I'm interested in seeing this update in atmosphere. What seems to be the trouble? It should just be a question of running some 'meteor' commands locally. 

https://atmospherejs.com/i/publishing

**Comment by mathiasrw** [comment]
It broke when meteor changed something (was it version 1.2?) so the js files could no longer be placed in any parent dir

But it's good to know someone is requesting this. 

I am not strong in meteor - but will try to follow your link and hopefully get it going

**Comment by mathiasrw** [comment]
First the problem was/is that Meteor changed so we cant have `../` in the path from `package.js` to main file. 

After solving this I found that Meteor 1.3 performs static analysis on the packages - so all references to `require(...)` and `__dirname` is blocking - even if never invoked...

AlaSQL is now on Athmosphere: https://atmospherejs.com/agershun/alasql
