### ISSUE TITLE
Extra row in XLSX from URL

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#548]
The document on

https://cdn.rawgit.com/agershun/alasql/6277197ee2db5add9b42c3116f350037e8943cc5/test/test411.xlsx

has headers and 4 rows - but when I say {headers:true} a `count(*)` gives me 5 instead of 4

http://jsfiddle.net/90xqbo58/

**Comment by agershun** [comment]
AlaSQL interpret last line as empty. See the example [here](http://jsfiddle.net/agershun/0wv94kn1/2/)

**Comment by mathiasrw** [comment]
_(You are linking to a TXT example)_

The `COUNT(*)` is correct 

The title could be changed. The problem is that in the data it has the correct 4 rows, and then an extra with no data: http://jsfiddle.net/2xmfdzyL/ (it sthe small `{}` at the bottom thats the problem)

**Comment by mathiasrw** [comment]
:+1:
