### ISSUE TITLE
Extra row for TXT() when ending on new line

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#549]
The document on

https://cdn.rawgit.com/agershun/alasql/9191d4726c8fbce7a615a370ce68b79366c16f7e/test/test157.txt 

has no headers but 8 rows - but when I say {headers:false} a `count(*)` gives me 9 instead of 8

http://jsfiddle.net/0wv94kn1/

**Comment by agershun** [comment]
Here is another situation than in XLSX case, because we need to analyze last line - is there any infotmation on it.

**Comment by mathiasrw** [comment]
Its a "\n" after the last value. 

I suggest we do a `.trim()` when content is downloaded before we do anything else.

**Comment by mathiasrw** [comment]
Test confirmed ok: https://travis-ci.org/agershun/alasql/jobs/103210218
