### ISSUE TITLE
Making DOT operator work for JSON properties

### ISSUE THREAD

**Issue by filipkis** [agershun/alasql#553]
Hi again, 

I was considering if it would be possible to make `.` work instead (or as well as) `->` as operator when accessing JSON. So I went and [tried it out myself](https://github.com/agershun/alasql/compare/develop...filipkis:json-dot) by modifying the parser.

And in fact it does work fine. There is only one catch and that is that first `.` in the expression will be treated as `table.column` so in other words one would always need to start with table alias when using this notation. 

Now I'm fine with that for my case, but I wonder if this is something that can be considered in general for AlaSQL or should I just keep it in my fork. My work is related to [OQL](https://visualvm.java.net/oqlhelp.html) and [YQL](https://developer.yahoo.com/yql/guide/select.html#specifying-the-elements-returned-projection), thus this request is not totally out of the blue.

There are also two other places where `ARROW` token appears (SetPropsList and SearchSelector) where I haven't made it into `ArrowOrDot` because I needed to take a deeper look if that would make sense there or not.

Btw. I didn't run your tests as I didn't find gulp task for it. Is there some documentation on how to execute the tests?

**Comment by agershun** [comment]
1. Tests:
```
> cd test
> mocha .
// or
> mocha test319.js
```

2. Dot or Arrow - we can do it, but we need to understand is left part the table or the property.
```
table.column
column->property
```
We can check this at compiling time (if left part in the list of data sources we will use ```table.column```, if not then ```column.property```.

I am worry about the situation, when table and column have same name. How to resolve this? We can givve priority to the table-column case, and use column-property for all other cases. What do you think?

**Comment by filipkis** [comment]
Oh this is even better then.

And yes, having table.column as priority would definitely make sense.

**Comment by agershun** [comment]
The simplest way to get desired result - is to change code here:

https://github.com/agershun/alasql/blob/develop/src/50expression.js#L827

and here:

https://github.com/agershun/alasql/blob/develop/src/50expression.js#L827

We can check if ```tableid``` is in the list of data sources.

**Comment by mathiasrw** [comment]
Sounds interesting!

> Tests: cd test && mocha .

If running the full test I recommend running `npm test` so it also compiles from src before testing. 

> single test: mocha test001.js

if you need to recompile each time you run the test I suggest that you pull last update of package.json file and do a `npm run test:this -- test001.js` - this will compile and run only this file

**Comment by agershun** [comment]
I added DOT to the grammar as replacer for ARROW, and now you can use DOT for nested properties, but not for first one (unfortunately, it was hard to do). For example:
```sql
SELECT a->b.c.d FROM ?  -- now valid
SELECT a.b.c.d FROM ? -- still invalid
```
I will work on it.

**Comment by mathiasrw** [comment]
This is really cool !

**Comment by filipkis** [comment]
Perfect!

Should we close this issue and open another one for the hard case (which I don't think is urgent at all), or should we just keep it here?

**Comment by agershun** [comment]
Let's keep for a week. Hope, I will solve this for most cases. 

At least we have to describe how to use it in documentation.

**Comment by mathiasrw** [comment]
It could be a setting if it should first try to look for what corresponds to table.row or row.property and it only try the second one if the first did not exsist

**Comment by agershun** [comment]
Yes, I am working on this way, but unfortunately I choosed wrong initial architecture to parse and compile expressions in SELECT, so I have to add some tricks to check if this is a part of existing tables. 

We definitely need to start AlaSQL2 with smart architecture and without error and bugs inside!:)

**Comment by mathiasrw** [comment]
> smart architecture and without error and bugs inside!:)

:)
