### ISSUE TITLE
Its not possible to create multiple spreadsheets with distinct queries for each spreadsheat

### ISSUE THREAD

**Issue by forcewill** [agershun/alasql#554]
It should be possible to create multiple spreadsheets using different queries for each spreadsheat (i.e different SELECT expressions for each spreadsheet).

I think we have 3 possible use cases.

1) we want to use one SELECT expression to select from multiple datasources 
2) we need to use multiple SELECT expression each one selecting different columns from different datasources and inserting in the appropriate sheet

3) same as 2) but using the same datasource (i.e User list datasource, i can select username into one spreadsheet and unique address's onto the other)

#226  seems to address 1) but leaves the other 2 cases without support

**Comment by mathiasrw** [comment]
Have a look at 

http://jsfiddle.net/sd7822df/1/

Here data is hardcoded. If you replace the hardcoded values with `alasql('select ...')` you can have different selects on two worksheets.
