### ISSUE TITLE
JISON for AlaSQL2

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#556]
> We definitely need to start AlaSQL2 with smart architecture and without error and bugs inside!:)

Inputs and ideas on how to structure the parser for AlaSQL2

**Comment by nickdeis** [comment]
Perhaps trying to decouple the parser from the compiler would be a good idea. I tried to make an inline string compiler using Babel but couldn't because SELECT statements can not be de/serialized.

**Comment by mathiasrw** [comment]
What if you use the output from alasql.parse? Does that help?

**Comment by nickdeis** [comment]
Sort of. 
More interesting is if I use alasql.compile
```javascript
compileSelectStatement.prototype.constructor.query.selectfns
```

It seems to have a stringified version of the function, but I need to make sure I include the right scope.

**Comment by mathiasrw** [comment]
Closed as its put on The Long List - only to be reopend when its time has come.
