### ISSUE TITLE
Environment Detection

### ISSUE THREAD

**Issue by nickdeis** [agershun/alasql#562]
Related to #527.
I've come to the conclusion that finding the global scope is actually a precursor to finding out which environment alasql is running in, since certain environments have certain functions which are native and immutable:
```javascript
//Inspired by System.global
function getGlobal(){
  try {
    return Function('return this')();
  }catch(e){
	//If Content Security Policy
    var global =  self || window || global;
    if(global) return global;
    else throw new Error('unable to locate global object');
  }
}

function isNativeFunction(fn){
  return typeof fn === "function" && !!~(fn.toString().indexOf("[native code]"));
}

function isWebWorker(){
  try{
    var importScripts = getGlobal().importScripts;
    return (isNativeFunction(importScripts));
  }catch(e){
    return false;
  }
}

function isNode(){
  try{
    return isNativeFunction(getGlobal().process.reallyExit);
  }catch(e){
    return false;
  }
}

function isBrowserWindow(){
  try{
    return isNativeFunction(getGlobal().location.reload);
  }catch(e){
    return false;
  }
}
```

**Comment by mathiasrw** [comment]
So - you are suggesting that we use `getGlobal`/`isWebWorker`/`isNode`/`isBrowserWindow` through out the code right?

**Comment by nickdeis** [comment]
getGlobal would def be useful. I'm surprised it worked even in a CSP setting (that's what the try/catch block is for).
Others may require more research, because monkey patching may destroy the legitimacy.
However, it's a far better detection than
```javascript
if(modules.export) //is Node
```
Since commonsjs sometimes exists in the browser.

**Comment by mathiasrw** [comment]
Have implemented the code in 15utils and changed everywhere we do a export, cordova og webworker check (but got 24 errors so will have to look into where i missed a detail...)

I am not quite sure about what the plan is with the `getGlobal` part - is it only to support the other functions, or do you have somewhere in mind where alasql should use the output from `getGlobal()` instead of `this` ?

**Comment by nickdeis** [comment]
Thanks @mathiasrw 
I plan to use it where window, self, or global is used or where "this" is used in the context of being the global.
I'll take a look later tonight where this occurs.

**Comment by mathiasrw** [comment]
(I have not uploaded it yet - Im still trying to find out what i fucked up...)
