### ISSUE TITLE
Database goes drop after refreshing the browser

### ISSUE THREAD

**Issue by ketan-silvertouch** [agershun/alasql#565]
Hi,
I am new in alasql.I have developed an application where I have used alasql as localstorage but Issue is that when I refresh the browser then my created database goes drop.Any solution for it.

**Comment by agershun** [comment]
Do you recreate database after reload? This can be a reason.

**Comment by ketan-silvertouch** [comment]
yes

**Comment by mathiasrw** [comment]
Would be awesome if you could show some code generating the problem.

**Comment by ketan-silvertouch** [comment]
alasql.options.autocommit = false;                    
createDatabase("my_test");
useDatabase("my_test"); 
I have developed application in angularjs.
the above code runs each time on click of a button.

**Comment by ketan-silvertouch** [comment]
I have used this syntax still it recreated & drop database. "alasql('CREATE localStorage DATABASE  IF NOT EXISTS '+databaseName);"

**Comment by ketan-silvertouch** [comment]
what should do I?

**Comment by mathiasrw** [comment]
What is the point of you `dropDatabase` function? When is it called?

The logic regarding `DETACH` ing a database and dropping if afterwards is confusing to me.

**Comment by ketan-silvertouch** [comment]
I am not call dropDatabase function to drop database.

**Comment by mathiasrw** [comment]
I am worried about the `alias` var that is taken from the global scope. Please send it as parameter and let me know the result.

**Comment by ketan-silvertouch** [comment]
I have defined it as global var alias = 'mobileApp_';

**Comment by mathiasrw** [comment]
> the above code runs each time on click of a button.

Only saw this now. I am very worried about the structure in your code if this runs for each click on a button. 

Please provide a list of what goes on from the user loads your website until he closes the browser + reopens it (when you expected the data to be there still).

**Comment by ketan-silvertouch** [comment]
On login button I call bellow code to create database.Function call from angularjs controller file.
alasql.options.autocommit = false;						
createDatabase("my_test");
useDatabase("my_test");   

bellow code is in external js file
var alias = 'mobileApp_';
function createDatabase(databaseName){    
    var result = false;     
    if(databaseName!='' && databaseName!=undefined){        
      result = alasql('CREATE localStorage DATABASE  IF NOT EXISTS '+databaseName);  
               alasql('ATTACH localStorage DATABASE '+databaseName+ ' AS '+alias+databaseName); 
        if(result == 1){
            return result; 
        }
    }    
    return result; 
}

function useDatabase(databaseName){    
    var result = false;    
    if(databaseName!='' && databaseName!=undefined){
         result =  alasql('USE '+alias+databaseName);
         
        if(result == 1){
            return result;
        }
    }    
    return result; 
}

**Comment by ketan-silvertouch** [comment]
After login user goes in different tabs and in different tab there multiple sub pages.

**Comment by ketan-silvertouch** [comment]
Give me solution

**Comment by mathiasrw** [comment]
> Plz. Give me solution

0. Create a version of your problem illustrated only by calls to `alasql(`. No other function calls. 
0. When the problem can be replicated with only calls to `alasql(` place the code here. 
0. We confirm the error - if any - and fix the issue. 
0. You use the new alasql.js code in your project
0. World peace

**Comment by mathiasrw** [comment]
Anything new on this?

**Comment by mathiasrw** [comment]
@ketan-silvertouch Have you found a solution?

**Comment by mathiasrw** [comment]
Please reopen if something pops up regarding this.

**Comment by renjiza** [comment]
hey can i ask, why when i refresh the browser (chrome) alasql database always gone ?, how can i do for make it stay available although refresh browser, thx

**Comment by mathiasrw** [comment]
Its gone because all data is in memory. To survive you need to store it using indexed db as "engine" (so the data will stay in the browser) 

Have a look at https://github.com/agershun/alasql/wiki/IndexedDB
