### ISSUE TITLE
Split on array

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [agershun/alasql#575]
Hello ALASQL team,

Could you give me an directio how to approach this:
We have got:
```

```
And we need:

**Comment by MarioVanDenEijnde** [comment]
Hello ALASQL team,

Could you give me a direction how to approach this:
 We have got:
```
res: [
{"title":"Keuring 01","inspecteur":"Jan","startDate":"2016-02-04"},
{"title":"Keuring 02","inspecteur":"Jan,Piet","startDate":"2016-02-03"}
]
```
And we need:
```
res1: [
{"title":"Keuring 01","inspecteur":"Jan","startDate":"2016-02-04"},
{"title":"Keuring 02","inspecteur":"Jan","startDate":"2016-02-03"}
{"title":"Keuring 02","inspecteur":"Piet","startDate":"2016-02-03"}
]
```

Kind regards,
Mario

**Comment by agershun** [comment]
Hi Mario
```js

    var res1 =  [
        {"title":"Keuring 01","inspecteur":"Jan","startDate":"2016-02-04"},
        {"title":"Keuring 02","inspecteur":"Jan,Piet","startDate":"2016-02-03"}
    ];

    var res2 = [
        {"title":"Keuring 01","inspecteur":"Jan","startDate":"2016-02-04"},
        {"title":"Keuring 02","inspecteur":"Jan","startDate":"2016-02-03"},
        {"title":"Keuring 02","inspecteur":"Piet","startDate":"2016-02-03"}
    ];
    var res = alasql('SEARCH / AS @a EX(inspecteur->split(",")) / \
        RETURN(@a.title AS title, _ AS inspecteur, @a->startDate AS startDate) FROM ?',[res1]);
```
Here I use ```SEARCH``` operator, It is designed for search over nested JSON objects.

**Comment by agershun** [comment]
Here:
* ```SEARCH ... FROM ?``` - search over JSON
* ```/``` - for each element of array or object
* ```AS @a``` - save current value to ```@a```` variable
* ```EX(...)``` - evaluate expression
* ```inspecteur->split(".")``` - split string with comma ```","``` - returns array
* ```/``` - loop over result array
* ```RETURN(...)``` - return JSON object with fields
* ```@a->title AS title``` - field ````title``` with value of ````tiltle``` field from variable ````@a````

**Comment by MarioVanDenEijnde** [comment]
Hello Andrey,

Hats off. You keep amazing me.
I still have to study your explanation but many thanks.

Kind regards,
Mario

**Comment by agershun** [comment]
Thank you, Mario! 
The idea of this ```SEARCH```operator is like XPath or jQuert selectors. Each element is element of search construction. You can understand twhat is going on by adding these elements  one by one in the line:
```sql
SEARCH FROM ?
SEARCH / FROM ?
SEARCH / AS @a FROM ?
SEARCH / AS @a EX(inspecteur) FROM ?
SEARCH / AS @a EX(inspecteur->split(",") FROM ?
```
and so on. There is some (weak) documentation here: 
* https://github.com/agershun/alasql/wiki/How-to-search-deep-nested-JSON
* https://github.com/agershun/alasql/wiki/Search
* https://github.com/agershun/alasql/wiki/How%20to%20parse%20a%20Json%20with%20array%20and%20objects%20and%20export%20the%20data%20into%20Excel%20file

**Comment by MarioVanDenEijnde** [comment]
Hello Andrey,

I tried the SEARCH on the example below to get each Fundering (split by a comma).
But I did not succeed (I only get 3 duplicates)
```
[{"Fundering":"A,B,C","Aannemer":"X","Id":100}]
```
I need to get:
```
[{"Funderingen": [{"Fundering":"A"},{"Fundering":"B"},{"Fundering":"C"}]}]
```
Kind regards,
Mario

**Comment by mathiasrw** [comment]
Closed due to inactivity. Please reopen if needed.
