### ISSUE TITLE
Replicated code

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#582]
https://github.com/Wisehorn/alasql/blob/58b7b074745e7b53e273ea088f38bc576aaaaa08/src/59convert.js#L68-L115 has a lot of replicated code. Lets make it more clean.

**Comment by mathiasrw** [comment]
Hmmmm. joined the status codes based on the following comment regarding format, but got 10 errors. Guess I will have to compare the manually...

**Comment by nbdamian** [comment]
Looking at that code...
I think the comments may be wrong.
```
101 should be mm/dd/yyyy
103 should be dd/mm/yyyy
104 should be dd.mm.yyyy
105 should be dd-mm-yyyy
106 should be dd mm yyyy
107 should be Mon dd,yyyy
110 should be mm-dd-yyyy
```
That is probably where your errors are coming from @mathiasrw

**Comment by mathiasrw** [comment]
@nbdamian you are awesome. thank you!
