### ISSUE TITLE
Alasql in browserify setup in the browser

### ISSUE THREAD

**Issue by nowzig** [agershun/alasql#583]
When doing importing or exporting of files (e.g. Excel) there is always an error like Uncaught TypeError: fs.writeFileSync is not a function

I use alasql with browserify in the browser.

I think it can be fixed by changing the checks like
`if (typeof exports === 'object')`
to 
`if (typeof exports === 'object' && process.browser !== true) `

Maybe there is a better solution?

**Comment by mathiasrw** [comment]
Good point. The problem is found [here](https://github.com/agershun/alasql/blob/797b84d31f5e2c153925855c1b163552be033aaf/src/15utility.js#L469) - and your suggestion to a change makes a lot of sense. 

In #562 we are looking into making a central place to check for enviroment, so when its working we will replace the `if (typeof exports === 'object')` with `if (isNode())` so that we also support browserify 

Would i be ok if I get back to you when we need to get it tested in browserify?

**Comment by agershun** [comment]
yes, agree.

NB: It is better to check if the ```process``` object availabe before: ```(typeof process === "object" && process.browser !== true)```

**Comment by nowzig** [comment]
Great, that you are already working on a solution based on a central environment detection.
I would be happy to test it.

Yeah, checking if the `process` object is available makes sense.

**Comment by nickdeis** [comment]
NB: You can exclude modules in browserify config by marking them as "external resources" or by pointing to an empty js file and aliasing it to that file.
@mathiasrw + @agershun 

Using isNode won't fix this, as both Webpack and Browserify use the AST and just pick up whatever has "require".
For Webpack I finally have a better solution this script-loader (and have been meaning to make a gist of it), but the other choice is to provide a build with all the requires stripped out.

**Comment by nickdeis** [comment]
Exclude works well enough.

**Comment by mathiasrw** [comment]
@nowzig Could you please retry again with the last version of [alasql.js](https://raw.githubusercontent.com/agershun/alasql/ef0bf8289e38f6de52a4fae85888c213bf0dfd8e/dist/alasql.js)?

**Comment by nowzig** [comment]
First of all thank you for the fast corrections.

But now I get the error `Uncaught Error: Please include a Promise library`. The error comes from  [here](https://github.com/agershun/alasql/blob/594527fa7d31b3582c729091d9360b7d96eb3ab6/src/18promise.js#L11) 

Could it be because the check is for `object` but `window.Promise` is of type `function`?

**Comment by mathiasrw** [comment]
Wops.... please try this one instread: https://github.com/agershun/alasql/blob/develop/dist/alasql.js

**Comment by nowzig** [comment]
Thanks for the fix. The Promise error is gone, but now I get the following error: `Uncaught TypeError: _fs.writeFileSync is not a function`. This error comes from xlsx.js:11412

**Comment by nickdeis** [comment]
Yeah, about time I add isNode/isWorker/isBrowser.

**Comment by mathiasrw** [comment]
@nowzig  Please try again with https://github.com/agershun/alasql/blob/develop/dist/alasql.js

@nickdeis I have included it as `util.isNode`, `util.isBrowser`... Its not a function as we only need to find out once. I have changed yoru gode from `util.getGlobal()` to `utils.global`. I was not sure if getting rid of the "get" part is a clever move, but when its not a function it felt strange to keep the ´get´

**Comment by nickdeis** [comment]
Should be fine for the most part. Kind of a fan of transitive values but that's the Java in me.

**Comment by mathiasrw** [comment]
transitive?

**Comment by nickdeis** [comment]
Computed value. It's really only a valid pattern in a multithreaded environments since you always want to reinsure that the value is indeed correct.
Web Workers don't really count, since they use message passing, which is always thread safe (best W3C Spec ever done btw).

Even though I use stuff like Akka for multithreading, I still get punished for using fields sometimes.

**Comment by nowzig** [comment]
So the `Uncaught TypeError: _fs.writeFileSync is not a function` error is solved.

But now I get `Uncaught TypeError: Cannot read property 'write' of undefined` [here](https://github.com/agershun/alasql/blob/883996162117d9e680a914138a47f50268c6dfda/src/833xlsx.js#L178) 

If I want to read from a xlsx file I get Error: `XLSX library is not attached` in this [line](https://github.com/agershun/alasql/blob/883996162117d9e680a914138a47f50268c6dfda/src/84from.js#L425)
Same with xls file but the error comes from [here](https://github.com/agershun/alasql/blob/883996162117d9e680a914138a47f50268c6dfda/src/84from.js#L412)

**Comment by mathiasrw** [comment]
Ok. We are slowly getting there...

AlaSQL uses js-xlsx library to read and export Excel files. Please include https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.min.js

**Comment by nowzig** [comment]
Step by step it's getting better ;)

I do now a `global.XLSX=require('xlsx')` in my code. Now reading a xlsx file is working,but for xls files the xls library is missing. So I guess i have to do a `global.XLS=require('xls')` 

For exporting a xlsx File I get `Uncaught TypeError: saveAs is not a function` [here](https://github.com/agershun/alasql/blob/a7042f35fd91b9ededaa5dfae2a5220cec9c7c61/src/833xlsx.js#L219)

I am also wondering wether there is a solution that alasql requires the libraries it depends on when it is used via browserify

**Comment by mathiasrw** [comment]
Oh boy... We are getting a lot of enviroment specifik things here. Lets hope we are solving more problems than we are introducing :)

If you can tell me how I can find out that its running in a browersify setup, then we can navigate around it...

**Comment by mathiasrw** [comment]
Woops

**Comment by mathiasrw** [comment]
@nowzig 

Could you do me a favor and run this in a browserify setup and tell me what is being printed to the log?

```js
var utils = {}

var getGlobal = function(){
  try {
    return Function('return this')();
 
  }catch(e){  
    //If Content Security Policy
    var global =  self || window || global;

    if(global){
    	return global;
    } else {
    	throw new Error('Unable to locate global object');
    }
  }
}
utils.global = getGlobal();

var isNativeFunction = utils.isNativeFunction = function(fn){
  return typeof fn === "function" && !!~(fn.toString().indexOf("[native code]"));
}

var isBrowser = function(){
  try{
    return utils.isNativeFunction(utils.global.location.reload);
  }catch(e){
    return false;
  }
}
utils.isBrowser = isBrowser();

var isBrowserify = function(){
  return utils.isBrowser && typeof exports === 'object';
}
utils.isBrowser = isBrowser();

console.log(JSON.stringify(utils, null, 4));
```

**Comment by nowzig** [comment]
I get a `Uncaught TypeError: Converting circular structure to JSON`

But if I am logging just the `utils` object I get this: 
`global: Window
isBrowser: true
isNativeFunction: function (fn)`

Maybe that is the information you want.

**Comment by mathiasrw** [comment]
Ohh, I see - sorry for that. 

Cool. I think we have a way to solve it then

**Comment by mathiasrw** [comment]
@nowzig Ok - I can figure out if browserify will be able to figure out that it should require XLSX - but try to run the latest https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.min.js where I let the utils.isBrowserify load XLSX same way as node, but handle saving a files same way as a browser...

**Comment by nowzig** [comment]
Great, the isBrowserify function seems to work. Thank you.

But now the checkings for some functions need to use this function:
The saveAs function must be defined when browserify is used, this should be done [here](https://github.com/agershun/alasql/blob/develop/src/97saveas.js#L1) I think.
Also [here](https://github.com/agershun/alasql/blob/d356a0f109c8358d5a559a8900f2753f7c678b98/src/84from.js#L407) and [here](https://github.com/agershun/alasql/blob/d356a0f109c8358d5a559a8900f2753f7c678b98/src/84from.js#L420) the isBrowserify function should be added.

**Comment by mathiasrw** [comment]
Im on it...

**Comment by mathiasrw** [comment]
Your suggested changes have been implemented in the latest build: https://github.com/agershun/alasql/blob/develop/dist/alasql.js

**Comment by nowzig** [comment]
Thanks for all your help and work. 
It seems like yesterday I was a little too early saying the isBrowserify detection works. I did some testing and I think the function should be:
`var isBrowserify = function(){
	return utils.isBrowser && process && process.browser
}`

Because the `process` object is not a child of the window object.

One other thing, in 97saveas.js the check should be `if(utils.isBrowser && !utils.isWebWorker) {` because otherwise the saveAs function does not get defined when used with browserify.

**Comment by mathiasrw** [comment]
Great. The changes have been implemented in the latest build: https://github.com/agershun/alasql/blob/develop/dist/alasql.js

**Comment by nowzig** [comment]
It is now working perfectly. Thank you very much.

**Comment by agershun** [comment]
Question: Is this statement works correct if `process` variable is not defined?

```js
return utils.isBrowser && process && process.browser;
```
Can we rewrite it wit ```typeof``` guard?
```
return utils.isBrowser && (typeof process !== "undefined") && process.browser;
```

**Comment by mathiasrw** [comment]
> I think we should,to rewrite it with typeof guard

I will rewrite.

**Comment by agershun** [comment]
:+1:

**Comment by mathiasrw** [comment]
@agershun Did you see my questino at https://github.com/agershun/alasql/commit/9045286fc77034d42ac12538021fe93ac7149cf2#commitcomment-15945734 ?

**Comment by agershun** [comment]
Sorry for delay, just answered.

**Comment by mathiasrw** [comment]
:) :+1:
