### ISSUE TITLE
SELECT RIGHT('00000'+ CONVERT(VARCHAR,Num),6) AS NUM FROM Numbers

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [agershun/alasql#588]
Hello ALASQL team,

Can we achieve something like below:
```
SELECT RIGHT('00000'+ CONVERT(VARCHAR,Num),6) AS NUM FROM Numbers
```
Kind regards,
Mario

**Comment by agershun** [comment]
You can try:
```
SELECT ('00000'+ CONVERT(VARCHAR,Num))->substr(-6) AS NUM FROM Numbers
```
I thinj you are right and we need to add `RIGHT()` and `LEFT()` string functions...

**Comment by mathiasrw** [comment]
I created a new issue and im closing this one. Please reopen if this did not solve your question :)
