### ISSUE TITLE
Dynamic File Name

### ISSUE THREAD

**Issue by charul2007** [agershun/alasql#59]
I am using the library with angularjs
For Example I have below query: 
alasql('SELECT * INTO XLSX("john.xlsx",{headers:true}) FROM ?',[$scope.items]);

I want to read the file-name from the scope, and not any hard coded name("john.xlsx").
I tried to search how this can be achieved but no luck.

**Comment by mrostron** [comment]
how about this:

var my_filename = "\"john.xlsx\"";
var my_query = 'SELECT * INTO XLSX(' + my_filename + ',{headers:true}) FROM
?',[scope.items]);

(also be careful w/sql injection).

**Comment by mrostron** [comment]
simpler:
var my_filename = 'john.xlsx';
alasql('SELECT * INTO XLSX("' + my_filename + '",{headers:true}) FROM
?',[scope.items]);

**Comment by charul2007** [comment]
Thank you so much for the answer. I have one more question should I ask here or open a question.

**Comment by mrostron** [comment]
either way works .... pls let's know

**Comment by charul2007** [comment]
I want to export multiple table into single excel file. Please find the below image:
![image](https://cloud.githubusercontent.com/assets/7284363/6174412/3637b990-b2b4-11e4-854b-65db17228dc7.png)

I have created objects as below:
var allFiles = {
      path: "app folder  > app  > js > All Files"
}

var fileDetails = {
      FileName: "app.js",
      FileSize: "10kb",
      FileType: "js"
}

Then I concated the above two objects because I want two different tales:
var allData = allFiles.concat(fileDetails);

Now when I am trying to export it exports only the first Object:
alasql('SELECT * INTO XLSX("details.xlsx",{headers:true}) FROM ?', [allData]);

Also for the "allFiles" object I want to only display the "value" and not the "key" as shown in the Image.

Any help is much appreciated. Thank you in advance.

**Comment by agershun** [comment]
1. Current version of XLSX export function does not support colors (this is because [xlsx.js library](https://github.com/SheetJS/js-xlsx, unfortunately, still does not support colors)). 


I have some plans to add new INTO-function with coloring (I will add the issue to the development plan)

2. I slightly modified your code, it exports two or more lines (see http://jsfiddle.net/p2yfqdub/5/).
Could you add more details to your question?

**Comment by agershun** [comment]
Now AlaSQL can save files to Excel and LibreOffice formats with colors and other
Excel formatting functions. This function also work in IE9. This is a code sample:

```js
    var mystyle = {
      headers:true, 
      column: {style:{Font:{Bold:"1"}}},
      rows: {1:{style:{Font:{Color:"#FF0077"}}}},
      cells: {1:{1:{
        style: {Font:{Color:"#00FFFF"}}
      }}}
    };
    alasql('SELECT * INTO XLSXML("restest280b.xls",?) FROM ?',[mystyle,data]);
```
See the working example in [jsFiddle](http://jsfiddle.net/95j0txwx/7/)

**Comment by meghbrume** [comment]
Hi, I am using this method to create xlsx but I am not able to open the generated sheet in excel. Is there new js for this?

**Comment by mathiasrw** [comment]
It shuld be ok. 

What data are you putting in and what is excel telling you?

**Comment by meghbrume** [comment]
It says not able to open the file because the file format of the file extension is not valid

**Comment by mathiasrw** [comment]
Can you provide an example?

**Comment by meghbrume** [comment]
cf.cancelstyle = {
            headers: true,
            column: { style: { Font: { Bold: "1" } } },
            columns: [{ columnid: 'hid', title: 'Hedge Refrence ID', width: 100 },
                { columnid: '', title: 'Comments', width: 100 },
            ]};


alasql('SELECT hid as [Hedge Refrence ID], Comments INTO XLSX("test.xlsx",?) FROM ?', [cf.cancelstyle, cf.chkselect]);

**Comment by meghbrume** [comment]
cf.cancelstyle = {
headers: true,
column: { style: { Font: { Bold: "1" } } },
columns: [{ columnid: 'hid', title: 'Hedge Refrence ID', width: 100 },
{ columnid: '', title: 'Comments', width: 100 },
]};

alasql('SELECT hid as [Hedge Refrence ID], Comments INTO XLSXML("test.xlsx",?) FROM ?', [cf.cancelstyle, cf.chkselect]);

**Comment by mathiasrw** [comment]
Can you also provide an example for the content in `cf.chkselect` ?

**Comment by sanjeetkumar170** [comment]
I want to export table into excel file with images is it possible through alasql

**Comment by mathiasrw** [comment]
Sounds like a crazy plan. 

Have a look at https://github.com/SheetJS/js-xlsx
