### ISSUE TITLE
UPDATE/DELETE in local storage?

### ISSUE THREAD

**Issue by KevinCocquyt39** [agershun/alasql#591]
I guess I'm missing something (or it is not possible at all).

When I try to use alasql with local storage, I can create tables, insert records and drop tables. But I cannot seem to get INSERT or UPDATE commands to work.

I always get the errormessage 'Uncaught TypeError: Cannot read property 'tables' of undefined' when trying eg. alasql('UPDATE MyAtlas.City SET population = "' + population + '" WHERE city = "' + city + '";');

Is this because this functionality does not exist? I can execute updates and deletes on memory tables... 

Why I am asking this is that I am currently writing a hybrid windows 10 app and would like to have some sort of an offline db on which I can perform CRUD operations.

**Comment by mathiasrw** [comment]
It should work. Woud be awesome if you could provide some code to replicate it.

**Comment by KevinCocquyt39** [comment]
Thanks for the quick reply! The code I'm using is quite simple as it is a copy of the code in the tutorials, but here it is... Maybe I'm missing something...

`// with local storage
alasql('CREATE localStorage DATABASE IF NOT EXISTS Atlas');
alasql('ATTACH localStorage DATABASE Atlas AS MyAtlas');

alasql('CREATE TABLE IF NOT EXISTS MyAtlas.City (city string, population number)');
alasql('SELECT * INTO MyAtlas.City FROM ?', [
    [
        { city: 'Vienna', population: 1731000 },
        { city: 'Budapest', population: 1728000 }
    ]
]);

var res = alasql('SELECT * FROM MyAtlas.City WHERE city = "' + id + '";');
alasql('UPDATE MyAtlas.City SET population = "' + population + '" WHERE city = "' + id + '";');
alasql('DELETE FROM MyAtlas.City;');
alasql('DROP TABLE MyAtlas.City;');

// in memory
alasql("CREATE TABLE cities (city string, population number)");
alasql("INSERT INTO cities VALUES ('Rome',2863223),('Paris',2249975),('Berlin',3517424),('Madrid',3041579)");

var res = alasql('SELECT * FROM cities');
alasql('DELETE FROM cities;');`

In memory, everything works. Using local storage, only the select and drop table works for me. The update query results in the stated errormessage as does a delete query.

**Comment by mathiasrw** [comment]
Where do you define `id` and population?

**Comment by KevinCocquyt39** [comment]
I am using some kind of a service I wrote in JS:

`var cityService = function() {
    var self = this;

    self.updateCity = function(id, population) {
        alasql('UPDATE MyAtlas.City SET population = "' + population + '" WHERE city = "' + id + '";');
    }
}`

And then call it like this:

`var svc = new cityService();
svc.updateCity('Vienna', '999');`

**Comment by mathiasrw** [comment]
Does @agershun have anything to say on this?

**Comment by joerch80** [comment]
Same issue on UPDATE/DELETE with local storage using Firefox 44.0.2. I'm pretty sure, that my Delete-Stmt (with old ver. 0.0.40) has worked for a long time. But now it doesn't work with 0.0.40 or 0.2.3.

**Comment by mathiasrw** [comment]
@Agershun we have something that was working that's not working any more. Any inputs?

**Comment by clarencekwan** [comment]
I remove "AS MyAtlas" alias in the attach statement.  And it works.

**Comment by mathiasrw** [comment]
Nice. Thanks for letting us know...
