### ISSUE TITLE
Exporting array to Excel

### ISSUE THREAD

**Issue by lakshmisriramula** [agershun/alasql#594]
function exportData() {
        alasql("SELECT * INTO XLSX('cities.xlsx',{headers:true}) FROM ? ",[data]);
    } 

can we give a save as option while exporting to excel. and when the data got exported to excel when a file is opened there is prompt saying "we found a promblem in .xlsx file do you want to recover as much as can?if you trust the workbook , click yes". how can i avoid this

**Comment by mathiasrw** [comment]
We have not found a fix for this:-/
