### ISSUE TITLE
FileStorage Issue on createTable

### ISSUE THREAD

**Issue by nbdamian** [agershun/alasql#596]
The FS.createTable method is returning the error:
alasql.js:16591 Uncaught TypeError: Cannot read property 'products' of undefined

My code:
```
alasql('CREATE FILESTORAGE DATABASE test1("./test1.json")');
alasql('ATTACH FILESTORAGE DATABASE test1("./test1.json")');
alasql('USE test1');
alasql("CREATE TABLE IF NOT EXISTS products (id INT, category_id INT, name string, created_at DATE)");
alasql("INSERT INTO products (category_id, name, created_at) VALUES (?,?,?,?)", [1, 2, 'XYZ', new Date()]);
```
Line that throws the error: (var tb = db.data[tableid];).
Is db.data[tableid]; not defined for some reason?

This also occurs without the "IF NOT EXISTS".

Is this a bug on your end, or is my code incorrect? (It happens with https://github.com/agershun/alasql/blob/324a8c07ee5739477779e7bae222f3f9ef17ee21/test/cordova/test1.js aswell).

**Comment by mathiasrw** [comment]
Interesting. Can I ask you to try with the latest build and tell me what line throws the error? 

https://github.com/agershun/alasql/blob/develop/dist/alasql.js

**Comment by nbdamian** [comment]
That one broke elsewhere...
alasql.js:3179 Uncaught ReferenceError: process is not defined

**Comment by nbdamian** [comment]
Overriding the isBrowserify to return false (fixes the issue above), it still returns the error on
var tb = db.data[tableid];

**Comment by mathiasrw** [comment]
Thank you for your detailed inputs. 

We just introduced the `utils.isBrowserify` so it could very well be that we created a new issue together with cordova (you are using cordova right?). 

Im not used to cordova. Would it be possible for you to make a minimum example of full code used for including alasql and getting the error in cordova?

**Comment by nbdamian** [comment]
Its the exact same code as in the first post.
I am using Ionic Framework which uses Cordova, Yes.
http://ionicframework.com/

**Comment by mathiasrw** [comment]
That is very kind of you. I have been trying to solve `[Error: Failed to find 'ANDROID_HOME' environment `. 

Any inputs?

**Comment by nbdamian** [comment]
What OS are you running? You just have to set ANDROID_HOME in your path.
(set it to the directory of the android-sdk).

**Comment by mathiasrw** [comment]
Hmm. So android-sdk is not comming with the `npm install -g ionic` ? Im on osX

**Comment by nbdamian** [comment]
Unfortunately not...

**Comment by nbdamian** [comment]
Hey @mathiasrw, Have you gotten anywhere with this?

**Comment by mathiasrw** [comment]
Hey. Nope. I got stalled on the amount of time it took me to get the android sdk up and running. Do you have any awesomely easy good ways where it just works?

**Comment by nbdamian** [comment]
There's a virtual machine called ionic-box.
https://github.com/driftyco/ionic-box

On 19/02/2016 5:58 PM, Mathias Rangel Wulff <notifications@github.com> wrote:

Hey. Nope. I got stalled on the amount of time it took me to get the android sdk up and running. Do you have any awesomely easy good ways where it just works?

-

**Comment by mathiasrw** [comment]
omg... thank you so much...

**Comment by mathiasrw** [comment]
argwww - looked all good but the script ended with

```

==> default: stdin: is not a tty
==> default: /home/vagrant/android-sdk-linux/platform-tools/adb: 1: /home/vagrant/android-sdk-linux/platform-tools/adb: 
==> default: Syntax error: ")" unexpected
==> default: /home/vagrant/android-sdk-linux/platform-tools/adb: 1: /home/vagrant/android-sdk-linux/platform-tools/adb: 
==> default: Syntax error: ")" unexpected
==> default: /home/vagrant/android-sdk-linux/platform-tools/adb: 1: /home/vagrant/android-sdk-linux/platform-tools/adb: 
==> default: Syntax error: ")" unexpected
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Giving a manual install another shot

**Comment by nbdamian** [comment]
http://cordova.apache.org/docs/en/3.4.0/guide/platforms/android/index.html#Android%20Platform%20Guide
Maybe this will help?

**Comment by nbdamian** [comment]
@mathiasrw It seems its a bug with the box, See this issue: https://github.com/driftyco/ionic-box/issues/49
They have a resolution in the issue as well.

Try changing the VagrantFile config.vm.box to use ubuntu/trusty64 instead of ubuntu/trusty32
Then reload the box.

**Comment by mathiasrw** [comment]
Omg. Im loosing track here. thanks for keeping my focus.

**Comment by nbdamian** [comment]
Haha, all good. I wish I could help more, but the JS is a bit too complex for me to figure out...
Although I am hoping this issue will be resolved within the next month (My app is having an overhaul to make it 50% faster, and AlaSQL is the best candidate for the local database).

**Comment by mathiasrw** [comment]
Does @agershun have any inputs?

**Comment by Enelar** [comment]
Please correct wikipage https://github.com/agershun/alasql/wiki/FileStorage

Lacking `("./test1.json")` part.

**Comment by nbdamian** [comment]
@mathiasrw 
https://github.com/nbdamian/alasql-ionic
Has been updated to the latest version of alasql, and some missing plugins have been added.

**Comment by nbdamian** [comment]
If you wait enough time after `USE test1` you are able to create tables.

**Comment by mathiasrw** [comment]
> If you wait enough time after USE test1 you are able to create tables.

Omg... It just hits me: after attaching a file all queries will be async.

so `alasql("CREATE TABLE IF NOT EXISTS products (id INT, category_id INT, name string, created_at DATE)");` will be running async so `products` are not created when we reach `alasql("INSERT INTO products (category_id, name, created_at) VALUES (?,?,?,?)", [1, 2, 'XYZ', new Date()]);`

I guess we should console.log a warning when a forced async call have an undefined callback (or when not on promise)

**Comment by nbdamian** [comment]
Right.. So running
```
alasql('CREATE FILESTORAGE DATABASE test1("./test1.json")', function() {
alasql('ATTACH FILESTORAGE DATABASE test1("./test1.json")', function() {
alasql('USE test1', function() {
alasql("CREATE TABLE IF NOT EXISTS products (id INT, category_id INT, name string, created_at DATE)", function() {
alasql("INSERT INTO products (category_id, name, created_at) VALUES (?,?,?,?)", [1, 2, 'XYZ', new Date()], function() {
});
});
});
});
});
```
Works correctly! :+1: 

Yes, I would agree adding a warning.
Would it be possible to check whether the user is using a callback or promise? then only displaying the warning IF they are not using an async method?

Otherwise, return the warning when ATTACH DATABASE is used. (since this would only be called once is done correctly).

**Comment by mathiasrw** [comment]
This is crazy ugly code! 

I have expanded the `.promise` notation to be able to handle a chain of queries - For the moment the only drawback is that you only get the result from the last query in the cain. 

Now you can pass an array of queries and they will execute in a chain (so one after the return of the promise of the other). 

```js
alasql.promise([
	'CREATE FILESTORAGE DATABASE test1("./test1.json")', 
	'ATTACH FILESTORAGE DATABASE test1("./test1.json")', 
	'USE test1', 
	'CREATE TABLE IF NOT EXISTS products (id INT, category_id INT, name string, created_at DATE)', 
	['INSERT INTO products (id, category_id, name, created_at) VALUES (?,?,?,?)', [1, 2, 'XYZ', new Date()] ],
	'SELECT * FROM products'	
]).then(function(res){
	console.log('Result from last query:',res)
}).catch(function(reason){
	console.log('Error:',reason)
})
```

Please note that t be able to combine parameters instead of a query string you must use an array with the query string at index 0 and (array of) parameters at index 1.

I have also included the promise-polifil so hopefully you wont get a warning about the Promise not being there. 

_(please note I added `id` into the `INSERT INTO products` query)_

**Comment by nbdamian** [comment]
I am unable to test as promises aren't working D:

**Comment by mathiasrw** [comment]
Sounds really strange. Can you check if they implement the Promise/A+ specification?

**Comment by nbdamian** [comment]
They as in angular or promisejs?

**Comment by mathiasrw** [comment]
AlaSQL is reliant on an object in the global scope called `Promise` implementing the Promise/A+ specification. 

In your browser please open a console and see if writing `Promise` will give you anything. 

If you could please tell me whats in the `alasql.version` variable that would also be very helpful.

**Comment by nbdamian** [comment]
> Promise
function L(t){this[rt]=O(),this._result=this._state=void 0,this._subscribers=[],p!==t&&("function"!=typeof t&&D(),this instanceof L?C(this,t):K())}
> alasql.version
"0.2.4-develop-1241"

**Comment by mathiasrw** [comment]
Ok. hmm. Looks correct. 

What do you get if you just execute:

```
alasql.promise('SELECT 123 as abc').then(function(res){
    console.log(res)
}).catch(function(reason){
    console.log('Error:',reason)
})
```

?
