### ISSUE TITLE
LocalStorage Webworker localStorage is not defined

### ISSUE THREAD

**Issue by nbdamian** [agershun/alasql#597]
Attempting to use Webworkers with a LocalStorage Database.
Works fine without Webworkers.

Build no: v0.2.3-develop-1198

```
alasql.js:16161 Uncaught ReferenceError: localStorage is not defined
LS.get @ alasql.js:16161
LS.createDatabase @ alasql.js:16241
yy.CreateDatabase.execute @ alasql.js:12982
alasql.dexec @ alasql.js:4287
alasql.exec @ alasql.js:4232
alasql @ alasql.js:120
self.onmessage @ blob:file%3A///2cb3d412-610f-4a11-aa79-a3eb21b8792b:1
js/alasql/alasql.js:17185
```

```
Uncaught #<ErrorEvent>alasql.webworker.onerror @ js/alasql/alasql.js:17185
2016-02-11 12:00:09.365 
```

**Comment by nbdamian** [comment]
Seems as though it is a limitation in Webworkers.

**Comment by mathiasrw** [comment]
> localStorage and sessionStorage are both undefined in a webworker process.

So its not supported by the browsers. Ill close the issue. Please reopen if you have more inputs on this.

**Comment by nbdamian** [comment]
Should it be added into the documentation that it is not supported?

**Comment by mathiasrw** [comment]
Good point - added it: https://github.com/agershun/alasql/wiki/Webworker
