### ISSUE TITLE
Get file extension from file name.

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [agershun/alasql#602]
Hello ALASQL team,

I have got a new challenge:
I have got a field value like:
```
"Name":"W-LB-FD-3.3 testmethode rotatoire wrijving lab eigenmethode.doc"
```

And I need:
```
"fileName":"W-LB-FD-3.3 testmethode rotatoire wrijving lab eigenmethode", "fileType":"doc""
```

Any idea?
Kind regards,
Mario

**Comment by mathiasrw** [comment]
Make a [user defined function](https://github.com/agershun/alasql/wiki/User-Defined-Functions)

```
alasql.fn.fileName = function(name) {
    var all = name.split('.')
    all.pop();
    return all.join('.');
};

alasql.fn.fileType = function(name) {
    return name.split('.').pop();
};
```

So you can 

`select fileName(name) as fileName, fileType(name) as fileType from ?`


_Code not tested_
