### ISSUE TITLE
can not create table with columnName 'value' or 'order'

### ISSUE THREAD

**Issue by atiertant** [agershun/alasql#605]
alasql('CREATE TABLE IF NOT EXISTS Database.table (value string, order int)');

return error:

    Parse error on line 1:↵...XISTS Database.table (valu…ecting 'LITERAL', 'BRALITERAL', 'AS', got 'VALUE'

is there a way to do it?

**Comment by agershun** [comment]
Please, use square brackets:
```js
alasql('CREATE TABLE IF NOT EXISTS Database.table ([value] string, [order] int)');
```

**Comment by atiertant** [comment]
thanks for your help !
