### ISSUE TITLE
CONCAT without space

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#608]
At the moment AlaSQL gives `a b` from

```sql
VALUE SELECT CONCAT('a','b');
```

Both MySQL and Postgres returns `ab`.

Is there any reason behind AlaSQLs `CONCAT` putting a space in between?

**Comment by agershun** [comment]
THe problem is here:
```js
stdfn.CONCAT = function(){
	return Array.prototype.slice.call(arguments).join(' ');
};
```
We need to change it and remove the space

**Comment by agershun** [comment]
:+1:
