### ISSUE TITLE
The wiki for Csv, test synchronously works wrong. Callback is OK.

### ISSUE THREAD

**Issue by BrightLamp** [agershun/alasql#610]
/*
https://github.com/agershun/alasql/wiki/Csv
my.CSV File:
a,b,c
1,2,3
4,5,6
*/
var alasql = require('alasql');

var res = alasql('SELECT * FROM CSV("my.csv", {headers:true})');
console.log(res);
//return undefine

alasql('SELECT * FROM CSV("my.csv", {headers:true})' , [], function(data){
	console.log(data);
});
/*
return
[ { a: 1, b: 2, c: 3 }, { a: 4, b: 5, c: 6 } ]
[ { a: 1, b: 2, c: 3 }, { a: 4, b: 5, c: 6 } ]

$Note that console.log(data) will return two times after undefine.
*/

**Comment by BrightLamp** [comment]
https://github.com/agershun/alasql/wiki/Csv
The . symbol below after "my.csv" is wrong, maybe is , symbol.
alasql('SELECT * FROM CSV("my.csv". {headers:true})');
alasql('SELECT * FROM CSV("my.csv". {headers:true, quote:"\'",separator:","})');
alasql('SELECT * INTO CSV("my.csv". {headers:true}) FROM ?',[data]);

Thanks.

**Comment by mathiasrw** [comment]
Really good you took the time to give some inputs... https://github.com/agershun/alasql/wiki/Csv has now been updated - both regarding async notation and regarding the `.` that should be a `,`

Could you please have a look and see if you find it better now?

**Comment by BrightLamp** [comment]
Many thanks.
I am new to javascript and cost great effort to understand async, promise, then, and catch.
It worths, promise is perfect.
I found that you also updated the xlsx wiki page, thanks.

By the way, whould you like to keep the callback example for csv and xlsx? I loves it, is my HELLO WORLD.
Maybe someone needs it too, so he/she need not to learn async-promise-then-catch before  having a try.
Thank you very much.

**Comment by mathiasrw** [comment]
Its a good point that the callback solution looks more simple. The callback solution does not give you any option to handle if an error occure. Handeling errors should be a priority to stable code.

I have changed the words to be

> Please note that when interacting with files AlaSQL will run async. We strongly recommend you to use the promise notation instead of the simple notation: alasql(sql, params, function(data) { console.log(data) })
