### ISSUE TITLE
How can I show multiple aggregate columns per row? Example provided

### ISSUE THREAD

**Issue by loque** [agershun/alasql#613]
I have a 'sales' table with the fields: country, product, units, date

Currently I have the following query:

```javascript
alasql('SELECT product, \
SUM(CASE WHEN date >= "' + period[0] + '" AND date < "' + period[1] + '" AND country = "country one" THEN units ELSE 0 END) AS `country one > this year`, \
SUM(CASE WHEN date >= "' + period[2] + '" AND date < "' + period[3] + '" AND country = "country one" THEN units ELSE 0 END) AS `country one > last year`, \
SUM(CASE WHEN date >= "' + period[0] + '" AND date < "' + period[1] + '" AND country = "country two" THEN units ELSE 0 END) AS `country two > this year`, \
SUM(CASE WHEN date >= "' + period[2] + '" AND date < "' + period[3] + '" AND country = "country two" THEN units ELSE 0 END) AS `country two > last year` \
FROM sales \
GROUP BY product \
');
```

And I can render it's results in a table like this:
```
            |        country one        |        country two        |
|  product  |  this year  |  last year  |  this year  |  last year  |
---------------------------------------------------------------------
|  prod 1   |      5      |      0      |      0      |      2      |
|  prod 2   |      8      |      4      |      3      |     16      |
```

The problem is that I would like to move the dimensions country and period (this year/last year) to a column so that I can render a table like this:
```
|  country      |  period     |  prod 1  |  prod 2  |
-----------------------------------------------------
|  country one  |  this year  |     5    |     8    |
|               |  last year  |     0    |     4    |
|  country two  |  this year  |     0    |     3    |
|               |  last year  |     2    |     16   |
```
For now, I'm able to get this table:
```
|  country      |  prod 1  |  prod 2  |
---------------------------------------
|  country one  |     5    |     12   |
|  country two  |     2    |     19   |
```
With this query:
```javascript
alasql('SELECT country, \
SUM(CASE WHEN product = "prod 1" THEN units ELSE 0 END) AS `prod 1`, \
SUM(CASE WHEN product = "prod 2" THEN units ELSE 0 END) AS `prod 2` \
FROM sales \
GROUP BY country \
')
```
But I can't figure out how to calculate the column period. Is there a way to do that with sql?

Here is an example in [jsFiddle](https://jsfiddle.net/theloque/snm8uykc/13/).

**Comment by agershun** [comment]
You can use `PIVOT` operator.

 Please, see these test files with examples:
* [test830.js](https://github.com/agershun/alasql/blob/develop/test/test380.js)
* [test831.js](https://github.com/agershun/alasql/blob/develop/test/test381.js)

Here is the possible query for your last example (sorry, not tested):
```
SELECT * FROM sales PIVOT(SUM(units) FOR product)
```

For 'first row'- 'last row' case...Probably you can use `UNPIVOT` operator:
* [test855.js](https://github.com/agershun/alasql/blob/develop/test/test355.js)


Sorry for slow documenting....

**Comment by agershun** [comment]
This is a partial answer to your question [in jsFiddle/](https://jsfiddle.net/snm8uykc/11/).

**Comment by agershun** [comment]
BTW: Please use CDN for alasql.min.js - https://cdnjs.cloudflare.com/ajax/libs/alasql/0.2.3/alasql.min.js

**Comment by loque** [comment]
Thank you for the answer!

Coming from MySQL I've never heard of PIVOT. Sounds interesting.

Right now I'm not able to show the information as intended. If I solve it I'll post it here for future reference.

**Comment by mathiasrw** [comment]
> BTW: Please use CDN for alasql.min.js - https://cdnjs.cloudflare.com/ajax/libs/alasql/0.2.3/alasql.min.js

I recommend using 

`http://cdn.jsdelivr.net/alasql/0.2/alasql.min.js`

as it will give you the latest version of 0.2.x
