### ISSUE TITLE
How to create multiple worksheets into a workbook

### ISSUE THREAD

**Issue by DickSwart** [agershun/alasql#614]
Hi Guys,

This question was logged previously (https://github.com/agershun/alasql/wiki/How-to-create-multiple-worksheets-into-a-workbook) and there is a working example on jsfiddle (http://jsfiddle.net/ry8fq0dL/) but I'm unable to get it working, don't know if it were taken out.

The jsfiddle example works as is, But as soon as I change the lib to use the latest lib it does not working any more.

Replacing:

```
<script src="http://alasql.org/console/alasql.min.js"></script>
<script src="http://alasql.org/console/xlsx.core.min.js"></script>
```

With:
```
<script src="https://cdn.jsdelivr.net/alasql/0.2.3/alasql.min.js"></script>
<script src="https://cdn.jsdelivr.net/alasql/0.2.3/alasql-worker.min.js"></script>
```

I'm working on a AngularJS project and need to export data to excel workbook with multiple sheets.

**Comment by mathiasrw** [comment]
That is terrible - something that worked stoped working. 

@agershun do you have any inputs on what it could be?

**Comment by mathiasrw** [comment]
(and thank you very much for taking the time to submit this step back)

**Comment by mathiasrw** [comment]
Please keep the xlsx.core.min.js and skip the alasql-worker.min.js file

Working example: http://jsfiddle.net/ry8fq0dL/55/

**Comment by DickSwart** [comment]
Thank you

**Comment by DickSwart** [comment]
I created a codepen if anyone is interested, making use of AngularJS, http://codepen.io/DickSwart/pen/wWPYpX/

**Comment by MuhammadRehanQadri** [comment]
I've solved this issue: https://github.com/MuhammadRehanQadri/export-google-map-markers/tree/master
