### ISSUE TITLE
Excel file : how to custom header with the name of index from javascript array

### ISSUE THREAD

**Issue by Dosix** [agershun/alasql#615]
Hii,

I would like custom my header with the name of index from javascript array

```
{"Blog international": [
{
"email":"email1@mydomain.fr",
"mark":31.25,
"coef":1
},
{
"email":"email2@mydomain.fr",
"mark":49.24,
"coef":1
},{
"email":"email3@mydomain.fr",
"mark":50,
"coef":1
}],
"PowerPoint":[
{
"email":"email1@mydomain.fr",
"mark":31.25,
"coef":1
},
{
"email":"email2@mydomain.fr",
"mark":49.24,
"coef":1
},{
"email":"email3@mydomain.fr",
"mark":50,
"coef":1
}],
"Culture WEB":[
{
"email":"email1@mydomain.fr",
"mark":31.25,
"coef":1
},
{
"email":"email2@mydomain.fr",
"mark":49.24,
"coef":1
},{
"email":"email3@mydomain.fr",
"mark":50,
"coef":1
}]}
```

I want get a Excel file like this : 

```
Email | Blog international | PowerPoint | Culture WEB
email1@mydomain.fr  |  31.25 |  31.25 |  31.25
email2@mydomain.fr  | 49.2 | 49.2 | 49.2
email3@mydomain.fr  | 50 | 50 | 50
```

Any ideas how to do that ?

**Comment by nbdamian** [comment]
Something like this:
https://jsfiddle.net/kprk8dh1/1/
Although, it seems as though there is an error somewhere in alasql causing XLSXML to fail.
@mathiasrw 
Thoughts on why this might be failing with this error?

**Comment by mathiasrw** [comment]
Hi @nbdamian 

Will they always have the same number of data?

**Comment by Dosix** [comment]
@nbdamian yeah but the name of index is dynamic, I can't put the name like your example in my query  :/

I can manipulate my json if needed

**Comment by nbdamian** [comment]
Could you supply an example of the name of the index being dynamic?

Sent using Boxer

On 15/03/2016 9:12 PM, Ludovic Fgt <notifications@github.com> wrote:

@nbdamian<https://github.com/nbdamian> yeah but the name of index is dynamic, I can't put the name like your example in my query :/

I can manipulate my json if needed

-

**Comment by nbdamian** [comment]
@mathiasrw I would expect the number of data would be dynamic.

**Comment by nbdamian** [comment]
@mathiasrw 
It seems as though an opts object is required. I believe we need a workaround to make it not required.
in the alasql.into.XLSXML function,
Directly after
```
if(typeof filename == 'object') {
	opts = filename;
	filename = undefined;
}
```
add
```
  opts = opts || {}
```

@Dosix 
https://jsfiddle.net/kprk8dh1/7/
Should now Download.

**Comment by mathiasrw** [comment]
@nbdamian Nice spotted! 

Please test the last version to see if it solved the problem: https://github.com/agershun/alasql/blob/develop/dist/alasql.js

**Comment by nbdamian** [comment]
Perfect. That update fixed the issue of not being able to save,
Though leave the issue open as it started as a request for help writing a query.

**Comment by Dosix** [comment]
@nbdamian It's almost what I need, so when i said my indexes are dynamic, i meant by example : "Blog international", "Power Point"...etc can change

**Comment by nbdamian** [comment]
@Dosix Ahh, That changes things. What we need to do is generate the query with javascript to have the indexed dynamic.
https://jsfiddle.net/kprk8dh1/10/
Should work for you.

**Comment by Dosix** [comment]
Thank you so muck, it works perfectly :+1:
