### ISSUE TITLE
Remove leading whitespace from fields when importing csv files

### ISSUE THREAD

**Issue by abalter** [agershun/alasql#616]
I implemented importing csv files based on [this example](http://alasql.org/demo/008file/).

	alasql('SELECT * FROM FILE(?,{headers:true})',[event],function(res){
		//data = res;
		data_string = JSON.stringify(res);
		console.log(data_string);
		data_string = data_string.replace(/"[ \t]+/g, '"');
		console.log(data_string);
		data = JSON.parse(data_string);

However, if the csv file has spaces after the commas (any amount of white space, spaces or tabs), the fields come in with a single leading space.

To prevent this, I had to add the above string replacement.

Spaces within fields should be tolerated. But many times csv files have spaces after the commas.

This came up for me because it was messing up queries.

**Comment by mathiasrw** [comment]
Good point. We should strip the value!

**Comment by abalter** [comment]
Yes. Workaround was easy, but a good thing for the future.

Thanks!

**Comment by mathiasrw** [comment]
Would it be possible for you to verify its fixed in https://github.com/agershun/alasql/blob/develop/dist/alasql.js ?

**Comment by abalter** [comment]
Appears to work!

http://plnkr.co/edit/FOWwVsW7zAUGwv3BDBdN?p=preview <http://plnkr.co/edit/FOWwVsW7zAUGwv3BDBdN?p=preview>

Let me know when you post the updated can so I can update the plunk, since it is public. I won’t leave that js file in my personal web space forever.

Thanks for working on it!

**Comment by mathiasrw** [comment]
We push a new version with every full moon (read: no fixed schedule but once a month'ish) so in about 3 weeks it will get into 0.2.5

Meanwhile you can link to the script: https://cdn.rawgit.com/agershun/alasql/46004f0df59de39f4c769730268186cbf44bf191/dist/alasql.min.js
