### ISSUE TITLE
Alasql select not returning all requested fields.

### ISSUE THREAD

**Issue by abalter** [agershun/alasql#621]
I have the following query:

http://plnkr.co/edit/a23iPQlGeGNXZHjwDJhd?p=preview

```
drop table if exists t1;
create table t1 (
	id int,
	name varchar(20)
);

insert into t1 values
(1, 'julja'),
(2, 'mark'),
(5, 'john'),
(6, 'ari');

drop table if exists t2;
create table t2 (
	id int,
	name varchar(20)
);

insert into t2 values
(1, 'patrick'),
(2, 'mark'),
(4, 'ari'),
(5, 'wes');

select * from t1;

select * from t2;

select t1.id, t2.id, t1.name, t2.name
from t1 inner join t2
on t1.id = t2.id;
```

which is returning:

| id |	name | 
| -----|--------- |
| 1 | julja |
| 2 | mark | 
| 5 | john | 
| 6 | ari |

| id | name |
| -----|------- |
| 1 | patrick |
| 2 | mark |
| 4 | ari |
| 5 | wes |

| id | name |
| -----|------- |
1 | patrick |
2 | mark |
5 | wes |

**Comment by agershun** [comment]
You need to use AS modificator to specify different field names for the fields with the same name. E.g.

SELECT t1.id AS t1_id, t2.id AS t2_id ...

Отправлено с iPhone

**Comment by abalter** [comment]
Is that a bug or a feature? I know, for instance, that neither MS SQL 
nor My SQL require that.

**Comment by mathiasrw** [comment]
Its a good point. Its from the nature of how the results are presented (as an object). Ill add it to the Readme.

@agershun tested out if MATRIX, RECORDSET would give some data with the same name but it did not. Is it correctly understood that we make the result (as traditional object) and then transforme it when using XXX OF SELECT ... ?

**Comment by agershun** [comment]
Yes, this is feature. AlaSQL uses JSON objects internally for result table. Probably it was not a best decision on early stages, and we can switch to array of arrays in the future versions. But currently it is so: we use JSON object, and new fields simply overrides old fields during join procedure. Sorry about that.

MATRIX OF ... uses the same approach: it converts result JSON object to array of arrays

Отправлено с iPhone

**Comment by abalter** [comment]
Thanks. It really does add a lot of extra typing.

I can understand if you have objects for two tables like this:

t1 = [{'a':1, 'b':2}]
t2 = [{'a':1, 'b':4}]

then how do you create keys for the result object? You can't use 'a' 
twice.

However, when the tables are created, they are given names. So rather 
than the user having to do an 'as', you could concatenate the table name 
and field name into a string for the keys in the result:

e.g.

select t1.a, t2.a, t1.b, t2.b
from t1 inner join t2
on t1.a = t2.a

result = [{'t1.a': 1, 't2.a': 1, 't1.b': 2, 't2.b': 4}]

I guess maybe another way to think about it is that if the use does not 
specify an as, then it defaults to the above

select t1.a as t1a --> 't1a' as key
select t1.a --> 't1.a' as key

**Comment by agershun** [comment]
We already had closed issue for this question and special modifacator option for this. Could you search for it in closed issues? Unfortunately, I am on mobile now...

Отправлено с iPhone

**Comment by abalter** [comment]
I'll take a look.


Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&amp;utm_medium=email&amp;utm_campaign=sent-from-mailbird]
On 3/11/2016 10:12:07 PM, Andrey Gershun <notifications@github.com> wrote:
We already had closed issue for this question and special modifacator option for this. Could you search for it in closed issues? Unfortunately, I am on mobile now...

Отправлено с iPhone

**Comment by abalter** [comment]
I found it. It is issue https://github.com/agershun/alasql/issues/547

I added a comment there. I think I have a much simpler solution than those discussed.

Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&utm_medium=email&utm_campaign=sent-from-mailbird]
On 3/11/2016 10:12:07 PM, Andrey Gershun <notifications@github.com> wrote:
We already had closed issue for this question and special modifacator option for this. Could you search for it in closed issues? Unfortunately, I am on mobile now...

Отправлено с iPhone

**Comment by mathiasrw** [comment]
Let's continue the chat in the other thread. 

I'll close this one.
