### ISSUE TITLE
CREATE TABLE IF NOT EXISTS return cb()

### ISSUE THREAD

**Issue by nbdamian** [agershun/alasql#623]
The CREATE TABLE IF NOT EXISTS statement should always return the cb(), even if the table exists, but returning 0 as the arg.
If someone relies on cb() to tell if a script finished at all, it will break their code.

Changing 10726 from
````return 0;````
to
````if(cb) res = cb(0);
        return res;````

(Is this issue a remnant of before alasql used cb()?)

**Comment by mathiasrw** [comment]
Sounds awesome. 

What value is stored in `alasql.version` in the file you have found the solution at line 10726?

**Comment by nbdamian** [comment]
0.2.4-develop-1229

**Comment by mathiasrw** [comment]
Hmmm. The line https://github.com/agershun/alasql/blob/develop/dist/alasql.js#L10726 is a comment. I have a feeling the correct place would be https://github.com/agershun/alasql/blob/develop/dist/alasql.js#L10732

I found a few other places where the callback was not involved in the return statement. No errors found in the test - lets hope I did not brake something. 

Could you please test if its fixed?

**Comment by nbdamian** [comment]
Perhaps I had some extra code somewhere that I was using for testing other bug fixed that pushed it down a bit far. Yeah, that looks like the correct location.
That works perfectly. If you want to test yourself, you can use:
```
alasql("CREATE TABLE IF NOT EXISTS `settings` (`id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(45) DEFAULT NULL, `value` text, PRIMARY KEY (`id`))", [], function(res) {alert(res);});
alasql("CREATE TABLE IF NOT EXISTS `settings` (`id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(45) DEFAULT NULL, `value` text, PRIMARY KEY (`id`))", [], function(res) {alert(res);});
You should get 2 alerts.
```
Just run it twice.
