### ISSUE TITLE
DELETE FROM table WHERE error

### ISSUE THREAD

**Issue by nbdamian** [agershun/alasql#624]
Using FileStorage and WebWorker.
Running the query "DELETE FROM table WHERE column = 'value'"
I get the error:

```
Uncaught TypeError: Cannot read property 'length' of null(…)
statement   @   alasql.js:12750
alasql.dexec    @   alasql.js:4249
alasql.exec @   alasql.js:4231
alasql  @   alasql.js:120
(anonymous function)    @   VM197:2
InjectedScript._evaluateOn  @   VM144:904
InjectedScript._evaluateAndWrap @   VM144:837
InjectedScript.evaluate @   VM144:693
```

Subtract 2 from any line after 12747 (I had 2 console.log() for testing).

Code to replicate:

```
alasql("CREATE TABLE IF NOT EXISTS `preferences` (`id` int(11) NOT NULL, `tab` varchar(45) DEFAULT NULL, `tab_id` int(11))", [], function() {
alasql("INSERT INTO `preferences` (`id`, `tab`, `tab_id`) VALUES (1, 'where', 1), (2, 'when', 8)", [], function() {
alasql('DELETE FROM preferences WHERE tab = "where"')
});
}); 
```

According to console logs, 
console.log(table); has no object of data
console.log(table.data); returns undefined.

**Comment by nbdamian** [comment]
The issue is to do with FileStorage. (if I don't use FileStorage it works)

**Comment by nbdamian** [comment]
Updated error with version v0.2.4-develop-1235:
```
Uncaught TypeError: Cannot read property 'length' of undefined(…)
statement @ alasql.js:12749
alasql.dexec @ alasql.js:4249
alasql.exec @ alasql.js:4231
alasql @ alasql.js:120
(anonymous function) @ VM157:4
FS.intoTable @ alasql.js:16806
statement @ alasql.js:12565
alasql.dexec @ alasql.js:4249
alasql.exec @ alasql.js:4231
alasql @ alasql.js:120
(anonymous function) @ VM157:3
yy.CreateTable.execute @ alasql.js:10732
alasql.dexec @ alasql.js:4286
alasql.exec @ alasql.js:4231
alasql @ alasql.js:120
(anonymous function) @ VM157:2
InjectedScript._evaluateOn @ VM149:904
InjectedScript._evaluateAndWrap @ VM149:837
InjectedScript.evaluate @ VM149:693
```

**Comment by mathiasrw** [comment]
interesting. Ill have a look

**Comment by mathiasrw** [comment]
I just realised you say you are using filestorage from webworker. 

Does it change anything if you do not use webworker?

**Comment by nbdamian** [comment]
Sorry, I'm not running webworker (I think it was late when I stopped using the webworker, so that's a fail on my behalf sorry).
It seems this async issue is in quite a lot of places, my issue of #596 most likely has the same problem.

**Comment by mathiasrw** [comment]
I have the same feeling: that something in the logic of how filestorage is implemented is misfittting the async nature. 

I have a feeling we need to get @agershun to have a look at it when he has the time.

**Comment by mathiasrw** [comment]
This example shows how to chain queries to a async backend

```
alasql.promise('SELECT 1,2')
      .then(function(res){
     
        	console.log(res); 
      		return alasql.promise('select 2,3')
     
      }).then(function(res){
     
        	console.log(res); 
      		return alasql.promise('select 3,4')
     
      }).then(function(res){
     
      		console.log(res);
     
      })
```

Would you test out if this fixes your error?

**Comment by mathiasrw** [comment]
What if you do 

```
alasql.promise('CREATE TABLE IF NOT EXISTS `preferences` (`id` int(11) NOT NULL, `tab` varchar(45) DEFAULT NULL, `tab_id` int(11))')
      .then(function(res){
      		return alasql.promise('INSERT INTO `preferences` (`id`, `tab`, `tab_id`) VALUES (1, 'where', 1), (2, 'when', 8)')
      }).then(function(res){
      		return alasql.promise('DELETE FROM preferences WHERE tab = "where"')
      }).then(function(res){
      		console.log('All done');
      }).catch(function(reason){
      		console.log('Error: ', reason);
      })
```

Does that help?

**Comment by nbdamian** [comment]
```
alasql.promise('CREATE TABLE IF NOT EXISTS `preferences` (`id` int(11) NOT NULL, `tab` varchar(45) DEFAULT NULL, `tab_id` int(11))')
      .then(function(res){
            return alasql.promise('INSERT INTO `preferences` (`id`, `tab`, `tab_id`) VALUES (1, "where", 1), (2, "when", 8)')
      }).then(function(res){
            return alasql.promise('DELETE FROM preferences WHERE tab = "where"')
      }).then(function(res){
            console.log('All done');
      }).catch(function(reason){
            console.log('Error: ', reason);
      })
```

Returns:
```
Uncaught TypeError: Promise is not a function(…)
alasql.promise @ alasql.js:4423
(anonymous function) @ VM153:2
InjectedScript._evaluateOn @ VM145:904
InjectedScript._evaluateAndWrap @ VM145:837
InjectedScript.evaluate @ VM145:693
```

**Comment by mathiasrw** [comment]
Ok. to sum up the issue - The following works: 

```js
alasql.promise([
    'CREATE FILESTORAGE DATABASE IF NOT EXISTS test1("./test1.json")', 
    'ATTACH FILESTORAGE DATABASE test1("./test1.json")', 
    'USE test1', 
    'CREATE TABLE IF NOT EXISTS `preferences` (`id` int(11) NOT NULL, `tab` varchar(45) DEFAULT NULL, `tab_id` int(11))', 
    'INSERT INTO `preferences` (`id`, `tab`, `tab_id`) VALUES (1, "where", 1), (2, "when", 8)',
    //'DELETE FROM preferences WHERE id = 1',    
    'SELECT * FROM preferences'    
]).then(function(res){
    console.log('Result from last query:',res)
}).catch(function(reason){
    console.trace(reason)
})
```

but if we uncomment the `DELETE FROM preferences WHERE id = 1` part we get an error: ´TypeError: Cannot read property 'length' of undefined´

Any inputs from @agershun ?

**Comment by nbdamian** [comment]
Well, No... I haven't tested with your latest update, but I am unable to use Promise at all, it returns that Promise is not a function, even using a promise library.

**Comment by mathiasrw** [comment]
Interesting. What is your setup? browser? Cordova? version?

**Comment by nbdamian** [comment]
Cordova running Crosswalk12

**Comment by mathiasrw** [comment]
Aw... im not in the Cordova world yet...

**Comment by nbdamian** [comment]
Ok, With a promise library working (Whooop).
Your code works with no errors.
Although the initial issue still occurs.
If I uncomment the "'DELETE FROM preferences WHERE id = 1'," It returns the error again,

```
VM347:13 TypeError: Cannot read property 'length' of undefined(…)
(anonymous function) @ VM347:13
P @ alasql.js:4420
x @ alasql.js:4420
T @ alasql.js:4420
A @ alasql.js:4420
a @ alasql.js:4420
```

**Comment by mathiasrw** [comment]
Nice!!!

**Comment by nbdamian** [comment]
Sorry but this still isn't resolved. You had the DELETE FROM commented out.

**Comment by mathiasrw** [comment]
Wups...

**Comment by nbdamian** [comment]
I was scanning through 72delete.js and 94filestorage.js and from the looks of it there is no direct check in 72delete.js that handles filestorage in the where block.
I will do some testing tomorrow if I find the time, but should FileStorage have something like 
`deleteFromTable(databaseid, tableid, wherefn, params, cb)` instead of running the default?

**Comment by mathiasrw** [comment]
> no direct check in 72delete.js that handles filestorage in the where block

nicely spottet

>  should FileStorage have something like 
`deleteFromTable(databaseid, tableid, wherefn, params, cb)` instead of running the default

I have a feeling that data operations are done in mem and then pushed to the file like https://github.com/agershun/alasql/blob/2ee7f79c28a89a6342badee875376232f9d2aa5d/src/94filestorage.js#L197 - but I must admit I dont know how its structured

**Comment by nbdamian** [comment]
I will run through the code some more today.
so far, I have found that when using filestorage (I don't know if this is the same in other engines), but the data is not stored in the db.tables[tableid] object.

**Comment by umasudhan** [comment]
The table was not populated correctly in the case of filestorage- this fixes it:

Index: src/72delete.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/72delete.js	(revision 882f0b874b43b670987513d2294e1cd9ba4af7fa)
+++ src/72delete.js	(date 1575952312931)
@@ -62,7 +62,7 @@
 				);
 			}
 
-			if (alasql.options.autocommit && db.engineid && db.engineid == 'LOCALSTORAGE') {
+			if (alasql.options.autocommit && db.engineid && (db.engineid == 'LOCALSTORAGE' || db.engineid == 'FILESTORAGE')) {
 				alasql.engines[db.engineid].loadTableData(databaseid, tableid);
 			}
 
@@ -97,7 +97,7 @@
 			}
 
 			var res = orignum - table.data.length;
-			if (alasql.options.autocommit && db.engineid && db.engineid == 'LOCALSTORAGE') {
+			if (alasql.options.autocommit && db.engineid && (db.engineid == 'LOCALSTORAGE' || db.engineid == 'FILESTORAGE')) {
 				alasql.engines[db.engineid].saveTableData(databaseid, tableid);
 			}

**Comment by mathiasrw** [comment]
OMG - how embarrassing... thank you!
