### ISSUE TITLE
Multiple Queries cb() response

### ISSUE THREAD

**Issue by nbdamian** [agershun/alasql#626]
I am running a query of
```DROP TABLE IF EXISTS `regions`; 
CREATE TABLE IF NOT EXISTS `regions` 
  ( 
     `id`           INT(11) NOT NULL, 
     `name`         VARCHAR(80) NOT NULL, 
     `file`         VARCHAR(80) NOT NULL, 
     `date_added`   VARCHAR(80) NOT NULL, 
     `date_updated` VARCHAR(80) NOT NULL, 
     PRIMARY KEY (`id`) 
  ) ```
And the cb() response is `[1, 1]`

I take it that this is an array of all of the queries executed?
E.g the first 1 is from the DROP TABLE, and the second is from the CREATE TABLE?

**Comment by mathiasrw** [comment]
Yes - if you have more than one command (seperated by `;`) you will get the answers of each command in the array
