### ISSUE TITLE
Cleaning up issues

### ISSUE THREAD

**Issue by nbdamian** [agershun/alasql#628]
Could I suggest going through all the issues, if they are marked as "solved, please test" and the user hasn't responded within a month or so, close the issue with a message of "Closing the issue due to lack of response, reopen if is not solved", or something similar.

The fact that there are over 260 issues, makes it look like this repo lacks support.

**Comment by mathiasrw** [comment]
:+1:

**Comment by agershun** [comment]
:+1:

Отправлено с iPhone
