### ISSUE TITLE
Inserting from an array

### ISSUE THREAD

**Issue by fredt34** [agershun/alasql#63]
It took me ages to find this syntax:

```javascript
	// Inserting an array (from a previous query) into Product table 
	//db.tables.Product.data =  data is elegant, but how to use it with varying table names ?
	myTable = "Product";
	db.exec('INSERT INTO ' + myTable + ' SELECT * FROM ?',[data]);  // That's THE syntax !! 
	//Guessed from https://github.com/agershun/alasql/wiki/Insert
```

(my 2 к. - sorry if it was obvious)

**Comment by agershun** [comment]
You can use three different methods to insert data from array into table:

```js
    var data = [{a:1}, {a:2}];
    alasql('CREATE TABLE one');
    // Method 1
    alasql.tables.one.data = data;
    // Method 2
    alasql('SELECT * INTO one FROM ?',[data]);
    // Method 3
    alasql('INSERT INTO one SELECT * FROM ?',[data]);
```
BTW: If you download data from external file, you can use this syntax:
```js
    alaslq('CREATE one; SELECT * INTO one FROM JSON("data.json")');
```

**Comment by joerch80** [comment]
Is it possible to insert data from JSON into a table which has already defined columns?
```javascript
alasql('CREATE TABLE test (row1 INT, row2 TEXT');
var data = [{"row1" : 1, "row2" : "String1"}, {"row1" : 2, "row2" : "String2"}];
alasql.tables.test.data = data;
```
I'm trying it on a localStorage database and don't get the rows from JSON into the table.

**Comment by agershun** [comment]
You can try this:

    alasql('SELECT * INTO mytable FROM ?',[data]);

Îòïðàâëåíî ñ iPhone

**Comment by joerch80** [comment]
After rewriting the part in my project it now works as mentioned above. Thanks for your help!
Probably I had a problem in calling the statements because it was an async operation. I'm using "promises" now.

**Comment by agershun** [comment]
Please, write here if you find the source of the problem!

**Comment by thekennysong** [comment]
has anyone gotten alasql.tables.one.data = data to work while using indexeddb? I've tried method 2 and 3 but for really large arrays it takes awhile to execute the callback.

**Comment by mathiasrw** [comment]
IndexedDB will not work with this.
