### ISSUE TITLE
JOIN retrieves only fields from 1 table instead of combination from both

### ISSUE THREAD

**Issue by seb-ster** [agershun/alasql#636]
Creating 2 tables with slightly different content, and performing some JOINs

`alasql('CREATE TABLE aa (id INT, gid INT, icao STRING, iata STRING)');
alasql('INSERT INTO aa (id, gid, icao, iata) VALUES (1, 1000,"LOWW", NULL)');
alasql('INSERT INTO aa (id, gid, icao, iata) VALUES (2, 1000,"EHAM", "AMS")');
`

`alasql('CREATE TABLE bb (id INT, gid INT, icao STRING, iata STRING)');
alasql('INSERT INTO bb (id, gid, icao, iata) VALUES (3, 1000,"LWSK", "SKP")');
alasql('INSERT INTO bb (id, gid, icao, iata) VALUES (4, 1000,"EBBR", NULL)');`

`alasql('SELECT * FROM aa JOIN bb USING gid');`
Returns the rows form bb 2 times. (4 rows in total)
But was expecting 4 rows with a combination of fields from aa and bb.

`alasql('SELECT aa.*, bb.* FROM aa JOIN bb USING gid');`
Yields same result.

`alasql('SELECT aa.id, bb.id FROM aa JOIN bb USING gid');`
Yields same result with only the id field from bb 2 times.

`alasql('SELECT aa.id AS aaID, bb.id AS bbID FROM aa JOIN bb USING gid');`
Expected result! Fetching all combinations of id's from aa and bb (4 rows in total)

I think the statements without field aliases (AS) just overwrite their particular fields in the result set.
Where SQL would probably prepend the table name/alias to those fields.
(Result would have fields like: aa.id, bb.id)

This might be related to #402 

(AlaSQL v0.2.5, FF45)

**Comment by mathiasrw** [comment]
Thanks for a great description. 

Lets talk about the subject in #547 to keep history (and as you closed this issue i guess thats what you had in mind...)
