### ISSUE TITLE
Can I get an Array of Arrays instead of an Array of Objects?

### ISSUE THREAD

**Issue by loque** [agershun/alasql#637]
Is it possible to get an Array of Arrays from a query instead of an Array of Objects?

I mean, instead of this:
```javascript
var result = alasql('SELECT field1, field2 FROM table_name');
// result = [{field1: "value1", field2: "value2"}, {field1: "value3", field2: "value4"}]
```
This:
```javascript
var result = alasql('SELECT field1, field2 FROM table_name');
// result = [["value1", "value2"], ["value3", "value4"]]
```

I know I can do it myself afterwards, but maybe there is a way of telling alasql to do it internally so that the results are not iterated over again by me. If result has 300k rows * 10 fields this makes a difference.

**Comment by mathiasrw** [comment]
By prepending `MATRIX OF ` before `SELECT` you will get what you are looking for. 

```js
var result = alasql('MATRIX OF SELECT field1, field2 FROM table_name');
// result = [["value1", "value2"], ["value3", "value4"]]
```

https://github.com/agershun/alasql/wiki/Matrix
