### ISSUE TITLE
local Time with moment js

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [agershun/alasql#639]
Hello ALASQL team,

I cannot seem to get the local time. I used below: but it differs 2 hours.
` ` `
moment.locale('nl');

alasql.fn.moment = moment;

alasql('SELECT moment(StartDate)->format("HH:mm") AS startTime,
` ` `
Can you advise?

Kind regards,
Mario

**Comment by mathiasrw** [comment]
Can you make momentjs spit out the correct values when not using AlaSQL?

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

I have captured the REST date output and the result = Wed Mar 30 2016 12:00:00 GMT+0200 (W. Europe Daylight Time)
We need to get 10:00:00
```
			var jsonDateTime = "\/Date(1459332000000)\/";
			var result = new Date(parseInt(jsonDateTime.substr(6)));
			console.log("result: "+result)
```
When I simply call moment() I get the right time at this moment.

Does this help?

Kind regards,
Mario

**Comment by mathiasrw** [comment]
@MarioVanDenEijnde

It looks like `moment.locale('nl')` is not having any effect. 

Feel free to fiddle around with http://jsfiddle.net/zpc8yzns/

However - using moments directly and using it via alasql yelds same result - so its not related to alasql - so Im closing the issue. Please reopen if you get a different result when using moments directly and using it via alasql.

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

I had to add ".utc()" to moment() and then it works fine.

Kind regards,
Mario

**Comment by mathiasrw** [comment]
Nice. Thanks for sharing.
