### ISSUE TITLE
Better Error Messages

### ISSUE THREAD

**Issue by nbdamian** [agershun/alasql#640]
Could I suggest error messages be similar to sql, for example:
If a column you are querying does not exist, you would error log:
**Unknown column 'columnname' in 'tablename'** or **Column 'columnname' doesn't exist in 'tablename'**

Also, a lot of errors are not being handled and return javascript errors, perhaps we should go through some common errors we know of and then add better error logging to them.

**Comment by mathiasrw** [comment]
Really good idea. Do you know if there is a standardised SQL error list?

> perhaps we should go through some common errors we know of and then add better error logging to them

Do you have any inputs which ones to start with?

**Comment by nbdamian** [comment]
I'm not sure there are any global standards for sql errors, but I would expect oracle to be a good choice.
https://docs.oracle.com/cd/B28359_01/server.111/b28278/toc.htm

**Comment by nbdamian** [comment]
I would say definitely, start with the basics, ones that happen with incorrect syntax, or missing something important.
E.G
Incorrect Column Name / Column does not exists
Missing table in FROM
Missing parenthesis

**Comment by mathiasrw** [comment]
The parenthesis is tricky as its part of the parser generated from JISON

Now - I got the most common errors with error in table name and error in column name

```js
alasql('create table abc (a int)')
1

alasql('select a from abc')
[]

> alasql('select b from abc')
Uncaught Error: Column does not exists: b

> alasql('select a from abcd')
Table does not exists: abcd
``` 

Pleaser try it out in the last version of https://github.com/agershun/alasql/blob/develop/dist/alasql.js

**Comment by nbdamian** [comment]
Perfect, although I am unsure whether it was caused by this update, but it seems that it is now required to wrap any columns like `columnname`, normally you can use it without the `.
It was returning an error of:
````
Uncaught Error: Column does not exists: 
````

Is this intentional?

**Comment by mathiasrw** [comment]
Hmm, what sql are you using. I cant replicate it: 

```js
// alasql.version: 0.2.5-develop-1262

> alasql('create table abc (a int)')
1

> alasql('insert into abc values(2), (5)')
2

> alasql('column of select a from abc')
[2, 5]

> alasql('column of select b from abc')
Uncaught Error: Column does not exists: b

```

**Comment by nbdamian** [comment]
Strange... I wonder what was causing it. Ignore then ;)
