### ISSUE TITLE
Export to Multiple Sheets using same data 

### ISSUE THREAD

**Issue by philibin** [agershun/alasql#643]
Note: I posted this on issue #226 but then saw the response to create a new issue. So that is what I am doing. If I am doing this wrong I am sorry, I am new here and not sure how everything works yet.

Basically, I have this working, but have to write three different files and then have the user combine them. I'd really like to do that in one step. So the below code works great... So what I want is, I guess, more functionality or an enhancement.

I have a javascript array that I am using to make a spreadsheet. I am using the following code:

```
[begin code]
var opts = {
headers:true, 
sheetid:"New"
};

window.exportExcel = function exportExcel() {
alasql("SELECT [1] AS [Bill Account], \
[2] AS [Case Number], \
[4] AS [Cust Name], \
[5] AS [Address] \
INTO XLSX('testing.xlsx',?) FROM ? WHERE [38] = 'False'",[opts,masterArray]);

}
[end code]
```
(I use more than 5 columns but didn't want to add all 34 that I do use here)

What I would like to do is, using the same array write to a spreadsheet with three tabs.

lets say the three tabs should be "New", "Previously Sent", "Paid" and I want to use the same Array to do this. The way I identify them is by using the same code above but changing the WHERE CLAUSE.

For Example: in the "New" sheet: FROM ? WHERE [38] = 'False'
In the "Previously Sent" sheet: FROM ? WHERE [38] = 'True' AND [41] = 'False'
and in the "Paid" sheet: FROM ? WHERE [38] = 'True' AND [41] = 'True'

I did see your post above that lets you use two arrays as datasets, and I could split the arrays I guess (but this would kill the memory in big tables)... and it would only do two sheets (not the three I need).

So, in my perfect world... I'd need to be able to write three "queries" and place each in a separate sheet in the same workbook. Could this be possible?

Thanks,
-Bill

ps - masterArray is a multidimensional javascript array with 45 columns and ~2500 rows.

**Comment by mathiasrw** [comment]
Its a good idea. 

I have a feeling we need to get someone with good knowledge of the source to look at this. @agershun for example...

While we are waiting for that I suggest that you have a look at https://github.com/SheetJS/js-xlsx#writing-workbooks and see if you can solve your problem by using alasql to get the results out and js-xlsx to format the data into sheets

**Comment by mathiasrw** [comment]
Have a look at 

http://jsfiddle.net/sd7822df/1/

Here data is hardcoded. If you replace the hardcoded values with `alasql('select ...')` you can have different selects on two worksheets.
