### ISSUE TITLE
[LAST_INSERT_ID] Into the "res" object or using a function

### ISSUE THREAD

**Issue by rognoni** [agershun/alasql#645]
Is there a way to have the last insert ID into the `res` object or using a function?

```javascript
db.exec('CREATE TABLE `schema` (id INT AUTO_INCREMENT, name STRING)');

db.exec('INSERT INTO `schema` (name) VALUES ("info")', [], function(res){
  console.log(alasql.databases.info.tables.schema.identities.id);
});

db.exec('INSERT INTO `schema` (name) VALUES ("info2")', [], function(res){
  console.log(alasql.databases.info.tables.schema.identities.id);
});
```
In this case the result is not correct:

```
Object { value=3,  step=1}
Object { value=3,  step=1}
[Object { id=1,  name="info"}, Object { id=2,  name="info2"}]
```

https://github.com/rognoni/adaptable/blob/master/Front-end/HTML5-Bootstrap4/database.js

**Comment by nbdamian** [comment]
@rognoni 
You should be able to run a query of:
````
SELECT LAST(id) AS id FROM `schema`
````
after your query. This will get the last inserted id from the table.

**Comment by csu7106** [comment]
Response Object : { [ ] }

**Comment by mathiasrw** [comment]
@csu7106 please create a new issue describing what code you are using and what result you expected to get.
