### ISSUE TITLE
Add Support for Bower

### ISSUE THREAD

**Issue by driannaude** [agershun/alasql#65]
Installation via bower would be awesome!

**Comment by agershun** [comment]
Thank you for the issue! I tried to add this support a month ago, but had some format problems. So, I will fixed it ASAP.

**Comment by MartynJones87** [comment]
This would be awesome if it could be done!

**Comment by agershun** [comment]
I just registered AlaSQL as a Bower package. May I ask you to verify, can it be installed via bower?

**Comment by agershun** [comment]
We need to clean bower.json ignore section. What usually people leave in the bower package? Only ```dist``` directory?

**Comment by driannaude** [comment]
Hey buddy, I'll have a look when I get home, normally the minimum is a `dist` folder with minified and un-minified versions, and optionally a `src` folder with 'uncompiled' code and any grunt tasks for users who like to build it themselves, at least, that's how I do it following the bootstrap example.

**Comment by agershun** [comment]
Thank you! I updated ```.bower.json``` (now it is in develop branch) and minimize the number of files included. Hope we can fix it after couple of iterations.

https://github.com/agershun/alasql/commit/970ef53a2a56b63bbde247a69e9c9f8b0cd6ee05

**Comment by driannaude** [comment]
@agershun - Are the bower dependencies in the `lib/` folder required by the files in the dist folder? I had a quick look, it doesn't look like it. Also, here are some good references [](http://addyosmani.com/blog/checking-in-front-end-dependencies/)

**Comment by driannaude** [comment]
Sorry, accidentally closed this... [Here](http://addyosmani.com/blog/checking-in-front-end-dependencies/) and [here](https://github.com/bower/bower.json-spec#ignore) is some good reading on ignores and well as the Spec from the Bower team respectively. I'd recommend pushing the dependencies as per the first article, there are some valid reasons. It just depends on whether or not the `lib/` directory actually requires them or if they have been compiled intp the `dist` JavaScript files with Gulp or Grunt.

**Comment by agershun** [comment]
Actually, alasql.js has no any dependencies at all. User can use it along with xlsx.core.min.js and tabletop.js (for import/export XLSX files), but it is not necessary for production. It just one file.

I will read the articles, and try to start use Bower to understand what is really needed :) 

Please, if you feel that something sould be changed, write it here or make a pull request. Thank you!
