### ISSUE TITLE
What is used to detect indexeddb support?

### ISSUE THREAD

**Issue by nbdamian** [agershun/alasql#655]
If a device does not support indexeddb, does alasql use its own polyfill to handle it, or simply returns an error?
If alasql does not polyfill it, what does alasql use to check for indexeddb support?

**Comment by nbdamian** [comment]
It seems that there is no warning if IndexedDB is not supported. should we implement one?

**Comment by mathiasrw** [comment]
Sure!

lets implement it in 15utility.js

**Comment by nbdamian** [comment]
I have created a pull request, although could you look at it and check why when I throw the error, it causes alasql to be undefined.

**Comment by mathiasrw** [comment]
Sure. Ill have a look at it tonight.

**Comment by mathiasrw** [comment]
Have PR'ed your PR :)

**Comment by nbdamian** [comment]
Merged
