### ISSUE TITLE
Read XLS File

### ISSUE THREAD

**Issue by cbugari** [agershun/alasql#658]
Hi, I'm referring to an Excel file as follows:

```js
alasql('SELECT Fecha FROM XLSX("http://databoard.com.ar/DEMOPrueba/Datos/crecimiento2.xlsx",{headers:true})',[],function(resFecha){
    
               alert(JSON.stringify(resFecha));
    });
```

I need to save the resulting JSON in a variable for later use, such as used below

var res = alasql('SELECT * FROM ? ',[result]);

I'm stuck and do not know how. Could you help me!!!
Thank you so much
cease

**Comment by mathiasrw** [comment]
Im not sure if you are asking about why the data is not present after your call to alasql or if you cant get resFecha to be in the global scope. 

If its to use the data later work with something like:
```js
myAwesomeData={};

alasql('SELECT Fecha FROM XLSX("http://databoard.com.ar/DEMOPrueba/Datos/crecimiento2.xlsx",{headers:true})',[],function(resFecha){
               myAwesomeData.recha = res.fecha
               alert(JSON.stringify(resFecha));
    });
```

If its the "why the data is not present after your call to alasql":

Interacting with files is async, so the code will continue before the result is ready. 

The code `alasql('SELECT * FROM ? ',[result]);` is sync, so it will only continue when the result is ready. 

So you need to work with your data in the function where you wrote `alert(JSON.stringify(resFecha));`

**Comment by cbugari** [comment]
Thanks Mathias.
I have to use resFecha later as a parameter in a graph. Therefore I need to know the value of the variable after the call to alasql. It is not possible to work synchronously from an Excel file?
The example that you pass me myAwesomeData, think of the same, outside the call to alasql myAwesomeData value is undefined, since the alert resolved before the alasql.
copy example

   myAwesomeData={};
  alasql('SELECT Fecha FROM XLSX("http://databoard.com.ar/DEMOPrueba/Datos/crecimiento2.xlsx",{headers:true})',[],function(resFecha){
               myAwesomeData.fecha = resFecha;
      });
      alert(myAwesomeData.fecha);


Thanks a lot.
regards
cease

**Comment by mathiasrw** [comment]
The call is async because its getting data from the internet

What you need to do is to put into a function that you can call after its done. 

You might want to have a look at http://rowanmanning.com/posts/javascript-for-beginners-async/

**Comment by cbugari** [comment]
Hola, disculpa por la insistencia. Segun la documentacion entiendo que puedo consultar de manera sync and async. 
Yo trato de hacer el ejemplo de la documentacion de manera sync con un SCV y me da error. (Titulo: Work with CSV, TAB, TXT, and JSON files en https://github.com/agershun/alasql)
La pregunta concreta para es: ¿Puedo leer archivos (xlsx, SCV)  de forma sync? 
Muchas Gracias por tu atencion..
Cesar

**Comment by mathiasrw** [comment]
I was pretty sure invoing files is always async - according to https://github.com/agershun/alasql/wiki/Async it is. But its correct that the example at https://github.com/agershun/alasql#work-with-csv-tab-txt-and-json-files indicates something different. 

Confusing. 

In any case - IF this is correct (will investigave) it would only be able to run sync on node and not in the browser. The reason is that the http(s) call would be async so its not the library but the way javascript interacts with the world.

**Comment by cbugari** [comment]
Mathias: It is not my idea to generate any confusion on the subject. What happens is that I'm using and I fully alasql arise difrentes problematic. Luckily I was able to solve the issue by generating another function and forcing the javascript code to be executed sequentially. If you like I can publish the solution.
Thanks for your time.
cease

**Comment by mathiasrw** [comment]
> It is not my idea to generate any confusion on the subject

Its the documentation thats confusing - not you...

Please share your solution for others to learn

**Comment by rkchunduri** [comment]
I want to know if there is any update on this issue.How can we read data from excel using alasql in synchronous manner.

**Comment by mathiasrw** [comment]
> How can we read data from excel using alasql in synchronous manner.

Please have a look at https://github.com/agershun/alasql/wiki/Async

I will close this issue as @cbugari seams not to share his solution from https://github.com/agershun/alasql/issues/658#issuecomment-213114141

**Comment by rkchunduri** [comment]
@mathiasrw  The Link you have given works only for async operations.How about sync ?

@cbugari Can you please provide me your solution

**Comment by cbugari** [comment]
Sorry for the delay in response. I was with some personal problems. Step implemented code.

-------- code -------
var datafile={};
$( document ).ready(function() {
     queryGeneral().done(function(){
perform some action, such as loading a graphic, for example  grafico1()
        });
});

function queryGeneral() {
             var r = $.Deferred();
            alasql('SELECT * FROM XLSX("Datos/Maestro_Clientes.xlsx",{headers:true})',[],function(resGen){
            datafile = resGen
            r.resolve();
        });
        return r;
};
----- END CODE -----
Document.ready, espera que termine de ejecutarse la funcion queryGeneral. Una vez cargado el query alasql en la variable datafile, prosigue el código y carga por ejemplo el grafico (función grafico1().

I hope I was clear in the explanation. Any inquiry to disposal.

Thank you so much

**Comment by mathiasrw** [comment]
Thank you @cbugari :)

@rkchunduri Please read the following:

>  AlaSQL will always run async in the following cases. 
* INTO-functions (for example `SELECT * INTO CSV(...)`)
* FROM-functions  (for example `SELECT * FROM CSV(...)`)
* If using AlaSQL as a [[WebWorker]]
* All operations involving [[IndexedDB]]

> If you are not sure what the point of async is, have a look at http://rowanmanning.com/posts/javascript-for-beginners-async
