### ISSUE TITLE
How to write data on specific cell or range of cells in excel

### ISSUE THREAD

**Issue by monajafi** [agershun/alasql#660]
I need to write on specific cell of excel. how should I do this?
also where can I find a a more style attributes like the one you wrote in following example
 var mystyle = {
      headers:true, 
      column: {style:{Font:{Bold:"1"}}},
      rows: {1:{style:{Font:{Color:"#FF0077"}}}},
      cells: {1:{1:{
        style: {Font:{Color:"#00FFFF"}}
      }}}
    };

**Comment by mathiasrw** [comment]
Pleae have a look at https://github.com/agershun/alasql/wiki/XLSX#range
