### ISSUE TITLE
Backslash character on windows misbehaves with some export paths

### ISSUE THREAD

**Issue by abrthel** [agershun/alasql#663]
Alasql does not seem to like backslash characters in certain paths when exporting tables as JSON files.

``` Javascript
const path = require('path');
const alasql = require('alasql');

var database = new alasql.Database();
var tableName = 'testTable';
var outputPath = path.join('./build/', 'factions.json'); // output: build\factions.json

database.exec(`SELECT * INTO JSON('${outputPath}') FROM ${tableName};`)
````

results in and error that looks like the following

```
ENOENT: no such file or directory, open 'C:\full\path\to\build♀actions.json'
```

However if I substitute `outputPath` in the above example for
```
var outputPath = path.join('./build/', 'outputFile.json'); 
```
then the execution works and an outputFile,json file is created in the build directory.

Environment:
Windows 7 SP1 x64
Node v5.10.1
Alasql v0.2.5

**Comment by mathiasrw** [comment]
Backslash is buggy at the momemt. You need to escape the string as normal AND you need to escape them again if you put them into "strings" in the sql string. 

So - you need to add an extra layer of `.replace(/\\/g,"\\\\")`

(or just do the much more easy understandable `.replace(/\\/g,"/")` - will also work on windows)
