### ISSUE TITLE
Operator ->

### ISSUE THREAD

**Issue by andyanderson** [agershun/alasql#669]
Hi,

I’m looking for an explanation of the operator `->` that I found in someone else’s code (and also in yours http://alasql.org/api/alasql.js.html). I cannot find it anywhere, seems like it should be on the operators page, https://github.com/agershun/alasql/wiki/Operators .

Thanks,

— Andy

**Comment by mathiasrw** [comment]
Good point. 

I actually dont know. Maybe @agershun can comment a bit here?

From https://github.com/agershun/alasql/blob/develop/src/alasqlparser.jison#L561-L563 I had the feeling it was a alias for `.` for indicating proppeties of objects - but looking into the source it looks like `a->b` is treated different than `a.b`

**Comment by andyanderson** [comment]
I did locate the code in AlaSQL’s code base:

https://github.com/agershun/alasql/blob/ee7c4afa250f4271bcafe6572ecbe7e17f125ca2/src/50expression.js#L288

Mostly it does this:

properties->text                    becomes         properties["text"]
properties->number              becomes         properties[number]
properties->function(args)    becomes         properties["function"](args)

I was hoping for a more complete explanation, though (and thinking about others who follow).

**Comment by mathiasrw** [comment]
I think thats it... Kind of the `->` in php

**Comment by andyanderson** [comment]
I recognized -> as the structure-pointer member operator in C/C++ and the object member operator in C++/Perl/PHP :-) so I sort of understood what it was doing. I was just surprised to see it in JavaScript (of course it’s not, really, it can only be embedded in SQL strings — I think).

**Comment by mathiasrw** [comment]
I have updated https://github.com/agershun/alasql/wiki/Operators

any inputs to improvements?

**Comment by andyanderson** [comment]
That’s great Mathias! I think the examples are really helpful. I would recommend that you also provide their outputs, e.g.

var data = [{a:{b:1,c:1}, {a:{b:2}}}]

alasql(‘SELECT a->b FROM ?’, [data]);

+------+
| a->b |
+------+
|  1   |
|  2   |
+------+

Maybe also put this example here:

	https://github.com/agershun/alasql/wiki/getting%20started

I suspect  this phrase “Arrow function -> property” is not what you had in mind. Perhaps “Embedded table properties” ? I think it would help to move this following the next example, which is simpler.

In the phrase “is used in AlaSQL to access nested data” can this say “is used in AlaSQL queries to access nested data.” Not sure if you have another name for these patterns, but I think it’s important to clarify that this doesn’t work more generally in JavaScript :-).

By the way, this operator does seem to be colloquially referred to as the “arrow”, but I like your heading “Access a child”.

— Andy

**Comment by mathiasrw** [comment]
Done !

Im closing this, but if you have any further inputs just let me know...
