### ISSUE TITLE
issue with DROP DATABASE - indexeddb

### ISSUE THREAD

**Issue by nbdamian** [agershun/alasql#675]
Running 
````
DROP DATABASE db_name
````
Returns the following error:
````
Cannot drop database 'db_name', because it is attached. Detach it.
````

Although, if you detach the database, alasql is unable to find it...
````
DETACH DATABASE db_name;
DROP DATABASE db_name;
````
Returns the following error:
````
Database 'db_name' does not exists
````

Is there something wrong with the checks in DropDatabase?

**Comment by nbdamian** [comment]
I have resolved this.
We should add to the documentation that you must run:
````
DROP INDEXEDDB DATABASE db_name
````

**Comment by mathiasrw** [comment]
Great !

I have updated https://github.com/agershun/alasql/wiki/IndexedDB and https://github.com/agershun/alasql/wiki/DROP

I would love if you could have a look and let me know how it can be improved.

**Comment by nbdamian** [comment]
I will run some testing, but it might be that FILESTORAGE requires the engine name as well.
Also, I'm not sure if you have control, over it or if it is how Github highlights the syntax,
`DROP INDEXEDDB DATABASE db_name` only highlights `DROP INDEX`
Also, in the DROP wiki page, should we fix the spelling mistake in 

> Note that [engine] is to be used when the database to be DROPed is hosed by a different engine. 
Example:

to 

> Note that [engine] is to be used when the database to be `DROP`ped is hosed by a different engine. Example:

**Comment by mathiasrw** [comment]
Thank you for input!
https://github.com/agershun/alasql/wiki/DROP is updated and informations was added to https://github.com/agershun/alasql/wiki/filestorage

The syntax highlight is not on as the word indexeddb is not a normal SQL word.
