### ISSUE TITLE
DOCs: XLSX file saving, can only save in .xls formats?

### ISSUE THREAD

**Issue by keyscores** [agershun/alasql#677]
I think the DOCs should be clear about why the XLSX exporting is actually using a .xls extension (instead of the expected .xlsx'.

Why this is an issue:
When a file is saved as '.xlsx'  Excel complains about loading the file. 'The file format or file extension is not valid'.

With '.xls'  excel will  usually open it as an XLSX . Except that for many Mac OSX users this will force it to open and parse as a .xls , often in the app Numbers.

Is this is a limitation of ALASQL or do the docs need updating?

**Comment by mathiasrw** [comment]
There was an error on https://github.com/agershun/alasql/wiki/XLSX stating that to save XLSX you must write `SELECT * INTO XLSXML("restest280b.xls") FROM ...`

The correct syntax is `SELECT * INTO XLSX("restest280b.xlsx") FROM`

The documentation has been corrected. There is a simple JSfiddle of the corrected syntax here: http://jsfiddle.net/j4wr3bze/

Please reopen if the new syntax does not help you out.

**Comment by keyscores** [comment]
@mathiasrw Thanks for answering quickly. However my local Excel cannot open the .xlsx file generated by the jsfiddle.

It's the same issue I mentioned above. Excel refuses to open and gives the error : 'The file format or file extension is not valid'.

I'm on OSX with the latest version of Microsoft Office.

**Comment by mathiasrw** [comment]
Hmm. Interesting. 

What version of excel are you using? 2016?

**Comment by keyscores** [comment]
It's the latest one for Mac as I understand.
Microsoft Excel for Mac 2011
Version 14.5.2 ( 150604 )

**Comment by mathiasrw** [comment]
Its hard for me to debug as I only have [Excel 2016 for Mac](http://www.microsoftstore.com/store/mseea/en_US/cat/Office/categoryID.69943800). If you have any inputs on what is not working / any debug information that would be much aprechiated.

**Comment by keyscores** [comment]
Strangely the error went away now... :) I'll close this and reopen when I can reproduce.
