### ISSUE TITLE
i use  alasqlparser.jison get some error,what problem ?

### ISSUE THREAD

**Issue by timtian** [agershun/alasql#679]
i is freshman about jison.
this my code 
![image](https://cloud.githubusercontent.com/assets/3632841/15348147/ab9f0ea2-1cfa-11e6-9907-9f98df3b971b.png)

but i got lot warning
![image](https://cloud.githubusercontent.com/assets/3632841/15348155/c07b029a-1cfa-11e6-8592-bb8c9337d361.png)

 is ok?

**Comment by mathiasrw** [comment]
> i is freshman about jison. 
?

If you want to parse the SQL you can use alasql.parse('SELECT ....')
