### ISSUE TITLE
Create Google Spreadsheets example

### ISSUE THREAD

**Issue by ryanlovett** [agershun/alasql#68]
The top-level wiki page mentions alasql's ability to use [Google Spreadsheets](https://github.com/agershun/alasql/wiki/Google%20Spreadsheets). I would be interested in seeing a recipe for using a sheet as a data source. Thanks!

**Comment by agershun** [comment]
Thank you! I added an example to [this page](https://github.com/agershun/alasql/wiki/Google-Spreadsheets).

**Comment by ryanlovett** [comment]
Perfect, thanks!


Ryan

**Comment by abubelinha** [comment]
The [jsfiddle example](http://jsfiddle.net/tov0zcmd/) I see in the [wiki](https://github.com/agershun/alasql/wiki/Google-Spreadsheets) is not working for me. 
When I run it I see nothing in the  results pannel.

Chrome developer console shows this message:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
(index):38 Uncaught ReferenceError: alasql is not defined at (index):38

```

**Comment by mathiasrw** [comment]
OH - i see. The reference is not working any more. Thank you for letting us know. 

I have updated the wiki with a link to a jsfiddle that has an updated reference: http://jsfiddle.net/xrgwh5v9/
