### ISSUE TITLE
join on using doesn't quite work with javascript property fields.

### ISSUE THREAD

**Issue by brendandburns** [agershun/alasql#680]
When I try to do a join using 'ON' and javascript properties (`a->b`) the join itself seems to work correctly, but the resulting data doesn't include all fields.

Fiddle:
http://jsfiddle.net/4nL08zg5/

**Comment by mathiasrw** [comment]
Nicely spotted!

**Comment by mathiasrw** [comment]
I can see that the `people` table never gets filled with data in your example. 

I fixed the empty table but could not replicate the `a->b` problem: http://jsfiddle.net/rdbzwy2f/

Is this solving your problem?

**Comment by mathiasrw** [comment]
Im closing. Please reopen if you still have problems.
