### ISSUE TITLE
Escaping Single and Double Quotes in Queries

### ISSUE THREAD

**Issue by gregmcd** [agershun/alasql#683]
It does not appear to be possible to escape single and double quotes in queries--am I missing something? After loading data into an AlaSQL database directly from a JavaScript object, I can't query against it with a query like the following without getting an error:

`alasql('SELECT * FROM table1 WHERE [Product Name]="The "Fast" Runner"')`

The query still has parse errors even when I try using \ and "" to escape the double quotes:
```
alasql('SELECT * FROM table1 WHERE [Product Name]="The \"Fast\" Runner"')
alasql('SELECT * FROM table1 WHERE [Product Name]="The ""Fast"" Runner"')
```

It likewise does not appear possible to insert into a table with a double quote as a value:
```
alasql("CREATE TABLE test (col1 text, col2 text)")
alasql('INSERT INTO test VALUES ("test\"3\"", "test4")')
```

How can I escape single and double quotes in queries such that I could even include a string as a WHERE clause that contained both single and double quotes?

**Comment by mathiasrw** [comment]
It should work - but the implementation is not perfect yet - so it does not. 

The thing is that when you escape the `"` you are only doing it in the string passed to alasql - but because alasql will parse strings in SQL as a javascript string the escape in a string needs to be escaped. 

So the solution is to have `\\` instead of `\`

```js
alasql('SELECT "The \"Fast\" Runner"')
-> Error

alasql('SELECT "The \\"Fast\\" Runner"')
-> No error
```

Where would be a good place in the documentation to put this information?

**Comment by gregmcd** [comment]
This works great. Thanks so much for the fast response, Mathias!

I think "Quirky.md" would be a good spot for this information. I can't figure out how to do pull requests on your Git wiki (looks like it [might not really be possible](http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github)) but I've made the suggested changes to the markdown file myself in [this zip file](https://github.com/agershun/alasql/files/287780/Quirky.and.Getting-started.zip). I also noticed a typo in Getting-started.md that I fixed in the attached (just a misspelling of "requiring").

Let me know if there's a better way to contribute to the documentation!

**Comment by mathiasrw** [comment]
The documentation is crappy to contribute to. Im working on placing iit into its own repo to make it easy to contribute.

I update https://github.com/agershun/alasql/wiki/Getting-started and https://github.com/agershun/alasql/wiki/Quirky - thank you for the inputs :)

**Comment by gregmcd** [comment]
Cool! Very happy to help.

When you have a sec, I noticed my contribution added a typo itself -- backslahes in Quirky.md should be backslashes. Sorry about that!

**Comment by rended** [comment]
single quotes still have trouble

**Comment by rended** [comment]
line 3234 is the problem,my temp solution:
in alasql:

// return '\\' + character;
return character;

and outside: 

    if(field.indexOf('\\') > -1)
        field = field.replace(/(\\)/g, '\\\\');
    if(field.indexOf("'") > -1)
        field = field.replace(/(\')/g, "\\'");
    if(field.indexOf('"') > -1)
        field = field.replace(/(\")/g, '\\"');
    return "`" + field + "`";

**Comment by mathiasrw** [comment]
Oh. Neat. Any chance you could do a PR so I am sure about where you suggest the change?
