### ISSUE TITLE
The hash key for different query statement are identical

### ISSUE THREAD

**Issue by tingli111** [agershun/alasql#685]
As per our testing, We found that hash key for different query statement can be identical sometimes.

For example,
![hashkey](https://cloud.githubusercontent.com/assets/19524495/15596627/9bff3848-23fb-11e6-8928-8470940d9703.png)

We can see that the value for [Field3] are different in above two statements, however the hash keys remain the same.

**Comment by mathiasrw** [comment]
Wow - crazy.

Thanks for letting us know. This must not happen. 

Could I ask you to paste the SQL into this issue without being an image (so I can test things out?)

**Comment by tingli111** [comment]
Sure.

y='SELECT COUNT(*)  FROM [Field1] WHERE (  ([Field2] >= "0") ) AND ( [Field3] = "1SIA-F5M4" ) ORDER BY [Field3]' 

alasql.utils.hash(y)
-2091544146

z='SELECT COUNT(*)  FROM [Field1] WHERE (  ([Field2] >= "0") ) AND ( [Field3] = "1SIA-F5LS" ) ORDER BY [Field3]' 

alasql.utils.hash(z)
-2091544146

**Comment by mathiasrw** [comment]
Please use the last version: https://github.com/agershun/alasql/blob/18b20596940708b16a8b3eb2d2558d5e93162565/dist/alasql.js to get a better hash function until we release next version.

**Comment by tingli111** [comment]
Hi @mathiasrw ,

Thanks for your quick fix.

I've tested that and it is working fine.
Those two statements are returning different hash keys now.
