### ISSUE TITLE
little mistake in wiki

### ISSUE THREAD

**Issue by kaktus40** [agershun/alasql#693]
Hello,
in [this wiki page](https://github.com/agershun/alasql/wiki/How-to-group-javascript-object-grouped-by-multiple-attributes), it's written
```
var res = json2group(input, ["age","class"]);
```
But it seems that class is a keyword and the example in jsfiddle does not work.
If you write the following code, it works:
```
var res = json2group(input, ["age","[class]"]);
```

**Comment by mathiasrw** [comment]
Thank you !
