### ISSUE TITLE
I need to import about 1 million data from excel but i could not fetch and it seems that it is taking time to select those data as well. Is there any solution to fetch huge amount of data from excel??

### ISSUE THREAD

**Issue by dipendra-s** [agershun/alasql#697]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Programming question?
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something not working as expected? 
- Describe the problem  
- Provide code that replicates the problem 
- We suggest to spawn a jsfiddle from http://jsfiddle.net/mtt9r7rx/

**Comment by mathiasrw** [comment]
Is it a one time import?

**Comment by dipendra-s** [comment]
Yes, I need to import data and i have used indexedDB to store data.

**Comment by mathiasrw** [comment]
Will there be an import every time a user uses the system or are you trying to do a one time transformation of data?

**Comment by dipendra-s** [comment]
on time transformation only.

**Comment by mathiasrw** [comment]
How big is the file and how much memory do you have on the computer you use?

**Comment by dipendra-s** [comment]
the file size is about 40 mb and i have got enough memory to process. It is ok if i import around 100,000 rows of data with 5 columns but when importing around 1 million of data browser stops working.

**Comment by mathiasrw** [comment]
if it's working with few data but not many data it's the browsers memory usage that's limiting you. 

If it's a one time thing I suggest looking into using MySQL or Postgres to import data and transform

**Comment by mathiasrw** [comment]
Im closing. Please reopen if you have more questions.
