### ISSUE TITLE
Cannot use two different sql queries to generate an XLS/XLSX/XLSXML with two sheets.

### ISSUE THREAD

**Issue by krizza** [agershun/alasql#698]
Is there a possibility to write 2 SELECT queries and generate it in one excel file for 2 sheets? Currently I don't find a way to achieve this kind of query. It would be very helpful! Thanks for your support! In  [stackoverflow](https://stackoverflow.com/questions/37540499/how-to-sum-a-column-in-alasql-angularjs) I've explained the problem something detailed.

**Comment by mathiasrw** [comment]
Not that I know

**Comment by krizza** [comment]
Would it be possible to implement it?

**Comment by mathiasrw** [comment]
I feel very confident it can. Its "just" a question about 

a) find a suitable syntax for the SQL
b) implement the syntax and integration to xlsx.js

To be frank, I have a feeling you would be better suited by using the [xlsx.js](https://github.com/SheetJS/js-xlsx) directly. Its a bit more code for you, but you get so much more controle.

**Comment by nbdamian** [comment]
The most logical way I can think of for the syntax if it is implemented, would be using sub queries.
I haven't used alasql for xlsx much, so am unsure on the current syntax.

**Comment by mathiasrw** [comment]
Its described here: https://github.com/agershun/alasql/wiki/Into

**Comment by nbdamian** [comment]
Would something like this work?
````
SELECT * INTO XLSX("file.xlsx",{opts}) FROM ((SELECT * FROM data1), (SELECT * FROM data2))
````

**Comment by krizza** [comment]
@nbdamian I will try it and give a feedback after that.

**Comment by mathiasrw** [comment]
Hmm. We are missing a bit about how we want the format for where data should be placed

**Comment by mathiasrw** [comment]
Have a look at 

http://jsfiddle.net/sd7822df/

Here data is hardcoded. If you replace the hardcoded values with alasql('select ...')` you can have different selects on two worksheets.
