### ISSUE TITLE
Read Data from XLS in a synchronous manner

### ISSUE THREAD

**Issue by rkchunduri** [agershun/alasql#699]
This is a duplicate issue of #658 .The Issue is closed,hence I opened a new defect.

How can we read data from XLS in a synchronous manner.

**Comment by cbugari** [comment]
Sorry for the delay in response. I was with some personal problems. Step implemented code.

-------- code -------
var datafile={};
$( document ).ready(function() {
     queryGeneral().done(function(){
perform some action, such as loading a graphic, for example  grafico1()
        });
});

function queryGeneral() {
             var r = $.Deferred();
            alasql('SELECT * FROM XLSX("Datos/Maestro_Clientes.xlsx",{headers:true})',[],function(resGen){
            datafile = resGen
            r.resolve();
        });
        return r;
};
----- END CODE -----
Document.ready, espera que termine de ejecutarse la funcion queryGeneral. Una vez cargado el query alasql en la variable datafile, prosigue el código y carga por ejemplo el grafico (función grafico1().

I hope I was clear in the explanation. Any inquiry to disposal.

Thank you so much

**Comment by mathiasrw** [comment]
> How can we read data from XLS in a synchronous manner.

Are you targeting node or browser?

**Comment by cbugari** [comment]
browser...

**Comment by mathiasrw** [comment]
If you fetch data sync you will stop all other interaction with the code. Why would you want that?

Anyway. Have a look at 

 http://stackoverflow.com/questions/9755485/stop-browser-locking-during-synchronous-ajax

For examples on how to run sync - fetch the raw data and feed it to alasql instead of the url.

**Comment by rkchunduri** [comment]
I am targeting node

On Thursday, June 9, 2016, Mathias Rangel Wulff <notifications@github.com>
wrote:

> How can we read data from XLS in a synchronous manner.
>
> Are you targeting node or browser?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/agershun/alasql/issues/699#issuecomment-224827326>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFG9ELUBOfGv4JJuZgOHjmbe5i-ErrFqks5qJ8nagaJpZM4IxYxJ>
> .
>


-- 
Sent from my iPhone

**Comment by mathiasrw** [comment]
Hi @rkchunduri

Use `fs.readFileSync` to read the file sync and pass it as parameter to alasql instad of url

**Comment by rkchunduri** [comment]
can you please send me an example for passing it as a parameter to alasql

On Thu, Jun 9, 2016 at 7:28 AM, Mathias Rangel Wulff <
notifications@github.com> wrote:

> Hi @rkchunduri <https://github.com/rkchunduri>
>
> Use fs.readFileSync to read the file sync and pass it as parameter to
> alasql instad of url
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/agershun/alasql/issues/699#issuecomment-224879786>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFG9EJqo-2PTCfovPpbxyw43JYnUGUCvks5qKAbggaJpZM4IxYxJ>
> .
>



-- 
Raghavendra Kumar,M.Tech
http://rkchunduri.blogspot.com

**Comment by rkchunduri** [comment]
Do have any update on the above issue @mathiasrw

**Comment by mathiasrw** [comment]
Im sorry. Its only CSV files that can be loaded like this.

**Comment by rkchunduri** [comment]
Do we have any way to read data from excel synchronously ?

On Fri, Jun 10, 2016 at 6:12 AM, Mathias Rangel Wulff <
notifications@github.com> wrote:

> Im sorry. Its only CSV files that can be loaded like this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/agershun/alasql/issues/699#issuecomment-225156092>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFG9EMuUxcvbrsnNbpotEj6hCw7IVLHwks5qKUa4gaJpZM4IxYxJ>
> .
>



-- 
Raghavendra Kumar,M.Tech
http://rkchunduri.blogspot.com

**Comment by mathiasrw** [comment]
Yes. Use `fs.readFileSync(path)` to read the file content sync.

I still - very very strongly - suggest that you look at http://rowanmanning.com/posts/javascript-for-beginners-async to structure your code in an async manner.

**Comment by rkchunduri** [comment]
Hi,

Right now my code is asynchronous.My Code is working as mentioned in the
given blog.

I am expecting a solution which should talk about exeucting async code in
sync way or how to make alasql  to read file synchronously.

On Fri, Jun 10, 2016 at 7:22 AM, Mathias Rangel Wulff <
notifications@github.com> wrote:

> Yes. Use fs.readFileSync(path) to read the file content sync.
>
> I still - very very strongly - suggest that you look at
> http://rowanmanning.com/posts/javascript-for-beginners-async to structure
> your code in an async manner.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/agershun/alasql/issues/699#issuecomment-225167835>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFG9EAw6-sQb2zRvzOsef67IW6WN2Z8Iks5qKVcSgaJpZM4IxYxJ>
> .
>



-- 
Raghavendra Kumar,M.Tech
http://rkchunduri.blogspot.com

**Comment by mathiasrw** [comment]
Sync is not a solution to async. 

Async is a solution to do more things at the same time.

**Comment by rkchunduri** [comment]
Thanks Mathias.

I am expecting a solution to read data from alasql in   *synchronous *manner.Is
it possible ?

On Fri, Jun 10, 2016 at 1:00 PM, Mathias Rangel Wulff <
notifications@github.com> wrote:

> Sync is not a solution to async.
>
> Async is a solution to do more things at the same time.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/agershun/alasql/issues/699#issuecomment-225252649>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFG9ECus02SrXapGch9VfwVDFj9wI7Bbks5qKaZMgaJpZM4IxYxJ>
> .
>



-- 
Raghavendra Kumar,M.Tech
http://rkchunduri.blogspot.com

**Comment by mathiasrw** [comment]
Its only CSV files that can be loaded sync.

**Comment by rkchunduri** [comment]
OK Thankyou.

On Fri, Jun 10, 2016 at 1:41 PM, Mathias Rangel Wulff <
notifications@github.com> wrote:

> Its only CSV files that can be loaded sync.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/agershun/alasql/issues/699#issuecomment-225263079>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFG9EO0hSMNDRx9pz9ouNZFga6iadicTks5qKa_PgaJpZM4IxYxJ>
> .
>



-- 
Raghavendra Kumar,M.Tech
http://rkchunduri.blogspot.com
