### ISSUE TITLE
Excel file with more than 26 columns not read "FROM" correctly

### ISSUE THREAD

**Issue by tolunoide** [agershun/alasql#70]
Hi,

If you have an Excel file with 27 columns (A to AA), it reads only the first column.
I checked and found that function xlscn is wrong for 2 or 3 chars columns.
Line 2930:
        n = n*26+s.charCodeAt(1)-65;
Should be corrected by
        n = (n+1)*26+s.charCodeAt(1)-65;
Same thing at line 2932:
            n = n*26+s.charCodeAt(2)-65;
should be corrected by
            n = (n+1)*26+s.charCodeAt(2)-65;

Best regards

**Comment by agershun** [comment]
Yes, thank you for the issue. I will update version.
