### ISSUE TITLE
Need support meteor 1.3 ES2015 import syntax

### ISSUE THREAD

**Issue by weilitao** [agershun/alasql#701]
When work with meteor and alasql, alasql is injected into script global automatically, not IDE friendly. Would you please to support ES2015 import style, like:

import { alasql } from 'meteor/agershun:alasql';

**Comment by mathiasrw** [comment]
Any inputs on how I support that?

**Comment by weilitao** [comment]
Sorry. I am not familar with Meteo internal, so I have no good idea on how to implement that. Other meteor packages look like just write code as `export {XXXX};`, but this would not works on browser envirnment for alasql.

Btw, I have tried just use npm version of alasql, and import it to my code with `import alasql from 'alasql';`, it works well. Maybe just use the npm version is acceptable in Meteor?

**Comment by mathiasrw** [comment]
>  tried just use npm version of alasql, and import it to my code with `import alasql from 'alasql';`, it works well.

Love that. Thanks !

**Comment by mathiasrw** [comment]
Package "withdrawn" from athmosphere with a messages about using the NPM import syntax
