### ISSUE TITLE
Time delay

### ISSUE THREAD

**Issue by zebasyed** [agershun/alasql#703]
I have an issue if i am using alasql.min.js. Since my webpage needs to export pdf,xcel and csv i am using all the separate min.js which is causing time delay to load my web page. Anyone has any clue as to if i could minimize alasql.min.js (it is 406 KB right now). I tried javascript minimizer it wont work. Kindly let me know if there is any available solution. Thanx in advance!!

**Comment by mathiasrw** [comment]
alasql.min.js can not be smaller at the moment. 

If you are using the lib only to export data I recommend you look into using https://github.com/SheetJS/js-xlsx and https://github.com/avoidwork/csv.js instead.
