### ISSUE TITLE
Exporting and utf-8

### ISSUE THREAD

**Issue by SamanthaAdrichem** [agershun/alasql#705]
When exporting data using the alasql library in utf-8 (containing for example the letter ë) the byte-order-mark isn't added to the CSV. This results in that MS Excel opens the file as ansii? by default. and shows the ë as Ã^ or something

Is it possible to enable this? Or is it currently not available?

**Comment by mathiasrw** [comment]
Its not supported - how can we add this byte-order-mark?

**Comment by SamanthaAdrichem** [comment]
You are using filesaver right? According to this, filesaver should already support it : https://github.com/eligrey/FileSaver.js/issues/160

it's in the filesaver code of your library:
```
    if (/^\s*(?:text\/(?:plain|xml)|application\/xml|\S*\/\S*\+xml)\s*;.*charset\s*=\s*utf-8/i.test(blob.type)) {
        blob = new Blob(["\ufeff", blob], {type: blob.type});
    }

```

It should even be on by default, but somehow it's not when using chrome atleast. ( I would not turn it on by default btw, people are now used to not having it and if you programatically read the file you need to 'skip' it yourself.

I think this should fix it: (atleast for CSV)
```
alasql.into.CSV = function(filename, opts, data, columns, cb) {
....
	opt.quote = '"';
	opt.utf8Bom = false;
	alasql.utils.extend(opt, opts);
	var res = data.length;
	var s = opt.utf8Bom ? "\ufeff" : '';
....
```

Atleast in my test it does. You can then enable it yourself by adding {utf8Bom: true} in the opts
I'll create a pull request in a minute

**Comment by mathiasrw** [comment]
Documentation added

https://github.com/agershun/alasql/wiki/Csv#options
