### ISSUE TITLE
Importing Excel data using alasql

### ISSUE THREAD

**Issue by Balakumar90** [agershun/alasql#707]
```
 var data;
               var path = 'D:\test.xlsx';
               alasql('select * from FILE(?, {headers:true})', [path], function (res) {
                   data = res;
               });
```
I get the below  error when I run the above code in IE.

0x80070057 - JavaScript runtime error: Invalid argument.

Thanks,
bk

**Comment by mathiasrw** [comment]
Dont know why you get this error. Please retry with `var path = 'D:/test.xlsx';` instead of `var path = 'D:\test.xlsx';` and let me know if it changes together witn information about what version of IE and a copy of the excel file

**Comment by Balakumar90** [comment]
I am still  getting the same error . 
IE Version : 11 

The excel just has 3 rows with below data.( I am unable to upload it )

Emp ID	Emp Name 	Emp Age
1	Sam	                       45
2	Ram	                       43
3	john	                       23

**Comment by mathiasrw** [comment]
What do you get from alasql.version?

**Comment by Balakumar90** [comment]
I didnt get you clearly . I suppose you are referring to the version of Alasql . Its AlaSQL v0.2.7

**Comment by Balakumar90** [comment]
Hi @mathiasrw  , is there any other work around to read an excel file ?

**Comment by mathiasrw** [comment]
Any othet library? Heaps. Try xlsx.js

**Comment by Balakumar90** [comment]
ok .. using Alasql , I am able to download excel from html table . works fine . But reading excel is where I faed issue. Expecting a positive response from you soon on the fix :+1: @mathiasrw

**Comment by mathiasrw** [comment]
Are you using a browser?

**Comment by Balakumar90** [comment]
Yes of course .

**Comment by mathiasrw** [comment]
There is no "of course" in using a browser for javascript. 

Cased soved. You can not link to a local file. You must serve the file + the html from a webserver. 

You have perl, node or php installed on your computer?

**Comment by Balakumar90** [comment]
I am new to Javascript @mathiasrw . So , we can read excel only if its placed in the webserver where the site is deployed ? . Is there anyway to make it work from the client site ? I need to read the excel file from the client side , do you have any suggestions ?

**Comment by mathiasrw** [comment]
Not an easy task. You will need to ask them to "upload" the file into the browser memory and then load the file as a blob instead of a string. (a blob is just the content of the file as a "string" of data)

Have a look at https://github.com/agershun/alasql/wiki/How-to-upload-and-parse-CSV-file-from-server-and-from-desktop

**Comment by Balakumar90** [comment]
@mathiasrw  . I tried the solution provided in the link . 

HTML : <input id="readfile" type="file" data-bind="event: { change: function() {  $parent.loadFileTest($element.files[0]) } }"/>

JS : 
  alasql('SELECT * FROM FILE(?,{headers:true})', [file], function (data) {
                                       // Process data here
                });

I get **0x800a139e - JavaScript runtime error: Wrong usage of FILE() function** Error .
