### ISSUE TITLE
JavaScript runtime error: Wrong usage of FILE() function Error 

### ISSUE THREAD

**Issue by Balakumar90** [agershun/alasql#708]
HTML :  
```html
<input`  id="readfile" type="file" data-bind="event: { change: function() { $parent.loadFileTest($element.files[0]) }  }"/> 
```

JS : 
```js
 alasql('SELECT * FROM FILE(?,{headers:true})', [file], function (data) {
 // Process data here
 });
```
I get  **0x800a139e - JavaScript runtime error: Wrong usage of FILE() function .** Error.

Please help.

**Comment by mathiasrw** [comment]
Please provide full code. I cant see how $parent is connected to the the alasql code

What kind of file are you reading?

**Comment by Balakumar90** [comment]
I have a tab control where I have the <input type . So I need to use $parent . When I click browse I am able to select the file ( XLSX) and then the loadFileTest funciton is triggered. I get the mentioned error in the alasql statement.
 
loadFileTest: function (file) {
                alasql('SELECT * FROM FILE(?,{headers:true})', [file], function (data) {
                    if (data != null) {
                    }
                    // Process data here
                });

            }

Attaching the snapshot for your reference.
![loadfiletest](https://cloud.githubusercontent.com/assets/20397056/16763505/add77a48-4846-11e6-9b95-92643e040801.jpg)

**Comment by mathiasrw** [comment]
Please reopen this issue when you have provided full html + js code to replicate the problem.

**Comment by jsahuxav** [comment]
Please try this:
Javascript code: 
function loadFileTest (event) {
alasql('SELECT * FROM FILE(?,{headers:true})', [event], function (data) {
if (data != null) {
}
// Process data here
});
 }

HTML Code:
<input type="file" onchange="loadFileTest(event)" />

note: provide alasql js references..

**Comment by wrengland** [comment]
I was able to get past that error by using [event.originalEvent] instead of event, but I encountered a new error: xlsx.js:11363 Uncaught TypeError: f.charCodeAt is not a function(…)

I am importing an xlsx file via <input> in Chrome.
