### ISSUE TITLE
Question about MIN() aggregator use

### ISSUE THREAD

**Issue by agerard** [agershun/alasql#709]
I've made huge progress with my proj. thanks to your help and library, and am in the home stretch (a slightly earlier version can be seen at http://beta.ciesin.columbia.edu/jbwq/) . But am having a problem with figuring out how to avoid 0 as the value returned from the MIN() aggregator for columns with null values(Nulls seem to be seen as 0,  but 0 isn't a useful minimum). What I think I'm really needing is "LEAST()" - i.e something that drops all nulls/0 values before aggregating. There are probably ways to make a custom function but I am really hoping not to have to do that at this point. My current workaround is to use MIN(IFNULL(' + selectedParam + ',10000)) so any nulls clearly won't be minimums...just wondering if there's a better way.

**Comment by agershun** [comment]
You can write a custom aggregator function like below:

```js
  alasql.aggr.MYMIN = function(v,s,stage){
    if(stage == 1) return v;
    if(stage == 2) {
        if(s == null) return v;
        else return Math.min(s,v);;
    }
    return s; 
  };
```
var res = alasql('SELECT MYMIN(a) FROM ?',[data])

**Comment by mathiasrw** [comment]
Hi @agerard - did this solve your problem?

I have updated the documentation in https://github.com/agershun/alasql/wiki/MIN and https://github.com/agershun/alasql/wiki/Max

**Comment by agerard** [comment]
Since I had a workaround, I have been chasing other bugs in preparation for alpha release and have not had a chance to try yet, but will do so today. I hope to close this before the end of the day. Thanks again for your prompt and helpful reply - alasql rocks!

**Comment by agerard** [comment]
It works perfectly. Will you be adding a LEAST aggregator to the library? I suppose I should be (or should have _been_) checking to see that my version is up to date....

**Comment by mathiasrw** [comment]
> Will you be adding a LEAST aggregator to the library?

This will be added - but I can say when.

**Comment by agerard** [comment]
Should this be a new issue? I've just realized that AVG and MEDIAN (perhaps STDEV as well?) are also interpreting nulls as zeros, which is not correct. I think I could probably work out custom aggregator fns for the first 2, but am pretty sure STDEV is beyond me. The nulls are in the data - not converted to 0's - so shouldn't the built-in aggregators ignore those?

**Comment by mathiasrw** [comment]
You are right!

Lets create an issue with each of Them. 

Will do when I get to my computer

**Comment by agerard** [comment]
Thanks!

**Comment by agerard** [comment]
The odd thing is, as I look more carefully at my code, I AM already at least _trying_ to eliminate nulls beforehand in my query, but perhaps it's not actually doing so?

`alasql('SELECT count(' + selectedChem + ') FROM ? WHERE ' + chemString
								+ ' ORDER BY _date', [ resultSet ]);`

where selectedChem might be 'w_temp' and chemString would then be 'w_temp is not null'

Trying this against original postGres table gives a different count. So, it appears IS NOT NULL is also not working?

**Comment by mathiasrw** [comment]
Hmm. What if you do a `' + chemString + ' != null` ?

**Comment by agerard** [comment]
Yes, changing chemString to  'w_temp != null' works. But still good to have those aggregators ignoring nulls... and/or have documentation suggesting the correct way to eliminate nulls from query, if 'IS NOT NULL' doesn't work.

Thanks much.

**Comment by mathiasrw** [comment]
I agree

**Comment by mathiasrw** [comment]
Its on the long list and will be reopend when someone look at it
