### ISSUE TITLE
AVG results missing when GROUP BY

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#71]
**AVG is not working as expected**

When taking AVG of data grouped by xyz it will correctly return one row per xyz but only first row contains the AVG data of the group. All other rows are empty.

```SELECT person, avg(sold) FROM ? WHERE 1 GROUP BY person```

could for example give

```[{"person":1,"AVG(sold)":12.5},{"person":2},{"person":3}] ```

Jsfiddle: http://jsfiddle.net/3mctugc9/

----

**SUM is working as expected**

AVG is expected to behave the same way as SUM (but with a different output ◕‿◕ ) so just for a reference: When taking SUM of data grouped by xyz it will correctly get a response with one row per xyz contaning the sum for the group

```SELECT person, sum(sold) FROM ? WHERE 1 GROUP BY person```

could for example give 

```[{"person":1,"SUM(sold)":25},{"person":2,"SUM(sold)":10},{"person":3,"SUM(sold)":40}] ```

**Comment by agershun** [comment]
Got it. This is bug, I will find the reason tomorrow. Thank you for the issue!

**Comment by agershun** [comment]
It does not work with groups if number of elements in the group is equal to 1. I will fix it.

**Comment by mathiasrw** [comment]
Sounds good. 

I am looking into how we can structure a testsuite for alasql around the sqllogictest - see example here: https://raw.githubusercontent.com/grahn/sqllogictest/master/test/select1.test

Some of the tests looks like out of scope for alasql, but it could still be a good indication of how mutch alasql covers of "traditional" SQL

**Comment by agershun** [comment]
I fixed AVG problem, now it should work. 

Thank you for the test. Currently, Alasql does not support construction like ```ORDER BY number```, but I can add it to the program to pass the test:

```sql
    SELECT a,b FROM one ORDER BY 2,1
```

**Comment by mathiasrw** [comment]
Hmmmm - the question is - is it important for alasql? 

if we focus on main situations - and describe the cases not supported - then not everything needs to be  implemented. 

Its a balance. Every feature has a price.

**Comment by agershun** [comment]
:) Looks like Brainf*ck language. 

Anyway, the test is good to check all functionality. At least, the parser.

**Comment by mathiasrw** [comment]
A large part of the SQL tests from https://raw.githubusercontent.com/grahn/sqllogictest/master/test/select1.test 
fails. Thats ok as its identifying new areas of improvements.

Normally I would always keep one test script that ran everything, but have a feeling it would be better to seperate them so you can run the sqllogictest seperate.

What do you think?
