### ISSUE TITLE
Please , I need your help with a corrupted excel file

### ISSUE THREAD

**Issue by muhanadbadee** [agershun/alasql#711]
We found a problem with some content in '....xlsx'. Do you want us to try to recover as much as we can?
If you trust the source of this workbook, click Yes.

I have important info in this file.

I think that the problem in sheet number 10

Could you help me please ? 

 
![1111111111111](https://cloud.githubusercontent.com/assets/20536800/16948481/91d29220-4dbd-11e6-9898-b974ac444939.png)

**Comment by mathiasrw** [comment]
Please try to click yes. 

Please reopen the issue when you can provide a full code example replicating your problem.

**Comment by muhanadbadee** [comment]
Dear @mathiasrw 

Please help me with this problem.

When I click Yes, the file is open but the repair operation deletes the most important sheet ( number 10 ).


![1111111111](https://cloud.githubusercontent.com/assets/20536800/16981911/b2a878c6-4e75-11e6-821f-08b2aeef0ee9.png)



The code that I'v got it is :

Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.
Removed Part: Print options.
Removed Part: Print options.
Removed Part: Print options.
Removed Part: Print options.
Replaced Part: /xl/worksheets/sheet10.xml part with XML error.  Whitespace expected. Line 2, column 113788.
Removed Part: Print options.
Removed Part: Print options.
Removed Part: Print options.
Removed Part: Print options.
Removed Part: Print options.
Removed Part: Data store.
Removed Records: Worksheet properties from /xl/workbook.xml part (Workbook)
Repaired Records: Cell information from /xl/worksheets/sheet1.xml part
Repaired Records: Column information from /xl/worksheets/sheet1.xml part
Repaired Records: Cell information from /xl/worksheets/sheet2.xml part
Repaired Records: Column information from /xl/worksheets/sheet2.xml part
Repaired Records: Cell information from /xl/worksheets/sheet3.xml part
Repaired Records: Cell information from /xl/worksheets/sheet4.xml part
Repaired Records: Column information from /xl/worksheets/sheet4.xml part
Repaired Records: Cell information from /xl/worksheets/sheet5.xml part
Repaired Records: Column information from /xl/worksheets/sheet5.xml part
Repaired Records: Cell information from /xl/worksheets/sheet11.xml part
Repaired Records: Column information from /xl/worksheets/sheet11.xml part
Repaired Records: Cell information from /xl/worksheets/sheet12.xml part
Repaired Records: Column information from /xl/worksheets/sheet12.xml part
Repaired Records: Cell information from /xl/worksheets/sheet13.xml part
Repaired Records: Column information from /xl/worksheets/sheet13.xml part
Repaired Records: Cell information from /xl/worksheets/sheet14.xml part
Repaired Records: Cell information from /xl/worksheets/sheet15.xml part
Repaired Records: Column information from /xl/worksheets/sheet15.xml part
Repaired Records: Cell information from /xl/worksheets/sheet16.xml part
Repaired Records: Column information from /xl/worksheets/sheet16.xml part
Repaired Records: Cell information from /xl/worksheets/sheet17.xml part

---------------------------------------------------------------------------------------

and the log is :


<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">

<logFileName>error098960_01.xml</logFileName>

<summary>Errors were detected in file 'C:\Users\simav\Downloads\30 - June - 2016 قوائم - Copy.xlsx'</summary>


-<additionalInfo>

<info>Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.</info>

</additionalInfo>


-<removedParts summary="Following is a list of removed parts:">

<removedPart>Removed Part: Print options.</removedPart>

<removedPart>Removed Part: Print options.</removedPart>

<removedPart>Removed Part: Print options.</removedPart>

<removedPart>Removed Part: Print options.</removedPart>

<removedPart>Replaced Part: /xl/worksheets/sheet10.xml part with XML error. Whitespace expected. Line 2, column 113788.</removedPart>

<removedPart>Removed Part: Print options.</removedPart>

<removedPart>Removed Part: Print options.</removedPart>

<removedPart>Removed Part: Print options.</removedPart>

<removedPart>Removed Part: Print options.</removedPart>

<removedPart>Removed Part: Print options.</removedPart>

<removedPart>Removed Part: Data store.</removedPart>

</removedParts>


-<removedRecords summary="Following is a list of removed records:">

<removedRecord>Removed Records: Worksheet properties from /xl/workbook.xml part (Workbook)</removedRecord>

</removedRecords>


-<repairedRecords summary="Following is a list of repairs:">

<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet1.xml part</repairedRecord>

<repairedRecord>Repaired Records: Column information from /xl/worksheets/sheet1.xml part</repairedRecord>

<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet2.xml part</repairedRecord>

<repairedRecord>Repaired Records: Column information from /xl/worksheets/sheet2.xml part</repairedRecord>

<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet3.xml part</repairedRecord>

<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet4.xml part</repairedRecord>

<repairedRecord>Repaired Records: Column information from /xl/worksheets/sheet4.xml part</repairedRecord>

<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet5.xml part</repairedRecord>

<repairedRecord>Repaired Records: Column information from /xl/worksheets/sheet5.xml part</repairedRecord>

<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet11.xml part</repairedRecord>

<repairedRecord>Repaired Records: Column information from /xl/worksheets/sheet11.xml part</repairedRecord>

<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet12.xml part</repairedRecord>

<repairedRecord>Repaired Records: Column information from /xl/worksheets/sheet12.xml part</repairedRecord>

<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet13.xml part</repairedRecord>

<repairedRecord>Repaired Records: Column information from /xl/worksheets/sheet13.xml part</repairedRecord>

<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet14.xml part</repairedRecord>

<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet15.xml part</repairedRecord>

<repairedRecord>Repaired Records: Column information from /xl/worksheets/sheet15.xml part</repairedRecord>

<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet16.xml part</repairedRecord>

<repairedRecord>Repaired Records: Column information from /xl/worksheets/sheet16.xml part</repairedRecord>

<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet17.xml part</repairedRecord>

</repairedRecords>

</recoveryLog>



Best regards,

**Comment by mathiasrw** [comment]
How did you generate the file?

**Comment by muhanadbadee** [comment]
Thanks for your quick reply.

This file is an old file and it didn't have a problem till yesterday morning.

**Comment by mathiasrw** [comment]
Have a feeling I cant help. Have a look at http://www.wikihow.com/Recover-a-Corrupt-Excel-File

Did you use AlaSQL to generate it at all?
