### ISSUE TITLE
SHOW COLUMNS table not working

### ISSUE THREAD

**Issue by tmrk** [agershun/alasql#714]
`SHOW COLUMNS` returns nothing, here's the example: https://jsfiddle.net/12mdj8q6/1/

**Comment by tmrk** [comment]
UPDATE: sorry, the example above was actually working, HOWEVER, if I insert values from a javascript object into an alasql table, then ` #SHOW COLUMNS` fails, see here: https://jsfiddle.net/cwz5gves/

**Comment by mathiasrw** [comment]
`SHOW COLUMNS` will give you information about columns defined for the table. 

In your example you are not defining any columns - only inserting data. 

Please replace

    CREATE TABLE Cities;

with

    CREATE TABLE Cities (City string, Population int);

to make `SHOW COLUMNS`  work

WOrking example: http://jsfiddle.net/v1e4ep5m/

**Comment by tmrk** [comment]
My question was rather pointing out the fact that `SHOW COLUMNS` doesn't seem to work if I use the `SELECT * INTO table` method - without explicitly defining the columns.

When you insert data into a table, shouldn't it automatically create those columns?

**Comment by mathiasrw** [comment]
Good point. 

I missed that...

> When you insert data into a table, shouldn't it automatically create those columns?

Trying to guess that data the user is putting in for each insert would would be time consuming. Asking "Show data" to check every row for every peace of data would be time consuming. 

I have a feeling the best approach would be to make a function that takes a `SELECT * FROM ...` and itterates over each row to fetch all column names.

**Comment by tmrk** [comment]
Sorry for dragging this out, but I'm still trying to figure something out in my code, and another idea came to me.

I understand what you wrote about the time issue, it makes sense.

However, when I explicitly SELECT columns FROM another table INTO a new table, couldn't those columns be created automatically in the new table? I mean there's no need to loop through anything, the columns to be created are already there in the `SELECT`. 

See my example here: http://jsfiddle.net/dqpkvgod/1/ (forked from yours)

**Comment by mathiasrw** [comment]
I agree. Lets put it on the list of things to be implemented.
