### ISSUE TITLE
Q: Create table leads to create index?

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#72]
Question regarding the console 

http://alasql.org/console/

When I enter 

```CREATE TABLE t9(  e9 INTEGER,  x9 VARCHAR(30))``` 

the console writes 

```CREATE INDEX undefined ON t9(e9 INTEGER,x9 VARCHAR(30))```

does alasql as default create an index behind the lines? I have not been able to find any information about it in the slides.

**Comment by agershun** [comment]
Sorry, this is a bug in toString() function.

**Comment by agershun** [comment]
Found and fixed. Thank you!
