### ISSUE TITLE
Column name with space, how to join?

### ISSUE THREAD

**Issue by kaktus40** [agershun/alasql#721]
Hello I have two json with a key id named "Numéro de support". How can I make a join on these columns? How can I select this peculiar column in select and where clauses?
```
let support= [
        {  "Numéro du support": 9720,   "Longitude": 2.82778,   "Latitude": 43.47806   },
        {  "Numéro du support": 9722,  "Longitude": 2.77917,  "Latitude": 43.57444  },
        {  "Numéro du support": 9724,  "Longitude": 2.70306,  "Latitude": 43.60056   },
        {  "Numéro du support": 9734,  "Longitude": 3.15222,   "Latitude": 43.61139 },
        {  "Numéro du support": 9736,  "Longitude": 3.54694,  "Latitude": 43.65972,  }
    ];
let antenne=  [
        { "Numéro de support": 9720, "Unité": "MHz"  },
        {  "Numéro de support": 9720,  "Unité": "MHz"  },
        {  "Numéro de support": 9720,   "Unité": "GHz" }
    ];

let result=alasql('select supp[Numéro du support], supp[Longitude], supp.`Latitude`, ant[Unité] from ? supp join ? ant on supp.`Numéro du support`=ant.`Numéro du support` ',[support,antenne]);
```
If I try ``alasql('select supp.`Numéro du support` from ? supp',[support])``, it returns empty columns.

**Comment by mathiasrw** [comment]
Interesting. 

Does What about `alasql('select `Numéro du support` from ?',[support])` give you anything?

What about `alasql('select `supp.Numéro du support` from ? supp',[support])` ?

**Comment by kaktus40** [comment]
Ok I identified some problems. First me: I didn't see that it is "Numéro **du** support" and "Numéro **de** support".  :-(
For alasql it seems that some tests in fiddle with latest version (0.3) are broken see [this](http://jsfiddle.net/38hj2uwy/10/), the sample 1 from  [here](https://github.com/agershun/alasql/wiki/Examples).
With promise version, it seems ok:
```
var support= [
        {  "Numéro du support": 9720,   "Longitude": 2.82778,   "Latitude": 43.47806   },
        {  "Numéro du support": 9722,  "Longitude": 2.77917,  "Latitude": 43.57444  },
        {  "Numéro du support": 9724,  "Longitude": 2.70306,  "Latitude": 43.60056   },
        {  "Numéro du support": 9734,  "Longitude": 3.15222,   "Latitude": 43.61139 },
        {  "Numéro du support": 9736,  "Longitude": 3.54694,  "Latitude": 43.65972,  }
    ];
var antenne=  [
        { "Numéro du support": 9720, "Unité": "MHz"  },
        {  "Numéro du support": 9720,  "Unité": "MHz"  },
        {  "Numéro du support": 9720,   "Unité": "GHz" }
    ];

alasql.promise('select supp.`Numéro du support`, supp.`Longitude`, supp.`Latitude`, ant.`Unité` from ? as supp join ? as ant using `Numéro du support`',[support,antenne]).then(function(res){
 document.getElementById('result').textContent = JSON.stringify(res,  null, '\t');
});

**Comment by kaktus40** [comment]
another example with promise and latest version of alasql [here](http://jsfiddle.net/hguw3LLk/27/)

**Comment by mathiasrw** [comment]
I don't quite get it with you last link here. It works without promise 

Www.jsfiddle.net/3nto4Ldj

**Comment by kaktus40** [comment]
Yes indeed. My bad, I think I incorporate only the worker version of alasql in the fiddle example when I tried it.
So it seems ol
