### ISSUE TITLE
PRIMARY KEY AUTOINCREMENT not working

### ISSUE THREAD

**Issue by fibigerg** [agershun/alasql#722]
Hi, in the code below PRIMARY KEY AUTOINCREMENT does not work for me. There are only undefined values in the id column. Did I miss something?

Thanks for help!

```
alasql('CREATE localStorage DATABASE IF NOT EXISTS Investments');
alasql('ATTACH localStorage DATABASE Investments AS Investments');
alasql('SET AUTOCOMMIT ON');
alasql('CREATE TABLE IF NOT EXISTS Investments.Products (id INTEGER PRIMARY KEY AUTOINCREMENT, name STRING, isin STRING)');
alasql('SELECT * INTO Investments.Products FROM ?', [[product]]);

alasql('SELECT * INTO Investments.Products FROM ?', [[{ isin:'LU0147784465', name:'AXA High Yield Bond' }]]);
alasql('SELECT * INTO Investments.Products FROM ?', [[{ isin:'IE0004851808', name:'Baring HY Bond' }]]);

vm.products = alasql('SELECT * FROM Investments.Products');
console.log(vm.products);
```

![image](https://cloud.githubusercontent.com/assets/5537140/17314175/a0238550-5862-11e6-89e8-2b05883572e0.png)

**Comment by mathiasrw** [comment]
Thanks for the issue. 

You did not miss anything - Its a bug - also mentioned in #462 

I will reference this issue in the #462 issue and close this one so we dont get duplicated issues.
