### ISSUE TITLE
would the following be possible? alasql.fn.

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [agershun/alasql#724]
Hello ALASQL team,

Would the following be possible? Basically I am asking alasql to wait for async data to return
```
alasql.fn.getDocuments = function(name) {
	var array = name.split(',');
	Promise.all(array.map(
	function(v){
		return $.getJSON("/myoffice/_vti_bin/ListData.svc/Documents?$filter=Id eq "+v+"&$select=Name,Title,Id",
	   {},
	   function showData(data, status) {
	   })
	}));
};
var companyProcessStepsSource = alasql('SELECT CASE ProcessInputDocuments WHEN null THEN "" ELSE getDocuments(ProcessInputDocuments) END AS ProcessInputDocuments FROM ?', [companyProcessStepsColl]);

```
Kind regards,
Mario

**Comment by mathiasrw** [comment]
Nope. wont work. 

You are not returning any value. And even if you did an async call like this can not return values to the query as `.fn` functions are called sync. 

its hard to find out what you are doing with a promise.all wihtout a ".then" (and avoid variablenames like `array`)

**Comment by MarioVanDenEijnde** [comment]
OK. Thanks.
