### ISSUE TITLE
IE9 issue

### ISSUE THREAD

**Issue by neirdahcier** [agershun/alasql#73]
Hi, i have an angular app that use your library. It's great it works with ie10, firefox and chrome but i'm having compatibility problem with IE9
I tested the emulate ie9 from ie11 and it say "blob" is undefined

you can test it yourself here : http://jsfiddle.net/agershun/00nfeq12/

Do you know how i can make it work with ie9 ?

**Comment by agershun** [comment]
Thank you for the issue. I will check it tomorrow with IE9.

**Comment by neirdahcier** [comment]
I tried to add https://github.com/eligrey/Blob.js/blob/master/Blob.js, and got arraybuffer undefined
then added this polyfill https://github.com/inexorabletash/polyfill/blob/master/typedarray.js and now i have object expected... I don't know what to do

**Comment by mathiasrw** [comment]
I had issues before where the browser was IE9 but was running compatibility mode - so was infact ie7. 

Check out http://stackoverflow.com/questions/3726357/why-does-ie9-switch-to-compatibility-mode-on-my-website

**Comment by neirdahcier** [comment]
I tried to add the extra meta for IE9 to use the last engine, but it does not change anything, There is a javascript problem with IE9 and the code

**Comment by smaugthehobbit** [comment]
please provide a workaround

**Comment by agershun** [comment]
The problem is here: [FileSaver](https://github.com/eligrey/FileSaver.js/) does not supports IE9, because it does not supports Blobs. I will add a check to exclude FileSaver from he scope if this is IE9. But at the same time AlaSQL will not be able to saver files from browser. But you can save this file yourself with construction like:
```js
    var data = alasql('SELECT * INTO CSV({headers:true}) FROM ?',[data]);
    // save file from data variable
```
Here if you do not provide filename. AlaSQL will provide selected and formatted data as result of the function.

I do not have IE9 in my computer. How can I install it or what flags should I use to test it?

**Comment by mathiasrw** [comment]
To force a webpage you are viewing in Internet Explorer 10 into a particular document compatibility mode, first open F12 Tools by pressing the F12 key. Then, on the Browser Mode menu, click Internet Explorer 10, and on the Document Mode menu, click Standards.

**Comment by smaugthehobbit** [comment]
Excuse me agershun, what do you mean by "you can save the fine yourself".
will i be able to do something like open.window(data) to send the file to the browser?
if not, explain how I can do that with IE9.
Thanks alot

**Comment by agershun** [comment]
@smaugthehobbit Unfortunately, I had not time to research this issue: how to save files correctly in IE9 yet. Probably, we can solve this problem in two steps:
a) first - to elimitate the bug from the library
b) find a way, how to save data in IE9. Probably, we can do it with ActiveX objects, but we need to write a custom function.

**Comment by agershun** [comment]
I look at the FileSaver site, they still have no solution:
https://github.com/eligrey/FileSaver.js/issues/67

Some recipes, how to save data with IE9 are here:
http://strongtypetech.blogspot.ru/2013/06/saving-client-side-files-using-internet.html

I will try to test AlaSQL with Downloadify plugin tomorrow

**Comment by agershun** [comment]
As usual: good news and bad news..

**Good news:** AlaSQL can save files in CSV, TSV, and pseudo-XLS format in IE9 as usual:
```js
    alasql('SELECT * INTO XLS("mydata.xls",{headers:true}) FROM ?',[data]);
```
**Bad news**: It still can not save data in XLSX binary format. I could not find a simple way to save 
binary data with ActiveX() ot Flash-based solutions. Sorry about that. Please let me know, if there are methods to do it, and we will include them into the library.

** Good over bad news**: AlaSQL XLS() export functions can add colors to Excel file, where XLSX() still does not.

We will work on it.

**Comment by harshamaddineni** [comment]
hi agershun. is filesaver.js working now for ie9? i am still facing the issue. please let me know if there is any alternative

**Comment by mathiasrw** [comment]
no known alternative

**Comment by rafael-adonis** [comment]
Hi agershun, I have a similar problem, when I export XLS file with chrome, the download is initialized automatically, but when I use IE9, he open a new tab and dialog to save file. Exist any way to export file without open a new tab and dialog to save in IE9?

**Comment by mathiasrw** [comment]
I have not met one. if you see one please let me know so we can implement it !

**Comment by roger2hk** [comment]
@harshamaddineni According to https://github.com/eligrey/Blob.js/pull/48, it is not possible to download generated content (except text, html) in IE < 10 due to browser limitation.
