### ISSUE TITLE
Error on ie11 for export to CSV

### ISSUE THREAD

**Issue by junedansari** [agershun/alasql#730]
Hi,
I am using alasql library for CSV export, it works perfectly fine for FF and chrome but giving me some unexpected results on ie11.

Giving me some extra information while exported into CSV as
function(t){for(var e=Object(this),n=parseInt(e.length,10),i=arguments[1],r=parseInt(i,10)||0,s=0>r?
Math.max(n+r,0):Math.min(r,n),o=arguments[2],a=void 0===o?n:parseInt(o,10)||0,u=0>a?Math.max(n+a,0):Math.min(a,n);u>s;s++)e[s]=t;return e}

**Comment by mathiasrw** [comment]
Can you provide code to replicate the problem?

**Comment by junedansari** [comment]
var csvRows = [
	["63 features analyzed | Summarize_Data", "  ", "  ", "  ", "  "],
	["Column", "  ", "Rectangle1(21)", "Circle1(42)", "All"],
	["TInteger", "Min", 2344, -214748364, -214748364],
	["TInteger", "Max", 2147483647, 978666, 2147483647],
	["TInteger", "Avg", 308963954.28571427, -20299810.333333332, 89454777.87301587],
	["TInteger", "Sum", 6488243040, -852592034, 5635651006],
	["TSmallInteger", "Min", -9764, -43, -9764],
	["TSmallInteger", "Max", 3453, 10000, 10000],
	["TSmallInteger", "Avg", -1062.904761904762, 1960, 952.3650793650794],
	["TSmallInteger", "Sum", -22321, 82320, 59999],
	["TFloat", "Min", 75.19, 24.56, 24.56],
	["TFloat", "Max", 23745.39, 656576.26, 656576.26],
	["TFloat", "Avg", 5891.389047619047, 61041.131904761896, 42657.88428571428],
	["TFloat", "Sum", 123719.16999999998, 2563727.5399999996, 2687446.7099999995],
	["TDecimal", "Min", 25.767433, 23.7899076000001, 23.7899076000001],
	["TDecimal", "Max", 968.3434545999999, 999.999999999999, 999.999999999999],
	["TDecimal", "Avg", 296.92968195580954, 277.4107434656267, 283.9170562956876],
	["TDecimal", "Sum", 6235.523321072, 11651.251225556322, 17886.77454662832]
]

var csvName = '63 features analyzed Summarize_Data.csv';
 alasql.promise('SELECT * INTO CSV(\"'+csvName+'\",{headers:false,separator:","}) FROM ?',[csvRows])
                    .then(function(){
                        console.log('CSV exported successfully');
                    }).catch(function(err){
                        console.log('Error in exporting CSV:', err);
                    });

**Comment by junedansari** [comment]
Giving this extra values on IE11 as given below
function(t){for(var e=Object(this),n=parseInt(e.length,10),i=arguments[1],r=parseInt(i,10)||0,s=0>r?Math.max(n+r,0):Math.min(r,n),o=arguments[2],a=void 0===o?n:parseInt(o,10)||0,u=0>a?Math.max(n+a,0):Math.min(a,n);u>s;s++)e[s]=t;return e}
function(t){for(var e=Object(this),n=parseInt(e.length,10),i=arguments[1],r=parseInt(i,10)||0,s=0>r?Math.max(n+r,0):Math.min(r,n),o=arguments[2],a=void 0===o?n:parseInt(o,10)||0,u=0>a?Math.max(n+a,0):Math.min(a,n);u>s;s++)e[s]=t;return e}

**Comment by mathiasrw** [comment]
Ran you code in both Microsoft Edge 25.10586 and Internet Explorer 11.420 and both gave me a file with the following content. 

```
"63 features analyzed | Summarize_Data",  ,  ,  ,  
"Column",  ,"Rectangle1(21)","Circle1(42)","All"
"TInteger","Min",2344,-214748364,-214748364
"TInteger","Max",2147483647,978666,2147483647
"TInteger","Avg",308963954.28571426,-20299810.333333332,89454777.87301586
"TInteger","Sum",6488243040,-852592034,5635651006
"TSmallInteger","Min",-9764,-43,-9764
"TSmallInteger","Max",3453,10000,10000
"TSmallInteger","Avg",-1062.904761904762,1960,952.3650793650794
"TSmallInteger","Sum",-22321,82320,59999
"TFloat","Min",75.19,24.56,24.56
"TFloat","Max",23745.39,656576.26,656576.26
"TFloat","Avg",5891.389047619047,61041.131904761896,42657.88428571428
"TFloat","Sum",123719.16999999998,2563727.5399999996,2687446.7099999995
"TDecimal","Min",25.767433,23.7899076000001,23.7899076000001
"TDecimal","Max",968.3434545999999,999.999999999999,999.999999999999
"TDecimal","Avg",296.92968195580954,277.4107434656267,283.9170562956876
"TDecimal","Sum",6235.523321072,11651.251225556321,17886.77454662832
 
```

What version of alasql are you using? (run alasql.version) 

What version of IE11 are you using exactly?

**Comment by junedansari** [comment]
Thank you so much for ur reply.
I am using 0.2.6 of alasql and 11.0.9600.18376 of IE

**Comment by mathiasrw** [comment]
Please upgrade to version 0.3.1 and see if you can update your IE 11 to the last release.

**Comment by junedansari** [comment]
thanks.
if i have  rows like [{0:"first"},{1:"second"}] then its giving me error for header but if have rows like [{'name':'first'},{'name':'second'}] then itz work fine on IE.

Closing the issue

**Comment by mathiasrw** [comment]
Thank you for clarifying :)
