### ISSUE TITLE
`s` is not defined in yy.Select.prototype.compileWhere

### ISSUE THREAD

**Issue by tkhyn** [agershun/alasql#736]
Hi and thanks heaps for making alasql available.

It looks like there is a missing variable declaration [here](https://github.com/agershun/alasql/blob/2ee7f79c28a89a6342badee875376232f9d2aa5d/src/422where.js#L6).

It has never been a problem for me until I bundled my little project and launched it in the browser. It worked fine in development (with standalone library files). The error is there whether the bundle is minified or not.

Adding the missing `var` statement at the beginning of the line solves the issue and `alasql` loads and works fine once it's there.

I'll be happy to submit a PR if you want but I'm not sure it's worth it as it's a 2s change.

Thanks again.

**Comment by mathiasrw** [comment]
Awesome - just implemented it - but we would always be happy to get a PR no matter how small :)

**Comment by tkhyn** [comment]
> but we would always be happy to get a PR no matter how small :)

Yes I imagine but when the ratio time to make a change / time to fork, clone, branch, change, push, PR, etc ... is very close to 0, it's much more time- and resource-efficient to let the repo owner who already has everything at hand do the changes himself.

Thanks for the very quick reply and fix.
