### ISSUE TITLE
INSERT WHERE NOT EXISTS

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#74]
Does alasql support this?
```sql
    INSERT INTO Table (col1, col2) VALUES (val1, val2) WHERE NOT EXISTS (SELECT 1 FROM Table)
```
I keep getting a parse error at my WHERE NOT EXISTS - "Expecting 'EOF', 'SEMICOLON', 'GO', 'COMMA', 'END', 'ELSE', got 'WHERE'"

**Comment by mathiasrw** [comment]
Any news on this?

**Comment by agershun** [comment]
This query looks something strange - it is not SQL complient. I cannot find the source of it. Closed.
