### ISSUE TITLE
Uncaught TypeError: Cannot set property 'textContent' of null

### ISSUE THREAD

**Issue by AsrRajiv** [agershun/alasql#749]
Hi,

I am new to this library. I am working in windows. I have copied the below code and run in my index.php file but it doesn't work. showing **"Uncaught TypeError: Cannot set property 'textContent' of null"**. I need to install or what is the issue ? any help immd. please

code 
```
<script src="http://cdn.jsdelivr.net/alasql/0.3/alasql.min.js"></script>
`var data = [{ dep: 'A', qt: 10, price: 5},
 { dep: 'A', qt: 5,  price: 2.30 },
 { dep: 'B', qt: 3,  price: 2.20 },
 { dep: 'C', qt: 1,  price: 4 },
 { dep: 'C', qt: 4,  price: 10 }];

var res = alasql('SELECT dep, SUM(qt) AS qt, SUM(qt*price) AS amt, AGGR(amt/qt) AS price FROM ? GROUP BY dep',[data]);
document.getElementById("res").textContent = `JSON.stringify(res);``
</script>
```

**Comment by mathiasrw** [comment]
is this the correct code? Something with your `JSON.stringify(res);` that is wrapped funny?

**Comment by AsrRajiv** [comment]
Hi,

I have copied the code given in github only....

**Comment by mathiasrw** [comment]
Ok - please avoid the ``` ` ``` around the `JSON.strin...` function. 

Where did you copy from?

**Comment by AsrRajiv** [comment]
Hi,

Sorry copied from jsfiddle .
url :+1: 
--------------
http://jsfiddle.net/c1hbytf1/

**Comment by AsrRajiv** [comment]
I have also tried this .. not working. it's a github code 

alasql("CREATE TABLE cities (city varchar(255), population int(11))");


alasql("INSERT INTO cities VALUES ('Rome',28), ('Paris',22), ('Berlin',35), ('Madrid',30)");


var res = alasql("SELECT * FROM cities WHERE population < 35 ORDER BY population DESC");


showResult(res)






function showResult(x){
    document.getElementById('result').textContent = JSON.stringify(x,  null, '\t');
}

**Comment by AsrRajiv** [comment]
Hi,

What happened ?

**Comment by mathiasrw** [comment]
Try this one

```
<script src="http://cdn.jsdelivr.net/alasql/0.3/alasql.min.js"></script>
`var data = [{ dep: 'A', qt: 10, price: 5},
 { dep: 'A', qt: 5,  price: 2.30 },
 { dep: 'B', qt: 3,  price: 2.20 },
 { dep: 'C', qt: 1,  price: 4 },
 { dep: 'C', qt: 4,  price: 10 }];

var res = alasql('SELECT dep, SUM(qt) AS qt, SUM(qt*price) AS amt, AGGR(amt/qt) AS price FROM ? GROUP BY dep',[data]);
console.log(JSON.stringify(res));
```

**Comment by mathiasrw** [comment]
Please reopen if you have more questisons.
