### ISSUE TITLE
UNION error when using same columns and add CORRESPONDING option

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#75]
When I UNION a table I expect that what I select from the second table to be unioned with the first table based on the order 

```
CREATE TABLE t1(a int,b int); 
INSERT INTO t1 VALUES(1,2); 
SELECT a, b FROM t1 UNION  SELECT b, a FROM t1;
```

in http://alasql.org/console/ I would expect 

```
#	a	b	
1	1	2
2	2	1
```

but I get 

```
#	b	a
1	2	1
```

The issue can also be seen for statements like

```
SELECT 1, 2 UNION SELECT 3, 4;
```

**Comment by mathiasrw** [comment]
This statement is more to the point:



gives me 

```

**Comment by agershun** [comment]
I think that the problem in my wrong understanding of ```UNION``` operator.
I will redesign it in the way, like from your example:
```sql
    CREATE TABLE t1(a int,b int); 
    INSERT INTO t1 VALUES(1,2);  
    SELECT a, b FROM t1 UNION  SELECT b, a FROM t1;
    -- gives
    #   a   b   
    1   1   2
    2   2   1
```

**Comment by mathiasrw** [comment]
:+1:

**Comment by mathiasrw** [comment]
Is this on the road map?

**Comment by agershun** [comment]
... yes. I will do it ASAP.  but not for 100% for current version, because Alasql does not keep order of columns in the record. So, it is impossible to predict results of this union operation:
```sql
    SELECT * FROM one UNION SELECT * FROM two
```

For Alasql2 it should be ok (I want to keep internal data in the format of array instead of object).

**Comment by agershun** [comment]
It is hard to fix this...

**Comment by mathiasrw** [comment]
is it because we do not track the original order?

**Comment by agershun** [comment]
I need to think how to convert merging arrays. Probably as a first step AlaSQL need to convert them to array of arrays, then merge, and then convert to array of objects back

**Comment by pietersv** [comment]
Whoa -- AlaSQL pays attention to the column names and matches columns when stacking tables vertically without worrying about order?  For me that is an awesome capability, which stats packages like SAS and SPSS offer, so would love to keep it personally.  But I believe that @mathiasrw is correct that SQL typically stacks only by column order and ignores the name, which is my only big complaint with SQL. 

http://stackoverflow.com/questions/5201653/union-tables-by-field-name-i-e-columns-order-cannot-be-guaranteed

**Comment by agershun** [comment]
Hmm... I like this CORRESPONDING notation (thank you, Peter!). 
<blockquote>
    "These forty years now, 
           I've been speaking in prose without knowing it! "
        (The [Bourgeois Gentleman](http://moliere-in-english.com/bourgeois.html), Moliere) 
</blockquote>

At least we can keep for compatibility two versions of UNION/UNION ALL/INTERSECT/EXCEPT operators: one with keeping order and one - based on column names. Like:
```sql
    SELECT a,b FROM one UNION ALL SELECT b,a FROM one
    -- gives
    -- a b
    -- 1 2
    -- 2 1
```
and 
```sql
    SELECT a,b FROM one UNION ALL CORRESPONDING  SELECT b,a FROM one
    -- gives
    -- a b
    -- 1 2
    -- 1 2
```

**Comment by mathiasrw** [comment]
Love the CORRESPONDING notation... :+1:

**Comment by agershun** [comment]
I FIXED THIS!!! See test254.js. Now we can release 0.1!!!

**Comment by mathiasrw** [comment]
Yayyyyy :)

so so awesome :)
