### ISSUE TITLE
[AngularJS]Export excel with file exist

### ISSUE THREAD

**Issue by aiduc0502** [agershun/alasql#754]
Hi, i'm a student in VietNam.
I have a issue.I defined one file report include title, header,width for every cell.... i call this my template (picture 1).I have used the alasql lib for export the excel for my website.I received a file (picture 2). Now, I want export data to my template but i don't know how to do that.So,Is there any way to make it export to my template with data? 
I can't post picture in this post.Please go to this link to see my picture:
http://stackoverflow.com/questions/39568016/angularjsexport-excel-with-file-exist
Thanks all!

**Comment by mathiasrw** [comment]
Sorry for long response time!

bonus info: just drag an image into the text area to insert image

AlaSQL is good to handle data. If you want good controle with the layout have a look at https://github.com/guyonroche/exceljs

**Comment by aiduc0502** [comment]
Thanks sir. I try do it to resolve my issue.
