### ISSUE TITLE
Fair jsperf test for sql.js

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#76]
Hey - please have a look at 

http://jsperf.com/sql-js-vs-alasql-js/8#run

and let me know if think its a fair test.

Interesting to se how firefox and chrome performe different...

**Comment by agershun** [comment]
To make it more failr, you can also turn off caching of precompiled statements, like in this example:

[jsPerf tests without caching](http://jsperf.com/alasql-js-vs-websql/7)

Now Firefox has significant optimization for asm.js, and I think to rewrite Alasql with ASM.js specifications to make it faster in FF and new IE.
