### ISSUE TITLE
Strange decimals when doing SUM GROUP BY.... eg: 129445.98000000001

### ISSUE THREAD

**Issue by tiagowippel** [agershun/alasql#760]
Hi, i got this statement...

```
alasql(
    `select ESTACLI,SUM(VLRTOTAL) AS SOMA
    from csv("c:/windows/temp/audit05.csv")
    group by ESTACLI
    order by SOMA`,[],(data)=>{
console.log(data);
});
```

and i have getting this output....

```
[ { ESTACLI: 'AC', SOMA: 35843.56 },
  { ESTACLI: 'AP', SOMA: 48573.69 },
  { ESTACLI: 'RR', SOMA: 129445.98000000001 },
  { ESTACLI: 'TO', SOMA: 360343.76000000007 },
  { ESTACLI: 'MA', SOMA: 733043.5499999999 },
  { ESTACLI: 'PA', SOMA: 1067937.7699999996 },
  { ESTACLI: 'RO', SOMA: 1139423.24 },
  { ESTACLI: 'AM', SOMA: 1165764.7 }, ...
```

I already ensure that the VLRTOTAL field of the csv file only have 2 decimals...

csv file...
```
NRNOTA,DATAEMI,VLRTOTAL,CODIVENNOT,CODINAT,ROMA1,VLR1PARC,CODCLI,NOMECLI,CODIVENCLI,ESTACLI
1,"11/03/2010",5115.84,114,611 ,554292,5115.84,5680,"COFIP COMERCIAL LTDA",61,"SP"
2,"11/03/2010",1827.80,6,611 ,554264,1827.8,5684,"MAGAZINE CHOHFI LTDA EPP-FL03",6,"SP"
3,"11/03/2010",1827.80,6,611 ,554265,1827.8,5685,"MAGAZINE CHOHFI LTDA EPP-FL 04",6,"SP"
4,"11/03/2010",1827.80,6,611 ,554266,1827.8,5683,"MAGAZINE CHOHFI LTDA- F05",6,"SP"
5,"11/03/2010",1827.80,6,611 ,554267,1821.6,6588,"MAGAZINE CHOHFI LTDA EPP.",6,"SP"
...
```

**Comment by mathiasrw** [comment]
If you do a simple `1.2-1.0` in javascript the result will be `0.19999999999999996`

Its because javascript uses floating points for numbers. 

As AlaSQL is based on javascript you experience the same with your numbers. 

For more information: http://floating-point-gui.de/

**Comment by tiagowippel** [comment]
ok, thank you, sorry for disturbing you...

**Comment by mathiasrw** [comment]
Its all good - thank you for taking the time to contact us to let us know something was wrong...

**Comment by Benoit75** [comment]
Hello, 
I kown it's an old post but for those who read this question i came up with a quick solution  (i work with JSON so it's not easy to use money type or [https://github.com/MikeMcl/bignumber.js/](BigNumber.js)  : 
sum(col*100)/100

For example : 
alasql(
    `select ESTACLI,SUM(VLRTOTAL*100)/100 AS SOMA
    from csv("c:/windows/temp/audit05.csv")
    group by ESTACLI
    order by SOMA`,[],(data)=>{
console.log(data);
});

Thank you for this amazing library !
Benoit.

**Comment by mathiasrw** [comment]
Hi @Benoit75 thank you for contributing to the subject :)

**Comment by mydewaz** [comment]
> Hello, I kown it's an old post but for those who read this question i came up with a quick solution (i work with JSON so it's not easy to use money type or [BigNumber.js](https://github.com/MikeMcl/bignumber.js) : sum(col*100)/100
> 
> For example : alasql( `select ESTACLI,SUM(VLRTOTAL*100)/100 AS SOMA from csv("c:/windows/temp/audit05.csv") group by ESTACLI order by SOMA`,[],(data)=>{ console.log(data); });
> 
> Thank you for this amazing library ! Benoit.

it's working, thanks a lot
