### ISSUE TITLE
From parent/child to nested json

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [agershun/alasql#766]
Hello ALASQL team,

Is there a way to transfer a parent/child object into a nested object?

Kind regards,
Mario

**Comment by mathiasrw** [comment]
Do you have an example of a parent/child object and your expected output?

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

I found the following code snippets: https://gist.github.com/smrchy/7040377#file-_querytreesort-coffee

I use them now but if ALASQL has a better way I am glad to here it.

Kind regards,
Mario

**Comment by mathiasrw** [comment]
I get it. 

Its not part of the scope for AlaSQL

**Comment by mathiasrw** [comment]
you should change your implementation to 

https://gist.github.com/smrchy/7040377#gistcomment-971422

its faster.

**Comment by MarioVanDenEijnde** [comment]
Hello Mathias,

I noticed and tried but got a javascript error so will implement it later.
Thanks a lot for thinking with me. ;-)

Kind regards,
Mario
