### ISSUE TITLE
alasql.min.js:10 Uncaught Error: Please include the xlsjs library

### ISSUE THREAD

**Issue by jefftham** [agershun/alasql#767]
Something wrong with the library. i try to upload a XLS files ( EXCEL 97 -2003 workbook) through [http://alasql.org/demo/008file/](http://alasql.org/demo/008file/).   

It shows an error `alasql.min.js:10  Uncaught Error: Please include the xlsjs library`  

i try to import the xlsx or xls files from [cdnjs.com](https://cdnjs.com/libraries/xlsx) but it seems that it is not support.   

importing CSV and XLSX are no problem but not XLS.

![image](https://cloud.githubusercontent.com/assets/5941263/19278978/667a4640-8fad-11e6-812d-b851b4c950d0.png)

**Comment by mathiasrw** [comment]
The demo is broken. 

Please see the wiki about `.XLS` ( https://github.com/agershun/alasql/wiki/XLS ) and the jsfiddle for example: https://github.com/agershun/alasql/wiki/XLS

**Comment by mathiasrw** [comment]
Btw: for excel support please use 

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.7.12/xlsx.core.min.js"></script>

**Comment by jefftham** [comment]
I did try that, but it doesn't work for xls format.

**Comment by mathiasrw** [comment]
It will solve 

> It shows an error alasql.min.js:10 Uncaught Error: Please include the xlsjs library

**Comment by jefftham** [comment]
![image](https://cloud.githubusercontent.com/assets/5941263/19360219/a44a17f8-914b-11e6-8198-9ee328cedc84.png)

i tested it before submitting this issue.

**Comment by mathiasrw** [comment]
XLS support have been added to the example. Please verify its working now...

**Comment by jefftham** [comment]
![image](https://cloud.githubusercontent.com/assets/5941263/19754125/ab000fc0-9bd8-11e6-8636-5047f746177d.png)

the problem is still existed.

**Comment by mathiasrw** [comment]
hmmmm

**Comment by sherifalfy** [comment]
Same issue is occuring to me

**Comment by SheetJSDev** [comment]
@mathiasrw  The versions need to be updated in the browser demos.  Here's an updated plnkr of the 008file demo: http://plnkr.co/edit/Atqtg7RKrKbXtJ8eH6Qz?p=info

```html
<script src="https://unpkg.com/alasql@0.4.2/dist/alasql.min.js"></script>
<script src="https://unpkg.com/xlsx@0.11.5/dist/xlsx.core.min.js"></script>
```

**Comment by mathiasrw** [comment]
Awesome! I have updated https://github.com/agershun/alasql-org/blob/gh-pages/demo/008file/index.html so the change should be reflected on http://alasql.org/demo/008file/ any time soon

**Comment by lzzattack** [comment]
this is my code:
alasql('SELECT * INTO XLSX("test.xlsx",{headers:true}) FROM ?', [vm.areaData])
but......
![2017-10-21 6 20 29](https://user-images.githubusercontent.com/25707176/31850841-b762f432-b61f-11e7-8d3e-d7767f56a713.png)

**Comment by fuser84** [comment]
hi @alexvingg 

After using

`alasql.utils.isBrowserify = false;`
`alasql.utils.global.XLSX = XLSX;`

I got error: `error TS2339: Property 'utils' does not exist on type 'AlaSQL'` in my angular application

could you please elaborate about utils in `alasql` as I did not manage to find any info about them

**Comment by yinyihui** [comment]
> 
> 
> @lzzattack I had the same problem.
> 
> I solved this:
> 
> `import alasql from 'alasql';`
> `import XLSX from 'xlsx';`
> 
> `alasql.utils.isBrowserify = false;`
> `alasql.utils.global.XLSX = XLSX;`

Well done with these configs in Vue. Thanks a lot.

**Comment by pg0** [comment]
I can confirm this solves the problem in react too

**Comment by devinfluencer** [comment]
I got `uncaught SyntaxError: The requested module '/node_modules/.vite/deps/xlsx.js?v=73938b01' does not provide an export named 'default'` with alasql version 4.1.2, xlsx version 0.18.5 in a plain typescript app when I try this workaround.
