### ISSUE TITLE
Add IN statement

### ISSUE THREAD

**Issue by silverhawk184** [agershun/alasql#77]
Please add the IN statement. For now I can use a custom JS function, but would be nice to have it built in.

**Comment by silverhawk184** [comment]
Actually, it looks like I cannot create custom functions as alasql.fn is undefined.

**Comment by agershun** [comment]
Please, look at the example with IN and alasql.fn:

    http://jsfiddle.net/jt7a35k8/1/

Could you write an example of your statement?

**Comment by silverhawk184** [comment]
I am using the latest version of alasql.min.js and/or alasql-worker.min.js (there is no versioning that I can see, but GitHub says it hasn't been updated in 2 months. 

Anyway, to test, I created a basic html file with the contents:
>&lt;script src="/js/alasql-worker.min.js" type="text/JavaScript"&gt;&lt;/script&gt;
>&lt;script type="text/JavaScript"&gt;
>alasql.fn.nick=function(a){return a};
>alasql('SELECT nick(1)',[],function(d){console.log(d);});
>&lt;/script&gt;

Chrome console inspector says: " Uncaught TypeError: Cannot set property 'nick' of undefined". But if I remove the function from it, it runs the query correctly.

**Comment by silverhawk184** [comment]
I tried my script using the jsFiddle and it works no problem. There must have been a change between the version on your website vs the version on GitHub that breaks the custom functions.

**Comment by agershun** [comment]
I will change version management to prevent problems like this. Thank you!
