### ISSUE TITLE
HELP returns dead url for AlaSQL

### ISSUE THREAD

**Issue by tmrk** [agershun/alasql#771]
The `HELP ` command returns an url that is missing an 'L' at the end!

See here:

https://github.com/agershun/alasql/blob/develop/dist/alasql.js#L15902

and here:

https://github.com/agershun/alasql/blob/develop/dist/alasql.js#L15911

**Comment by mathiasrw** [comment]
Thanks ! its fixed now. 

(what a crazy misspelling...)
