### ISSUE TITLE
Database "dbnew" not found

### ISSUE THREAD

**Issue by PhoenixAlx** [agershun/alasql#772]
Hello,
The first, awesome job, thank you.

The next. I run this code on my browsers, firefox version 49.0.1 and chromium(chrome) version 53 with the alasql version version 0.3.3-develop-1438

```
alasql('CREATE INDEXEDDB DATABASE IF NOT EXISTS dbnew');
alasql('ATTACH INDEXEDDB DATABASE dbnew');
var mybase = alasql.Database('dbnew');
```
but the console show me these errors
alasql.js:4777 Uncaught Error: Database "dbnew" not found
alasql.js:16254 Uncaught Error: IndexedDB: Cannot attach database "dbnew" because it does not exist

what is the problem? can you help?

**Comment by mathiasrw** [comment]
All IndexedDB operations are asyncronous. 

Please see more about async code execution: https://github.com/agershun/alasql/wiki/Async
