### ISSUE TITLE
The file format extension of .. don't match

### ISSUE THREAD

**Issue by aiduc0502** [agershun/alasql#776]
Please help me!
I recieved this bug when exported.This bug appearance when I tried to use properties width and wordwrap column in my code.I'm using angularjs in my project . How to fix this?Thanks
![untitled1](https://cloud.githubusercontent.com/assets/22289259/19792876/b2002a00-9cf3-11e6-84d7-bb4d370a1345.png)

**Comment by mathiasrw** [comment]
I know... Its really sad.

Hvad a look at https://github.com/agershun/alasql/issues/487
