### ISSUE TITLE
LIKE operator is not case-insensitive 

### ISSUE THREAD

**Issue by silverhawk184** [agershun/alasql#78]
In mySQL syntax LIKE is case insensitive.

**Comment by agershun** [comment]
I updated current version 0.0.40. Now LIKE is case-insensitive.

See the example [in jsFiddle] (http://jsfiddle.net/7na7tkf7/2/)

**Comment by silverhawk184** [comment]
I tired it again today and the issue is back. I am loading data from a JavaScript object.

**Comment by agershun** [comment]
Thank you! I will check.

**Comment by mathiasrw** [comment]
I have added tests at https://github.com/agershun/alasql/commit/84f7312d07f657c7c037067dfe0a3622692759a1

**Comment by mathiasrw** [comment]
Tests passed ! https://travis-ci.org/agershun/alasql/jobs/101649931

**Comment by agershun** [comment]
![Like Chip and Dale](http://static.comicvine.com/uploads/original/11117/111171244/3940306-chip-n-dale.jpg)

**Comment by mathiasrw** [comment]
Hihihi :+1:

**Comment by mathiasrw** [comment]
btw. Added AlaSQL to http://up-for-grabs.net/

**Comment by agershun** [comment]
:+1:

Отправлено с iPhone
