### ISSUE TITLE
.xlsx file with excel for mac

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#781]
The example from the dokumentation page

https://github.com/agershun/alasql/wiki/XLSXML

Does not give a working .xlsx file on excel for mac

https://jsfiddle.net/vL4tsaef/

It states that the file format is wrong

**Comment by reviewher** [comment]
@mathiasrw Excel 2016 disabled certain types of filetype punning (where the extension doesn't match the format).  `XLSXML` uses the SpreadsheetML format.  Excel expects SpreadsheetML files to be named with the xls extension.

I updated the fiddle https://jsfiddle.net/vL4tsaef/1/ by changing the generated filename to `"restest280b.xls"` and it works properly.

**Comment by mathiasrw** [comment]
You are awesome !

So the "real" extension of XLSML is `.xls` 👍 

We have some documentation we should update now !
