### ISSUE TITLE
How do i format number when export to xls?

### ISSUE THREAD

**Issue by needforspeed** [agershun/alasql#783]
I need to format number like 12345.6789 into 12,345.68, and display as number in excel - not display as text in excel. Or else, some excel functions like filter, sorting won't work properly. 

I did read example here: https://github.com/agershun/alasql/wiki/XLS, but couldn't figure out a way to format number in excel.

E.g. if the number is in text, sorting would be like

.
.
.
1.98
1.99
10.00
.
.
.
2.00
.

if sorting number instead of text, it should come as:

.
.
.
1.98
1.99
2.00
.
.
.
10.00
.
.
.

Thanks in advance!

**Comment by mathiasrw** [comment]
This is same problem as #651

I will close this issue an look for updates in the other tread...
