### ISSUE TITLE
deepEqual - hasOwnProperty - false negatives for extended primitives

### ISSUE THREAD

**Issue by Skarnivorous** [agershun/alasql#785]
I use another library which appears to extend the Array object with a 'first' function.
When alasql attempts to compare two arrays with deepEqual (x and y), x.first is found during the property loop but when comparing to y, y.first does not pass 'hasOwnProperty' check and deepEqual returns false.

However, x.first property should not even be checked as it is part of prototype or other inheritance.
I think the deepEqual function should be updated to something like:
```Javascript
var deepEqual = function(x, y) {
	if (typeof x === "object" && null !== x && (typeof y === "object" && null !== y)) {
		if (Object.keys(x).length !== Object.keys(y).length) {
			return false;
	}
	for (var prop in x) {
//only compare property of x if it is belongs to object explicitly
		if(x.hasOwnProperty(prop)){
			if (y.hasOwnProperty(prop)) {
				if (!deepEqual(x[prop], y[prop])) {
					return false;
				}
			} else {
				return false;
			}
		}
	}
	return true;
	} else {
		if (x !== y) {
			return false;
		} else {
			return true;
		}
	}
};

```

Reproduce failure by attempting the usual multi-sheet xlsx export method and have bootgrid library included. This adds the .first property to Array type and results in the deepEqual failing, leads to array of datasources not being structured properly.

I believe the deepEqual should be altered to do hasOwnProperty check on both test objects even though I also think the Array primitive shouldn't have been adjusted in this way by bootgrid.

**Comment by mathiasrw** [comment]
Nicely spotted...

As I see it the bug is that only one of the elements compared are checked for `hasOwnProperty` and your suggestion to a solution could fix this. 

Im wondering if it would be more correct to remove the `hasOwnProperty` check, as this would compare all poperties of the object?

**Comment by Skarnivorous** [comment]
If you need to be sure every property including prototype is the same (and I suppose it does say 'deep' in the function name) then take out the hasOwnProperty check altogether.

 Not sure there's a faster way to do a full equality check, though you might cut out a few scenarios where both x and y are literally the same object by doing an early if(x===y) check.

You could also maybe early exit before prototype property iteration by checking by comparing x.constructor.name and then against instanceof y or y.constructor.name?

If x.constructor isn't reliable, I guess then full property compare is the way.

As for whether any of the early exits I'm suggesting actually provide any performance worthwhile, I'll have to learn how to jsPerf.
