### ISSUE TITLE
Example XLSX Import Not working

### ISSUE THREAD

**Issue by AmyBlankenship** [agershun/alasql#787]
The JSFiddle linked to in your documentation for importing Excel (http://jsfiddle.net/3ve90afo/) doesn't work. This is possibly related to an error in xlsx.full.min.js: f.charCodeAt is not a function at line 18. I tried spawning a new fiddle and using the latest cdn available at jsdelivr for alaSql and xlsx.js, but this did not solve the problem.

**Comment by mathiasrw** [comment]
Thank you for taking the time to let us know!

**Comment by AmyBlankenship** [comment]
Any word on this? FWIW, the similar Sheet JS demo is working http://oss.sheetjs.com/js-xlsx/

**Comment by mathiasrw** [comment]
Nothing new on this. Any inputs would be awesome... also that you found out that the sheetjs thing is working (so, for sure its alasql fucking up...)

**Comment by AmyBlankenship** [comment]
Did you close it because you fixed it, or because you removed the link to the jsfiddle from the docs?

**Comment by reviewher** [comment]
@AmyBlankenship The fiddle was changed but the README wasn't updated.  According to the commit http://jsfiddle.net/s2h9d59a/3/ should work.

**Comment by mathiasrw** [comment]
The link will work as soon as the next version is published. 

I should have explained that the merge referred here solved the issue...
