### ISSUE TITLE
Error: XLSX library not found

### ISSUE THREAD

**Issue by technorodent** [agershun/alasql#790]
I originally did a number of tests (6 weeks or so ago) before implementing alasql and everything seemed to work fine. 

No I am getting errors, the worst of which is 
```
Debugger listening on port 5858                                   
 error: [Error: XLSX library not found]                           
Assertion failed: (err) == (0), file src\debug-agent.cc, line 154 
```

Do you have a go-back build so that this can be made to work again?

**Comment by mathiasrw** [comment]
Are you including the xlsx.js file?

**Comment by technorodent** [comment]
Oh, and yes I tried npm installing alasql and xlsx. I just picked up a node alasql test file file from 2 months ago and tested it within the context of an Express app, and I am getting positive results writing an array to xlsx file. I'm trying to track down the differences now. I will work on this until I have a solution and will post results here. Thanks for your attention. Don't worry for now, I shall work on this.

**Comment by mathiasrw** [comment]
Sounds great. 

Please remember to share version numbers (`alasql.version`) also...

**Comment by FranzSkuffka** [comment]
I had a similar issue using nodeJS. The culprit turned out to be the faulty `isNode` function. alasql@0.2.x - @0.3.x

**Comment by mathiasrw** [comment]
@FranzSkuffka

`isNode` is faulty? Any inputs on how to make it better would be awesome.

**Comment by FranzSkuffka** [comment]
Essentially, to make my build work on node v4.7.3 I shortwired the function to simply `return true`.
`return utils.isNativeFunction(utils.global.process.reallyExit)` fails on me for detecting the environment.
https://github.com/agershun/alasql/blob/develop/dist/alasql.js#L3335

I have not dug deeper so unfortunately that's all the intel I can give now.

**Comment by mathiasrw** [comment]
Interesting - thank you for the input. 

Is it just a plain `var alasql  = require 'alasql'`?

Are you using some kind of package manager? Bower? browserify? webpack? roleup? someting someting?

**Comment by FranzSkuffka** [comment]
I am requiring alasql this inside a gulp v3.9.1 task:
`var alasql = require('alasql');`

**Comment by mathiasrw** [comment]
What do you get if you do a 

```
var alasql = require('alasql');
console.log(alasql.utils.isNode)
```

?

**Comment by FranzSkuffka** [comment]
If I don't patch the function I get (for alasql.utils):

```
...
  isNativeFunction: [Function],
  isWebWorker: false,
  isNode: false,
  isBrowser: false,
  isBrowserify: false,
  isRequireJS: false,
  isMeteor: false,
  isMeteorClient: false,
  isMeteorServer: false,
  isCordova: false,
  hasIndexedDB: false,
...
```

```js
// inside utils.isNode IIFE
  console.log(utils.global.process.reallyExit)
  console.log(utils.isNativeFunction(utils.global.process.reallyExit))

// > [Function: processReallyExit]
// > false
```

But I suggest we don't invest any further time into this. I am afraid this is some kind of error inside the project build, modifying a global var or whatever. As long as no other dev has this problem I don't see much purpose in you fixing the legacy code I got inside a GitHub issue...

Thank you & if I can assist any further just let me know.

**Comment by mathiasrw** [comment]
@technorodent Please reopen this repo when you can provide more info about your problem

**Comment by bkniffler** [comment]
I'm using rollup to bundle a lambda function and its recognized as isNode=false. Any advice on this? Cheers!

**Comment by bkniffler** [comment]
This seems to be working for now: 
```
import alasql from 'alasql';
alasql.utils.isNode = true;
```
