### ISSUE TITLE
Data export; Getting data instead of excell file

### ISSUE THREAD

**Issue by MmtBkn** [agershun/alasql#791]
Hi,

I'm trying to generate excel file from array of data, that user entered.

`alasql('SELECT * INTO XLSX("john.xlsx",{headers:true}) FROM ?',[orders])`

works perfect at browsers, however I'm working on mobile environment(ionic2), and I want to upload file instead of download it.

Is there any way to return file content as blob or whatever, instead of starting download process, if no, that would be great to have it.

Thank you.

**Comment by mathiasrw** [comment]
Hmmm. Not at the moment. 

It should try to save the file instead of downloading it. 

What file (version) are you using?

**Comment by MmtBkn** [comment]
Ok, 

What do you mean by version?

**Comment by mathiasrw** [comment]
What do you get from `alasql.version` - Are you using alasql.js or alasql.fs.js?

**Comment by MmtBkn** [comment]
Ohh..

```
alasql.version
"0.3.4"
```

Scripts
```
  <script src="https://cdn.jsdelivr.net/alasql/0.3/alasql.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.7.12/xlsx.core.min.js"></script>
```

**Comment by mathiasrw** [comment]
Hmm. What do you get if you in ionic run

```js
alert('  Environment detected: '+JSON.stringify({
										alasqlPath: alasql.path,
										isBrowser: alasql.utils.isBrowser,
										isCordova: alasql.utils.isCordova,
										isMeteor: alasql.utils.isMeteor,
										isMeteorClient: alasql.utils.isMeteorClient,
										isMeteorServer: alasql.utils.isMeteorServer,
										isNode: alasql.utils.isNode,
										isWebWorker: alasql.utils.isWebWorker
									},null,2));
```

**Comment by mathiasrw** [comment]
I am closing this one. Please reopen if new information apears...
