### ISSUE TITLE
Double quotation marks in CSV output #431 : getting same error on latest version ie 0.3.4

### ISSUE THREAD

**Issue by junedansari** [agershun/alasql#793]
getting extra quotes on first column header while exporting CSV

like #431

**Comment by mathiasrw** [comment]
Terrible - can you provide some code that generates the problem?

**Comment by Dhananjay05414** [comment]
Hi Mathias,
Whenever using **"alasql": "0.2.6"** version it's working fine but I have updated **"alasql": "0.3.4"** then facing  double quotation issue in downloaded output CSV .Please find attached screenshot and code snippet.

  alasql.promise('SELECT * INTO CSV(\"'+fileName+'\",{headers:true,separator:","}) FROM ?',[dataToWrite])
![input_format_of_csv](https://cloud.githubusercontent.com/assets/24468450/21095601/3812bcfa-c082-11e6-9926-4442aeec35e5.png)
![output_format_of_csv](https://cloud.githubusercontent.com/assets/24468450/21095602/3812cbf0-c082-11e6-96a7-803eb6656b15.png)

Please let me know if you need more information.

**Comment by mathiasrw** [comment]
Thanks for a good bug... lets see who will get the time to fix it...

**Comment by kanghj** [comment]
The issue seems to be an additional BOM added to the front of the file. Possibly caused by the version upgrade of FileSaver in 0.3.2. I'll try to submit a pull request sometime this week.

**Comment by mathiasrw** [comment]
@junedansari 

Can yuo check if this problem is fixed with the last version of https://github.com/agershun/alasql/blob/develop/dist/alasql.fs.js ?

**Comment by Dhananjay05414** [comment]
Thanks, I have tested and it's working fine now.

**Comment by junedansari** [comment]
@mathiasrw Thank you so much, itz working fine now.
