### ISSUE TITLE
Is it a feature that can replace null as empty string when export to excel

### ISSUE THREAD

**Issue by allenz0810** [agershun/alasql#794]
I was trying to export to excel in angular controller with an array of object, but when export the data to excel sheet all the null are coming with it. Is it a way i can set the null to empty string? 

For more information please check out following link.

http://stackoverflow.com/questions/40984737/using-alasql-can-you-replace-null-column-with-empty-string

**Comment by mathiasrw** [comment]
Hmm. Not at the moment. 

I would `select * + where ...` and use a double loop to replace all `null` with `""` and the do a `alasql('SELECT * INTO XLSX("ExchangeReport' + time + '.xlsx") FROM ?',[cleanDataObj])`

I will close this one as this is also posted on stackoverflow.
