### ISSUE TITLE
Proposal fix XMLHttpRequest.DONE

### ISSUE THREAD

**Issue by filchakov** [agershun/alasql#796]
Hello!

I had a problem with importing data through an AngularJS controller (i use theme Flatkit). 
In a console, I see that the file has been successfully downloaded. 
But he was not imported into the database.

I resolved this problem for Angular. 
Please change method "loadFile"  (Load text file from anywhere)

Original version 

`if (xhr.readyState === XMLHttpRequest.DONE) {`

Need version

`if (xhr.readyState === 4) {`

In my case XMLHttpRequest.DONE return 

`function dispatchEvent() { [native code] }`

**Comment by mathiasrw** [comment]
Thanks :)
