### ISSUE TITLE
Returning array of values or of objects

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#80]
Using 

```db: new alasql.Database('tableName')```

I experience that ```db.exec``` sometimes gives me an array of values and sometimes an array of objects with values. 

First I understood it as returning an array of values if only one column was selected. But the same query with a DISTINCT returns an array of objects. 

![alasqlarrayobject](https://cloud.githubusercontent.com/assets/1063454/6536251/56796b50-c44c-11e4-820a-b76537c0565c.png)

I tried to replicate the issue but did not succed ( http://jsfiddle.net/rndy99jy/ )

Do you have clues of why it would ever return an array of values?

**Comment by mathiasrw** [comment]
Any news on this one?

**Comment by agershun** [comment]
It is strange...

By specification, it has to provide always array of objects, except if you are using modificators like:
```sql
    SELECT VALUE mycol FROM mytable -- returns a value of first column of first line
    SELECT COLUMN mycol FROM mytable -- returns array of values from first column
    SELECT ROW mycol FROM mytable -- returns array of values from first row
    SELECT MATRIX mycol FROM mytable -- returns array of arrays 
```
If this is not an answer, we need to develop example to find the source of the problem.

**Comment by agershun** [comment]
Now you example works fine. http://jsfiddle.net/rndy99jy/ Probably the problem is fixed :)

**Comment by mathiasrw** [comment]
Yayyy :)
