### ISSUE TITLE
All select queries with column names broken? 

### ISSUE THREAD

**Issue by megastef** [agershun/alasql#800]
I used alasql in the past and had no issues. 
Today I used alasql 0.3.4 (and tried also older versions) and get no SQL command working, which uses column names. Only 'select *' works!

http://jsfiddle.net/dkb83en6/1/

**Comment by megastef** [comment]
Sorry, forgot that data for tables needs to be wrapped in an array.

**Comment by mathiasrw** [comment]
👍🏼
