### ISSUE TITLE
Please instead of all 'instanceof Array' by 'Array.isArray'

### ISSUE THREAD

**Issue by renhongxu123** [agershun/alasql#803]
I' m using alasql and the vm in nodeJS, and it occurs some problems. 'instanceof Array' in alasql can't work cause the vm in nodeJS has own context, and I don't want to use runInThisContext.

So, please instead of all 'instanceof Array' by 'Array.isArray'. Thanks a lot.

**Comment by mathiasrw** [comment]
Done!

**Comment by renhongxu123** [comment]
thanks. By the way, when is the next release?

**Comment by nanquan** [comment]
Encountered the same issue, hope the new version can be release asap :+1:

**Comment by mathiasrw** [comment]
In about half an hour...
