### ISSUE TITLE
How to reduce the file size?

### ISSUE THREAD

**Issue by tommytian770401** [agershun/alasql#805]
When I export xlsx files with json array at the client side, it works fine but the size of the output is amazing, the blob is almost 10 times larger then the original one. After open-save the xlsx generated,  the size of file change into reasonable size.

I do not understand what happened of the background. Is there any solution for the reducing blob size?

**Comment by mathiasrw** [comment]
This is a really good point. 

I have no idea. We use https://github.com/SheetJS/js-xlsx to generate the files - I suggest you raise it as an issue there to see if they would like to have a look at it.
