### ISSUE TITLE
Select.toString() omits table aliases from joins

### ISSUE THREAD

**Issue by ndxbxrme** [agershun/alasql#812]
Hi Andre

I absolutely love alasql but have run into a tiny bug.
Calling .toString() on an alasql.yy.Select object omits the table aliases of joined tables.
eg `JOIN table AS t` comes out as `JOIN table`
Here's a jsfiddle to show it action http://jsfiddle.net/ndxbxrme/ryx7b5yz/1/
and here is a proposed fix for the `yy.Select.prototype.toString` function (approx line 6992)
```javascript
if(jn.table){
  ss += 'JOIN '+jn.table.toString();
  if(typeof jn.as !== "undefined") {
     ss += ' AS ' + jn.as; 
  }
}
```
Here's a jsfiddle with the fix implemented http://jsfiddle.net/ndxbxrme/eyLy4zy9/1/

Cheers
Kieron

**Comment by mathiasrw** [comment]
You are awesome. Ill get it into the code!

**Comment by ndxbxrme** [comment]
Haha, thanks Mathias but don't speak too soon!
I've been using .toString() quite heavily recently and have found a few more bugs.
Here's a jsfiddle showing them all with some fixes included http://jsfiddle.net/ndxbxrme/eyLy4zy9/3/

**Comment by mathiasrw** [comment]
Thank you!
