### ISSUE TITLE
Aggregate MEDIAN, STDEV not work with ROLLUP

### ISSUE THREAD

**Issue by brunodenis** [agershun/alasql#816]
error s.sort is not a function

SELECT MEDIAN(value) from ? GROUP BY ROLLUP(column)

**Comment by mathiasrw** [comment]
Thank you for taking the time to let us know :)

**Comment by agershun** [comment]
You need to rewrite this to:
```
SELECT MEDIAN([value]) from ? GROUP BY ROLLUP([column])
```

2017-02-05 16:04 GMT+03:00 Mathias Rangel Wulff <notifications@github.com>:

**Comment by brunodenis** [comment]
Thanks for your answer.

both methods share the same error message, see below.
var data = [
	{DEX:"A",WEEK:"S1",IND1:5,IND2:90},
	{DEX:"A",WEEK:"S1",IND1:10,IND2:90},
	{DEX:"A",WEEK:"S2",IND1:7,IND2:60},
	{DEX:"B",WEEK:"S1",IND1:10,IND2:41},
	{DEX:"B",WEEK:"S2",IND1:5,IND2:11}
];

var ancestors = 'SELECT DEX,MEDIAN(IND1) FROM ? GROUP BY ROLLUP(DEX)';
var ancestors = 'SELECT DEX,MEDIAN([IND1]) FROM ? GROUP BY ROLLUP([DEX])';

mmkSQL.promise(ancestors,[data])
.then(function(data){
     console.log(data);
}).catch(function(err){
     console.log('Error:', err);
});

Error:  s.sort is not a function

**Comment by brunodenis** [comment]
Hi,
Any update on this ?

**Comment by brunodenis** [comment]
Please find correct MEDIAN aggregate that works with ROLLUP
alasql.aggr.MEDIAN = function(v,s,stage){
    if(stage == 1) {
      return [v];
    } else if(stage ==2) {
      s.push(v);
      return s;
    } else {
    	if(!s.length) {
      	return s;
      } else {
        var r = s.sort();
        var p = (r.length+1)/2;
        if(Number.isInteger(p)) {
        	return r[p-1]; 
        } else {
        	return (r[Math.floor(p-1)] + r[Math.ceil(p-1)])/2;
        }
      }
    };
  };

**Comment by mathiasrw** [comment]
Awesome!

I can see you are counting the null values too - any inputs on why its better than not counting them?

Code optimized slightly and committed to development branch for next release

**Comment by brunodenis** [comment]
nulls shall not be counted
