### ISSUE TITLE
broken PayPal button image

### ISSUE THREAD

**Issue by DTrejo** [agershun/alasql#817]
Thanks for AlaSQL, looking forward to using it at some point :)

![image](https://cloud.githubusercontent.com/assets/56119/22613815/60fafb5a-ea30-11e6-8b7b-efc216011261.png)

Something not working as expected:
- Describe the problem  : broken paypal button image

**Comment by mathiasrw** [comment]
Thank you for reaching out. 

Is the image still missing? When I open the page I get:


![skaermbillede 2017-02-06 00 12 34](https://cloud.githubusercontent.com/assets/1063454/22626428/41bcecda-ec01-11e6-9c68-ae77b001bc14.png)

**Comment by DTrejo** [comment]
works now, strange, and I had hard-refreshed too. cheers!
