### ISSUE TITLE
function GROUP_CONCAT() doesn't work

### ISSUE THREAD

**Issue by silverhawk184** [agershun/alasql#82]
>alasql('SELECT Type,GROUP_CONCAT(Name) AS Names FROM ? GROUP BY Type',[[{Type:'PT',Name:'Steve'},{Type:'PT',Name:'Dan'}]]);

returns
>Uncaught SyntaxError: Unexpected token ;

should be
>[{Name: "Steve,Dan", Type: "PT"}]

or, even better, unless "separator" was defined
>[{Name: ["Steve","Dan"], Type: "PT"}]

**Comment by agershun** [comment]
Thank you!

Could you try ARRAY() aggregator:
```js
    var res = alasql('SELECT Type,ARRAY(Name) AS Names FROM ? GROUP BY Type',[[{Type:'PT',Name:'Steve'},{Type:'PT',Name:'Dan'}]]);
```
it gives [{"Type":"PT","Names":["Steve","Dan"]}]

Or you can implement GROUP_CONCAT user-defined aggragator function:

```js
    alasql.aggr.GROUP_CONCAT = function(v,s){
        if(typeof s == "undefined") return v; else return s+','+v;
    };
```
Here v - is a value, and s - is an accumulator. 

It gives [{"Type":"PT","Names":"Steve,Dan"}] 

This is [an example in jsFiddle](http://jsfiddle.net/vuodybtf/2/)

**Comment by agershun** [comment]
Now GROUP_CONCAT() is in Alasql.

**Comment by silverhawk184** [comment]
Here is an update to the GROUP_CONCAT function. I was getting "undefined" results through out  the string:
`
    alasql.aggr.GROUP_CONCAT = function(v,s){
        if(typeof v === "undefined" && typeof s === 'undefined') return '';
        else if(typeof v === "undefined" && typeof s !== 'undefined') return s;
        else if(typeof v !== "undefined" && typeof s === 'undefined') return v;
        else return s+','+v;
    };
`

**Comment by gabrielmongefranco** [comment]
Hello, @agershun / @silverhawk184 . Did this fix ever make it into the code? I tried using GROUP_CONCAT in the latest version, 4.17, and it also didn't work.

**Comment by gabrielmongefranco** [comment]
Never mind - I got it. The syntax in the code is the internal syntax. The one in SQL (which I don't see in the docs) is:

SELECT
  Field1,
  **GROUP_CONCAT(Field2 ORDER BY Field2 ASC SEPARATOR ',')**
FROM MyTable
GROUP BY Field1
