### ISSUE TITLE
Not able to download sub_document in xlsx format

### ISSUE THREAD

**Issue by gomathi04** [agershun/alasql#822]
Hi,

I have a list of user details in that each user object have list of family members ,  I want  to download user details along with family member details , but in excel I am getting family member details as [object] [object][object]  I tried MATRIX but am getting same result ,Is there any possibilities to format like below 

1. **.username1, mobile , mail , address,age,gender, number of family members**
-    _member1_name , member1_age,member1_gender_
-    _member2_name.member2_age,member2_gender__
2. **.username2, mobile , mail , address,age,gender, number of family members**
-    _member1_name , member1_age,member1_gender_

 .xlsx or any other report format is fine..
Please suggest.

**Comment by mathiasrw** [comment]
Please provide a working code example by making a jsfiddle and reopen this issue when its provided.
