### ISSUE TITLE
Broken link on wiki

### ISSUE THREAD

**Issue by kanghj** [agershun/alasql#823]
https://github.com/agershun/alasql/wiki/Ionic gives a link to http://blog.glaucocustodio.com/2015/03/30/local-storage-with-alasql-in-cordovaionic-framework/, but it has moved to https://glaucocustodio.github.io/2015/03/30/local-storage-with-alasql-in-cordovaionic-framework/

**Comment by mathiasrw** [comment]
Awesome! thanks :)
