### ISSUE TITLE
Export to xlsx does not work

### ISSUE THREAD

**Issue by akob** [agershun/alasql#824]
Hi!
I want to have multiple worksheets with custom headers. But I have an exception 

**Uncaught TypeError: Cannot convert undefined or null to object**

see example 

https://jsfiddle.net/we884d53/19/

```
window.saveFile = function saveFile () {
var data1 = [{a:1,b:10},{a:2,b:20}];
    var data2 = [{a:100,b:10},{a:200,b:20}];
    var opts = [{sheetid:'One',headers:true},{sheetid:'Two',headers:true}];
    var res = alasql('SELECT a AS Alpha, b AS Betta INTO XLSX("restest344b.xlsx",?) FROM ?',
                     [opts,[data1,data2]]);
}
```

**Comment by akob** [comment]
HI! When it will be fixed?

**Comment by mathiasrw** [comment]
I have no idea. As soon as someone makes a PR ill release a new version.
