### ISSUE TITLE
Issue in Mozilla browser

### ISSUE THREAD

**Issue by muddassir297** [agershun/alasql#828]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Programming question?
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something not working as expected? 
- Describe the problem  
- Provide code that replicates the problem 
- We suggest to spawn a jsfiddle from http://jsfiddle.net/mtt9r7rx/

**Comment by mathiasrw** [comment]
Please provide mire information about the problem and reopen the issue when you have contributed example code.
