### ISSUE TITLE
alasql main function missing in node js

### ISSUE THREAD

**Issue by gregaubert** [agershun/alasql#83]
Hello,
It seems it is not possible to use `alasql(‘SELECT * FROM ? WHERE a >= ?’, [data, 2]);` directly in node.js. (data variable being a javascript array)
When requiring alasql node module, the object returned by index.js is not the alasql function :

```javascript
var alasql = require('./alasql.js');

for(var key in alasql) {
  exports[key] = alasql[key]
}
```

Is there a particular reason for not exporting the whole function with `module.exports = require('./alasql.js');` ?
Or defining alasql.js as the main script in package.json ?

**Comment by agershun** [comment]
## Question 1
```js
    alasql(‘SELECT * FROM ? WHERE a >= ?’, [data, 2])
```
I checked it in  browser: see [jsFiddle](http://jsfiddle.net/7hL44jco/)

Also I checked it in node.js (below is the sample of the program. It stored in ```examples``` subdirectory):

```js
    var alasql = require('../alasql.min.js');
    var data = [{a:0},{a:1},{a:2},{a:3},{a:4}];
    var res = alasql('SELECT * FROM ? WHERE a >= ?', [data, 2]);
    console.log(res);
```

In both cases they give:
```
    [{"a":2},{"a":3},{"a":4}]
```

Probably the problem with require('./alasql.min.js').

## Question 2

I will check how to make a proper declaration of ```alasql``` in the module. Can I simply replace ```for(var...){...}``` with ```module.export = require(./alasql.js')``` ? I can check it tonight.

Thank you!

**Comment by gregaubert** [comment]
### Question 1

Sorry I was probably not accurate enough in my previous comment. The alasql function works right. And your example works perfectly right too, the bug is the way of requiring the alasql module.

If I require it the way you did in the example, by directly targeting the `alasql.js` file, it's all good. But if I require it the "npm" way, like I require all the modules I install using npm : `var alasql = require('alasql');`, then I don't have access to the alasql function at all, probably because `index.js` is wrong.

### Question 2

Yeah changing the module declaration or the `index.js` file would solve the problem of Question 1.

I can see 3 ways of solving this :

1. Like you said: replacing all the content of `index.js` with `module.exports = require(./alasql.js');`.
2. Remove the `index.js` file and change the `package.json` file to set `"main": "alasql.js"`.
3. Keeping your actual index.js and add something like : `exports.mainFct = alasql;`
   * It's probably the worst solution but at least we could access the main function by writing : 
    ```javascript
    var alasql = require('alasql');
    var data = [{a:0},{a:1},{a:2},{a:3},{a:4}];
    var res = alasql.mainFct('SELECT * FROM ? WHERE a >= ?', [data, 2]);
    ```

Thank you for the quick answer!

**Comment by agershun** [comment]
Great! Thank you! Now I know how to fix it! .

**Comment by gregaubert** [comment]
Are you going to release a fix for the package.json file soon ?
If you want I can do a pull request for it ? Or else I will just do a fork and use it from npm.

**Comment by agershun** [comment]
I am going to do it today. 

Отправлено с iPhone

**Comment by gregaubert** [comment]
Great thank you, and will you update the version to 0.41 on npm too ? So we can get it with the updated package.json.

**Comment by agershun** [comment]
Hi, I did all modifications. Could you verify the result?

**Comment by gregaubert** [comment]
Hi, I just tested your modifications. I installed alasql directly from npm and now it works all good. Thank you.
I saw your commit and noticed that your changed the package.json, to point directly to alasql.js, so now your index.js file is not needed anymore (to work with node js at least, I don't know about the other system your support).

**Comment by agershun** [comment]
Yes, I did the both changes :) We will see some time, if index.js will be
unnecessary, we will remove it.  Thank you!

2015-03-16 12:01 GMT+03:00 Aubert Grégoire <notifications@github.com>:
