### ISSUE TITLE
typo in code example CVS instead of CSV

### ISSUE THREAD

**Issue by aniston** [agershun/alasql#830]
In the WiKi example 

> How to read from CSV for Google Maps?

there is a typo error CVS instead of CSV

> `alasql('SELECT MATRIX * FROM CVS("data.csv", {headers:false})',[],function(data){
    // process data array
});`

**Comment by mathiasrw** [comment]
Awesome - thank you!

https://github.com/agershun/alasql/wiki/How-to-read-from-CSV-for-Google-Maps is not corrected :)
