### ISSUE TITLE
Export to excel breaks formatting for Div containing multiple tables with different number of. Olin a

### ISSUE THREAD

**Issue by ak4wrapp** [agershun/alasql#831]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Programming question?
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something not working as expected? 
- Describe the problem  
- Provide code that replicates the problem 
- We suggest to spawn a jsfiddle from http://jsfiddle.net/mtt9r7rx/

**Comment by ak4wrapp** [comment]
I am exporting a div with three tables 
First table -4 columns
Second - 10 columns (table is places inside div with scroll)
Third table has two inner tables with 4 rows each

The final output excel is broken

**Comment by mathiasrw** [comment]
Hi @ak4wrapp - thanks for reaching out so we can make the lib better. 

If you can provide the code that generates the error that would help a lot. 

Please reopen the issue when you have provided the example code demonstrating the problem.

**Comment by aki-84** [comment]
Thanks for replying, sure below is the sample fiddle code

`http://jsfiddle.net/k4mz5ars/3/`

**Comment by aki-84** [comment]
@mathiasrw Thank you for reopening this issue

**Comment by aki-84** [comment]
I am sorry I somehow copied wrong JSFiddle link 
http://jsfiddle.net/k4mz5ars/4/

**Comment by mathiasrw** [comment]
Mozilla Firefox is not even opening the JSfiddle. Strange. 

AlaSQL does not support including more tables at once. Its a bug, not a feature that it does not halt when more tables are in the element of the `id`

I suggest you make a table of the columns you want, and one by one you select into the table, and in the end select from the table into an `.xlsx`
