### ISSUE TITLE
Angular 2 with  Webpack

### ISSUE THREAD

**Issue by crh225** [agershun/alasql#837]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Programming question?
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something not working as expected? 
- Describe the problem  
- Provide code that replicates the problem 
- We suggest to spawn a jsfiddle from http://jsfiddle.net/mtt9r7rx/

Im trying to add alasql to my package.json. I installed through npm. I am using webpack with angular 2.

![image](https://cloud.githubusercontent.com/assets/19475195/23713409/6d6e27d4-03eb-11e7-813b-7a4e6282f351.png)

**Comment by crh225** [comment]
I have since gotten rid of the errors in the first picture by adding this to webpack config:
`new IgnorePlugin(/(^fs$|cptable|jszip|xlsx|xls|request|^es6-promise$|^net$|^tls$|^forever-agent$|^tough-cookie$|cpexcel|^path$)/)`

however, now Im getting cannot find module XLSX. Im using this fiddle as an example on how to download into excel.
http://jsfiddle.net/9d6yrom9/

Im importing alasql like ```import * as alasql from 'alasql';```

**Comment by crh225** [comment]
I have also tried the noparse:
![image](https://cloud.githubusercontent.com/assets/19475195/23714875/677abe5a-03f0-11e7-945b-46c16c7dc932.png)

**Comment by mathiasrw** [comment]
You need to include the xlsx.js library: https://www.npmjs.com/package/xlsx

Please reopen if this does not resolve your issue

**Comment by doublewaterfish** [comment]
I met the same problems, what do you mean include the xlsx.js library, I add it in the package.json file, is that correct?

**Comment by mathiasrw** [comment]
Please read https://github.com/agershun/alasql#webpack-browserify-and-react-native
