### ISSUE TITLE
CREATE FUNCTION/AGGREGATE statement

### ISSUE THREAD

**Issue by sasha-alias** [agershun/alasql#839]
Thank you guys for a great work. AlaSQL looks really awesome!
Here is a feature request. It would be very handy to be able to define user's functions or aggregates using a SQL notation.
Smth like:
``` sql
CREATE FUNCTION cube AS function(x) { return x*x*x; };
```
or
``` sql
CREATE AGGREGATE myaggr AS function(value, accumulator, stage) { ... };
```

This would allow to write more advanced transformations being in SQL context only, when javascript context is not available to the user.

**Comment by mathiasrw** [comment]
Good idea. Hmmmm...

I am thinking about 2 solutions. 

a) We make sure the "sql" command - as all other SQL - can be part of a multi SQL statement (seperated by `;`) this would demand the function to be surrounded by `"`or `'` like a normal stirng. This is a bit annoying if you have to escape elements as the statement is a string you have to double escape the string representing the function, and dont get started with escaping within stirngswithin the function within the SQL statement...

b) We make a special case where everything after the `AS` is considered the soruce of the string and simply avoid parsing it. This limits this statment to not being able to be part of a multi statement SQL.


Inputs?

**Comment by sasha-alias** [comment]
I think option `a` is more preferable since it's more consistent with other SQL statements. Moreover I'd expect this statement to run as a part of multiple statements scripts in most of the cases.
Regarding quoting issue, I agree, that will be a pain to escape quotes in functions especially the ones using JSON. But this can be approached a [postgresql way](https://www.postgresql.org/docs/9.6/static/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING). For the simplicity I think we don't need fully dynamic dollar quoting, just double dollar quotes would be enough for most of the cases. So the final syntax can be like this:
``` sql
CREATE FUNCTION cube AS $$ function(x) { return x*x*x; } $$;
```
What do you think?

**Comment by mathiasrw** [comment]
Just found out that AlaSQL supports to give javascript as expression - when its surrounded by ``` ``....`` ```

Function is working as expected 👍 

Aggregate for some reason only works when you do it async. Looking into why before realeasing next version.

**Comment by sasha-alias** [comment]
Wow, that was fast! Thank you.
FYI, I just released a new version of [SQL Tabs](http://www.sqltabs.com/) with basic AlaSQL support. Basically it has alasql built in, so people can write SQL queries over files without need to load them to any external database.

**Comment by mathiasrw** [comment]
Looks really nice

If you make an excel plugin that can let people use sql to make graphs you can sell that. 

----

Was there any specific reason you suggested `AGGREATE` in your first input? I have a feeling `AGGREGATOR` is more gramatically in the flow. Is `AGGREATE` used in other languarges? Inputs?

**Comment by sasha-alias** [comment]
I just thought that aggregates are very similar to [functions](https://github.com/agershun/alasql/wiki/User-Defined-Functions), 
so should be easy to achieve. 
`CREATE AGGREGATE` statement is present in Postgresql, MS SQL, Oracle. Not sure about other databases. I believe in most of analytical databases it should be present. 
From own experience custom aggregates are used not that often as functions, mostly on specific data types where built-in aggregates are not enough. If it makes some complications I think it's fine to leave it outside of this ticket.

**Comment by mathiasrw** [comment]
We keep both...

Its "fixed" by letting the documentation say that it only workds async... awww - lazy solution...

I will close this issue and make a new one with only the async thing

**Comment by mathiasrw** [comment]
Wuups - was already closed...
