### ISSUE TITLE
Keeping the master branch up to date

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#84]
I recommend that the master branch always contains the latest stable version.

That will make it easy to link to

https://cdn.rawgit.com/agershun/alasql/master/dist/alasql.min.js

knowing that its always updated.

**Comment by agershun** [comment]
Mathias, thank you! Could you help me, if you know: how to copy all files from one branch (e.g. version-0.0.40) to master branch from command line. I am not to much familiar with GitHub...

**Comment by mathiasrw** [comment]
Sure.

Go to your git dir on your computer and

```
git checkout master
git merge version-0.0.40
git push
```

The last one is to get the changes to github

( Or have a look at https://www.atlassian.com/git/tutorials/using-branches/git-merge )

**Comment by agershun** [comment]
thank you!

2015-03-11 12:09 GMT+03:00 Mathias Rangel Wulff <notifications@github.com>:

**Comment by agershun** [comment]
Done. Now `master``` branch is the latest version.

**Comment by mathiasrw** [comment]
Sweet - please do when ever you have a new stable version :)

**Comment by agershun** [comment]
I a little bit confused with these branches... The only working method I found was to rename branch with working version to ```master```. (the method you proposed by some reasom did not work - it can not finishe with ```merge``` command.)

**Comment by mathiasrw** [comment]
A good idea is to have two branches - master and develop(ment). 

The master contains the latest "stable" version, the development contains the "edge" version of the latest changes.

If more features are being developed at the same tie one can branch out from the develop, do the development and merge into development again - and when all features are set merge into master. 

We are not the first people to face a challenge like this. Infact - there is a specific way of using git called "git flow" that helps out with this. 

To use it I reccomend this free program http://www.sourcetreeapp.com/ it works quite nice. Or - if you are more like a shell guy you install by 

```
apt-get install git-flow
git flow init
``` 

(on linux) 

To start working on a new feature:

```git flow feature start MYFEATURE```

When its done you get the changes back into the develop branch by

```git flow feature finish MYFEATURE```

When you feel development is ready for a new stable version you

```git flow release start RELEASE````

effectively creating a midstep (releace candidate) between development and master where one can run tests and make sure everything is good. And finally one write 

```git flow release finish RELEASE```


I recommend taking a look at http://danielkummer.github.io/git-flow-cheatsheet/

**Comment by mathiasrw** [comment]
Let me know it that helps you - or if we should work on another setup

**Comment by agershun** [comment]
Mathias, thank you! I will read about this software and try to apply the approach that you proposed on weekends.

**Comment by agershun** [comment]
I created ```develop``` branch and installed git-flow. Now I start to test the [feature/NULL]](https://github.com/agershun/alasql/tree/feature/NULL) branch. Hope, this will work and increase the quality of development.

**Comment by mathiasrw** [comment]
:+1:
