### ISSUE TITLE
node-red-contrib-alasql : problem with JOIN

### ISSUE THREAD

**Issue by hamild** [agershun/alasql#846]
Hello - first of all, I really like this node! 
It works fine for a simple query from a spreadsheet but I am having difficulty if I try to use JOIN. 
For example, in my node, I use - SELECT * FROM XLS("c:\GB_All.xls") JOIN XLS("c:\hs_postcodes.xls") USING POSTCODE where POSTCODE LIKE  'AB%'; 
This gives me "Error: Unknown type of FROM clause" in the debug node (for alasql).   Is this a user problem? 
Apologies in advance... I'm relatively new to Node-Red (and to ALASQL).

**Comment by mathiasrw** [comment]
At the moment AlaSQL does not support joining on data read from a file.

You can solve it by reading one (or both) files into a table and using that. 

_crap code, but you should get the point_

```sql
create table postcodes (fields...);
select * from XLS("c:\hs_postcodes") into postcodes;
SELECT * FROM XLS("c:\GB_All.xls") JOIN postcodes USING POSTCODE 
where POSTCODE LIKE 'AB%';
```

It might be that you need to read both files before joining. Please let me know how you go. 

I will close this issue, but please reopen if this does not solve your problem.
