### ISSUE TITLE
OFFSET behavior not conventional

### ISSUE THREAD

**Issue by webdori882** [agershun/alasql#858]
The current behavior of alasql when performing limit/offset is not in line with what major SQL DB engines provide. The conventional expectation when passing these "pagination" params is the "OFFSET" number or rows are skipped but that is not the case based on the example provided "http://jsfiddle.net/efn1yoer/1/" and based on the function "doLimit()".

Please confirm if this is intended behavior and what it is modeled after.  

Thanks in advance, - J

**Comment by mathiasrw** [comment]
I feel confident that it is not intended. 

Postgress: 
> OFFSET says to skip that many rows before beginning to return rows.

Oracle:
> skip the N first rows in a result set before starting to return any rows

MSSQL:
> Skip first 10 rows from the sorted result set and return the remaining rows

MySQL is the same...

This will be fixed

**Comment by mathiasrw** [comment]
Will be part of the next release. Thanks for letting us know...

**Comment by webdori882** [comment]
Thanks for the prompt update, you guys rock!
