### ISSUE TITLE
Not able to hide column using "skipdisplaynone: true"..while exporting excel using alasql

### ISSUE THREAD

**Issue by RaghavendraJha** [agershun/alasql#859]
Below is the code:
var opts = [{ sheetid: sheetName, header: true, skipdisplaynone: true }];
                var res = alasql('SELECT INTO XLSX("' +
                    templateName +
                    '.xlsx",?) FROM ?',
                    [opts, [itemsToInsert]]

here ItemsToInsert is a list of rows, i am getting from json.
I am not able to the set the style element for columns  in the list as well.
Any help will be highly appriciated.
Thanks.

**Comment by mathiasrw** [comment]
Its hard to help if you do not provide data. Please reopen when you can provide data. 

input: you dont need to add the .xlsx part of the name.
