### ISSUE TITLE
How to hide some property from array when exporting to Excel by alasql

### ISSUE THREAD

**Issue by piyush135** [agershun/alasql#870]
Hi team,

I'm generating excel by alasql plugin and binding column from array collection.
                var opts = [{ sheetid: sheetName, header: true }];
               alasql('SELECT INTO XLSX("' + templateName +'.xlsx",?) FROM ?',[opts, [itemsToInsert]]);

Now I want to hide some property from collection (ItemsToInsert). Here My source file is not html. Could you please assist me in this case.

Thanks

**Comment by mathiasrw** [comment]
do a `SELECT xxxm, yyy, zzz INTO ....` to only select the 3 columns xxx, yyy, and zzz

Not sure you can do this if  souce is HTML. Try. If not you need to insert data into temp table and select from it mentioning the columns as mentioned above.
