### ISSUE TITLE
Uncaught SyntaxError: Parse error on line 1:

### ISSUE THREAD

**Issue by SWard1992** [agershun/alasql#872]
I am receiving an error when I try to load an excel CSV file, the error i am receiving is: 
![image](https://cloud.githubusercontent.com/assets/28388872/25700312/35994fc4-3095-11e7-9d14-0df2e9c787fd.png)
I am just building a simple webpage that allows me to compare two database tables from different environments to find differences.

 I export the tables from Toad as an Excel CSV and then load them in using this line of code: `alasql('SELECT * FROM FILE(?,{headers:true})',[event],function(data){` and this seems to be the particular line that error is occurring on, the weird thing is that it only throws the error for one particular CSV file. 

 I have been able to successfully load multiple other CSV files but one particular CSV file is causing the issue. Any help would be much appreciated.

**Comment by mathiasrw** [comment]
> I have been able to successfully load multiple other CSV files but one particular CSV file is causing the issue. Any help would be much appreciated.

Please provide the file that is causing the problem

**Comment by SWard1992** [comment]
Sure thing 
[246tbx-DEV.zip](https://github.com/agershun/alasql/files/978647/246tbx-DEV.zip)

**Comment by SWard1992** [comment]
I actually figured the issue out I did some research and it ends up that one of the columns was using a reserved word that I needed to escape and that's why it was throwing the exception.
