### ISSUE TITLE
Export to excel grouped columns

### ISSUE THREAD

**Issue by sandeepappetals** [agershun/alasql#873]
This is my json array object:
```js
var data =[{
    "ID":'1', 
    "Name":'Parent',
    "Children": [{"Name": 'Child1' }, {"Age": '10'}],
    "Grand Children": [{"Name": 'Child3'}, {"Age": '4'}]
},{
    "ID":'2', 
    "Name":'Parent2',
    "Children": [{"Name": 'Child1' }],
    "Grand Children": [{"Name": 'Child3'}, {"Age": '6'}]
}
];
```
I'm using alasql("SELECT * INTO XLSX('relation.xlsx',{headers:true}) FROM ? ",[data]);
I get the below result:

![first](https://cloud.githubusercontent.com/assets/16206632/25738015/6dbecdda-3198-11e7-80b3-99333b748085.jpg)

But, what i exactly need is the below result:
![second](https://cloud.githubusercontent.com/assets/16206632/25738162/3f0338f4-3199-11e7-8ce1-5fd3f918c451.jpg)

**Comment by mathiasrw** [comment]
That would be really awesome. At the moment AlaSQL does not support cells spanning multiple columns
