### ISSUE TITLE
How to add style css to XLSX export or removing warning message XLS export 

### ISSUE THREAD

**Issue by RAFBOUK** [agershun/alasql#874]
Hello every body,
I have the same problem when i try to open the export ==>
**alasql( 'SELECT * INTO XLS("' + exportFileName + '.xls",?) FROM ?',[ opts, data] );**
and when I use this second request **alasql( 'SELECT * INTO XLSX("' + exportFileName + '.xlsx",?) FROM ?',[ opts, data] )**; I don't have the warning but i can't include styles inside xlsx file, I think it's normal because in the alasql's documentation they use the request without any "opts" just like this (**alasql( 'SELECT * INTO XLSX("' + exportFileName + '.xlsx",?) FROM ?',[data] );**),
My question is : 
**How can I export excel file from json with ALASQL without the warning message when I try to open it and, I must to include some styles inside the file ?**
thx in advance for your responses

**Comment by mathiasrw** [comment]
> I have the same problem when i try to open the export 

What problem are you mentioning?

**Comment by RAFBOUK** [comment]
Hi @mathiasrw ,
I have to add an excel export from json with css style in the excel file, 
the first request  **(alasql( 'SELECT * INTO XLS("' + exportFileName + '.xls",?) FROM ?',[ opts, data] );)** does this work well but I have a warning message when I try to open the file :( ... I must remove this warning message. 
With the seconde request **((alasql( 'SELECT * INTO XLSX("' + exportFileName + '.xlsx",?) FROM ?',[data] );),)**, I don't have the warning message but I can't add css into the excel file ...
So I have the choice between two solutions : 
1. if I will use the first request, I must remove the warning message when i try to open the excel file.
2. if I will use the second solution, I must add css to the excel file 
Can you help me for what can I take as a solution ?
Thank you in advance

**Comment by mathiasrw** [comment]
Have you looked into the https://github.com/agershun/alasql/wiki/XLSXML option?

**Comment by RAFBOUK** [comment]
I just tried it and I have the same warning like the first request when I try to open the excel file 
![sans titre](https://cloud.githubusercontent.com/assets/28432137/25825785/871f4d28-3444-11e7-8a36-e9190ef5340d.png)

**Comment by RAFBOUK** [comment]
Hi @mathiasrw 
Do you have a solution for this problem ? 
:)

**Comment by mathiasrw** [comment]
Nope :-/

**Comment by RAFBOUK** [comment]
Any help plz :-/ ??!!
Perhaps another library witch offers me the behavior that I need ?!
I'm looking everywhere and I don't find anything ... :(

**Comment by mathiasrw** [comment]
xlsx.js maybe?

https://github.com/SheetJS/js-xlsx

**Comment by abroy88** [comment]
Hi, I need help with styling multiple sheets in one workbook, when using alasql.js. 
Apart form sheet name and header as opts, i am not able to style the sheet's.
alasql('SELECT INTO XLSX("restest344b.xlsx",?) FROM ?',[opts,[data1,data2]].
Please help with a solution or an alternate that can work with multisheet
