### ISSUE TITLE
insert into table using an array of array variable

### ISSUE THREAD

**Issue by leehin** [agershun/alasql#876]
alasql('CREATE TABLE country1(country string primary key, capital string)');
alasql('CREATE TABLE country2(country string primary key, capital string)');
alasql('CREATE TABLE country3(country string primary key, capital string)');
// i can insert values into country1 table using the following 
alasql('INSERT INTO country1 VALUES \\
("Malaysia1","Kuala Lumpur"), \\
("China1","Beijing"), \\
("United Kingdom1","London"), \\
("Philippines1","Manila") \\
')
// i can insert into country2 table using array of object
var data2 = [
{country:'Malaysia',capital:'Kuala Lumpur'},
{country:'China',capital:'Beijing'},
{country:'United Kingdom',capital:'London'},
{country:'Philippines',capital:'Manila'}
]
alasql.tables.country2.data = data2
// but i want to insert an array of array into country3 table
// so i try this but failed
var data3 = [
['Malaysia','Kuala Lumpur'],
['China','Beijing'],
['United Kingdom','London'],
['Philippines','Manila']
]
alasql('INSERT INTO country3 VALUES data3')   //failed 

Does alasql provide any way to insert into table from an array of array?`

**Comment by mathiasrw** [comment]
This is not supported.
