### ISSUE TITLE
Problems/Doubts attaching a sqlite3 db

### ISSUE THREAD

**Issue by shotgun469** [agershun/alasql#88]
Hi,

I am not clear on how to attach a sqlite3 db with alasql and sql.js.

I am getting a 

Uncaught Error: Parse error on line 6:
...t current_timestamp)
----------------------^
Expecting 'LPAR', got 'RPAR'

trying to replicate your example using Chinook's db. The db is not in the same directory as the file calling it.

Could anyone provide another example please?

Thanks,

**Comment by agershun** [comment]
I prepared two examples (for browser and Node.js) where you can read SQL.js databases (unpack [this file](https://www.dropbox.com/s/gqm6zxldca199ji/alasqlsql.zip?dl=0)).

To run in browser you need put files somewhere in webserver (e.g. I use [http-server](https://www.npmjs.com/package/http-server).

To run example in node.js use the following command:
```
    node runme
```

First - include alalsq.js and sql.js files into you page (or ```require()``` them for node.js)
```html
<script src="alasql.min.js"></script>
<script src="sql.js"></script>
```
Then open SQL.js database:
```js
    alasql('ATTACH SQLITE DATABASE Chinook("Chinook_Sqlite.sqlite")',[],function(){ ... });
```
Here:
a) you need to use async version of alasql()
b) you can not save SQL.js

Please, let me know if there are problems with running these examples.

**Comment by shotgun469** [comment]
Hi agershun,

Thank you for the reply,

1) I tried to replicate your example using my db and I am getting the following error in console:

Uncaught Error: Parse error on line 6:
...t current_timestamp)
----------------------^
Expecting 'LPAR', got 'RPAR'.

2) In your example, the newly inserted data is not saved to the chinook db. Is that a limitation of alasql.js?

thanks again,

**Comment by agershun** [comment]
1. The problem, that Alasql parse SQL.js table definition, and it cannot parse it ... Could you post the table definition of your database, so I can check how to parse it in Alasql.

2. Yes, Alasql cannot save directly. But probably you can do it with SQL.js function:

https://github.com/kripken/sql.js/#write-a-database-to-the-disk

And you can find SQL.js database at ```alasql.database[youDatabaseId].sqldb```.

This is should be something like:
```js
    var fs = require("fs");
    var data = alasql.databases[databaseid].export();
    var buffer = new Buffer(data);
    fs.writeFileSync("filename.sqlite", buffer);
```

**Comment by shotgun469** [comment]
This is the table:

create table practice_quiz_results(
  id integer primary key,
  quiz_id integer not null,
  user_id integer not null,
  score integer not null,
  created_ts timestamp default current_timestamp
)

I am using the browser and not node.js

Thank you for the guide and the support,

**Comment by agershun** [comment]
I think that the parser can not parse "current_timestamp" as a value. 

I modify parser to accept this default value, But Alasql will not put anything into this field!
Can you try it?

**Comment by mathiasrw** [comment]
Its a dangerous road to go - that alasql accepts / implements features that will work with one backend but with other / no backend.  

Another way of solving could be to catch the keyword ```current_timestamp ``` and throw an error stating that this SQL is not fully supported by alaSQL and should therefore be executed directly on the backend

So instead of having

```sql
alasql(''CREATE TABLE t1 (a int, b current_timestamp)')
alasql(''INSERT INTO t1 (a) VALUES (1)')
alasql('SELECT * FROM t1')
```

We guide the users to write 

```sql
alasql.database[youDatabaseId].sqldb.exec(''CREATE TABLE t1 (a int, b current_timestamp)')
alasql(''INSERT INTO t1 (a) VALUES (1)')
alasql('SELECT * FROM t1')
```

What do you think about that?

**Comment by shotgun469** [comment]
@agershun ,

Yes, Now I can see the contents of the DB. 

Also, it is OK to not put anything on that field since it is directed in the DB to use current_timestamp as a default value when no value is entered. Same happens with the ID that it's "auto-incremented".

Now I need to save the new inserts into the DB file. 

Thanks a lot for the help.

**Comment by agershun** [comment]
@mathiasrw  I think at some stage we need to review AlaSQL datatypes, including AUTOINCREMENT / IDENTITY, DATETIMESTAMP and ROWVERSION.  Some people use them frequently in "big" SQL projects.
