### ISSUE TITLE
When working with JSON,  instead of summarizing alasql conatenates values.

### ISSUE THREAD

**Issue by datelligence** [agershun/alasql#888]
Using for the first time this awesome library,  I've found an issue when summarizing data from a JSON file.  In a shopping cart,  if I update the quantity of any given product,  the alasql statement instead of SUM,  concatenates values.  Is there a method to set values as INT instead of treating as strings?

var json = [{"id":"9874","price":19,"q":1}, {"id":"9874", "price":19, "q":2}]
when invoking alasql to summarize this data,  'Select id, price, SUM(q) as q from ? group by id', [json]
I found two issues:
1) Price does not get computed,  I must summarize price to get a value,  for example MIN(price) or AVG(price).  If Select price ... ,  I get an undefined value.
2) the result for the sum is a concatenation instead of a math Sum.

**Comment by mathiasrw** [comment]
> Price does not get computed, I must summarize price to get a value, for example MIN(price) or AVG(price). If Select price ... , I get an undefined value.

This works as intended

> the result for the sum is a concatenation instead of a math Sum.

please verify that you are using the last version of the lib

Live working examples: http://jsfiddle.net/9bprfujg/
