### ISSUE TITLE
How to use [ ] in column names

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#89]
Now Alasql supports column names enclosed with [ and ]. What if the column name has [ and ]?

Current RegExp for bracketed columns is:
```
    \[([^\]])*?\]
```
and it should be improved to accept something like escape character before ```]```.

**Comment by agershun** [comment]
Now you can use ` to enclose such column names, like
```
    SELECT `my [column]` FROM ?
```

**Comment by mathiasrw** [comment]
Nice ! thanks :+1:
