### ISSUE TITLE
How can I set column width and background color in alasql  with js-xlsx library

### ISSUE THREAD

**Issue by akashdeshwal** [agershun/alasql#890]
It can be easily done if I have one tab then I can do this using XLSXML() renderer but how can I do this with XLSX() where I have multiple tabs

**Comment by mathiasrw** [comment]
I dont think this can be done

**Comment by akashdeshwal** [comment]
is there any other way through which I can manipulate the width of columns if I have multiple tabs in my excel sheet?

**Comment by mathiasrw** [comment]
Have a look at the documentation of https://github.com/SheetJS/js-xls
