### ISSUE TITLE
xlsx.core.min.js has snoman character instead of code \u2603 due to whihc xlsx generation on IE 11 browser fails

### ISSUE THREAD

**Issue by clgnik** [agershun/alasql#894]
I am using alaql to generate an excel file. It fails in some IE11 browsers of my client due to snoman symbol in minified code of xlsx.core.min.js
xlsx.core.min.js has snoman character instead of code \u2603 due to whihc xlsx generation on IE 11 browser fails

Step to find this code : search for ^☃]*) in xlsx.core.min.js

the Fix for this issue is : simply replace ^☃]) by \u2603]) in xlsx.core.min.js

I dont have idea about the owner/github url of xlsx.core.min.js please inform that team about this issue.

**Comment by mathiasrw** [comment]
https://github.com/SheetJS/js-xls

**Comment by reviewher** [comment]
This was fixed in xlsx 0.10.6 -- bumping the dependency version would resolve the issue
