### ISSUE TITLE
Export CSV does not consider the separator option, always uses semicolon

### ISSUE THREAD

**Issue by jorgefsimoes** [agershun/alasql#896]
Hi,
I am joining two tables and exporting into a CSV (string), using this Javascript statement:

`alasql('SELECT * INTO CSV(?, {asstring:true, headers:true, separator:","}) FROM ? obj1 JOIN ? obj2 USING ' + joincol, [res, obj1, obj2]);`

My expectation was to have a comma-separated list of values. But independently of what I define to be the separator, the output is always using semicolon (";") as a separator. 

I tried importing CSV and it works fine with commas. Only exporting seems to be an issue.

**Comment by mathiasrw** [comment]
crazy! this must be fixed immediately.

**Comment by kanghj** [comment]
@jorgefsimoes, can you provide a full test case to reproduce this? I'll see if I can fix this.

Btw, see if using this pattern instead can work for you: `var res = alasql('SELECT * INTO CSV({header:true, separator:","}) FROM ? obj1 JOIN ? obj2 USING ' + joincol, [obj1, obj2]);` ?

**Comment by jorgefsimoes** [comment]
Hi @kanghj , thanks for your quick response. I can not seem to replicate the issue anymore with the latest version of alasql. Something must have changed since the problem seems to have been solved. Weird!

**Comment by jorgefsimoes** [comment]
In any case, here is the code I used to initially verify this behavior:

```
var file1 = "DATETIME,Name,Surname\n2017-06-25,John,Smith\n2017-06-26,James,Cook\n"
var file2 = "DATETIME,Weight,Heigth\n2017-06-25,80,180\n2017-06-26,75,175\n"
var joinCol = "DATETIME"

var obj1 = alasql('SELECT * FROM CSV(?, {asstring:true, headers:true, separator:","})', [file1]);
var obj2 = alasql('SELECT * FROM CSV(?, {asstring:true, headers:true, separator:","})', [file2]);

var res = alasql('SELECT * INTO CSV(?, {asstring:true, headers:true, separator:","}) FROM ? obj1 JOIN ? obj2 USING ' + joinCol, [res, obj1, obj2]);

console.log(res);
```

**Comment by mathiasrw** [comment]
@kanghj thank you for tipping in!

@jorgefsimoes I will close this issue if it can not be replicated in the last version of AlaSQL - please reopen if you find a way to reproduce.
