### ISSUE TITLE
Applying styles with XLSX fucntion when rendering excel 

### ISSUE THREAD

**Issue by indunilw** [agershun/alasql#902]
alasql XLSXML function can be used with styling as a parameter. 
Are there any **support for styling in XLSX** fucntion which can be used to render styles.

**XLSXML code -**
```
var opts = {
      column: { width: 200 }
    };
 var data = alasql('SELECT * FROM HTML("#tabledata",{headers:false})');
alasql('SELECT * INTO XLSXML("john.xls",?) FROM ?', [opts, data]);
```

**Comment by barneyliu708** [comment]
I am having the same problem. It looks like it does not support styling when exporting to xlsx

**Comment by mathiasrw** [comment]
XLSX does not support styling at the moment. If you have any inputs on how this can be done that would be awesome.
