### ISSUE TITLE
Excel Size is too large

### ISSUE THREAD

**Issue by Shany1992** [agershun/alasql#903]
I found new Scenario when I tried to export 93,000 records into excel it does not give any response because of my excel size is more than 146MB.

**Comment by Shany1992** [comment]
Why my excel size too large for only 93000 records

**Comment by mathiasrw** [comment]
Please provide code example you are using - or provide full info about columns, and xls, xlsx or xlmxls usage

**Comment by Shany1992** [comment]
Service.ajaxPost('api/Common/GetExportData', { "FromDate": FromDate, "ToDate": ToDate, "StustId": vm.paramValue, "LobId": vm.LobID }).then(function (data) {
            vm.exportData = data["ExportInfo"];
            for (var key in vm.exportData) {
                if (vm.exportData[key].length > 0) {
                    tmp.push(key);
                }
            }
            var exportArr = [];
            var opts = [];
            for (var i = 0; i < tmp.length; i++) {
                var data1 = alasql('SELECT * FROM ?', [vm.exportData[tmp[i]]]);
                if (data1 != 0 && data1 != null) {
                    exportArr.push(data1);

                }
                opts.push({ sheetid: tmp[i], header: true });
            }
            if (exportArr.length > 0) {
                var res = alasql('SELECT INTO XLSX("VendorGSTDetails.xlsx",?) FROM ?',
                                 [opts, exportArr]);
            }
            else {
                var msg = "No Data Found"
                toaster.pop('Warning', msg);

            }
        });

**Comment by Shany1992** [comment]
vm.exportData consist more than 93000 records of data,

**Comment by mathiasrw** [comment]
This is a peformance problem with AlaSQL.

I suggest using the CSV format.
