### ISSUE TITLE
direct query into data variable - (newbie question ; looking for a use case ) 

### ISSUE THREAD

**Issue by joebarry1234** [agershun/alasql#907]
Hi,

Trying to pull multiple sheets into a single workbook.  That part is actually working ok ; it's querying an Oracle database directly ( data2 below) that has no luck so far.  We can query from HTML successfully but its not picking up the oracle query (data2).  Briefly : what am I doing the *most* wrong here ?? I think its just a syntax problem but I just do not know.    Looking for the quick win.  THANKS Andrey; formidable library.  

```js
<script type='text/javascript'>
window.saveFile = function saveFile () {
    var data1 = alasql('SELECT * FROM HTML("#table1",{headers:false})');
    var data2 = alasql('SELECT GLOBAL_NAME FROM GLOBAL_NAME');
    var opts = [{sheetid:'One',header:false},{sheetid:'Two',header:false}];
    var res = alasql('SELECT INTO XLSX("WorkbookName.xlsx",?) FROM ?',
                     [opts,[data1,data2]]);
}</script>
```

**Comment by mathiasrw** [comment]
How is `GLOBAL_NAME` defined? what do you get using `select * from GLOBAL_NAME` ?

**Comment by mathiasrw** [comment]
Please reopen when more information has been provided
