### ISSUE TITLE
Case insensitive table/column names

### ISSUE THREAD

**Issue by amitauras** [agershun/alasql#908]
Can we include case-insensitive table/column names feature in alasql library as _it's very common to have SQL query with table/column names in different case but column names in excel in different case_. And then alasql doesn't read data of those columns as it considers them to be different columns.

Using following jsfiddle 
https://jsfiddle.net/amitauras/08bnjkc6/
we can try passing an excel file with one column named "account" and it logs following to console

```
[
    {
        Account: undefined
    }
]
```

but if we rename column "account" to "Account" the same jsfiddle will log following to console

```
[
    {
        Account: 12 // in my case I have entered 12 as cell value for column "Account"
    }
]
```

**Comment by mathiasrw** [comment]
Any pull request including an option you can set to `true` for this behaviour would be much appreciated.

**Comment by mathiasrw** [comment]
Thank you for the PR - Its now live with version 0.4.1
