### ISSUE TITLE
Arithmetic

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#91]
alaSQL must be able to understand that a statement like 

```
select + -1 
```

is the same as 

```
select -1 
```

as dynamic combination of sql based on calculated values can create situations like this. 

----

Also statements as

```
SELECT 70 * + 1
```

should be valid, returning same result as

```
SELECT 70 * 1
```

Same way statements like

```
SELECT + col1 + 4 FROM t1
```
and 

```
SELECT - col1 + 4 FROM t1
```

and 

```
SELECT col1 - + - col0 FROM t1
``` 

and

```
SELECT col1 * + col2 FROM t1
```
and

```
SELECT DISTINCT + col1 * + 5 FROM t1
```
and
```
SELECT + 36 * + ( + 16 ) 
```

should be valid to complly with standart SQL

**Comment by agershun** [comment]
I will check the unary plus operator (now it works only with unary minus). Thank you!

**Comment by agershun** [comment]
Now it works. See test247. Thank you!

**Comment by mathiasrw** [comment]
Great !!!
