### ISSUE TITLE
hash(sql) returns same result for 2 different sql strings

### ISSUE THREAD

**Issue by tkhyn** [agershun/alasql#910]
Hi and thanks once more for alasql,

I ran into an glitch with 0.3.9 (the issue is still there in 0.4.0 as the hash function is the same) where a query wrongly returned a previously cached result. I tracked it down to the fact that:

```
hash('SELECT * FROM tasks WHERE (pk = "vr") ORDER BY rank ASC')
```

returns -157912141

and

```
hash('SELECT * FROM tasks WHERE (pk = "Uq") ORDER BY rank ASC')
```

also returns -157912141

Which means that when I want to fetch the object with pk = "Uq" it fetches the object with pk = "vr" ...

I'm afraid it's hard to reproduce but it clearly happens (that's the first time I take the time to track the problem down !!). I'd think that the only way to fix that would be to use a more robust hash function ?

**Comment by mathiasrw** [comment]
Horrible. We must find a better hash function - (yet knowing that we will not be able to limit collisions totally.

**Comment by tkhyn** [comment]
I'm no expert at hash functions, but what if a different initialization prime number for the [hash function](https://github.com/agershun/alasql/blob/develop/src/15utility.js#L817) is picked each time the library is loaded? So that at least reloading the page generates different hashes?

**Comment by tkhyn** [comment]
Here is a [SO discussion](https://stackoverflow.com/questions/7616461/generate-a-hash-from-string-in-javascript-jquery) about performance of hash functions in JS (there are others, but that's the most relevant one IMO).

Overall it seems that a good compromise for speed/uniqueness is to use [this implementation of murmurhash](https://github.com/garycourt/murmurhash-js/blob/master/murmurhash3_gc.js).

What do you think ? Tweak the simple and fast current version so that results are not the same from one session to another or replace the function altogether by a possibly slower but more robust implementation ?

**Comment by mathiasrw** [comment]
The existing hash function looks like its ignoring any input beyond 

`hash('SELECT * FROM tasks WH')`

Its still a mystery to me... Maybe its too late for me to think clear. 

The murmurhash looks awesome - but compared to the simplicity of [the existhing](https://github.com/agershun/alasql/blob/develop/src/15utility.js#L817-L825) (not so well working) hash I could be worried about a peformance hit. 

We have to find a solution! I will do some tests to see how much we lose...

**Comment by mathiasrw** [comment]
I cant replicate the "only fist part of the string gets hashed..."... so ignore that part please. 

The murmurhash peforms best on long strings - so as the normal case for SQLs are not to be consideret long, i have descided on basing the hash on FNV-1a also described.

**Comment by tkhyn** [comment]
Thanks a lot for the very quick fix Mathias. Indeed, I missed the part regarding better performance of FNV-1a for short strings vs murmurhash, so FNV-1a is clearly the reasonable choice.
