### ISSUE TITLE
alasql within reactjs app

### ISSUE THREAD

**Issue by kausti** [agershun/alasql#915]
Hi,

I am trying to use alsql within reactjs app and facing some problems.
This could be related to https://github.com/agershun/alasql/issues/738

Has anyone successfully got this to work withing a reactjs app?
I would really like to use this in a react component rather than in html file within script tags. 

So far I have done following
Installed alasql as 
`npm install alasql --save`

Imported alasql in the app as
`import * as alasql from  'alasql';`

But I am getting following complation error

```
Failed to compile.
./~/react-native-fs/FS.common.js
Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\Shinde\reactProj\hawk\node_modules\react-native-fs\FS.common.js'
    at Error (native)

```
I tried to install native-react and native-react-fs but then it keeps going into other dependencies and errors..

```
./~/react-native-fetch-blob/index.js
Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\Shinde\reactProj\hawk\node_modules\react-native-fetch-blob\index.js'
    at Error (native)
```
I do not even need native file system support as this is purely browser based and data will be fetched online. It would really be brilliant if this worked. 

Any ideas?

This was also posted on SO https://stackoverflow.com/questions/45252995/alsql-in-react-react-native-error

Thanks,
Kaustubh

**Comment by nickdeis** [comment]
Related to #913.
Hey Kaustubh,
You have a few choices here.
* add alasql to your `public` folder and use a `<script>` tag to add it.
* Eject your react app and follow the webpack instruction [here](https://github.com/agershun/alasql/wiki/readme#use-webpack-and-browserify)

**Comment by kausti** [comment]
Thanks nickdeis.

Your solutions assume webpack development. However, I am working in react js app created using command

`create-react-app my-app`

Customizing config files in the app is not easy by design..at least to me as I am fairly new to the whole thing.  If you can share more detailed steps that would be massively useful.

Thanks

**Comment by nickdeis** [comment]
See either [npm run eject](https://github.com/facebookincubator/create-react-app#converting-to-a-custom-setup) or [When to Use the public Folder](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#when-to-use-the-public-folder)

Best,
Nick

**Comment by mathiasrw** [comment]
@kausti Please reopen if this does not solve the problem
