### ISSUE TITLE
React native

### ISSUE THREAD

**Issue by sm2017** [agershun/alasql#916]
Is react native supported?? I see https://github.com/agershun/alasql/issues/795 and want to know after months what happened

**Comment by mathiasrw** [comment]
I dont know - I have never used React Native... but i see no reason why it should not work regarding the "inside" of AlaSQL

From https://github.com/agershun/alasql/issues/915#issuecomment-317283498 the challenge is to set things up correctly. 

Have a look at https://github.com/agershun/alasql/blob/develop/README.md#webpack-browserify-and-react-native (it has just been updated a few days ago)
