### ISSUE TITLE
Error in delete from table with DOM

### ISSUE THREAD

**Issue by Julianhm9612** [agershun/alasql#918]
Hi, boys!

I'm trying to delete a data from table, this is my example code:
```
alasql('CREATE localStorage DATABASE IF NOT EXISTS test');
alasql('ATTACH localStorage DATABASE test AS t');
alasql("CREATE TABLE IF NOT EXISTS t.cities (city string, population number)");

alasql("INSERT INTO t.cities VALUES ('Rome',2863223), ('Paris',2249975), ('Berlin',3517424), ('Madrid',3041579)");

var res = alasql("DELETE FROM t.cities WHERE city = ?", ["Berlin"]);
//var res = alasql("SELECT * FROM t.cities ORDER BY population DESC");

showResult(res);

function showResult(x){
    document.getElementById('result').textContent = JSON.stringify(x,  null, '\t');
}
```

![image](https://user-images.githubusercontent.com/24255842/28627564-cddca4dc-71e7-11e7-80e6-f533d6d22b46.png)

The error is: 

![image](https://user-images.githubusercontent.com/24255842/28627504-a44e02f0-71e7-11e7-98fe-1ae0f4edcaaa.png)

If you need test this, i have this jsfiddle: http://jsfiddle.net/472echqq/

**Comment by Julianhm9612** [comment]
My only solution for this tyme is:

alasql('ATTACH localStorage DATABASE Joyeria');

But it is not the expected solution. You have one?

**Comment by mathiasrw** [comment]
Interacting with local storage is async - so you are basically trying to insert before the table is created. 

Have a look at this and reopen if this does not help you.  

https://github.com/agershun/alasql/wiki/Async
