### ISSUE TITLE
How to return empty array if no results?

### ISSUE THREAD

**Issue by iamvitali** [agershun/alasql#927]
Hi,
from my query that looks something like this:

```
SELECT column1, column2
FROM ?
GROUP BY column1, column2
ORDER BY column1 ASC 	
```
I'm getting an array with one object (where there should be no results found). That one object has those 2 columns as keys with values being `undefined`.

**Comment by mathiasrw** [comment]
Sounds bad.

what data are you using?

**Comment by elincognito** [comment]
@mathiasrw 
`alasql('SELECT academicYearId, academicYear, courseName, planStudy, ARRAY(_) as ucs FROM  ?' +
                            ' GROUP BY academicYearId, academicYear, courseName, planStudy ' +
                            ' ORDER BY academicYearId DESC', [[]])`

this will produce:  an  array with a single object with undefined property values:

`
[{academicYearId: undefined, academicYear: undefined, courseName: undefined, planStudy: undefined, ucs: undefined}]`

**Comment by mathiasrw** [comment]
@elincognito thank you for input
