### ISSUE TITLE
Math functions MIN and MAX in conflict with aggregators MIN and MAX

### ISSUE THREAD

**Issue by gregaubert** [agershun/alasql#93]
Hi,
I was trying to use the MIN and MAX functions defined in the 55functions.js file but it seems the names are in conflict with the aggregation functions MIN and MAX defined directly in the jison parser.

Can't get these example to work : 
```javascript
var a = [ { a: 1, b:5 }, {a: 2, b: 0}, {a:0, b: -5}, {a: 5, b:5} ];
alasql('SELECT MIN(`a`, `b`) AS c FROM ?', [a]);
alasql('SELECT * FROM ? WHERE MIN(`a`, `b`) > 1', [a])
```

Perhaps the MIN and MAX math function should be renamed so we can use them...

**Comment by agershun** [comment]
... yes. What should name we use? Do you know what standards say about these functions and aggregators?

**Comment by gregaubert** [comment]
I know for sure that the aggregation function MIN and MAX are totally right and shouldn't be renamed as they are standard.
But I don't know much about the standards for the math functions. I think it doesn't exists in standard SQL. But I know that in __Oracle__ there is the __GREATEST__ and __LEAST__ functions that do the same job.
So you could eventually rename them like that...

**Comment by agershun** [comment]
As far as I found:

1. There is no such function in T-SQL (see [this StackOverflow question](http://stackoverflow.com/questions/124417/is-there-a-max-function-in-sql-server-that-takes-two-values-like-math-max-in-ne) or [this](http://stackoverflow.com/questions/71022/sql-max-of-multiple-columns))

2. Standard functions for this are MySQL and Oracte are GREATEST and LEAST

I renamed these MAX() and MIN() functions (not aggregators) to GREATEST() and LEASTS(). Master branch is updated.

Thank you!

**Comment by agershun** [comment]
I found this distinguishing definition of MIN()/LEAST() and MAX/GREATES
<blockquote>
    min()

    Returns the minimum value. If invoked with more than one parameters, the function doesn't aggregate,   but returns the minimum value between all the arguments.
</blockquote>

Probably, I can change parser to check what type of MIN/MAX was used.

**Comment by agershun** [comment]
Fixed. Now AlaSQL supports constructions like this:
```sql
    SELECT MAX(MAX(a),MIN(a)), MIN(MAX(a),MIN(a)) FROM ?
```
Will be available in release 0.0.50, now in develop branch.

**Comment by mathiasrw** [comment]
:+1:

**Comment by gregaubert** [comment]
:+1: Nice!
And seeing your fix GREATEST/LEAST should still be supported!

**Comment by agershun** [comment]
Yes, but only as functions, when MIN/MAX are aggregators/functions depending on the number of arguments.
