### ISSUE TITLE
Tabletop reads in empty cells as numeric 0 instead of empty string

### ISSUE THREAD

**Issue by renxida** [agershun/alasql#933]
Replicating code:

https://jsfiddle.net/oh0m5d85/

Spreadsheet used in code

https://docs.google.com/spreadsheets/d/1KF0w8f0pvoetEDcnE3VNPiE7QLhtadMMcfxn7q2u11Y/edit#gid=0

This is a big problem for me because I've been using handlebars to present the data alasql returns as html, and all those ugly zeroes really drive me nuts.

I would try solving the problem with a pull request, but I'm new to the javascript world and know nothing about how things are packaged, tested, versioned, and published.

I am currently suspecting this commit for causing this behavior:
https://github.com/agershun/alasql/commit/ee7c4afa250f4271bcafe6572ecbe7e17f125ca2

And I think this is not the way to properly handle numbers: I checked tabletop's documentation (today), and they have a special init option that allows converting numbers automatically. It is off by default, but if I'm reading the code right, alasql allows passing additional init options to tabletop. So the changes in that commit should nolonger be necessary.

Again, I'm new to github and opensource development. Please tell me if I'm formatting anything wrong, and I would deeply appreciate it if someone could tell me how this project works and how I could have fixed this with a pull request.

I really love alasql and would like to contribute.

**Comment by mathiasrw** [comment]
Hi @renxida 

Thank you for a very profound analysis of the problem. 

Have you been poking around with node development before? Are you used to git?

**Comment by renxida** [comment]
@mathiasrw I know how to commit, push, and do pull requests. However, I have never done anything at all with Node (I was more of a Python person), and I don't know how this project is built or tested.

Can I just go in and try changing the code I think is wrong? How do I make alasql.min.js once I have done that? And will I need to do anything with the test cases and/or the code coverage thing I don't quite understand?

Thank you.

**Comment by mathiasrw** [comment]
Sure! just poke around...

Make sure you have node (and npm) on your computer and follow https://github.com/agershun/alasql/blob/develop/CONTRIBUTING.md - let me know if you have problems getting to the first `npm test` to run the tests as they are now.

**Comment by renxida** [comment]
I'm back! Spent the morning trying to make the test.

Mocha reports tabletop to be missing. What I did was `npm install tabletop`, and I also added this to the beginning of the test file:
`if(typeof exports === 'object') {
	var assert = require("assert");
	var alasql = require('..');
	var Tabletop = require('tabletop')
}`

What am I missing？ Should I be doing something special to allow Alasql to find tabletop?

**Comment by renxida** [comment]
Problem can be solved by removing var before Tabletop. I wonder why though?

**Comment by mathiasrw** [comment]
Hmmm. strange...
