### ISSUE TITLE
How to group object field data by property value

### ISSUE THREAD

**Issue by kobyp** [agershun/alasql#942]
How to group object field data by property value department->id and return the field data as its original structure?

var data = [
    {
      department: {
        id: 1,
        text: 'Marketing'
      },
      amount: 120      
    },
    {
      department: {
        id: 1,
        text: 'Marketing'
      },
      amount: 140      
    },
    {
      department: {
        id: 2,
        text: 'IT'
      },
      amount: 50      
    }
  ];

Expected result:
[
    {
      department: {
        id: 1,
        text: 'Marketing'
      },
      amount: 260      
    },
    {
      department: {
        id: 2,
        text: 'IT'
      },
      amount: 50      
    }
  ]

**Comment by agershun** [comment]
You can try this query:
```
var result = alasql("SELECT FIRST(department) AS department,SUM(amount) AS amount FROM ? GROUP BY department->id", [data]);
```
The example is here - http://jsfiddle.net/n52t9tw4/

**Comment by kobyp** [comment]
Thanks
