### ISSUE TITLE
XLSXML export getting failed when I try to pass email.

### ISSUE THREAD

**Issue by balaspider2608** [agershun/alasql#943]
I am trying to export json object to excel with styling. For that I am using XLSXML. Issue is

when I add email column,  after export I am not able to open the file and its throwing file corrupted error .
`Code:
        alasql("SELECT Email as Email INTO XLSXML('restest280b.xls',?) FROM ?", [opts, data]);
json obj `:`
{
Id : `10`
Email : "ex@ample"
ExclDL : "No"
}
Could you please help on `this;``

**Comment by mathiasrw** [comment]
Please provide of data and code to recreate the problem and reopen
