### ISSUE TITLE
Feature request: Would be nice to have anti join instead of left join and where is null

### ISSUE THREAD

**Issue by peon501** [agershun/alasql#949]
Feature request
anti join.
Its lame we have to write
SELECT
*
FROM table1 t1
LEFT JOIN table2 t2 ON t1.id = t2.id
WHERE t2.id IS NULL
in normal sql.
Would be better:

SELECT
*
FROM table1 t1
ANTI JOIN table2 t2 ON t1.id = t2.id

**Comment by alexpeattie** [comment]
Looks like this already exists? From [`test037.js`](https://github.com/agershun/alasql/blob/develop/test/test037.js):

```js
it('ANTI JOIN', function(done){
  var res = alasql("SELECT * FROM one ANTI JOIN two ON one.a = two.e");
  assert.equal(res.length,2);
  done();
});
```

**Comment by mathiasrw** [comment]
Awesome - guess we can close this issue then...
