### ISSUE TITLE
IndexDB How to?

### ISSUE THREAD

**Issue by neomicho85** [agershun/alasql#955]
Hi, I'm using the indexDB example
It create the IndexDB as well as the table and populate all data, later on I try to get the table this way below:

`alasql(' ATTACH LOCALSTORAGE DATABASE gls; SELECT DISTINCT(CountryCode) AS Country FROM locations ORDER BY Country ASC').then(func`

But it says:
Table does not exists: locations
![error](https://user-images.githubusercontent.com/13896628/32574072-124f52c8-c49e-11e7-8bf8-077633f58bfd.png)

**Comment by mathiasrw** [comment]
You have to ise the asunc notation with indexDB

**Comment by neomicho85** [comment]
So, you say every time I try to get a table or make a query in indexDB I have to do this:

`alasql('ATTACH INDEXEDDB DATABASE ' + dbName + '; \
			USE ' + dbName + ';', [], function() {

		alasql.promise('SELECT DISTINCT(CountryCode) AS Country FROM locations ORDER BY Country ASC').then(function(countryQuery) {`

Always have to attach indexDB?

**Comment by neomicho85** [comment]
I try that way, my DB has only 1 table with 6000 rows, every query took like 2.23 seconds to retrieve data

**Comment by mathiasrw** [comment]
Please do something like

```
function init(dbName, callback){
    alasql([['ATTACH INDEXEDDB DATABASE ?;',dbName],
            ['USE ?',dbName]])
    .then(callback)
}

function fetch(callback){
    alasql(['SELECT DISTINCT(CountryCode) AS Country FROM locations ORDER BY Country ASC'])
        .then(function(res){callback(res[0])})
}
```

make sure to call init only once. If performance is not good you might want to store the content from a select * in a variable and just run any new SQL on the array of objects.
