### ISSUE TITLE
Hi, I need help with styling multiple sheets in one workbook, when using alasql.js.  Apart form sheet name and header as opts, i am not able to style the sheet's. alasql('SELECT INTO XLSX("restest344b.xlsx",?) FROM ?',[opts,[data1,data2]]. Please help with a solution or an alternate that can work with multisheet

### ISSUE THREAD

**Issue by abroy88** [agershun/alasql#956]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Programming question?
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something not working as expected? 
- Describe the problem  
- Provide code that replicates the problem 
- We suggest to spawn a jsfiddle from http://jsfiddle.net/mtt9r7rx/

**Comment by mathiasrw** [comment]
Please use upwork.com when you need to extend your development team or use http://stackoverflow.com/questions/ask?tags=alasql if you want to ask the internet.
