### ISSUE TITLE
Data manipulation in Wiki no links?

### ISSUE THREAD

**Issue by li01452** [agershun/alasql#957]
[Data manipulation](https://github.com/agershun/alasql/wiki/Data-manipulation)
I want to know How to filter an array using an array?

**Comment by mathiasrw** [comment]
Hmm. The links where working previously...

https://github.com/agershun/alasql/wiki/How-to-filter-an-array-using-an-array

**Comment by LukaszWiktor** [comment]
The links are still broken:

![image](https://user-images.githubusercontent.com/2964543/44795679-8db4e500-abab-11e8-8985-e08684959060.png)

I'd make a pull request but unfortunately it's not possible for wiki pages.

**Comment by mathiasrw** [comment]
Links fixed.

**Comment by LukaszWiktor** [comment]
Thanks a lot!
