### ISSUE TITLE
Implement master-development branches approach

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#96]

**Comment by mathiasrw** [comment]
:+1:

**Comment by agershun** [comment]
I have read ```git flow``` documentation, and after some tests will we use it. Thank you!

**Comment by gregaubert** [comment]
Really good idea!

**Comment by agershun** [comment]
New ```develop``` branch created (according git-flow recommendations).

**Comment by agershun** [comment]
Thanks to Udacity ,I finished [amazing course](https://www.udacity.com/course/ud775) and fixed my bugs with Git, so I more or less ready for more serious collaboration in development.
