### ISSUE TITLE
XLSXML - corrupt file 

### ISSUE THREAD

**Issue by ankita199** [agershun/alasql#969]
Hi,
I am using alasql in my angular 4 project for downloading xls file with formatting. this is working but when i am opening the file it says 'The file you are trying to open 'filename.xls' has a different format than specified by the extension. Verify that the file is not corrupted and it is from a trusted source before opening the file.Do you want to open the file now?'

i dont want to show this warning to my client..is this bug or what?

let mystyle = {
headers: true,
column: {
style:{
Font:{
Bold:"1",
Color:"#DCDCDC",
Size: "10"
}
}
}
};
alasql( 'SELECT * INTO XLSXML("' + fileName + '",?) FROM ?', [mystyle,json] );

**Comment by mathiasrw** [comment]
We are not aware why this error comes. If you find a solution please let us know.
