### ISSUE TITLE
read from blob not working

### ISSUE THREAD

**Issue by SamanthaAdrichem** [agershun/alasql#971]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Something not working as expected? 
we're using https://github.com/danialfarid/ng-file-upload for uploading files resulting in a File Object
(https://developer.mozilla.org/nl/docs/Web/API/File)
So basically you would expect that i could read it from a blob using the following code:

`alasql.promise('select * from CSV(?)', file).then( function() { console.log( arguments ) }, function() { console.log( arguments ) } );
`
or this code
`alasql.promise('select * from CSV(?)', [file]).then( function() { console.log( arguments ) }, function() { console.log( arguments ) } );`

it however does nothing, no errors, no promise resolved nothing.

I'm expecting atleast an error :(

I just downloaded the latest zip from here. We're loading these two files:

> alasql/dist/alasql.min.js
> alasql/console/xlsx.core.min.js

**Comment by SamanthaAdrichem** [comment]
for csv's i can do something like:

```
let reader = new FileReader();
let csvContents = "";

reader.addEventListener('loadend', (e) => {
 csvContents+= e.srcElement.result;
});

alasql.promise('select * from CSV(?)', csvContents);
```
and thus read from string. I'd prefer a blob though. So that the syntax with XLSX is the same

With XLSX i  get the following error if i add the blob.

> TypeError: Cannot read property 'uint8array' of undefined
>     at Object.exports.transformTo (eval at module.exports (webpack-internal:///110), <anonymous>:2:31270)
>     at ZipEntries.prepareReader (eval at module.exports (webpack-internal:///110), <anonymous>:3:4593)
>     at ZipEntries.load (eval at module.exports (webpack-internal:///110), <anonymous>:3:4652)
>     at new ZipEntries (eval at module.exports (webpack-internal:///110), <anonymous>:3:851)
>     at JSZip.module.exports [as load] (eval at module.exports (webpack-internal:///110), <anonymous>:2:9664)
>     at new JSZip (eval at module.exports (webpack-internal:///110), <anonymous>:2:8756)
>     at Object.readSync [as read] (eval at module.exports (webpack-internal:///110), <anonymous>:9:7407)
>     at eval (eval at module.exports (webpack-internal:///110), <anonymous>:2:18112)
>     at Object.C.loadBinaryFile (eval at module.exports (webpack-internal:///110), <anonymous>:11:9131)
>     at S (eval at module.exports (webpack-internal:///110), <anonymous>:2:17993)
>     at Object.A.from.XLSX (eval at module.exports (webpack-internal:///110), <anonymous>:15:23722)
>     at Object.eval [as datafn] (eval at <anonymous> (eval at module.exports (webpack-internal:///110)), <anonymous>:3:28)
>     at eval (eval at module.exports (webpack-internal:///110), <anonymous>:2:6973)
>     at Array.forEach (<anonymous>)
>     at o (eval at module.exports (webpack-internal:///110), <anonymous>:2:6933)
>     at s (eval at module.exports (webpack-internal:///110), <anonymous>:12:8415)
>     at Function.A.dexec (eval at module.exports (webpack-internal:///110), <anonymous>:11:16550)
>     at Function.A.exec (eval at module.exports (webpack-internal:///110), <anonymous>:11:15985)
>     at A (eval at module.exports (webpack-internal:///110), <anonymous>:2:20394)
>     at eval (eval at module.exports (webpack-internal:///110), <anonymous>:11:24088)
>     at new ZoneAwarePromise (webpack-internal:///485:890:29)
>     at j (eval at module.exports (webpack-internal:///110), <anonymous>:11:24053)
>     at Function.A.promise (eval at module.exports (webpack-internal:///110), <anonymous>:11:24596)
>     at parseFile (webpack-internal:///2050:82:11)
>     at eval (webpack-internal:///2050:63:5)
>     at Object.forEach (webpack-internal:///487:408:20)
>     at AdminFinanceSovendusExportConverterController.processFiles (webpack-internal:///2050:62:12)
>     at fn (eval at compile (webpack-internal:///487), <anonymous>:4:260)
>     at update (webpack-internal:///1643:967:27)
>     at eval (webpack-internal:///1643:1033:11)
>     at eval (webpack-internal:///487:20545:31)
>     at completeOutstandingRequest (webpack-internal:///487:6419:10)
>     at eval (webpack-internal:///487:6699:7)
>     at ZoneDelegate.invokeTask (webpack-internal:///485:425:31)
>     at Zone.runTask (webpack-internal:///485:192:47)
>     at ZoneTask.invokeTask (webpack-internal:///485:499:34)
>     at ZoneTask.invoke (webpack-internal:///485:488:48)
>     at timer (webpack-internal:///485:2040:29)


The XLSX itself is a simple created xlsx in microsoft excell containing two rows

> a, b, c
> 1, 2, 3

**Comment by mathiasrw** [comment]
Creat bug report.  Lets solve this together. Ill have a look next time I have 30 mins free.

**Comment by SamanthaAdrichem** [comment]
I've found this issue online: https://github.com/open-xml-templating/docxtemplater/issues/102
basically stating, maybe that has something to do with the XLSX issue

"The issue was the .docx file was not in the same folder as the HTML page."

though it's a blob in memory

**Comment by SamanthaAdrichem** [comment]
I've created a work-around which is quite browser compatible according to caniuse.com which i would just add to your documentation as the solution:


```
let fileAsObjectUrl = URL.createObjectURL( file );
alasql.promise('select * from xlsx(?, {autoExt: false})', [fileAsObjectUrl])
    .then( function() { console.log( arguments ) }, function() { console.log( arguments ) } );

```
where xlsx can also be changed to csv and it also works for csv's
