### ISSUE TITLE
Converting the syntax tree back to SQL with multple joins adds commas to the sql

### ISSUE THREAD

**Issue by kylebernhardy** [agershun/alasql#972]
If you have multiple joins in the AST and convert to SQL, commas are added to the end of each join, rendering the SQL invalid. See linked jsfiddle: https://jsfiddle.net/nizzlenitz/pmyowznw/

**Comment by alexpeattie** [comment]
I think the fix is to add `.join('')` to the end of [this line](https://github.com/agershun/alasql/blob/d997e41d327765bbefda99decebe4ab261275eb7/src/40select.js#L85)

**Comment by mathiasrw** [comment]
Thanks for your help @alexpeattie

**Comment by alexpeattie** [comment]
No worries ☺️ !
