### ISSUE TITLE
Converting the syntax tree back to SQL with a BETWEEN throws an internal error

### ISSUE THREAD

**Issue by kylebernhardy** [agershun/alasql#975]
When there is a BETWEEN in the WHERE clause and you convert the AST back to SQL an internal error is thrown. 

See code snippet at: https://runkit.com/kylebernhardy/alasql.between.issue

**Comment by mathiasrw** [comment]
Anyone wanting to dig into this: feel free to find inspiration in #970

**Comment by sljohnsondev** [comment]
@mathiasrw Hope you're well.  If you don't mind assigning me to this issue I can get a PR posted shortly. Thanks!
