### ISSUE TITLE
When using SUM, the values are concatenated instead of added up

### ISSUE THREAD

**Issue by tenshis** [agershun/alasql#98]
The following code:

`var res1 = alasql('SELECT CUSTOMER, YEAR as id, SUM(REVENUE) as revenue FROM ? WHERE CUSTOMER = "Some customer" GROUP BY CUSTOMER, YEAR', [revenueTestData]);`

will return the correct fields, but the REVENUE column isn't being added up, instead it looks like this: 

`[{"CUSTOMER":"Some customer","id":"2009","revenue":"7533.363475799568406.0847520828211099.13727760317055.143251419079471.969194412231434.697957038889537.901611328132353.847265243539256.821279525766645.71525573739794.012145996096947.63191223145"}`

I've seen this problem with multiple javascript sum functions. Usually an operator like "| 0" is used to make sure even NaN values (when there is no revenue to add) are taken into consideration as zeroes. However, I couldn't get this to work with alasql. Any ideas?

**Comment by agershun** [comment]
Thank you! 

Probably, the reason of string concatenation is that the source column has "string" type.

Please try [this example in jsFiddle](http://jsfiddle.net/agershun/6fpkgegw/3/) where I tried to reproduce your error. Here I used CAST / CONVERT / :: operator to convert strings to numbers:
```
    SUM(REVENUE::NUMBER) as revenue
```
If the error still exists, could you provide the couple lines of your source data?

**Comment by tenshis** [comment]
Hello agershun, you are correct, of course. Thank you !
