### ISSUE TITLE
Allow second parameter of Alasql to be a function that returns data array

### ISSUE THREAD

**Issue by peterprib** [agershun/alasql#982]
alasql(‘SELECT a->b FROM ?’,[data]);
to allow 
alasql(‘SELECT a->b FROM ?’,()=>{return[data]})

**Comment by mathiasrw** [comment]
If you could add more words to why this is beneficial that would be great.

**Comment by peterprib** [comment]
Would allow function that could pull information from screen attributes directly including parameters. 
Know could achieve similar with adding table function but this allows simplified code. 

Actually would be great if call back was added as parameter.  Be more interesting if call back could be called multiple times which re-runs SQL as that way one could change a parameter and initiate a rerun which could result in html output being refreshed or data added to table.  I suppose this has greater implications to consider when SQL part of a sequential process.

The issues that started be on the track was the annoying "Cross origin requests are only supported for protocol scheme" which means I have to add a step to screen for user to specify select file would be great if table functions for files could be made to work off <input type='file' id='choose' />

**Comment by mathiasrw** [comment]
Interesting. Can you make a code example where it makes sense to use it instead of just calling a function that returns the value 

```
alasql(‘SELECT a->b FROM ?’,[returnData()]);
```

**Comment by peterprib** [comment]
Can close as discovered it does what I want in test case although haven't tested.
