### ISSUE TITLE
Searching a JSON with special character in key

### ISSUE THREAD

**Issue by varunrayen** [agershun/alasql#984]
I am using alasql to search through a JSON object. But when I try to return values of a specific key (eg; "@type") it doesn't return any data.

Is it because the key name has special character? If so, how would I be able to process it.

Thanks!

**Comment by mathiasrw** [comment]
Can you please try to use ``` `@type` ``` or `[@type]` and see if this helps?

**Comment by varunrayen** [comment]
@mathiasrw Yeah, [@type] works. Thanks!
