### ISSUE TITLE
new Function - from data to string to data

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#99]
Looking at https://github.com/agershun/alasql/blob/27a5178c3a164996c36559ac22e8eb964a08aefb/src/74update.js#L37

```Javascirpt 
var s = '';
this.columns.forEach(function(col){
    s += 'r[\''+col.columnid+'\']='+col.expression.toJavaScript('r','')+';'; 
});
var assignfn = new Function('r,params,alasql',s);
```

I was surprised about seeing structured data converted it to a string and parsed back to structured expressions of the ```assignfn``` function 

Could you put some words to why this approach was chosen? Have a feeling there is some complexity I have not thought about regarding why its good.

**Comment by agershun** [comment]
Mathias, thank you for the deep analysis of Alasql code!

I did this to make the UPDATE operator fast on large datasets. So, I create assignfn() function and "compile" it (in terms of JavaScript), so it runs faster if it is called more than twice (at least in Chrome). Actually, Alasql generates function like:
```sql
    UPDATE one SET two = three + 1;
```
to
```js
    function(r,params,alasql) { r['two']=(r['three']+1); }
```
Probably, I did not understand the question, could you clarify it?

**Comment by mathiasrw** [comment]
Ahh, ok... so its part of the caching?

**Comment by agershun** [comment]
Yes, some sort of. It realyy fast for Chrome, but probably not for all browsers.
